### ISSUE TITLE
Incorrect Point Costs for Expert Handling (Talent)

### ISSUE THREAD

**Issue by rjbrill** [raithos/xwing#10]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

Expert Handling (Talent) should have a variable cost, worth 2, 4, or 6 points depending on if the ship base is small, medium or large respectively.
### Actual Behavior

However, this upgrade was given a variable cost, worth 3, 6, or 9 points depending on if the ship base is small, medium or large respectively.

### Language

English

**Comment by rjbrill** [comment]
Let me try to show you the discrepancy with these images below:

[cid:feeae5a1-2122-4762-842e-d3e336707020]

[cid:bf9fbb47-34f3-47bf-a33e-4573117d3374]
________________________________

**Comment by raithos** [comment]
will be fixed in the next update
