### ISSUE TITLE
(Work in progress) Ships are in french in all language ?

### ISSUE THREAD

**Issue by Gan0n29** [raithos/xwing#1005]
Hi,

I'm working on a full French version of YASB, it's still in progress, and I put in the ships sections of the file "cards-fr.coffee" all the new ships, for example :

    exportObj.renameShip """Nimbus-class V-Wing""", """V-Wing de Classe Nimbus"""
    exportObj.renameShip """Trident-class Assault Ship""", """Vaisseau d'Assaut de Classe Trident"""
    exportObj.renameShip """ST-70 Assault Ship""", """Vaisseau d'Assaut ST-70"""
    exportObj.renameShip """Vulture-class Droid Fighter""", """Chasseur Droïde de Classe Vulture"""
    exportObj.renameShip """Xi-class Light Shuttle""", """Navette Légère de Classe Xi"""

And if I test YASB with my french translation file, in every language, those new ships are in french. It's because they don't exist in the file "cards-en.coffee" ? If it's the case I will add them in english if you want.

Thank you.

**Comment by raithos** [comment]
yes thats the reason, if you are switching between languages it will not move those back to english because tehy dont appear in the english version. However, this is an edge case where you might not need to make the extra additions. like consider that normally you would just choose your language and then default to that language, you wouldn't be switching between them that often, so it might be fine to just leave it. that being said, if you want to im not going to stop you :)

**Comment by Gan0n29** [comment]
Because I know that some people in France prefers to switch in English because they_more used to that language, I think it's a good thing to add them ;)

Here is the code :


    exportObj.renameShip """Belbullab-22 Starfighter""", """Belbullab-22 Starfighter"""
    exportObj.renameShip """Gauntlet Fighter""", """Gauntlet Fighter"""
    exportObj.renameShip """CR90 Corellian Corvette""", """CR90 Corellian Corvette"""
    exportObj.renameShip """Raider-class Corvette""", """Raider-class Corvette"""
    exportObj.renameShip """C-ROC Cruiser""", """C-ROC Cruiser"""
    exportObj.renameShip """Gozanti-class Cruiser""", """Gozanti-class Cruiser"""
    exportObj.renameShip """Delta-7 Aethersprite""", """Delta-7 Aethersprite"""
    exportObj.renameShip """Delta-7b Aethersprite""", """Delta-7b Aethersprite"""
    exportObj.renameShip """Eta-2 Actis""", """Eta-2 Actis"""
    exportObj.renameShip """Syliure-class Hyperspace Ring""", """Syliure-class Hyperspace Ring"""
    exportObj.renameShip """Fireball""", """Fireball"""
    exportObj.renameShip """HMP Droid Gunship""", """HMP Droid Gunship"""
    exportObj.renameShip """Hyena-Class Droid Bomber""", """Hyena-Class Droid Bomber"""
    exportObj.renameShip """Sith Infiltrator""", """Sith Infiltrator"""
    exportObj.renameShip """LAAT/i Gunship""", """LAAT/i Gunship"""
    exportObj.renameShip """Naboo Royal N-1 Starfighter""", """Naboo Royal N-1 Starfighter"""
    exportObj.renameShip """Nantex-Class Starfighter""", """Nantex-Class Starfighter"""
    exportObj.renameShip """Resistance Transport""", """Resistance Transport"""
    exportObj.renameShip """Resistance Transport Pod""", """Resistance Transport Pod"""
    exportObj.renameShip """TIE/rb Heavy""", """TIE/rb Heavy"""
    exportObj.renameShip """GR-75 Medium Transport""", """GR-75 Medium Transport"""
    exportObj.renameShip """Droid Tri-Fighter""", """Droid Tri-Fighter"""
    exportObj.renameShip """V-19 Torrent""", """V-19 Torrent"""
    exportObj.renameShip """Nimbus-class V-Wing""", """Nimbus-class V-Wing"""
    exportObj.renameShip """Trident-class Assault Ship""", """Trident-class Assault Ship"""
    exportObj.renameShip """ST-70 Assault Ship""", """ST-70 Assault Ship"""
    exportObj.renameShip """Vulture-class Droid Fighter""", """Vulture-class Droid Fighter"""
    exportObj.renameShip """Xi-class Light Shuttle""", """Xi-class Light Shuttle"""
    exportObj.renameShip """BTL-B Y-Wing""", """BTL-B Y-Wing"""
    exportObj.renameShip """BTA-NR2 Y-Wing""", """BTA-NR2 Y-Wing"""
