### ISSUE TITLE
Feature Request: "Clear All Upgrades" button for each ship and for entire list

### ISSUE THREAD

**Issue by ConfusedUs** [raithos/xwing#1009]
With the new loadout system, ships tend to have a lot of upgrades. I would like to be able to clear upgrades quickly, with a single click, on both the individual ship level and the entire list. 

* Click a button next to a ship to clear all the upgrades for that ship. There is no need to confirm the click, just like clone/delete. (Place to right of ship alongside the Delete/Copy buttons).
* Click a button to clear all upgrades on the entire list. This option should confirm the click with an "are you sure" kind of question. (Place in the top menu bar to the left of + New Squad)

**Comment by raithos** [comment]
After considering and reviewing the suggestion, I've decided that I'm not interested in putting in the work to implement this feature, as while its minorly more convenient, the work required and layout regigging needed to make it work isn't something I'm willing to do at this time. if a lot more people ask for the feature, ill revisit, or if someone else codes it i can merge and revistit.
