### ISSUE TITLE
Bug Report: Very slow performance when logged in with Facebook

### ISSUE THREAD

**Issue by ConfusedUs** [raithos/xwing#1010]
### Expected Behavior

YASB should have the same performance when logged in as when it's not.

### Actual Behavior

YASB is **significantly** slower when logged in with Facebook. It can take upwards of 30 seconds after choosing a ship to populate the list of pilots. Similar delays happen after choosing the pilot, when selecting upgrades, etc. Every click takes ages. This does not occur when not logged in. I have not tested other types of login. 

I'm happy to demo; email me at confusedus@gmail.com if you want to set up a time via discord or whatever.

**Comment by raithos** [comment]
does this also happen for any of the other login options?

**Comment by ConfusedUs** [comment]
I’ve confirmed it now with both Google and Facebook logins on two separate
devices.

It’s faster with google login than with Facebook. Both are slower than not
logged in at all.

I don’t have a Twitter or discord to test with.

I’m happy to demo if you like!

**Comment by raithos** [comment]
which browser are you using?

**Comment by ConfusedUs** [comment]
Firefox. Latest version.

Both with and without uBlock enabled.

**Comment by raithos** [comment]
I was afraid of that. Can you try something, disable auto-fill/autocomplete in your firefox settings and try again? this is a known issue with no clear solution

**Comment by raithos** [comment]
Haven't heard anything about this in a while, so I'm going to close this for now

**Comment by ConfusedUs** [comment]
I’ll try it out tomorrow and get back to you.

It reads to me like it’s waiting on some kind of call from the
Authenticator….but I don’t know why you’d be sending info to them outside
of login logout. It’s weird.
