### ISSUE TITLE
Card browser don't work in other languages than english, pilots and ships are seen like an upgrade

### ISSUE THREAD

**Issue by Gan0n29** [raithos/xwing#1013]
I think the problem is in the file browser.coffee in this line :

@all_cards = @all_cards.concat ( { name: card_data.name, display_name: card_data.display_name, type: exportObj.translate('singular', type), data: card_data, orig_type: exportObj.translate('singular', type) } for card_name, card_data of exportObj[type] )

It should be "orig_type: type" without translation right ? And keep the translation only for "type: exportObj.translate('singular', type)"

**Comment by Patschke** [comment]
I'm aware of this issue, was too lazy to actually fix it, and it's not just changing that line. It shouldn't be too hard though :D

**Comment by Gan0n29** [comment]
Yes I just tried to fix it and it's not that simple ^^

**Comment by raithos** [comment]
@Patschke whatever it is, its not affecting german, so I assume you know how to fix it?

**Comment by Gan0n29** [comment]
It works in German for pilots but not for ships. Because the word "pilot" is the same between German and English.

**Comment by raithos** [comment]
i fixed it, but it wont go live for a bit yet, working on another browser related bug i found while working on this.
