### ISSUE TITLE
Xws Import hangs on specific list

### ISSUE THREAD

**Issue by moff-wildfire** [raithos/xwing#1014]
## YASB 2.0 Bug Report
I'm guessing there are issues with the xws file from another app since both in yasb and infinite arenas doesn't load the last ship, Jango Fett. However the issue I'm writing about is how the site hangs when the name of the list contains url encoded space in the xws. So then your code url encodes the percent sign and the page is hung. 

Also this is occurring in Chrome on Android. 

### Expected Behavior

List should import 

### Actual Behavior

Website is grayed out and I can't scroll

### Language

The affected language(s). 

`{"version":"1.0.0","faction":"separatistalliance","name":"Dynamus%20list","pilots":[{"id":"generalgrievous","ship":"belbullab22starfighter","upgrades":{"talent":["outmaneuver"],"modification":["imperviumplating","afterburners"],"title":["soullessone"]}},{"id":"wattambor","ship":"belbullab22starfighter","upgrades":{"talent":["crackshot"],"modification":["imperviumplating","hullupgrade"]}},{"id":"skakoanace","ship":"belbullab22starfighter","upgrades":{"modification":["imperviumplating","hullupgrade"]}},{"id":"bobafettsep","ship":"firesprayclasspatrolcraft","upgrades":{"cannon":["autoblasters"],"crew":["jangofett"],"illicit":["overtunedmodulators"],"modification":["ablativeplating"],"title":["slaveisep"],"gunner":["veterantailgunner"]}}],"obstacles":[],"points":20,"vendor":{"xwsd":{"builder":"X-Wing 2nd Ed. Squads Designer","builder-link":"https://www.dmborque.eu/swz"}}}`

**Comment by moff-wildfire** [comment]
After sitting down at a computer, the bug is as a result of the title for slave 1 being wrong between YASB and XWSD. 

I'll poke at XWSD to fix their XWS IDs for both boba's separatist ship and the slave 1 title.

It must have been a coincidence that removing everything in the URL including sn= fixed the issue, leading me to have thought the url encoded space and percent sign were the issue.

**Comment by raithos** [comment]
ill close this for now, but i think there's a larger discussion going on right now about what we're doing about xws long term. I'll keep the title in mind as we move forward. For the record, the new slave one title xws is correct, as indicated by the xws rules
