### ISSUE TITLE
Request - How can I create a backend server ?

### ISSUE THREAD

**Issue by Gan0n29** [raithos/xwing#1017]
Hi Raithos and Patschke,

When I created the fork of YASB 2.0 https://xwing-legacy.com, it was for my personal use but now a lot a player who don't like 2.5 use it ;)
And their main request is to allow players to save their squadrons.

For that I see 2 solutions :
1 - Authorize this fork to use the old YASB backend : https://yasb-backend.herokuapp.com, but I fully understand if you don't want to ^^
2 - Create a dedicated backend server.

I try this second solution, I created a heroku website and a cloudant database, but I'm stuck here... For example I created in heroku the env variable "CLOUDANT_URL" with the cloudant link in it but it doesn't work.

![image](https://user-images.githubusercontent.com/66066277/158864280-57883f8a-e49e-4472-84f7-6690c3c7762e.png)

Thanks.

(I put an image for every cards in this fork, don't hesitate to use them in yasb.app if you want, but that will use more bandwidth)

**Comment by raithos** [comment]
most likely your cloudant_url is incorrect looking at the format of your link. the link used must also include the authentication to access likely using an api-key as a part of the authentication. There are a bunch of ways to do this, here are some documentation https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-managing-access-for-cloudant https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-work-with-your-account#authentication
