### ISSUE TITLE
UnicodeDecodeError when using translate script

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#102]
@Patschke So, I'm not familiar with Python, sorry if this is due to an error I made.

Translation helper readme does not mention what command to run so I tried this:

    $ python3 translate.py

And I'm getting this error:

> Traceback (most recent call last):
>   File "translate.py", line 7, in <module>
>     data_de = json.load(open('api_export_de.json'))
>   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1801: invalid continuation byte

Again I don't know python but it seems to me that the problem is that the `api_export_de.json` file is saved as ISO-8859-15 rather than UTF-8. Shouldn't this file be saved as UTF-8 as are all other files in the project, including `cards-de.coffee`? Is it okay for me to change this?

I'm using python 3.7.0.

**Comment by Patschke** [comment]
Ah, well. I'm sorry for creating files on my windows machine. You may of course change the files to UTF-8, or add `encoding = "ISO-8859-1"` to the open commands, e.g. `data_en = json.load(open('api_export_en.json', encoding = "ISO-8859-1"))`

**Comment by iwazaru** [comment]
No problem! I just wanted to make sure that this wasn't intended and avoid to break everything :)
