### ISSUE TITLE
Card Browser - Base Size bug

### ISSUE THREAD

**Issue by jazzmang** [raithos/xwing#1026]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Only display specified bases that are checked

### Actual Behavior

Always shows all bases regardless of what size you pick and if you don't have at least small checked, nothing happens.

Tried this ins both Firefox and Chrome on Windows.

### Language

English
![image](https://user-images.githubusercontent.com/5102958/159927939-b8f635e2-3a5d-4f04-825e-8e1933533193.png)
![image](https://user-images.githubusercontent.com/5102958/159928086-fe97e150-4a69-4344-b699-171dc9fd62e6.png)

**Comment by raithos** [comment]
oh this is probably due to a change i made to how bases are recorded. ill fix this soon
