### ISSUE TITLE
Unable to log in from iPad

### ISSUE THREAD

**Issue by SnowDH** [raithos/xwing#1028]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

I expect to tap the log in link and get the same log in options as in mi laptop browser

### Actual Behavior

When i tap the log in link the link is highlighted but nothing happens. Other links work well. I tríes on Safari and Chrome. On two different iPads

### Language

The affected language(s).

**Comment by raithos** [comment]
are you using google, facebook discord or twitter tto login?

**Comment by SnowDH** [comment]
Yes, google.

**Comment by XPav** [comment]
You have to turn-off "Prevent Cross-Site Tracking", globally in Settings->Safari to be able to login.

**Comment by raithos** [comment]
@XPav no this is no longer necessary as part of the domain move the login is now under a subdomain and no longer needs that setting.

@SnowDH when you say nothing happens, does the pop up not happen or does the popup happen but its a blank page?

**Comment by raithos** [comment]
without more information I cant resolve this, and haven't been able to reproduce it.
