### ISSUE TITLE
Unable to build according to instructions

### ISSUE THREAD

**Issue by Plunderbird** [raithos/xwing#1029]
## YASB 2.0 Bug Report

Hi - I was hoping to have a play with YASB 2.0 to see how it worked on the back-end and maybe have a go at modifying it. However, when built according to the instructions on the github readme, the resulting index.html does not seem to work properly:

![image](https://user-images.githubusercontent.com/78153609/160252981-412fb51c-f409-4357-95b6-d3f659dfe8a5.png)

Instructions were followed on a Linux VM running Ubuntu 20.04.4 on a fresh installation.

Definitely not ruling out user error here - if I've missed something obvious, please let me know!

### Expected Behavior

The generated website should be functionally identical to the current yasb.app functionality.

### Actual Behavior

Besides the top bar, the site does not load any content. Clicking the faction buttons changes the URL to the extension #rebelContent, #empireContent etc but no other site change occurs and no content loads.

### Language

English

**Comment by Patschke** [comment]
I recently had some issues getting the bower task to run properly. Could you check if that behaves correctly, maybe running it on its own? Could you check if copying files from the bower dir to app/bower_components resolves this issue?

**Comment by Plunderbird** [comment]
Copying from the default bower folder to app/bower_components produces the following (no change besides loading circle in top right):

![image](https://user-images.githubusercontent.com/78153609/160466491-5ae9c47f-ba90-4a7b-86de-a37dd4e1f94a.png)

I repeated the above after running bower directly by removing everything else from the gruntfile (not all that familiar with grunt, so it's a bit of a guess):

![image](https://user-images.githubusercontent.com/78153609/160467177-40e4786e-f022-41a2-a774-7dc0cd3f80a3.png)

This produced the following:

![image](https://user-images.githubusercontent.com/78153609/160467294-71405759-176e-4743-bd83-39b765b2867c.png)

Not sure if this is the expected result or not for bower. Either way, when putting the bower_components file into /app after doing so no change was observed besides the loading circle still being present and animating. The result of copying bower_components into the default /app folder after running grunt can be seen at https://plunderbird.github.io/.

Your initial hunch was right on the money, though - the bower_components folder is totally absent from /app when running grunt from the unmodified project.

**Comment by Plunderbird** [comment]
I've just added that step to my local gruntfile and I can confirm it's resolved the issue both locally and when hosted. There's no ship image flashes when you pick one in the builder itself, but that's not exactly a critical functional issue. Thanks for the help!
