### ISSUE TITLE
Feature request Add new checkbox option to simple print 

### ISSUE THREAD

**Issue by moff-wildfire** [raithos/xwing#1035]
Please add a full card text option to the Simple print.

With how complicated lists are now in 2.5 it can be helpful to just hand your opponent a sheet with your full squad on it with card text.

While this is possible using the Fancy option, I'd like to have this basic and no color option that Simple gives me.

**Comment by raithos** [comment]
you can print fancy in no color, and you would still have to include all the relevant text as in fancy for the purpose you described. I'm not seeing the value here.
