### ISSUE TITLE
Unhandled exception when printing modified dials

### ISSUE THREAD

**Issue by covertsonic** [raithos/xwing#1041]
### Expected Behavior

When attempting to open the print dialog for a dial that has been modified (e.g., Quick Build card for Edrio Two Tubes, T-65 X-Wing, has an R4 Astromech that modifies the dial), the print dialog should open.

### Actual Behavior

The print dialog does not open, and an unhandled error occurs. 

### Proposed Fix
change line 2033 in system/xwing.coffee to:
`
"""#{if maneuvers_modified.toString() != maneuvers_unmodified.toString() then " (*)" else ""}</h4>""" + #previous behavior was giving an uncaught exception where "(*)" is now - Uncaught ReferenceError: modified is not defined
`

![image](https://user-images.githubusercontent.com/19481035/161437507-5f6427e8-f060-4761-b38c-0756caf5e0b5.jpeg)

**Comment by Patschke** [comment]
I'd rather add the missing `""` marks (to me it wouldn't be directly clear what `(*)` stands for in this context, and I think we have enough space available here). Than for the note, will be fixed!

**Comment by covertsonic** [comment]
Makes sense!  Thank you.
