### ISSUE TITLE
Illicit Cloaking Device can be equipped to Medium base ships  -- restriction is "Small Ship"

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#1048]
![image](https://user-images.githubusercontent.com/10382630/162257723-c3b4536d-a369-4849-963c-138dcb50dce8.png)

Could be related to the "Small ShipSmall Ship" description on the card

**Comment by raithos** [comment]
for the record cloaking device has always been ok on medium bases, its just the description logic that got messed up
