### ISSUE TITLE
Missing charge on Burnout Thrusters

### ISSUE THREAD

**Issue by TobbyZ** [raithos/xwing#1049]
Hey,
The Modification Burnout Thrusters seem to be missing the "Charge" icon on top of the description stating how many charges the card has.

Mvh
TobbyZ

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s). 
![Burnout Thrusters](https://user-images.githubusercontent.com/71729430/162476394-0c2ed980-3a35-430e-b502-6cbd2956d9ba.PNG)

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.
