### ISSUE TITLE
Updated Quick Build Cards for ST-70 Assault Ship and Gauntlet Fighter

### ISSUE THREAD

**Issue by covertsonic** [raithos/xwing#1050]
I created the coffee JSON for the Quick Build cards for the `ST-70 Assault Ship` and the `Gauntlet Fighter` for everything except ST-70's Din Djarin (the pilot card is not yet in cards-en.coffee, and I haven't yet learned how to add pilot cards).  

Providing here as I don't have write-access to the repo.  All tested successfully on my local build.

![image](https://user-images.githubusercontent.com/19481035/162548325-1798af13-b533-4477-94b9-469691b02714.png)

        {
            id: 603
            faction: "Scum and Villainy"
            pilot: "Outer Rim Enforcer"
            ship: "ST-70 Assault Ship"
            threat: 2
            upgrades: [
                "Tracking Fob"
            ]
        }
        {
            id: 604
            faction: "Scum and Villainy"
            pilot: "Q9-0"
            ship: "ST-70 Assault Ship"
            threat: 4
            upgrades: [
                "Outmaneuver"
                "The Mandalorian"
                "The Child"
                "Migs Mayfeld"
                "Tracking Fob"
                "Burnout Thrusters"
                "Razor Crest"
            ]
        }
        {
            id: 605
            faction: "Scum and Villainy"
            pilot: "Guild Bounty Hunter"
            ship: "ST-70 Assault Ship"
            threat: 3
            upgrades: [
                "Peli Motto"
                "IG-11"
                "Hotshot Tail Blaster"
                "Tracking Fob"
                "Hull Upgrade"
            ]
        }
        {
            id: 606
            faction: "Scum and Villainy"
            pilot: "Maul"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Heightened Perception"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 607
            faction: "Scum and Villainy"
            pilot: "Rook Kast"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Elusive"
                "Mandalorian Super Commandos"
                "Drop-Seat Bay"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 608
            faction: "Scum and Villainy"
            pilot: "Shadow Collective Operator"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Blazer Bomb"
                "Overtuned Modulators"
                "Shield Upgrade"
            ]
        }
        {
            id: 609
            faction: "Galactic Republic"
            pilot: "Bo-Katan Kryze (Republic)"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Outmaneuver"
                "Nite Owl Commandos"
                "Veteran Tail Gunner"
                "Drop-Seat Bay"
                "Hull Upgrade"
                "Gauntlet"
                "Swivel Wing"
            ]
        }
        {
            id: 610
            faction: "Galactic Republic"
            pilot: "Nite Owl Liberator"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Veteran Tail Gunner"
                "Concussion Bombs"
                "Hull Upgrade"
                "Swivel Wing"
            ]
        }
         {
            id: 611
            faction: "Separatist Alliance"
            pilot: "Pre Vizsla"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Predator"
                "Death Watch Commandos"
                "Blazer Bomb"
                "Shield Upgrade"
                "Swivel Wing"
            ]
        }
        {
            id: 612
            faction: "Separatist Alliance"
            pilot: "Bo-Katan Kryze"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Outmaneuver"
                "Veteran Tail Gunner"
                "Swivel Wing"
            ]
        }       
        {
            id: 613
            faction: "Separatist Alliance"
            pilot: "Death Watch Warrior"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Hull Upgrade"
                "Shield Upgrade"
                "Concussion Bombs"
                "Swivel Wing"
            ]
        }
        {
            id: 614
            faction: "Rebel Alliance"
            pilot: "Ezra Bridger (Gauntlet Fighter)"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Shattering Shot"
                "Clan Wren Commandos"
                "Shield Upgrade"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 615
            faction: "Rebel Alliance"
            pilot: '"Chopper" (Gauntlet Fighter)'
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Predator"
                "Veteran Tail Gunner"
                "Hull Upgrade"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 616
            faction: "Rebel Alliance"
            pilot: "Mandalorian Resistance Pilot"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Clan Wren Commandos"
                "Swivel Wing"
            ]
        }
        {
            id: 617
            faction: "Galactic Empire"
            pilot: "Gar Saxon"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Imperial Super Commandos"
                "Drop-Seat Bay"
                "Hull Upgrade"
                "Shield Upgrade"
                "Swivel Wing"
            ]
        }
        {
            id: 618
            faction: "Galactic Empire"
            pilot: "Captain Hark"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Combat Boarding Tube"
                "Imperial Super Commandos"
                "Swivel Wing"
            ]
        }
        {
            id: 619
            faction: "Galactic Empire"
            pilot: "Imperial Super Commando"
            ship: "Gauntlet Fighter"
            threat: 2
            upgrades: [
                "Outmaneuver"
                "Veteran Tail Gunner"
                "Concussion Bombs"
                "Hull Upgrade"
            ]
        }

**Comment by Patschke** [comment]
Thank you very much for the input! It's added to #1051 and will be live when that's merged. `Din Djarin` does exist - the card name is `The Mandalorian`. I do not own those expansions (yet), and the Quickbuilds are not in the x-wing wiki (yet), so I couldn't add it in myself...

**Comment by covertsonic** [comment]
ah!!  rookie move on my part... I see it now.  Thank you.

JSON updated below (inserted The Mandalorian as id 606).  It might look funny on the quick build in the app saying "The Mandalorian" while the quickbuild card says "Din Djarin," but it works!  Pictures below with all the pilot & quick build cards in the two sets.

{
            id: 603
            faction: "Scum and Villainy"
            pilot: "Outer Rim Enforcer"
            ship: "ST-70 Assault Ship"
            threat: 2
            upgrades: [
                "Tracking Fob"
            ]
        }
        {
            id: 604
            faction: "Scum and Villainy"
            pilot: "Q9-0"
            ship: "ST-70 Assault Ship"
            threat: 4
            upgrades: [
                "Outmaneuver"
                "The Mandalorian"
                "The Child"
                "Migs Mayfeld"
                "Tracking Fob"
                "Burnout Thrusters"
                "Razor Crest"
            ]
        }
        {
            id: 605
            faction: "Scum and Villainy"
            pilot: "Guild Bounty Hunter"
            ship: "ST-70 Assault Ship"
            threat: 3
            upgrades: [
                "Peli Motto"
                "IG-11"
                "Hotshot Tail Blaster"
                "Tracking Fob"
                "Hull Upgrade"
            ]
        }
        {
            id: 606
            faction: "Scum and Villainy"
            pilot: "The Mandalorian"
            ship: "ST-70 Assault Ship"
            threat: 4
            upgrades: [
                "Notorious"
                "Burnout Thrusters"
                "Kuiil"
                "The Child"
                "Hull Upgrade"
                "Tracking Fob"
                "Razor Crest"
            ]
        }
        {
            id: 607
            faction: "Scum and Villainy"
            pilot: "Maul"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Heightened Perception"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 608
            faction: "Scum and Villainy"
            pilot: "Rook Kast"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Elusive"
                "Mandalorian Super Commandos"
                "Drop-Seat Bay"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 609
            faction: "Scum and Villainy"
            pilot: "Shadow Collective Operator"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Blazer Bomb"
                "Overtuned Modulators"
                "Shield Upgrade"
            ]
        }
        {
            id: 610
            faction: "Galactic Republic"
            pilot: "Bo-Katan Kryze (Republic)"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Outmaneuver"
                "Nite Owl Commandos"
                "Veteran Tail Gunner"
                "Drop-Seat Bay"
                "Hull Upgrade"
                "Gauntlet"
                "Swivel Wing"
            ]
        }
        {
            id: 611
            faction: "Galactic Republic"
            pilot: "Nite Owl Liberator"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Veteran Tail Gunner"
                "Concussion Bombs"
                "Hull Upgrade"
                "Swivel Wing"
            ]
        }
         {
            id: 612
            faction: "Separatist Alliance"
            pilot: "Pre Vizsla"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Predator"
                "Death Watch Commandos"
                "Blazer Bomb"
                "Shield Upgrade"
                "Swivel Wing"
            ]
        }
        {
            id: 613
            faction: "Separatist Alliance"
            pilot: "Bo-Katan Kryze"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Outmaneuver"
                "Veteran Tail Gunner"
                "Swivel Wing"
            ]
        }       
        {
            id: 614
            faction: "Separatist Alliance"
            pilot: "Death Watch Warrior"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Hull Upgrade"
                "Shield Upgrade"
                "Concussion Bombs"
                "Swivel Wing"
            ]
        }
        {
            id: 615
            faction: "Rebel Alliance"
            pilot: "Ezra Bridger (Gauntlet Fighter)"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Shattering Shot"
                "Clan Wren Commandos"
                "Shield Upgrade"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 616
            faction: "Rebel Alliance"
            pilot: '"Chopper" (Gauntlet Fighter)'
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Predator"
                "Veteran Tail Gunner"
                "Hull Upgrade"
                "Nightbrother"
                "Swivel Wing"
            ]
        }
        {
            id: 617
            faction: "Rebel Alliance"
            pilot: "Mandalorian Resistance Pilot"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Enduring"
                "Clan Wren Commandos"
                "Swivel Wing"
            ]
        }
        {
            id: 618
            faction: "Galactic Empire"
            pilot: "Gar Saxon"
            ship: "Gauntlet Fighter"
            threat: 4
            upgrades: [
                "Imperial Super Commandos"
                "Drop-Seat Bay"
                "Hull Upgrade"
                "Shield Upgrade"
                "Swivel Wing"
            ]
        }
        {
            id: 619
            faction: "Galactic Empire"
            pilot: "Captain Hark"
            ship: "Gauntlet Fighter"
            threat: 3
            upgrades: [
                "Combat Boarding Tube"
                "Imperial Super Commandos"
                "Swivel Wing"
            ]
        }
        {
            id: 620
            faction: "Galactic Empire"
            pilot: "Imperial Super Commando"
            ship: "Gauntlet Fighter"
            threat: 2
            upgrades: [
                "Outmaneuver"
                "Veteran Tail Gunner"
                "Concussion Bombs"
                "Hull Upgrade"
            ]
        }

![IMG_9271](https://user-images.githubusercontent.com/19481035/162576498-62efadf5-08e8-49dc-9a69-bc617239f220.JPEG)
![IMG_9272](https://user-images.githubusercontent.com/19481035/162576499-790b0002-42f2-4e32-9762-91ba2e584872.JPEG)

**Comment by Patschke** [comment]
Yeah, sometimes the Quickbuilds are not very accurate in terms of pilot names. Thanks again for the valuable input!
