### ISSUE TITLE
Enduring upgrade says it's not in the gauntlet expansion 

### ISSUE THREAD

**Issue by Bmaenz** [raithos/xwing#1052]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

I expected enduring (upgrade) to say it came in the gauntlet expansion 

### Actual Behavior

Enduring says it only comes in the razor crest expansion 

### Language

English

**Comment by Patschke** [comment]
Thanks for the note, will be fixed
