### ISSUE TITLE
importing extended squads

### ISSUE THREAD

**Issue by nitrobenz** [raithos/xwing#1058]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

The builder should stay in the extended format if selected and display all ships from the imported list. 

### Actual Behavior

The builder automatically switches to Standard format and if Extended format ships/upgrades are in the imported list they are cut out of the displayed list.

### Language

English

**Comment by raithos** [comment]
xws does not contain information about the legality of the list theres no way to know which format should be loaded, however, youre right that xws should import from extended and not standard, so ill rectify that.
