### ISSUE TITLE
Add Icons and Sort Options to Collection

### ISSUE THREAD

**Issue by UsrRed7** [raithos/xwing#1059]
## Upgrade/Pilot Card Icons

It would be super nice to have the icon of a card next to it when browsing 'Your Collection'. 
(i.e. Crew icon next to Perceptive Copilot, Talent Icon next to Marksmanship...)

This also goes for Ship Icons next to pilots

**Additionally** this would resolve the issue of differentiating between cards with the same name, _Especially_ Pilots. 
(Ezra Bridger, Ezra Bridger, Ezra Bridger, and Ezra Bridger is super unclear)

### Expected Behavior

* Slot Icon of Upgrade card next to it when browsing collection
* Ship Icon of Pilot card next to it when browsing collection
* (Gauntlet Ship Icon is also missing entirely. Thought I saw it in the ttf file, but don't see it anywhere on the site yet)

### Actual Behavior

* No icons when in viewing 'Your Collection'

### Language

* English

## Sorting Options

The inventory is great to know if you have cards or not when building squads, but it currently is difficult to use for much more.

### Expected Behavior

* Ability to sort Upgrade and Pilot cards by upgrade/ship type then alphabetically (Ideally by default, though that may be a personal preference)
* Likely separately sort pilot/upgrade cards

### Actual Behavior

* When browsing collection there is no way to sort or filter the lists at all.

### Language

* English

I noticed when browsing the code that there seems to already be the system to sort, but just isn't being used? I've been looking at the code, getting a feel for it. But I don't understand the structure well enough yet to do it myself. I'd love to help however I can though if that's something you'd appreciate. 

**Device:** Windows Computer
**Browser:** Same behavior on both Chrome and Edge

**Comment by raithos** [comment]
probably doable. have to think  about it
