### ISSUE TITLE
Bo-Katan Kryze (Vizsla's Lieutenant) missing Recurring Charge

### ISSUE THREAD

**Issue by lemonadesunshine365** [raithos/xwing#1060]
### Expected Behavior

The Bo-Katan Kryze (Vizsla's Lieutenant) Pilot should have one Recurring Charge.

### Actual Behavior

Bo-Katan Kryze (Vizsla's Lieutenant) does not have a Recurring Charge.

### Language

English.

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.
