### ISSUE TITLE
Wrong initative on Hark

### ISSUE THREAD

**Issue by TobbyZ** [raithos/xwing#1061]
Captain Hark of the Empire is listed as an I2 pilot, when he should be an initiative 3 pilot.

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.
