### ISSUE TITLE
Captain Hark (Gauntlet) has incorrect Initiative value

### ISSUE THREAD

**Issue by sjohns37** [raithos/xwing#1062]
Captain Hark (Gauntlet) is shown to be initiative 2 when he should be 3. 

https://pbs.twimg.com/media/FIWoEDiX0AQc8Xv.jpg

**Comment by Patschke** [comment]
Duplicate of #1061 

Though I have to admit, that you both basically raised this issue at the same time - so still thanks for the note ;-)
