### ISSUE TITLE
Hello, Thank you for all your hard work on this great website! I have a feature request: would it be possible to include the tie aggressor and tie bomber in an Imperial squad? I did not see them available. Thanks! 

### ISSUE THREAD

**Issue by LtKetch** [raithos/xwing#1065]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Please select a game mode where those ships are legal. They have not been released in 2.x and are therefore not allowed in standard.

**Comment by LtKetch** [comment]
Got it. Thank you!
