### ISSUE TITLE
Xwing 2.0 Builder - Missing Crew Slot - Scum and Villainy - Firespray

### ISSUE THREAD

**Issue by sub780lime** [raithos/xwing#1066]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpretation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported. 

### Expected Behavior

The Firespray should display a crew slot

### Actual Behavior

No crew slot is listed

### Language

The affected language(s). 

![image](https://user-images.githubusercontent.com/15984777/165833991-e2628346-07fe-4a2a-8060-299c9fd9f1e1.png)

**Comment by Patschke** [comment]
We do not update the 2.0 YASB anymore. YASB 2.5 (found at yasb.app) seems to be all up to date. To be honest, I'm not even sure where to check which 2.0 pilot should have which slots - the old point PDFs appear to no longer exist.

If this is an actual issue for 2.5 please provide some additional information. The image shown is for YASB 2.0.

**Comment by raithos** [comment]
In 2.0 Boba Fett did not have a crew slot. This is working as intended. As Patrick said, you should look at yasb.app for the up to date version of the game.
