### ISSUE TITLE
missing upgrades in collection Sith Inf

### ISSUE THREAD

**Issue by windshieldwiper** [raithos/xwing#1073]
it seems like some upgrades are missing from the collection/availability feature.
getting a warning i do not have certain upgrades when i do

Sith Infiltrator Expansion:
ion torpedoes 
novice technician 

there maybe more, but these the ones i noticed

if im not mistaken you or someone on the team has to manually put these in, and it probably just got accidentally skipped

**Comment by Patschke** [comment]
thanks for the note, will be fixed.
