### ISSUE TITLE
Can't equip Grand moff Tarkin on Lambda shuttle?

### ISSUE THREAD

**Issue by Mackay001** [raithos/xwing#1074]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Attach Grand Moff Tarkin to the Lambda shuttle  or Reaper.  We have an extended event and I could previously attach Tarkin to the lambda.

### Actual Behavior

Grand Moff tarking is greyed out for the Lambda shuttle, all pilots, as well as the reaper.  I can however attach him to the Decimator.  

### Language

The affected language(s).

**Comment by Patschke** [comment]
You can only equip Tarkin if you have a target lock action, which neither the lambda nor the reaper does. You'd have to figure out some way to give them a target lock action first.

**Comment by Mackay001** [comment]
Thanks
 Now I just feel dumb.
