### ISSUE TITLE
Points changes may make previously legal lists impossible to build

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#1076]
Apologies, this doesn't fit the format and may be a feature request, not a bug/issue.

Basically, with potential point changes upcoming, it will be very difficult/impossible to host events using "old" points using YASB, because if the loadout of a ship is reduced it will not be possible to create that list anymore, as you are not able to put upgrades that go over the loadout limit of a ship onto that limit.

This is related to:
https://github.com/guidokessels/xwing-data2/issues/542

Where we can hopefully get versioning/historical points data into XWS to help alleviate, but there are two large events on the weekend of May 27th, and from the sounds of it, points dropping on or before that date. If players need to submit lists for those events, it will be difficult to do so under the new AMG style points without the option to swap to historical versions of points, or go over loadout limits.

EDIT: Realized a specific example might be more helpful.
Let's say Barriss Offee loses 1 loadout point in whatever upcoming changes. While creating or repairing lists for "old" tournaments, it becomes impossible to put Concussion Missiles + Instinctive Aim on her, because it would go above the points cap. Would it be possible to allow upgrades to be brought past the loadout limit (with an error saying it is not legal)? In the longer term, sourcing historical points from XWS seems more preferable as it would also fix any potential upgrade slot changes, with an option for version at squadbuilding, but that is presumably dependent on that historical data actually existing first!

**Comment by raithos** [comment]
for any pre 2.5 tournament, use raithos.github.io. i didnt remove it. i specifically did this because i knew this would happen.

**Comment by chrisalleng** [comment]
@raithos this is not for a pre-2.5 tournament, this is for a 2.5 tournament that is hosted AFTER the 1.4.1 points set is no longer correct/relevant.

The old (second edition/2.0) builder doesn't help with this, because the problem here to solve is running an event, or building a list for current points (1.4.1) AFTER new 2.5 points have dropped, which supposedly is happening in the next week or two.

**Comment by raithos** [comment]
oh i guess you never noticed this before, but whenever a new points hits, i usually make a copy of the old setup  under /old
