### ISSUE TITLE
Feature Suggestion: Apply Banlist Checkbox

### ISSUE THREAD

**Issue by quall3** [raithos/xwing#1078]
Some Tournaments use Banlist in a format, some don't.
Maybe it would be convenient to have a checkbox to apply the banlist to pilot/upgrade selection.
My suggestion would be to add it next to the Format Dropdown. 
[x] Apply Banlist
Checked by default, unchecking it allows selection of banned cards.

**Comment by Patschke** [comment]
You can just use extended? The only card formally banned there is Delta-7B, which does not make any sense since the Deltas got split up. The only point of standard really is to ban some ships/pilots/upgrades, isn't it?

**Comment by quall3** [comment]
yeah you can do that, but what if you wanted extended *with* ban list?

anyways, its just a suggestion. if you reject it, just close.
im okay with that.

**Comment by raithos** [comment]
I have historically only supported official formats. I can wait and see if that becomes popular, but for now, i will close for the aforementioned reason.
