### ISSUE TITLE
Restricted list building

### ISSUE THREAD

**Issue by f-e-z** [raithos/xwing#108]
## YASB 2.0 Bug Report

Would be great to have the options for FFG restricted squad building.

Cheers

**Comment by Patschke** [comment]
We do have the Extended and Second Edition formats from FFG available. Are you asking about adding No Glory, Battle of Yavin and Playing Favourites, or a general Custom Format allowing you to define your own settings? 

It depends a little bit on how often FFG is about to change their variants formats, as I am not aware of (an api access to) a list of allowed cards for them.

**Comment by f-e-z** [comment]
Thanks,

Mainly just the 2nd edition. I’m using the web site on my phone and can’t seem to find the option for 2nd edition. I’ll keep looking. I feel a little stupid now🤪.

Cheers

**Comment by iwazaru** [comment]
It's located on the dropdown menu that shows "Extended" by default. Here's a screenshot on a phone screen:

![capture d ecran 2018-09-25 a 15 36 58](https://user-images.githubusercontent.com/5627688/46017955-0343a080-c0d9-11e8-9ed0-7bffa66c9efb.png)

If that covers your need, you can close the issue :)

**Comment by f-e-z** [comment]
Cheers
