### ISSUE TITLE
Current v upcoming points

### ISSUE THREAD

**Issue by FirestormSquadronfirecast** [raithos/xwing#1086]
I know everyone is excited for new points  but we have the worlds qualifier in the uk in 2 weeks and the current points are live until mid june is there a way you could please have a version accessible 
for both points costs
 ## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Available at yasb.app/old (just as it was for about every point update during the last years...)

**Comment by FirestormSquadronfirecast** [comment]
U are a superstar
