### ISSUE TITLE
CIS Rouge-class pilots can't equip Independent Calculations

### ISSUE THREAD

**Issue by totemxw** [raithos/xwing#1093]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

I should be able to equip Independent Calculations on the CIS Rouge-class starfighter pilots, with the exception of Cad Bane

### Actual Behavior

Independent Calculations is greyed out

### Language

The affected language(s).

**Comment by raithos** [comment]
i totally forgot about this one
