### ISSUE TITLE
Points during transition period

### ISSUE THREAD

**Issue by danoliv** [raithos/xwing#1099]
As the official date for the new points and rule is the 15/6/2022 it is possible to select the previous ones until the official date ?

Thanks

**Comment by Patschke** [comment]
yasb.app/old

**Comment by danoliv** [comment]
Thanks, I believe that a link just under “ Current Version: 06/15/2022” with previous version would be perfect

**Comment by raithos** [comment]
i do not intend to add a link, the old version is not active all the time, only during transitionary periods
