### ISSUE TITLE
Gas Cloud Indexing Issue

### ISSUE THREAD

**Issue by JackBP1** [raithos/xwing#1101]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Expected gas clouds to be indexed 0-5 like the other obstacles, with gas clouds 0-2 from the republic/separatist expansions and 3-5 from never tell me the odds.

### Actual Behavior

Gas clouds are listed from 1-6 instead, and gas cloud 6 is marked as unreleased.

Also wanted to say thank you for keeping this running, really appreciate everything you've done for the community :)

### Language

The affected language(s).

**Comment by raithos** [comment]
not sure i should change it at this point, since its tied in with xws as well

**Comment by raithos** [comment]
ill fix 6 being unreleased though
