### ISSUE TITLE
YASB 2.0 feature request / Font Update

### ISSUE THREAD

**Issue by babyblued** [raithos/xwing#1102]
## YASB 2.0 feature request

the site works great this is a feature request

### feature request

First, I love your site THANK YOU for your dedication.
my request is I would like to know if you are actively updating the web font with the ST-70, Gauntlet, rouge-class, and  Clone Z-95
I have the basic vectorized files I made of the ships if it helps to update it, they look good to me but I'm not sure how the font crew got the ones they use.

![Rogue_Class_Starfighter](https://user-images.githubusercontent.com/65516030/170154142-8fd72b7a-b7d1-4cca-bd5d-46d3690f293f.svg)
![gauntlet_fighter](https://user-images.githubusercontent.com/65516030/170154143-17396b3d-2267-4ffc-802b-43e6b29a331c.svg)
![ST-70](https://user-images.githubusercontent.com/65516030/170154145-9ab92bb0-f439-4d07-aaf5-26debdcbfc63.svg)
![Clone_Z-95_Headhunter2](https://user-images.githubusercontent.com/65516030/170154147-49d0c871-ce3b-472b-964d-90a60aea8371.svg)

**Comment by raithos** [comment]
im not the one updating the fonts, but if you post to https://github.com/CrazyVulcan/xwing-miniatures-font thats what im using for the fonts now.
