### ISSUE TITLE
Twin Ion Engines upgrade stays in statbox after moving off V-Wing

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#1113]
Make a new list.

Put an ARC-170 in first, then a V-Wing.

Put your mouse on the V-Wing's pilot drop down, and then move it up to the ARC-170's pilot drop down.

You end up with:

![image](https://user-images.githubusercontent.com/10382630/173454922-e4d010a8-e224-44ab-96fd-e0bc5ac3edad.png)

When you move up to the ARC-170's ship drop down, the Twin Ion Engine upgrade disappears.

**Comment by raithos** [comment]
tried to reproduce and could not. any other details you can provide?

**Comment by XPav** [comment]
https://user-images.githubusercontent.com/10382630/174404026-ceb9c16e-e876-4c54-a818-8fdcc3c38b70.mp4

Here's a video of how I reproduced.   Using the latest version of Edge.
