### ISSUE TITLE
FB login down?

### ISSUE THREAD

**Issue by iswehr** [raithos/xwing#1114]
## YASB 2.0 Bug Report
Trying to log in with OAuth via facebook

### Expected Behavior

When I choose to log in using FB, I expect it to let me log in using FB

### Actual Behavior

I pick the option to log in using FB, and I get sent immediately to a FB error page with message :"Feature Unavailable: Facebook Login is currently unavailable for this app, since we are updating additional details for this app. Please try again later."

### Language

English

**Comment by raithos** [comment]
i just tried logging in and it seems fine. what browser are you using?

**Comment by iswehr** [comment]
Hey thanks for the quick response.  It's Chrome running on an Android phone.  It's a bit mysterious in that it's been running fine for a long time with me just staying logged in, but I accidentally logged out today. Tried logging back in - tried the Google option 1st which has taken me back to all my old 2.0 200pt lists in my saved lists.  So, I figured I must have started logging in with FB after the 2.5 app switch, and then hit that error msg trying the FB login option.
- Stephan 
 
  On Fri., 17 Jun. 2022 at 22:22, ***@***.***> wrote:   


i just tried logging in and it seems fine. what browser are you using?

**Comment by raithos** [comment]
Have you tried clearing your cookies on your browser and trying to log in again? I've double checked and while the login doesn't bring you back to the page properly, it does succeed in logging you in if you go back to the page on android chrome

**Comment by raithos** [comment]
found it

**Comment by iswehr** [comment]
Cool - thought I had managed to fix it by removing yasb from within my FB app permissions and trying again, but you discovered something on your side?  Regardless, working well now! Thanks for the help and for all your on-going work on YASB.

- Stephan (Bytown Smugglers - Ottawa) 
 
  On Fri., 17 Jun. 2022 at 23:42, ***@***.***> wrote:   


found it
