### ISSUE TITLE
Independent Calculations problem in list including Cad Bane and MagnaGuards

### ISSUE THREAD

**Issue by kksuke** [raithos/xwing#1116]
## YASB 2.0 Bug Report

At separatist list including MangaGuards and not including Cad Bane, MagnaGuards can choose Independent Calculations to Modification upgrade.

But at separatist list including MangaGuards and Cad Bane cannot choose Independent Calculations.
(Independent Calculations is not greyed but is not reflected list.)

### Expected Behavior

MangaGuards equip Independent Calculations.
Cad Bane does not equip Independent Calculations.

https://forums.atomicmassgames.com/topic/6374-cis-rogue-class-and-independent-calculations/

### Actual Behavior

All rogue cannot equip Independent Calculations if there is Cad Bane.
 
### Language

English, Japanese

**Comment by Patschke** [comment]
Thanks for the note. Will change to that behaviour with PR #1118 

We could consider waiting until the announced RRG update is there - but if it is supposed to work this way, I'm fine with doing it now.
