### ISSUE TITLE
Additional unexpected search results

### ISSUE THREAD

**Issue by KMitchell-GitHub** [raithos/xwing#1117]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Card Browser - using textsearch option to browse cards. Expect to see results for the string entered in the search bar

### Actual Behavior

searched for text appears, but a number of invalid results appear as well
Ex: Searching for 'Mayfeld'. The expected result is to only have the upgrade card 'Migs Mayfeld' appear (which it does)
Additional cards that appear are:
212th Battalion Pilot
709th LEgion Ace
Baktoid Drone
Carida Academy Cadet
Colossus Station Mechanic
First Order Cadet
First Order Provocateur
Jedi General
Kijimi Spice Runner
Loyalist Volunteer
MagnaGuard Executioner
New Republic Patrol
Onyx Squadron Sentry
Outer Rim Hunter
Reaper Squadron Scout
Red Fury Zealot
Red Squadron Bomber
Separatist Predator
Shadow Squadron Escort
Shadow Squadron Veteran
Sienar-Jaemus test Pilot

### Language

English (haven't tested others)
<img width="519" alt="Screen Shot 2022-06-19 at 11 09 13" src="https://user-images.githubusercontent.com/52535738/174476022-3abc4915-fd99-478b-9fd3-579810bf91d5.png">

**Comment by Patschke** [comment]
Thanks for the report, will be fixed. There was some missplaced bracket causing issues with pilots having empty texts.
