### ISSUE TITLE
Electro Chaff information (effect of the cloud)

### ISSUE THREAD

**Issue by starjoe4** [raithos/xwing#1120]
Hi - when you select Electro Chaff Missile, the information about the device is shown but not the effect of the cloud.  That may be intentional but if the text describing the effect of the cloud could be added that would be useful.   Same suggestion for Blazer Bomb (effect of the Blaze)

**Comment by raithos** [comment]
thats intentional. it might be a bit annoying but those pieces of information have always been in the rules, and theres a rules tab to view it if you need.
