### ISSUE TITLE
Electro-Chaff Clouds - Incorrect Rules Text

### ISSUE THREAD

**Issue by sirloinsandvich** [raithos/xwing#1125]
## YASB 2.0 Bug Report

Note: I see that the rules reference section has only been updated to 1.4.2, so you may already be aware of this.

### Expected Behavior

The text under the Rules section for Electro Chaff Clouds is incorrect. It should read as follows, per RRG v1.4.3.1:

Moving through and overlapping:
The ship breaks all its locks and all locks on it and then is assigned one jam token. Roll one attack die. On a [hit] or [crit] result, the ship is assigned one stress token.

While overlapping:
The ship cannot acquire locks and cannot be locked.

### Actual Behavior

The rules text reads:

An electro-chaff cloud has the following effects on ships:
• While a ship is at range 0 of an electro-chaff cloud, it cannot be locked, jammed, or coordinated by other ships.
• While a ship executes a maneuver, if it moves through or overlaps an electro-chaff cloud, it executes its maneuver as normal. Then, it gains one jam token and breaks all locks on it. Then, the ship skips its Perform Action step this round.
• While a ship is not executing a maneuver, if it moves through or overlaps an electro-chaff cloud, it gains one jam token and breaks all locks on it.

### Language

English

**Comment by Patschke** [comment]
Actually it should read "See Obstacles", where the correct version can be found. We will update that.
