### ISSUE TITLE
T-70 Pilots x Weapon Hardpoint

### ISSUE THREAD

**Issue by lg-sabino** [raithos/xwing#1128]
Hello,

Both Nien Nunb and Karé Kun have missile and cannon upgrade slots, which don’t allow them to equip double slot upgrades such as barrage rockets and proton cannons. According to the Rules Reference, they cannot equip those because Weapon Hardpoint just allows the ship to equip a single slot upgrade. Can you help us with that?

**Comment by Patschke** [comment]
See #934

> I can see that this ruling is indeed written in a way, that one can come to the conclusion that this is not possible. However, I will still leave it as is for now for the following reason: When this ruling was written, neither T-70s nor M-3A had any Cannon/Missile slots in addition to the Hardpoint slot. For me the ruling seems to clarify that the ability `You can equip 1 cannon, torpedo, or missile upgrade.` only grants a single slot (since it is otherwise unclear if you are allowed to equip a double-slot weapon in a single hardpoint slot - it's still one upgrade card after all). I'd wait for an official explicit ruling (or the community agreeing that I am wrong) before I change that.

**Comment by raithos** [comment]
https://forums.atomicmassgames.com/topic/6455-double-upgrade-slots-and-weapons-hardpoints/

looks like its been clarified. Im pushing a fix now
