### ISSUE TITLE
Backward Attack Arch displays "true"

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#1130]
### Expected Behavior
Patrick has already seen it. He is sitting there → 
Hello

### Actual Behavior

![grafik](https://user-images.githubusercontent.com/43551730/176991770-f18af5bf-5548-4e83-9a83-3b8ccb2e65d7.png)

### Language

The affected language(s).

**Comment by raithos** [comment]
What if i dont want to change it because i find this funny

**Comment by raithos** [comment]
when i try to reproduce it, it doesnt appear. have you refreshed lately? if so, what browser are you using?

**Comment by raithos** [comment]
i fixed it anyway
