### ISSUE TITLE
Reposition of pilot ability request

### ISSUE THREAD

**Issue by FirestormSquadronfirecast** [raithos/xwing#1132]
Hi there

I had a thought when looking at lists today. It is usually quite easy to remember the stat line of a chassis. It's harder to remember specific pilot abilities. Due to screen size limitation you usually need to scroll down to see the ability.
Could the pilot abilities and stat lines be swapped so pilot ability would be shown after the ship name loadout and base size instead?
Or could it be listed directly under the pilot name where you currently have the "cards in your collection" info?

Obviously this is not essential. I  thought it may make your squad builder even MORE user friendly than it already is.
Thank you for being such an awesome part of this [community,
Nic 

![reposition of pilot ability](https://user-images.githubusercontent.com/50548376/178133736-4e5f04ba-e314-445e-8040-d2406c9ace9f.JPG)

**Comment by FirestormSquadronfirecast** [comment]
ive not put it quite in the right position but you get the idea.

**Comment by raithos** [comment]
im actually not a fan of gametext before stats, so im not inclined to do that, however, i see your point about moving gametext up, so as a compromise, i reorganized it so that theres less buffer space before text appears

**Comment by FirestormSquadronfirecast** [comment]
Fair enough bud. its your builder and I appreciate you even doing that.
you didnt have to at all.
keep up the amazing
