### ISSUE TITLE
Electro Chaff Cloud description -- include effects rules?

### ISSUE THREAD

**Issue by drdov** [raithos/xwing#1134]
## YASB 2.0 Bug Report

Can Electro Chaff Cloud describe the effects on overlap, etc in the box at the bottom of the screen?  Like Thermal Detonators do (see pic)

### Expected Behavior

See all effects

### Actual Behavior

Only lists fuse removal

![Screen Shot 2022-07-14 at 9 27 37 PM](https://user-images.githubusercontent.com/33042133/179150479-7eb2b476-39f7-4e4e-9468-1f3f7a35da5b.png)

**Comment by raithos** [comment]
at this time I have no intention to put it in the card, obstacle rules are all in one place in the rules doc, which we don't cover in the condition cards. whats in the card is the same text that is in the appendix for the specific obstacle as is consistent. I have to draw the line somewhere so here it is.
