### ISSUE TITLE
2.0 app pleeeaase

### ISSUE THREAD

**Issue by YautjaDreads** [raithos/xwing#1135]
We demand an app! Long live 2.0!

**Comment by Patschke** [comment]
How comes that you demand anything at all here from us? Be thankful that the 2.0 app is still online (https://raithos.github.io). We do maintain this project (as 2.5 running at https://yasb.app) in our free time without getting paid or being affilitated with AMG in any way. Go maintain your own 2.0 app if you want to (YASB is open source. We can surely help you to get started if you are interested), but don't demand anything to be done at all. If at all, politely ask if you want to have something.

**Comment by YautjaDreads** [comment]
I totally didn’t mean to sound aggressive, I honestly wasn’t even expecting a response back, which is awesome.

I’m new to X-Wing, but was there before AMG. I found out that none of the mobile apps support 2.0 anymore which bummed me out. I wish I was skilled enough to create my own app for 2.0, but I know nothing, especially since I’m new to X-Wing. 

Man, that’s awesome that you guys are keeping it online, I will totally donate to show appreciation. Thank you
