### ISSUE TITLE
Components printout list

### ISSUE THREAD

**Issue by meftyster** [raithos/xwing#1138]
I have an idea, that can help new players! Can we have a printout export of the list in form of components you need to gather for the list: ship models / bases (number of small/medium/large) / dials / pilot tokens / pilot cards / upgrade cards (with ther slot type) / tokens (number of double-turret/single-turret/shields/charges/force/focuses/evades/calculates/reinforces and etc.)?

**Comment by raithos** [comment]
So we already have something like this. If you build a list and get the warning that you cant field the list with your current collection, hovering over it shows in the right sidebar all of the missing expansions to field the list. In addition, any upgrade or pilot that is not in your collection when you build shows up with red text. Of course, you need to be logged in and with a collection to see these features, but I guess I need more convincing that what you're suggesting is doing more than what what these features already provide.

On a side note, I have no intention of tracking what tokens people need to bring for a list. That seems like a lot of work for little real payoff.

**Comment by Patschke** [comment]
I agree with raithos and am also not going to implement anything further in this direction. Most of the stuff you list is fulfilled trivially anyway if you have the required cards and ships (if you have a ship model, you'll also have a matching dial, base and all cardboard (shield, focus, evade, calculate, ...) required for that ship in the same expansion. Same goes for other stuff, e.g. a bomb card will always come with that bombs cardboard). The answer to the question "which expansions to buy for fielding a specific squad" isn't clear anyway, as most cards are available from a bunch of different expansions (would you rather buy one expansion from a faction you don't play, which contains two cards you need, or buy two expansions from factions you do play, that each contain one card? Two small ship might even be cheaper than a large one. etc.). 

If you wonder "what do I need to pack to have a everything together I need" I recommend that you have one squad-agnostic box of stuff that you always grab (maneuver templates, damage deck, dice, a sufficient set of bases, tokens and other cardboard,...) and just add the cards+ships+dials for whatever squad you wanna field right now.

**Comment by raithos** [comment]
Im going to close this for now, if you have a good counter argument I'm happy to reopen this again and review
