### ISSUE TITLE
Card Search and huge/epic/unreleased content

### ISSUE THREAD

**Issue by meftyster** [raithos/xwing#1141]
Exclude all EPIC/huge ship content and unreleased content (pilots) from the search when the **Standard legal** check box is applied.

**Base size** _Huge_ check box is not working? Example: Trident (Trident-class Assault Ship Huge ship title). It appears as a search result only when _Small_, _Medium_ and _Large_ boxes are all checked. Checking or unchecking _Huge_ does nothing. Unchecking any one of _Small_, _Medium_ or _Large_ boxes make the search result disappear. Same thing for Command Upgrades and every other type.

**Comment by raithos** [comment]
fixed the huge filter bug, will not fix the command upgrades, we don't know the legality of the upgrades and if they ever add a command slot to a standard ship I'd rather not have to recode something when right now its working fine.

**Comment by meftyster** [comment]
So now Huge Ship pilots are just gone from the card browser, while Huge command cards, hardpoints and etc (that have huge as a retrictions printed on the card, it's not just a type of a slot exclusive to a huge ship) and Huge ships are still in. Also manipulating Small, Medium, Large, Huge check boxes now collapses the list to pilots and ships (except Huge, cuz huge pilots are gone). Is that by intention? For example now you can't find all the upgrades that have small ship restriction.

**Comment by raithos** [comment]
that's working as intended. huge pilots don't show up because the default init is set from 0-6, but huge ships are init 7 and 8.  Change the setting and they show up. 

Collapsing them to pilots only is working as intended as well, those tags were never meant to determine the restrictions for cards. There is no current tag on sorting by restriction, its something we can possibly add at a later time.

**Comment by Patschke** [comment]
Maybe we can set the default init range to 0-10 instead of 0-6. Won't matter much, but I can see that people would expect everything to show up in default settings, and not everything but epic pilots.

**Comment by meftyster** [comment]
Also Huge pilots have double initiative, on of them is 0 btw
