### ISSUE TITLE
Sabine Wren Command Crew

### ISSUE THREAD

**Issue by Ccwebb** [raithos/xwing#1142]
I cannot load Sabine Wren, command/crew, in any ship.  The website also shows her cost is 99 points.  

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Ccwebb** [comment]
I cannot load Sabine Wren, command/crew, in any ship.

**Comment by Patschke** [comment]
I guess everything is working as intended. There is: 
  * Sabine Wren (Crew), 3 points, banned in standard and legal in extended
  * Sabine Wren (Gunner), 2 points, legal in standard and extended
  * Sabine Wren (Command + Crew), ? points, epic only
As long as all epic cards are not included in the latest points document, we list the old cards with their last point value, but fill in 99 for new ones. I hope that there will be points for epic ships&upgrades somewhen soon, but I don't really see what we can do about that.

**Comment by Ccwebb** [comment]
Ok.  Thank you for the quick response, I was afraid I was miss reading or doing something wrong.

Thank you,

Chris

Sent from my R2 unit.

On Aug 9, 2022, at 01:34, Patrick Mischke ***@***.***> wrote:

﻿

I guess everything is working as intended. There is:

  *   Sabine Wren (Crew), 3 points, banned in standard and legal in extended
  *   Sabine Wren (Gunner), 2 points, legal in standard and extended
  *   Sabine Wren (Command + Crew), ? points, epic only
  *

As long as all epic cards are not included in the latest points document, we list the old cards with their last point value, but fill in 99 for new ones. I hope that there will be points for epic ships&upgrades somewhen soon, but I don't really see what we can do about that.
