### ISSUE TITLE
Multiple Imperial ships - Incorrect upgrade slots

### ISSUE THREAD

**Issue by Rydiak** [raithos/xwing#1145]
Is listed as having two modification slots, but only has one

**Comment by Patschke** [comment]
Will be fixed, thanks for the note!

**Comment by Patschke** [comment]
Did they recently and silently change that, without updating the effective-date of the document? :thinking: 

The German document actually does (still?) show two mod slots (https://asmodee-resources.azureedge.net/media/germanyprod/Anderer%20Bonuscontent/Star_Wars_X-Wing_Schiffspunkteliste_15-06-2022_v2.pdf). In case of doubt the English version is of course the officially correct one, but I wonder why we have so many stuff wrong.

BTW: you can just create one issue for all the stuff you found :smile:

**Comment by Rydiak** [comment]
https://www.atomicmassgames.com/s/SWZ_Ship_Points_062022.pdf

**Comment by Patschke** [comment]
I'm aware that you are correct and those are the slots according to the latest official document. I'll update YASB. But I still wonder why there are so many differences - it seems unlikely to me, that we just made up all those additional slots? Though it is for sure not impossible - we might have wrongly copied stuff over from whoever is the first pilot in a ship, and did not remove double slots for the other pilots. 

Thanks for spotting all those mistakes!

**Comment by Rydiak** [comment]
TIE/sk Striker - Duchess: -1 mod slot
TIE/sk Striker - Pure Sabacc: -1 mod slot
TIE/rb Heavy - Lyttan Dree: -1 mod slot
TIE/rb Heavy - Rampage: -1 mod slot
TIE Advanced X1 - Ved Foslo: -1 talent, -1 mod slot
TIE Advanced X1 - Zertik Strom: -1 talent slot
TIE Advanced X1 - Tempest Squadron Pilot: -1 mod slot
TIE Advanced X1 - Storm Squadron Ace: -1 missile, +1 talent slot

**Comment by raithos** [comment]
i'll push this live later tonight when i get home
