### ISSUE TITLE
Adding IG-88D Crew does not add calculate icon to action bar

### ISSUE THREAD

**Issue by Nick-Hansen** [raithos/xwing#115]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

When I add IG-88D crew member to the YT-1300, I should see the calculate icon in the action bar for the ship

### Language

English

**Comment by raithos** [comment]
fixed
