### ISSUE TITLE
Missing Upgrades From Collection

### ISSUE THREAD

**Issue by CaughtJesting** [raithos/xwing#1152]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

I purchased a new ship (Republic Arc-170) and added it to my collection. The cards within the expansion should now be accessible to me in list building.

### Actual Behavior

Some cards such as "Novice Technician" "Ion Torpedoes" & "Perceptive Co-pilot" are still in red and do not show up in my inventory.

### Language

English
![Screen Shot 2022-08-18 at 1 39 46 am](https://user-images.githubusercontent.com/111447677/185182877-8be8cced-3bb0-45d6-9664-bbee9c06f9a0.png)
![Screen Shot 2022-08-18 at 1 38 07 am](https://user-images.githubusercontent.com/111447677/185182885-305af286-8d0b-47ca-91c8-9b3cd26e8132.png)
![Screen Shot 2022-08-18 at 1 40 06 am](https://user-images.githubusercontent.com/111447677/185182901-9409461f-5574-4fcd-8f5f-7421fe7d05c3.png)

**Comment by Patschke** [comment]
Thanks for the note, I checked what is listed in the wiki to add the missing cards.
