### ISSUE TITLE
Scum Modified TIE/ln Fighter has the wrong name

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#1154]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Ship name for scum TIEs should be: Modified TIE/ln Fighter

### Actual Behavior

Ship name for scum TIEs appears as: Mining Guild TIE Fighter

### Language

English

**Comment by chrisalleng** [comment]
![image](https://user-images.githubusercontent.com/3527305/185476312-e76f07ba-a90f-4a69-bc6c-feac21df6a3e.png)

Example card w/ text for ship name

**Comment by raithos** [comment]
be aware that your note resulted in 3 hours of rework

**Comment by chrisalleng** [comment]
> be aware that your note resulted in 3 hours of rework

i do love making work
