### ISSUE TITLE
tie whisper tech upgrade issue 

### ISSUE THREAD

**Issue by WOLF-VIPER112** [raithos/xwing#1159]

**Comment by Patschke** [comment]
For me everything works as it's supposed to. The Enhanced Jamming Suite occupies the second slot, but after removing it you can use it just fine. The jamming suite is automatically equipped, since it's a 0 points upgrade you almost always want to play. I don't think we want to remove that feature.

**Comment by raithos** [comment]
without any more info as to whats broken, i think i can close this
