### ISSUE TITLE
Ship with translated names missing when selecting "Second Edition" game type

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#116]
### Expected Behavior

When creating a Scum squad with the "Second Edition" game type selected, I should be able to choose from 4 ships: Escape Craft, Fang Fighter, Firespray and YT-1300 (Scum). This works when English language is selected.

### Actual Behavior

When french language is selected, only the Firespray is available. When german language is selected, no ship is available. It seems that ships with translated names don't show up.

### Language

Able to reproduce with french and german.

**Comment by Patschke** [comment]
Working on a fix.
