### ISSUE TITLE
Limited Tri Fighter Pilots Break Autoassignement of Independent Calculations

### ISSUE THREAD

**Issue by quall3** [raithos/xwing#1165]
If i select multiple limited Tri Fighter pilots and equip one of them with Independent Calculations, it does not auto equip the other pilots with the same upgrade. 

If i try to equip a second pilot manually with that upgrade, it unequips it from the first one.

**To Reproduce**
1.Go to separatists
2. Select 2 Limited Tri fighter pilots
3. Equip one of them with Independent Calculations
4. The other does not get auto equipped with that upgrade
5. manually equip the other pilot with Independent Calculations
6. first pilot gets unequipped that upgrade

**Expected behavior**
Equipping one Limited Tri Fighter Pilot with Independent Calculations should automatically equip every other limtied PIlot with that upgrdae.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - V102.0.1esr (64-Bit

**Comment by quall3** [comment]
Just checked, Same for Rogueclass Pilots.

**Comment by Patschke** [comment]
Ah, I guess there is some issue with having two mod slots.

**Comment by raithos** [comment]
yeah this is a popup issue related to another issue that i fixed with double mod standard upgrades. I have a fix for this but i got sidetracked, hopefully in the next few hours

**Comment by raithos** [comment]
Im going to do some more work on this.
