### ISSUE TITLE
Gauntlet Fighter Commandos Bug

### ISSUE THREAD

**Issue by tayjacobs11** [raithos/xwing#1167]
**Describe the bug**
**The Gauntlet Fighter on the Rebel Faction cannot equip the Clan Wren Commandos even though you have two crew member slots available when the Nightbrother upgrade is equipped. **

**To Reproduce**

1. Go to 'Rebels and equip the Gauntlet Fighter with Nightbrother.'
2. Click on 'Crew drop-down and try to equip Clan Wren Commandos.'
4. See error (Clan Wren Commandos is greyed out and you cannot select them.

**Expected behavior**
Clan Wren Commandos come with the Gauntlet fighter pack and should be able to be equipped.

**Screenshots**
![2022-09-21](https://user-images.githubusercontent.com/114128329/191657404-6116fd1f-4a4d-4a6f-9989-1fe2ec03e213.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge and Firefox
 - Version ???

**Additional context**

**Comment by Patschke** [comment]
Clan Wren Commandos is unique. In the screenshot above you already have it equipped to the Falcon, so you can't equip it for the Gauntlet as well (though you tried to hide that piece of information from the screenshot it is still given away in the URL, where W450 is the ID of Clan Wren Commandos). 

From what I can tell everything works as intended here.
