### ISSUE TITLE
Corran Horn Missing

### ISSUE THREAD

**Issue by lg-sabino** [raithos/xwing#1170]
The pilot Corran Horn is missing in the list of pilots for the E-wing in the extended Rebel listing.

**Comment by Patschke** [comment]
Seems like he, got overwritten with the new X-Wing Corran-Horn. Will be fixed. Thanks for the note

**Comment by lg-sabino** [comment]
I see… We thank you! :)

On 4 Oct 2022, at 9:44 AM, Patrick Mischke ***@***.***> wrote:

﻿

Seems like he, got overwritten with the new X-Wing Corran-Horn. Will be fixed. Thanks for the note

**Comment by raithos** [comment]
will resolve this tonight
