### ISSUE TITLE
Can't add ship - Separatist Alliance

### ISSUE THREAD

**Issue by Brachinus** [raithos/xwing#1172]
When choosing the faction "Separatist Alliance" the "select a ship" dropdownfield is missing.
![image](https://user-images.githubusercontent.com/15608219/194412918-b5804e38-522e-4fab-b1e1-8a3f008b71b3.png)
![image](https://user-images.githubusercontent.com/15608219/194412967-8bf424a1-5a68-4842-8acc-4a2032a2f202.png)

**Comment by raithos** [comment]
this should be resolved
