### ISSUE TITLE
Vectorized Cannons (RZ-1) and Saving?

### ISSUE THREAD

**Issue by billfrank** [raithos/xwing#1173]
**Describe the bug**
Lists that include "Vectorized Cannons (RZ-1)" on a Rebel RZ-1 A-Wing will not load correctly after they have been saved.

**To Reproduce**
1. Create a new list with at least 1 A-Wing w/ "Vectorized Cannons (RZ-1)"
2. Save List
3. Load List
4. See Error (Vectorized Cannons won't show, ships after the A-Wing don't show, new ship add button is missing)

**Expected behavior**
List should be the same after load as it was when it was saved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (but also happens on iOS)
 - Browser Edge (but also on iOS Safari)
 - Version Up to Date

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 16.0
 - Browser Safari
 - Version Stock

**Additional context**
They may also be some related weirdness when 2 A-Wings try to have Vectorized Cannons but not 100% consistent and maybe I'm missing rules.
![Screenshot 2022-10-07 081217](https://user-images.githubusercontent.com/3923383/194551116-d7e9e9ae-722d-4ea0-9be8-4c908032bfb0.png)
![Screenshot 2022-10-07 081150](https://user-images.githubusercontent.com/3923383/194551119-6681c778-39bd-4c8f-8bac-0ee09a3f692c.png)

**Comment by raithos** [comment]
this should be resolved
