### ISSUE TITLE
Collision Detector not appearing in card browser

### ISSUE THREAD

**Issue by KMitchell-GitHub** [raithos/xwing#1174]
**Describe the bug**
Attempts to see Collision Detector in the Card Browser returns zero results

**To Reproduce**
1. Go to Card Browser
2. Click on Textsearch
3. Type collision detector
4. See error - No results

**Expected behavior**
Expect to see Collision detector in the search results

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Chrome
 - Version 106.0.5249.91

**Smartphone (please complete the following information):** 
 NA

**Additional context**

**Comment by Patschke** [comment]
Thanks for the note. Will be fixed. We made a mistake when adding `Juno Eclipse`, preventing everything after that in the internal search order from showing up.
