### ISSUE TITLE
Pilot Names Won't Show Up In Card Browser While Searching

### ISSUE THREAD

**Issue by P199Y-07** [raithos/xwing#1175]
**Describe the bug**
When I searched for a pilot in the card browser, no pilot name showed up — only a few upgrade names.

**To Reproduce**
1. Go to Card Browser
2. Type any pilot name into the textsearch (e.g. 'Wedge Antilles')
4. See error - no results

**Expected behavior**
The pilot name should show up but it doesn't.

**Screenshots**
![Screenshot (48)](https://user-images.githubusercontent.com/99363322/194725978-f1410b85-3717-472a-be09-94afbcb90c42.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 22H2

**Additional context**
I definitely didn't have any filters on. The names just simply wouldn't show up.

**Comment by Patschke** [comment]
Thanks for the note. Will be fixed. We made a mistake when adding `Juno Eclipse`, preventing everything after that in the internal search order from showing up.
