### ISSUE TITLE
Card Search won't report any matches after Devices in the card list

### ISSUE THREAD

**Issue by thelogicdump** [raithos/xwing#1176]
When searching card text, no card after "Devices" in the card list will be returned.

**To Reproduce**
1. Go to Card Search.
2. Type "Therm" in "Text Search"
3. You will see "Thermal Detonators" in the list of cards.
4. Type "104" in "Text Search"
5. You will see no cards in the card search even though there is a pilot "104th Battalion Pilot" in the card list if "Text Search" is left blank.

**Expected behavior**
I would expect the card search to return all matches, not the current subset.

**Desktop (please complete the following information):**
- OS Windows
- Firefox v104.0.2

**Comment by Patschke** [comment]
Thanks for the note. Will be fixed. We made a mistake when adding `Juno Eclipse`, preventing everything after that in the internal search order from showing up.

**Comment by thelogicdump** [comment]
Thanks guys,

I assumed it was something like that. It is usually the simplest things that cause issues like this.

love your work and keep it up
