### ISSUE TITLE
Gar Saxon crew says Friendly Unit. You have it saying friendly ship.

### ISSUE THREAD

**Issue by Echowhisper** [raithos/xwing#1178]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
Thanks for noting, will be fixed (interestingly the [wiki](https://xwing-miniatures-second-edition.fandom.com/wiki/Gar_Saxon_(Crew)) has the same bug in the text, while the image of the card proves you right...)

**Comment by Echowhisper** [comment]
Thats why there is a debate on if theybworknon Commandoes or notSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Patrick Mischke ***@***.***> Date: 10/13/22  2:10 AM  (GMT-05:00) To: raithos/xwing ***@***.***> Cc: Echowhisper ***@***.***>, Author ***@***.***> Subject: Re: [raithos/xwing] Gar Saxon crew says Friendly Unit. You have it
  saying friendly ship. (Issue #1178) 
Thanks for noting, will be fixed (interestingly the wiki has the same bug in the text, while the image of the card proves you right...)
