### ISSUE TITLE
Gar Saxon Crew wording is incorrect

### ISSUE THREAD

**Issue by Absolutsurgen** [raithos/xwing#1180]
Gar Saxon crew says"
" While a friendly ship at range 1-3 with an initiative of 4 or lower ..."
it should say
" While a friendly **unit** at range 1-3 with an initiative of 4 or lower ..."
https://media.discordapp.net/attachments/423853799614971914/1029901191024484402/received_653388376387472.jpg

**Comment by Patschke** [comment]
Duplicate of #1178
