### ISSUE TITLE
List corrupted on point cost change

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#1187]
When I load previous squads with a saved URL I realize I lost loadout items from several ships since point cost cannot exceed specific value of each pilot, but I LOST the upgrades, so I do not know what was included before points change. 

So in my humble opinion the app should allow exceed the limit of loadout in a pilot but warn you that is not legal.

**Comment by Patschke** [comment]
Use yasb.app/old if you want to load old lists. We won't support building invalid lists, since that would end up in chaos.

**Comment by negroscuro** [comment]
I see, but the problem is that all my web browser tabs containing lists... when loading, they lose the original list, so I have no way to recover the original list URL since it is updated for the current-fixed-list once it is loaded so thats late to do anything...
:(

**Comment by Patschke** [comment]
Disconnect your device from the internet, then click a tab. This should usually not change the URL, so you can save it or add the /old in between.

**Comment by negroscuro** [comment]
Cool, thank you for the tip, I will try that :D

**Comment by raithos** [comment]
this is just a really bad way to manage your lists. make an account and save your lists with our list saving system!
