### ISSUE TITLE
Atomic Mass is wrong

### ISSUE THREAD

**Issue by TimTheITGuy** [raithos/xwing#1192]
**Is your feature request related to a problem? Please describe.**
Atomic Mass games has not given Boba Fett the Mandalorian keyword. They are wrong. In Legends he was THE Madalore, and even in canon, he has mando-only upgrades.

**Describe the solution you'd like**
A checkbox for characters like Boba Fett to grant them keywords they haven’t yet been given. I cannot think of any other examples at the moment.

**Describe alternatives you've considered**
Unlimited mode: all upgrades and ships available without point, faction, keyword, uniqueness, or other restrictions.

**Additional context**
I play casual epic games with rules that are scenario play & having a mode that allows non-std lists would be helpful.

**Comment by raithos** [comment]
Sir, this is a Wendy's.
