### ISSUE TITLE
New Standardized Loadout Talents like Fanatic Vengeful listed as unreleased

### ISSUE THREAD

**Issue by lemonadesunshine365** [raithos/xwing#1195]
The Fanatic and Vengeful Talents are listed as unreleased, despite the Battle of Yavin Pack having been released. I expect this is because the app doesn't list sources for Talents that are exclusive to standardized loadouts.

**Comment by raithos** [comment]
correct. i dont have any intention to do so either, since theyre inherently tied to the pilot cards.
