### ISSUE TITLE
Second Delta-7 miniature listed as owned in dropdown menu

### ISSUE THREAD

**Issue by lemonadesunshine365** [raithos/xwing#1196]
I noticed that the Delta-7B is displayed as an available miniature in my collection while I have the standard Delta-7 already included in my squadron and vice versa. As I only have a single Delta-7 miniature in my collection, the other Delta-7 variant should be displayed in the red missing item text in the dropdown menu.
![Screenshot (1)](https://user-images.githubusercontent.com/100968130/201019870-e02e4317-8829-461c-b8f2-8f954804a9e9.png)

**Comment by raithos** [comment]
this is a limitation of the system we use, the 7 and 7b are considered discreet different objects so we have to consider them separate ships even though they use the same model. I could create a unique workaround but it doesnt seem worth it at this time until we run into a situation were another ship has a completely different loadout but uses the same model.
