### ISSUE TITLE
Pops y-wing BOY 

### ISSUE THREAD

**Issue by grim0126** [raithos/xwing#1199]
**Describe the bug**

Rebel BOY y-wing pops is listed as 20 points??

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  iPhone11

**Additional context**

**Comment by raithos** [comment]
https://puu.sh/Jry9W/3c321cfe24.png
this is what i see. what are you seeing?
