### ISSUE TITLE
Just Typos

### ISSUE THREAD

**Issue by ScumMan47** [raithos/xwing#12]
Hi Raithos.  Thank you for putting this together.  We at the X-Wing community appreciate you and the time you've taken to keep this up.  Going through the process of putting together lists from pdf files is a pain and though I purchased a core set and conversion kits at Gencon I haven't opened any, because at the moment I don't have the time to put lists together.  Now with the help of this update I am excited to open up my sets and get to work.  Thank you again.  May the Lord bless you with greatness.

I did notice some typos on some of the cards.  You should take a look at Gunner - Bistan.  It says shipe instead of ship.  I will provide you more of these when and I see them again.  I know I saw a few more.  If you are interested in fixing some of these I will let you know where I see them.  Thank you.

## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by raithos** [comment]
will be addressed in the next update
