### ISSUE TITLE
Error on BoY Dutch

### ISSUE THREAD

**Issue by mrkyle4** [raithos/xwing#1202]
Really just a simple fix, you have him as I4 but this version he is an I5. That's all :)

**Comment by raithos** [comment]
this is incorrect. he was errated to i4

**Comment by Patschke** [comment]
Maybe we should add an `errata` property to our cards as distinct property from the text. This would on one hand allow us to have a statement for stuff like that somewhere. On the other hand it would allow to include erratas for languages which do not receive official errata documents (where we can't simply update the card text). Perhaps I'll look into something like that.

**Comment by raithos** [comment]
On the english translations I do include errata text at the bottom already, its written in under the card ability. In fact BoY Dutch HAS such an errata listed on its gametext already. I don't think we need to do anything, If people are missing that theyre not going to notice it anywhere.
