### ISSUE TITLE
Simple function to add

### ISSUE THREAD

**Issue by Tharlin-DE** [raithos/xwing#1205]
Could you add a simple "win / loss" counter for each save list?
So that people can track how their lists performed?

Would help a lot to keep an overview over list performance.

**Comment by Patschke** [comment]
Hi Tharlin,
there is a box for arbitrary squad notes near the bottom of the page. Nothing stops you from having win/loss counters in there. The squad notes are also displayed in the squad loading screen, so you can easily keep an overview of the performance of different lists. 

I'm not sure that I see a benefit in a dedicated win/loss counter - perhaps you can elaborate why the existing notes do not work for what you want to do and in which way a win/loss counter should behave differently from those to be an actual improvement (without cluttering the UI for a "normal" user that just wants to use a squad builder to build squads - after all that's what our main goal is)?

**Comment by raithos** [comment]
I'm also of the opinion that a win/loss counter isn't necessary for the site. i know some people do track but there have always been ways to do that that did not require a dedicated integration with list builders. As @Patschke suggests, just adding that to notes should be sufficient to keeping track. Outside of that, I personally have no interest in coding something like that
