### ISSUE TITLE
initiatives errata

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#1206]
SCUM
Modified TIE fighter- Lapin --> initiative should be 3.
https://forums.atomicmassgames.com/topic/8322-lapin-pilot-base-vs-card-initiative-discrepancy/

CIS
Vulture - Kelrodo-Ai holdout --> initiative should be 1.
https://forums.atomicmassgames.com/topic/8325-kelrodo-ai-holdout-initiative/

**Comment by raithos** [comment]
this is already done
