### ISSUE TITLE
Add Syliure-class Hyperspace Ring to Standard and Extended formats?

### ISSUE THREAD

**Issue by lemonadesunshine365** [raithos/xwing#1208]
I'm wondering how this would be best implemented, but the Hyperspace Ring is legal in the Siege of Coruscant scenario. Adding it to Standard and Extended wouldn't exactly be accurate since it isn't available in those formats. Should there be a Siege of Coruscant format one can toggle, where Republic players can list build to 20 and place 2 free Standardized Loadout ships in reserve (plus up to 2 Hyperspace Rings if the ships are compatible), while the Separatist can build to 25 points? I know it would be a hyperspecific thing to implement.

**Comment by raithos** [comment]
i mean, why does it need to be in the builder at all? aren't the hyperspace rings just addons based on player choice and not a part of listbuilding at all? like the rings dont decrease your total listbuilding points do they?

**Comment by lemonadesunshine365** [comment]
I suppose they are technically free to add to the also free of charge Republic reinforcements in the scenario (should they be a standardized Eta or V-wing), but there is confusion over whether or not the Hyperspace Docking Ring ability is available in scenario play. They provide the mechanical benefit of the Syliure-31 Hyperdrive upgrade by default in scenario play, with the added stipulation that ships must be placed beyond range 3 of the Invisible Hand. Perhaps the ring has no Hyperdrive upgrade slot since it's baked into the rules.

**Comment by raithos** [comment]
i'm going to close this issue. if it gets points, or if it becomes legal for standard, we can revisit it.
