### ISSUE TITLE
Stop displaying unowned items in red text when "Check Collection Requirements" is disabled

### ISSUE THREAD

**Issue by heckinahandbag** [raithos/xwing#1213]
**Is your feature request related to a problem? Please describe.**
The red text on white when I don't own an item is significantly harder for me to read. It takes much more effort than the higher contrast black on white. I don't own and don't plan to own X-wing, I play exclusively with my friends' lists or online over Tabletop Simulator

**Describe the solution you'd like**
I'd like all items to be shown in black text when *Check Collection Requirements* in *Your Collection* is unchecked. Similarly to the behavior when logged out.

**Comment by raithos** [comment]
this already works, you just need to refresh the page after checking the box to blank.
