### ISSUE TITLE
Various upgrades not showing in the textsearch

### ISSUE THREAD

**Issue by P199Y-07** [raithos/xwing#1215]
**Describe the bug**
Many upgrades are not showing up in the textsearch. Some include Outmaneuver, Shield Upgrade, Marksmanship, Ion Torpedoes, Proton Torpedoes, Concussion Missiles, Cluster Missiles, and probably more.

**To Reproduce**
1. Go to Card Browser
2. Enter any of the upgrades above
3. Results do not show up

**Expected behavior**
Upgrades should show up but they don't.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108.0.5359.125

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
https://puu.sh/Jv5lS/f24859c033.png
seems to be working fine for me. do you have any other information? otherwise i will close this

**Comment by P199Y-07** [comment]
That's weird...
I tried logging out and switching profiles it was working just fine, but when I logged back into my main account I had the same issue. I also don't have any filters on so I'm unsure of what to do. Do you know what could be the cause of this?

![Screenshot (135)](https://user-images.githubusercontent.com/99363322/209689638-2c55f206-85d3-4d2f-86f4-c0b4547dda64.png)

**Comment by P199Y-07** [comment]
That's weird...
I tried logging out and switching profiles it was working just fine, but
when I logged back into my main account I had the same issue. I also don't
have any filters on so I'm unsure of what to do. Do you know what could be
the cause of this?
