### ISSUE TITLE
Rogue Class Fighter - Durge - Scum - X-Wing 2.5

### ISSUE THREAD

**Issue by innseanach** [raithos/xwing#1216]
**Describe the bug**
Durge — Rogue-class Starfighter for X-Wing 2.5 does not seem to be built out.

**To Reproduce**
1. Go to 'YASB for X-Wing 2.5 Scum (https://yasb.app/old/?f=Scum%20and%20Villainy&d=v9ZhZ20Z&sn=Unnamed%20Squadron&obs=)’
2. Click on 'select a ship’
3. Scroll down to 'Rogue-class Starfighter’
4. Click on ‘pilots drop down’
5. Select “Durge”
6. See that the pilots point value is not correct (20/99 not 4/10) and that the load outs are not reflected correctly (missing 2 talent drop-downs, 2 cannon drop-downs, and 1 illicit drop-down)

**Expected behavior**
Change the point values and update the drop downs associated with the Durge pilot

**Screenshots**
![BDC6982E-DCC5-4914-B35F-C6A94473041F](https://user-images.githubusercontent.com/121647636/210024750-7a987636-dfa2-4f02-8ece-445a88faf172.jpeg)
![4238B5B0-903B-457C-84CA-596D82789EED](https://user-images.githubusercontent.com/121647636/210024751-134b9a12-c7ea-46be-8cbe-689d93de92d8.jpeg)
![EB91C9FB-DDE6-413F-AE4D-C2E4F8A14881](https://user-images.githubusercontent.com/121647636/210024752-638d6e3c-baa4-431d-970f-82c9dda3b1a3.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS16.2
 - Browser: safari
 - Version: 16

**Additional context**
X-Wing 2.5 points list 
https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/638e0ec5ea9ee118b32b499e/1670254279113/SWZ_Ship_Points_11252022_v2.pdf

**Comment by raithos** [comment]
youre on the wrong yasb. youre using yasb.app/old. YOU CAN TELL BY THE COLOR.
