### ISSUE TITLE
Coruscant "unreleased" & Not enough cards

### ISSUE THREAD

**Issue by Ijighen** [raithos/xwing#1218]
**Describe the bug**
Error #1 :The website tells me Battle over Coruscant pilots are "unreleased content"
Error #2: Kelrodo-Ai Holdout's card is included 3x in Hotshots and Aces II reinforcement pack, but the website tells me I have only one

**To Reproduce**
1. Create a CSI list
2. Add any BoC-exclusive pilot
3. the alert "This squad uses unreleased content!" appears

**Expected behavior**
Error #1: the alert should no longer be visible since BoC has been released.
Error #2: Adding 1 Hotshots and Aces reinforcement pack to the collection should add 3 Kelrodo-Ai Holdout cards to the collection

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by raithos** [comment]
boc ships have been assigned for a while now. they are not listed as unreleased for me. fixed the error for holdouts
