### ISSUE TITLE
Translated ship names turns into english when a ship is selected

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#122]
### Steps to reproduce

1. Choose Deutch language
2. Create a new squadron
3. Add "BTL-A4-Y-Flügler" ship to the squadron

### Expected Behavior

Should display " BTL-A4-Y-Flügler" as the selected ship

### Actual Behavior

Displays "Y-Wing". Sometimes this only happens after selecting another pilot.

### Language

French and deutsch at least.

![sans titre](https://user-images.githubusercontent.com/5627688/46242284-36cb4700-c3c7-11e8-8b00-cc3a054b5777.gif)

**Comment by Patschke** [comment]
I'll have a look at this, but not today. Probably I forgot changeing a name to display_name somewhere. 
I kind of expected that this could happen somewhere, if it is only this single location I'm happy

**Comment by raithos** [comment]
this is the gold standard of bug report submitting
