### ISSUE TITLE
German translation for 'Pivot Wing' is missing one (vital) sentence

### ISSUE THREAD

**Issue by fmkuhn** [raithos/xwing#1221]
**Describe the bug**
Don't know if this is the right place for this kind of issue, but I'll put it here anyway since I didn't find any other place to put it.

The german translation of the card 'Pivot Wing' (in german 'Schwenkflügel') is missing the translation of the first sentence of the **Closed** state ("While you defend, roll 1 fewer defense die."). The missing sentence in german is

> Solange du verteidigst, wirfst du 1 Verteidigungswürfel weniger.

**To Reproduce**
1. Switch to german
2. Choose a rebel squad
3. Add a "UT-60D-U-Flügler", the 'Schwenkflügel' will already be preselected
4. See the text of the card is missing the above sentence

**Expected behavior**
Correct and full translation

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17848428/212014263-eb474f4d-ee28-4b89-88ef-fb72aab5ff7d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 108.0.2

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 11
 - Browser Firefox
 - Version 108.0.2

**Additional context**
Picture of the card:
![IMG_20230112_090909](https://user-images.githubusercontent.com/17848428/212013815-9e4be5ca-177a-49cf-87ea-bec5c5dadddb.jpg)

**Comment by Patschke** [comment]
Ja, du bist hier völlig richtig. Das ist mir wohl irgendwie durchgegangen, wird behoben werden - danke für den Hinweis.

**Comment by fmkuhn** [comment]
> Ja, du bist hier völlig richtig. Das ist mir wohl irgendwie durchgegangen, wird behoben werden - danke für den Hinweis.

Danke Dir! Haben gerade wieder mit X-Wing angefangen und ich hatte die Sachen nur ausgedruckt dabei und mich gewundert, dass die Seite keinerlei Nachteil hat 😁

**Comment by Patschke** [comment]
Wird mit dem nächsten Update online sein. 

Leider bin ich in "letzter Zeit" (eine inzwischen eher längere letzter Zeit) nicht mehr dazu gekommen, überhaupt deutsche Übersetzungen zu erstellen. Früher konnte ich die automatisiert aus dem offiziellen Builder auslesen, aber den gibt's ja nicht mehr. Aktuell müsste ich also händisch die Kartentexte abtippen - das sorgt dafür, dass alle "neueren" Karten leider nur auf Englisch da sind. Zumindest Errata pflege ich aber ein, da falsche Kartentexte irgendwie doof wären - insofern gut aufgepasst, ohne Nachteil ergäbe das tatsächlich wenig Sinn. 

Viel Spaß mit und willkommen bei X-Wing, vielleicht läuft man sich ja eines Tages mal auf irgendeinem Event über den Weg ;-)
