### ISSUE TITLE
Export Collection Option

### ISSUE THREAD

**Issue by InblEric** [raithos/xwing#1227]
Please let me know if I should open this issue elsewhere! I saw there is a backend repo which is probably where this would be developed but the feature request on the squadbuilder page led me here.

Also, I believe this has been suggested before but not done as you can just copy paste your collection manually. However as I mention below if nobody wants to do this I may be interested in taking a stab at it in the future myself.

**Is your feature request related to a problem? Please describe.**
As is common with board games or related hobbies, interest comes and goes and projects fade or stagnate. This project is fantastic, but like previous squad builders, it is possible it will become unaccessible in the future. For example, I can't log in to the very original YASB to view my 1.0 collection anymore. Hopefully this version will continue on for a long time, but it won't last forever (no offense intended).

**Describe the solution you'd like**
I would love a way to export the entirety of my collection to a csv, simple text, etc. Something that shows all the expansions I marked as owned, all the individual ships I own, etc. A full view of my collection represented in the squad builder in case I ever lose access for whatever reason. It could download the file directly, email it to the user's email when the export is ready, or something else.

I've considered making this contribution myself, and am not opposed to doing so, but I am unfamiliar with coffeescript and ruby, so if anyone else is interested in this feature, assistance would be great.

**Describe alternatives you've considered**
Alternatives right now consist of manually copy-pasting, taking screen shots, or keeping a running list on my own which I would have to keep in sync with my collection here.

**Additional context**
N/A

**Comment by raithos** [comment]
there's a tab at the end of the collections area called inventory, which does exactly that sans expansions (which is less relevant if all cards are accounted for). It seems like this does what youre looking for, it would not be hard to copy everything and paste that into excel using a '-' as a delimiter.

**Comment by Patschke** [comment]
If you want a even more machine-readable version: You can always use the browser JS console. `col = backend.loadCollection()` will query the server for your collection (you have to be logged in), and then you can just grab the json as js-object (`responseJSON`) or as text (`responseText`): 

![image](https://user-images.githubusercontent.com/17853362/215413971-0b64ae8a-8d1d-450a-b7e0-f4cf08c4b02d.png)

Of course, once you log in the same data has already been queried. It is e.g. stored in `exportObj.builders[0].collection`, where you can access it as well.

**Comment by raithos** [comment]
I'm going to close this for now. If I get a response, I may reopen it, but I feel there is sufficient existing features to justify closing
