### ISSUE TITLE
Feature Request: Custom points/data loading

### ISSUE THREAD

**Issue by Simplician** [raithos/xwing#1228]
This idea occured to me when I saw a group post their custom 2.5 huge ships points on the subreddit. I thought, it would be nice if I could use these points in YASB. But trying to engage with every different fan made points list everyone could conceivably make would obviously be insanity.

But then I considered that it may not be out of the realm of possibility to have the option to import custom points data from rich text, and have it saved on a player's profile much like lists and collections are saved. So if people want to share and use custom points, it is simply on them to create and share the text, and no one is coming to YASB to implement anything specific.

I'm imagining each custom data/text you upload is shown on a list much like the collection, using a title defined by the creator, so you can toggle them on and off. Custom data should also include a 2-4 letter tag that shows in identifiable brackets next to the entry name (similar to how the BoY/SoC repeats do, but different brackets), to remind you that it is a custom entry, and which custom data list it is from.

So, using my example of the folks who posted their huge ship points on reddit, they could have added a link to the text that would add those points to a players YASB profile. It would show as "Custom Huge Ships" or some such in your custom data folder. And when you select a rebel CR90, an "Alderaanian Guard <CHS>" pilot would be available, etc etc.

**Comment by raithos** [comment]
Anyone has the ability to fork YASB and create their own points set and create their own site. That's what Xwing legacy for 2.0 did for example. I'm not interested in supporting alt points formats, or coding the necessary functionality to make that possible. Just way outside the scope of what I'd want to do for the site.
