### ISSUE TITLE
Could this system link with launchbay app?

### ISSUE THREAD

**Issue by Akroe84** [raithos/xwing#123]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
What do you mean by link?

**Comment by Patschke** [comment]
Currently we are able to import and export from and to xws, and launch bay is able to do so, too. Unfortunately a quick test showed, that we cannot import launch bay exports, and launch bay cannot import ours. I'll try to work out if we can improve that.

**Comment by Patschke** [comment]
Hmm... We actually allow that already. I'll keep looking...

**Comment by Patschke** [comment]
https://github.com/raithos/xwing/pull/127/commits/c75882dc4066f4ccb8a84ddff9526a8b21138d8b (part of #127) will allow to import xws from Launch Bay. I'd consider that some kind of "linked to", but maybe @Akroe84 will specify what exactly the expectation was?

One should maybe consider to prevent people from opening Issues with the default text...

**Comment by Akroe84** [comment]
Thank you for he original answer that was very clear and explains the issue
I was having thank you very much, I was having trouble moving lists from
YASB to launch bay for offline access at events

**Comment by raithos** [comment]
for events, printing to pdf is definitely a better route. You want to have a static document to show people so there is no way to allow for tampering with a list once the event has started.

**Comment by Patschke** [comment]
I guess we can close this?
