### ISSUE TITLE
Squad Evaluation Stats

### ISSUE THREAD

**Issue by dewmhammer** [raithos/xwing#1231]
**Is your feature request related to a problem? Please describe.**
With 2.5, there are more factors to consider when evaluating a squad, such as objectives and general matchups vs list types.  Often people build many lists and try to figure out how to narrow them down.  A simpler method to rank your squad's capabilities might allow for easier evaluation.

**Describe the solution you'd like**
On a squad page above notes, I would suggest having a list of "evaluators" including each objective along with some key matchups like Vs High initiative, Alpha Strike, high ship count, etc., with a rank value next to each (1-5).  Each evaluator could have a toggle to mark it is considered for an overall average ranking.

**Describe alternatives you've considered**
Notes already exist and could be used.  

**Additional context**
![image](https://user-images.githubusercontent.com/125039478/218112757-c9b5abb0-ccd4-4af9-a81a-9762e4d56b1b.png)

**Comment by raithos** [comment]
I am currently not interested in creating that. Something like that can go into the notes IMO, and sorting by these ratings I don't think is something that will provide real value considering that the points change every 6 months.
