### ISSUE TITLE
Selfless on BoY Biggs is LIMITED

### ISSUE THREAD

**Issue by KyloChris** [raithos/xwing#1232]
**Describe the bug**
When you have selected boy, Biggs, you are able to select another ship, for example, such as a U-Wing, to have the selfless upgrade. Meanwhile, once you have boy Biggs, his selfless upgrade is limited.

**To Reproduce**
1. Go to 'Boy Biggs’
2. Click on 'Select him. Then go select another ship, such as Benthic in the U-Wing. Select him. 
3. Scroll down to 'EPT, and select SELFLESS.
4. See error is you should NOT be able to select Selfless on another ship once you have BoY Biggs. 

**Expected behavior**
See error is you should NOT be able to select Selfless on another ship once you have BoY Biggs. 

**Additional context**
your website 

> rocks!!
![E686C095-42E1-4E63-B38B-B390D22813C4](https://user-images.githubusercontent.com/100956543/218313913-e2f5d6e9-40ee-4bdc-bd72-1030b43ca4a4.jpeg)

**Comment by raithos** [comment]
I followed the instructions as you indicated, and selfless was greyed out as expected. I found a different version of the bug where if you have a ship that already has selfless and you add biggs the other ship has selfless which i will fix however
