### ISSUE TITLE
Ghost in quick build not updating values 

### ISSUE THREAD

**Issue by sblenkhorne** [raithos/xwing#1234]
**Describe the bug**
When I try changing the pilot of the VCX light freighter (Ghost) it doesn't update the squad value.

**To Reproduce**
1. Go to quick build Rebellion
2. Click on ship and choose VCX100 Light Freighter.
3. Change default pilot to Hera on her own (not with Sheathipede and A wing).
4. Change A wing to another ship
5. Won't update squad value 

**Screenshots**
![Screenshot_20230212-195650](https://user-images.githubusercontent.com/1450078/218360359-a0b80d4f-2ea6-4236-babf-1e987611d397.png)

**Smartphone (please complete the following information):**
 - Device: Google pixel 6a
 - OS: Android
 - Browser: Google Chrome
 - Version 

**Additional context**

**Comment by Patschke** [comment]
I can confirm that it is possible to create invalid states using those Ghost wing builds. Some interaction of Ship pair (Ghost+Phantom) and Wing might be the issue. The steps you describe are unclear to me, but I can get an error with the following steps:

1. Select VCX with Hera+Phantom+Awing
2. Change Sheathipede to AP 5+Ghost
3. Change VCX back to Hera

The actual error happens at step 2, where the claiming of unique cards does not work properly and AP-5 ends up in some faulty state. Refreshing the page will resolve that, but it's still a bug. 

Thanks for the report, I should look into that. It might take a bit until I actually do though.

**Comment by Patschke** [comment]
I pushed what I hope is a fix in #1242 
At least I couldn't break it anymore when testing. Those quickbuild multip ship thingies are nasty.
