### ISSUE TITLE
Lambda shuttle not appearing in ship list or collection

### ISSUE THREAD

**Issue by dschu2** [raithos/xwing#1238]
**Describe the bug**
The Lambda shuttle expansion does not appear in the collections area and it does not appear in the list of Imperial ships when building a squad. I added the ship and pilots individually and it still doesn't appear

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Browser: Safari
 - Version 16.2

**Additional context**

**Comment by raithos** [comment]
lamda is a 1.0 ship that is only accessible in conversion kits. also its not in the standard format, you need to change the format to extended.

**Comment by dschu2** [comment]
Thank you for the clarification!-Daniel SchusterOn Feb 20, 2023, at 21:57, raith ***@***.***> wrote:﻿
lamda is a 1.0 ship that is only accessible in conversion kits. also its not in the standard format, you need to change the format to extended.
