### ISSUE TITLE
Z95 HeadHunter

### ISSUE THREAD

**Issue by Infyrna** [raithos/xwing#1240]
**Describe the bug**
the Black sun soldier allows for a missile slot, but should only have access to a mod and illicid slot.

**To Reproduce**
1. Go to Scumand Villainy
2. Click on Z95-Head hunter
3. Scroll down to Black Sun Soldier Pilot
4. See the ship has three updares and not just 2.

**Expected behavior**
The Black Sun should only show a modification and an illicit slot.

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.

**Comment by Infyrna** [comment]
Hi,

How is it closed? The website still showing a missile upgrade on the ship?

**Comment by raithos** [comment]
also hold your horses, its going to be live in 3 seconds

**Comment by Infyrna** [comment]
Sorry, I am a dev I don't trust closed cases 😳😅
