### ISSUE TITLE
Ideas people asked me about

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#1241]
I'll look into those myself, I just needed a place to write them up properly, so I don't forget anything. 

* [x]  *not gonna do that* 
More visibility for the ship artworks. Suggestion was to make the background of the dropdowns semi-transparent. Something like this, perhaps having the text still at 100% opacity. 
![grafik](https://user-images.githubusercontent.com/17853362/220374593-76f6e79a-6cb9-4e0d-a218-7239b32d9a6a.png)
Not sure what to think about this, I like the focus on content over design. Might play around with it a bit. 

* [x] More print option buttons in mobile view. Apparently people want to print stuff from their mobile devices those days. 
![grafik](https://user-images.githubusercontent.com/17853362/220377623-2ccc9216-05b2-46ac-a7b0-00dc6a7ffcc1.png)
There is not really space to fit the fancy view nicely, but one could perhaps add an misc option to enable it. I guess the majority still does not print stuff from mobile, and therefore only needs the buttons to export it to other digital platforms. 

* [x] Obstacle select on mobile is not really showing the obstacles. In principle it would work, but it triggers on mouse-hover events. Most people don't seem to have a mouse available on their mobile device to hover stuff. Perhaps I can find a nice place to show the selected obstacles. 

* [ ] Adding ships via pilot name search thing. Not sure how important this is, most people would likely know which ship a pilot they search for is flying?

* [ ] Add ship icons to list preview. Seems doable. 
* [x] German rules reference. Yep, an official version exists, so this could be a thing.

**Comment by raithos** [comment]
1. ehhhhhh i dont know if i like that.
3. Obstacles need to be reworked in general. I wrote some stuff to allow you to multiselect things and it just broke obstacles. 
4. Seems unnecessary but i dunno
6. we dont have any translation setup for it, but theoretically wouldn't be too hard to do

**Comment by raithos** [comment]
sorry i ddint notice you made this a checklist and i fucked around with the buttons lol

**Comment by raithos** [comment]
reworked obstacles.

**Comment by Patschke** [comment]
6 is done with #1343 

I'll not do 4 and 5, so I'll close this. Sorry for having an Issue open that long, now we can soon go back to having no issues open (thus being a perfect and 100% bug free project).
