### ISSUE TITLE
Obstacle Selection

### ISSUE THREAD

**Issue by copperblue74** [raithos/xwing#1246]
**Describe the bug**
When I select my obstacles they aren't staying with my squad when I save them.  I get the confirmation that I have 3 obstacles selected.  I hit SAVE SQUAD and when I double check, they are no longer selected.  I've tried doing so on my mobile device and 2 browsers (Safari and Chrome) on my computer.  The only way I could get the obstacles to save was to copy the obstacle code and paste into the link in the browser and resave that way.  I don't think that's how it should be for sure.  Not sure if anyone else is having this issue?

**Comment by raithos** [comment]
yup this is a known issue. I havent had time to resolve it yet

**Comment by raithos** [comment]
fixed
