### ISSUE TITLE
Issue with standardized upgrades

### ISSUE THREAD

**Issue by Gan0n29** [raithos/xwing#1247]
Hi Raithos and Patschke 

There is a little issue with standardized upgrades with pilots with different chassis.

For example if we take Volan Das (Tri-Fighters), if his mod slot is filled, others Tri-Fighter pilots can't take independant calculations.

I'm pretty the cause is there in the code :

    standardized_check: (upgrade_data) ->
        if upgrade_data.standardized?
            for ship in @builder.ships
                if ship?.data? and ship.data.name == @data.name
                    if upgrade_data.restrictions? and ship.restriction_check(upgrade_data.restrictions?, upgrade_data) and not (ship.pilot?.upgrades?)  <------------------- **Here is maybe where the fix can be, by checking pilot's chassis and not only ship's chassis**
                        slotfree = false
                        for upgrade in ship.upgrades
                            if upgrade_data.slot == upgrade.slot and not upgrade.data?  **<------------ Here is the cause I guess**
                                slotfree = true
                        if slotfree == false
                            return false
        return true

Thanks.

**Comment by raithos** [comment]
oops, typo, should be fixed shortly
