### ISSUE TITLE
Add damage cards and condition cards to card browser

### ISSUE THREAD

**Issue by opsmason** [raithos/xwing#1250]
**Is your feature request related to a problem? Please describe.**
not a problem, but a quality of life request

**Describe the solution you'd like**
Please add damage cards and condition cards to the card browser. It would be nice to be able to look them up while watching streams. 

**Describe alternatives you've considered**
I could scan the cards and keep a pdf in my phone.

**Additional context**
Nothing in can think of.

**Comment by raithos** [comment]
condition cards are already in the card browser, at the bottom, I'll think about the damage deck.

**Comment by Patschke** [comment]
I've added the normal damage cards as part of #1258 
Let's see if at some point somebody is interested in the epic ones as well ;-)
