### ISSUE TITLE
Button to show list URL and/or copy list URL to clipboard

### ISSUE THREAD

**Issue by roshow** [raithos/xwing#1251]
**Is your feature request related to a problem? Please describe.**
When I save YASB to my iPhone homescreen it opens as a PWA which means there's no URL address bar. This is cool but then there's no way for me to copy and share the list via URL without having to reopen it all in my regular Safari app. Would be nice to have a UI element to show the URL and/or copy it to the clipboard

**Describe the solution you'd like**
Maybe a button then when pressed displays the list URL in a text box like the other share options?

**Describe alternatives you've considered**
Anything along those lines that assumes the user can't access the browser's address bar for seeing the list URL

**Additional context**
That's it, thank you so much, love the app!

**Comment by Patschke** [comment]
You can always click the print button (on mobile that's just an icon) and the URL is given e.g. at the bottom of the "Text" view. Do I understand you correctly, that you'd like to have an additional tab beside simple/text/reddit/tts/xws that is "url" and just has the URL? I'm not sure if that is really that much more useful, than copying the URL from the text view?

**Comment by Patschke** [comment]
I think I have found a reasonable solution for this. We can check if YASB is opened in PWA mode and add a copy-url button in that case to the print preview. This way the UI does not get cluttered for people viewing in normal mobile view, but PWA users have an option to copy the URL.
