### ISSUE TITLE
Pilots and upgrades in portuguese

### ISSUE THREAD

**Issue by Thunderpombo** [raithos/xwing#1252]
Since just the first wave of second edition was regionalized to brazilian portuguese, almost everything we have is in english, and a lot of players find a barrier on it. So i've started a project with Rodrigo Nascimento (Brazilian Marshall and judge, and the oficial translator for the second edition first wave) to translate the cards, he is doing almost all the translations and I'm revising it and puting the text on the cards, and I would like to know if there is any chance that those translated scripts could find a way into your builder. We have almost all pilots translated (except for the gauntlet, rogue and the BoY and SoC), and a few upgrade types are ready too.

Thanks in advance.

**Comment by Patschke** [comment]
I'd welcome those translations very much and do not see any reason for not including them. We could consider adding a "non-official-translation" flag, but in my opinion that would not be needed - even for official translations the English rulings are the only binding ones, so there is not really any difference in community made or official translations. 

If you are familiar with the usage of git a PR is welcome. If you need help on where to place the translations let me know. 
If you are not familiar with git (and don't want to make yourself familiar with how to use it), you can also provide the texts in some other, reasonable digital form and I'll put them in place.

**Comment by Thunderpombo** [comment]
Nice, I'm note familiar with git (Shame on me) and I want to give you the
least amount of work, so If you could provide some basic instructions, I
can put the translation myself

Em seg, 3 de abr de 2023 12:30, Patrick Mischke ***@***.***>
escreveu:

**Comment by Patschke** [comment]
* One-time setup:
  *  You need an account on Github (guess you already got that).
  *  You create your own working copy of the YASB source code on Github. This works via a so called "Fork", which you can find as Button in the upper right corner of https://github.com/raithos/xwing or https://github.com/patschke/xwing.
  * Optional: If you don't like to work in the browser, you can install git on your computer. In that case you have to download your project copy afterwards with the command "git clone https://github.com/Thunderpombo/xwing".
* You add translations. For this you edit the cards-pt.coffee file. You have to use the same syntax as for the existing cards: English card name followed by the Portugese name as "display_name" and the Portugese text as "text". Keep the existing formatting - unfortunately it is actually important to use the same amount of spaces (no tabs) for indentation. Whether new translations are added alphabetically or simply at the end of the correct category (pilots/upgrades/etc) doesn't matter.
  * If you are working in the browser there is an edit button, or via https://github.com/Thunderpombo/xwing/edit/master/coffeescripts/translations/cards-pt.coffee
  *  If you have Git installed and are working locally you can use a (text) editor of your choice. Git is a version control software. After you are done editing the file you need to tell git to commit the changes to your working copy on the github server. This is done by the commands "git add .", "git commit -m [short description of changes]" and "git push". There's no automatic synchronization in the background (like you might be used to by cloud services).
* Very optional: at this point it is basically possible to test if everything works - you could compile YASB locally to create your own running copy (I wouldn't recommend for you at the beginning. I can check just fine if everything works and compiling YASB from source is not beginner friendly).
* You create a so-called "pull request" on https://github.com/raithos/xwing or https://github.com/patschke/xwing. With this you give us the option to put your changes live. Don't worry, you can't break anything at any point. You simply don't have any access rights even if you tried ;-)
* Occasionally you should synchronize your working copy with our version (especially whenever new cards are added to the game). This can be done in the web interface via "Sync fork", a button you will find on the main page of your working copy (https://github.com/Thunderpombo/xwing).
  * If you have Git installed and are working locally, you will then need to keep the copy on the github server in sync with your downloaded version using the "git pull" command.


I hope this gives you a first overview? If you have any questions, feel free to ask!

If you look at the source code and think "I don't want to touch any of this", I'm also happy to set up a spreadsheet for you to put in the translations. This is not much work for me (as in: at this point I've got an automated script to do so) but might be easier to use for you?

**Comment by Thunderpombo** [comment]
Thanks, your expalanation was really easy to understand. I think I'll
manager to get ir fone. But If by any means I get stuck I scream for you

Em ter, 4 de abr de 2023 03:28, Patrick Mischke ***@***.***>
escreveu:

**Comment by raithos** [comment]
as with the other translation threads, I'm going to close this for now. If you run into any issues, respond to this thread and I'll reopen the thread, otherwise, looking forward to your commits for the portuguese translations

**Comment by Thunderpombo** [comment]
No problem. I have almost finished the pilots and soon will PR for testing

Em dom, 9 de abr de 2023 23:16, raith ***@***.***> escreveu:
