### ISSUE TITLE
Incorrect Points?

### ISSUE THREAD

**Issue by squalopus** [raithos/xwing#1253]
**Describe the bug**
Incorrect Points for Durge and Merle Cobben. See screenshots. 

**Screenshots**
attached

**Desktop (please complete the following information):**
Mac OS 12.6
Chrome 111
![Screen Shot 2023-04-08 at 12 01 38 PM](https://user-images.githubusercontent.com/123266510/230733864-a070ee75-46a4-4851-8992-7e5d16d01a5b.png)
![Screen Shot 2023-04-08 at 12 01 17 PM](https://user-images.githubusercontent.com/123266510/230733866-0cd39b8e-4a31-431c-8a0f-81ca6466735d.png)

**Comment by Patschke** [comment]
I guess you are using yasb.app/old (which pupousfully has old points, as the name suggests) instead of yasb.app. The current points show up correctly for me.

**Comment by squalopus** [comment]
That's on me then. Thanks Patrick.
