### ISSUE TITLE
Custom Loadout Values

### ISSUE THREAD

**Issue by Wurms2** [raithos/xwing#1257]
**Is your feature request related to a problem? Please describe.**
Could there be a way to bypass loadout values for pilots? So pilots essentially have infinite loadout and can take any amount of loadout?

**Describe the solution you'd like**
In the dropdown where you select Standard, Extended, Epic, Quickbuild, maybe there can be a fifth option called like "Custom" where pilots have infinite loadout, and it includes extended pilots and upgrades as well.

**Comment by Patschke** [comment]
I'm not a huge fan of that. In the end people will just scroll through their saved squads and click on a "infinite-loadout" list without remembering that some ship(s) use a few more points of loadout than they should. I like and value the approach of "whatever the squadbuilder allows you to do is allowed". I could possibly see adding such a play-around mode when disabling the print and save options for any squads created in this mode. 

Perhaps my main issue is that I do not really see the benefit of that. For kitchen table play you can go ahead and play with whichever upgrades you think are fun, nobody will stop you. Does having such an option help you in any way to build your normal lists?

**Comment by raithos** [comment]
Sorry, I have no intention on doing this. Even as a custom mode, there is potential that people will mistake this as legit and falsify lists for events, and many people rely on yasb for a quick check to see if a list is valid or not

**Comment by Wurms2** [comment]
It would be more for things like Aces High, where you can say bring a
couple 5pt ships with 20 Loadout. Or an escalation game where every time a
ship is destroyed it comes back with +10 Loadout. Other things is like a
jank tank style tournament where every ship gets a free upgrade that doesnt
go against their loadout costs. Just fun formats that dont need to be
written down everytime. Maybe can have a warning when a user pulls that
list up that it's illegal for standard play or something? Or maybe you cant
even save these lists, just strictly for print and play? Grab the XWS code
and toss it in TTS.
