### ISSUE TITLE
TTS Export option missing

### ISSUE THREAD

**Issue by paulbfuller** [raithos/xwing#1259]
**Describe the bug**

**To Reproduce**
1. Go to 'Print/Export'
2. Export to TTS not showing up

**Expected behavior**
Expect to see TTS as an option for export.

**Screenshots**
![image](https://user-images.githubusercontent.com/55157596/232135605-394ea1cf-0f57-45ca-918e-09cacd268af5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Occurs on Brave, Edge, Chrome
 - Version 10.0.19045 Build 19045

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s22 Ultra
 - OS: Android 13 One Ui
 - Browser Stock and Chrome
 - Version 5.1

**Additional context**

**Comment by raithos** [comment]
this is already resolved, please refresh the page
