### ISSUE TITLE
Scum Jumpmaster 5000 - Punishing One do not remove Crew upgrade slot

### ISSUE THREAD

**Issue by jebbo** [raithos/xwing#126]
### Expected Behavior

When i choose Punishing One Tilte on Jumpmaster 5000 (Scum) must appear Astromech upgrade and must disapper Crew Upgrade.

### Actual Behavior

Astromech upgrade appear correctly, but Crew Upgrade is visible.

### Language

I tried english but i guess that the bug is present in every languages,

**Comment by Patschke** [comment]
You can do so yourself by hitting that close issue button.
