### ISSUE TITLE
Scum/Gauntlet Fighter/Title Upgrade

### ISSUE THREAD

**Issue by pgk117** [raithos/xwing#1260]
Cannot assign _Nightbrother_ title to Rook Kast pilot.

**To Reproduce**
1. Add a Gauntlet Fighter to a Scum squadron
2. Select Rook Kast as pilot
3. No Title upgrade option appears

**Expected behavior**
Title upgrade option to appear and _Nightbrother_ be selectable

**Additional context**
Title is restricted to Rebel/Scum, Gauntlet Fighter, Uses Extra Modification. All three of these are met by Rook. Other Unique pilots that meet these criteria can select this title.

**Comment by Patschke** [comment]
Everything works as expected. While the title might be in theory legal for Rook Kast, he simply does not have a title slot available to equip it. Maul is the only Scum pilot for the Gauntlet that has a title slot. 

See the [latest ship points](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/638e0ec5ea9ee118b32b499e/1670254279113/SWZ_Ship_Points_11252022_v2.pdf) available from https://www.atomicmassgames.com/xwing-documents

![gauntlet](https://user-images.githubusercontent.com/17853362/232981908-08b31491-9a7b-40a8-bb98-008622e3e811.png)
