### ISSUE TITLE
In Resistance BTA-NR2 Y-Wing dissapear the Wartime Loadout Standarized selection in the Ships when choosing 2 o 3 ships with it

### ISSUE THREAD

**Issue by PoneyBoy** [raithos/xwing#1261]
**Describe the bug**
In Resistance BTA-NR2 Y-Wing dissapear the Wartime Loadout Standarized selection in the Ships when choosing 2 o 3 ships with it

**To Reproduce**
1. Go to Resistance
2. Select YWing
3. Select Wisla
4. Go to Configuration
5. Choose Wartime LoadOut
6. Select another Ywing
7. Choose Teza
8. Go to Configuration
9. Choose Wartime LoadOut

**Expected behavior**

**Screenshots**
I![FireShot Capture 032 - YASB- yasb app](https://user-images.githubusercontent.com/35730852/233837651-4b085e4d-8142-4516-a5c7-423e3b16e626.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Chrome
 - Versión 112.0.5615.121 (Build oficial) (64 bits)

**Comment by Patschke** [comment]
I see the issue but I am not sure what the correct ruling would be in that case. Standardized requires every ship of that type to equip the corresponding card if it 
  * has the ship ability
  * is not a standard build with fixed upgrade choices. 
 
In this case the Kimji Spice Runner meets those restrictions and is therefore forced to equip "Wartime Loadout". However, he has only 4 Loadout points available, so he can't do so (Wartime Loadout costs 5 points after all). I'd guess you are simply not allowed to field a Kimji Spice Runner with other BTA-Nr2 Y-wings if they want to equip Wartime Loadout? 

Before implementing it this way I'd like to check if there is any official ruling on this?

**Comment by raithos** [comment]
this is working as intended. if the ship cannot take the upgrade, then none of the ships can take the upgrade.

**Comment by Patschke** [comment]
I have to disagree. It's throwing an error and resulting in empty search bars. There is definitively an error here. I am just not sure what the correct behaviour would be.

**Comment by raithos** [comment]
Oh I see what you're saying. The correct interaction is that adding a spice runner should unequip the upgrade from all other ships and remove the upgrade from the standardized table list.

**Comment by Patschke** [comment]
I believe I've figured this out in d071bb2a52a9eaa9a09edf9c6534d38de16011a9. 

The only non-intuitive behavior that will be left is that adding a new BTA-NR2 Y-wing from the select-ship menu will remove all Wartime Loadouts from the other ships. The cheapest (and therefore default) Y-Wing is the Kijimi Spice Runner, who is unable to equip it. This behavior is therefore correct, but people quickly changing to another pilot may not notice it. Copying an existing Y-Wing works fine.
