### ISSUE TITLE
Save/Load Pilot Builds

### ISSUE THREAD

**Issue by Wurms2** [raithos/xwing#1266]
Wondering if there could be an option to save/import pilots . For instance, I can build the three different Luke Skywalker's that I like and save those loadouts. Then when I am building a list, I can build a list up to 14pts, then just "import" one of my 6pt Luke builds, instead of having to build the pilot over and over again for all my lists. 

This would also allow sharing pilots. So say someone shares a list with a yasb link. I load the list, and although I dont care for the list, I like their Bossk YV build, so I can just save Bossk, that way when I build a scum list, I can just load that Bossk.

This would help save so much time, where I just have two or three loadouts built of pilots I use the most, and can just plug and play so-to-speak. Like I can have a few different builds of eight different 5pt ships, and can build a list in just like 4 clicks by loading my saved pilots.

Was thinking, when you get the dropdown of pilot names, the first option could be "Import" And then just like your saved lists the pop-up comes with your saved pilots for that ship. 

So I would choose T-65 X-Wing. Then when selecting pilot, I choose "Import" and all my saved T-65 Xwing pilots appear in popup, and I click the download button to add it to the current list.

The standard loadout cards are becoming popular, and this would sort of be like making your own standard loadout pilots, able to share them with the Xwing community.

**Comment by raithos** [comment]
This has been asked before, but the answer is I'm not looking to implement this for several reasons, some logistic, programmatic and philosophical.
