### ISSUE TITLE
FO - Liutenat Galek - Talet slot replaced by Tech slot

### ISSUE THREAD

**Issue by Mucurini** [raithos/xwing#1268]
Hi

First Order
TIE/fo
Lieutenant Galek

Should have 2 Talent slots, and one Tech slot

Same as there in "upgreade slots"
https://xwing-miniatures-second-edition.fandom.com/wiki/Lieutenant_Galek

**Screenshots**
Marked yellow
![image](https://user-images.githubusercontent.com/126404388/236397727-4916aa49-3f78-405e-955e-3fd93ffe804e.png)

Thanks :)

**Comment by Patschke** [comment]
I don't think so. According to the latest [point list](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/638e0ec5ea9ee118b32b499e/1670254279113/SWZ_Ship_Points_11252022_v2.pdf) available from [Atomic Mass Games X-Wing Documents](https://www.atomicmassgames.com/xwing-documents). 

![image](https://user-images.githubusercontent.com/17853362/236399708-66371f26-695e-497d-9369-c16a2a8245df.png)


I guess YASB is right here and the Wiki is wrong. Feel free to update the wiki.
