### ISSUE TITLE
Tooltips around for icons

### ISSUE THREAD

**Issue by RKopczynski** [raithos/xwing#1273]
**Is your feature request related to a problem? Please describe.**
I'm a pretty new user of this tool and definitely absolute noob in X-Wing game. It's really frustrating to me when I cannot get what each picture means. Take for example picture below, for me (as a total noob, I know), many of those symbols are unknown when reading some new card skill.

![image](https://github.com/raithos/xwing/assets/11996103/a27cbbf6-f977-4fdc-822b-839487ddce96)

**Describe the solution you'd like**
If possible, it would be perfect to just have a tooltip around those symbols (at least in web app) that would resolve to symbol name that would be easier to find on wiki. Instead of just image that tbh is cryptic enough for noob that it takes too long to find out. Even as a more knowledgeable player, I personally tend to forget a thing or two so this might be some help/reminder even for better players than me. It could work similarly to how tooltips are shown on [fandom pages](https://xwing-miniatures-second-edition.fandom.com/wiki/Actions) (see screen below).

![image](https://github.com/raithos/xwing/assets/11996103/6d72d413-7d3b-4eb9-8dcf-fec82958efd5)

**Describe alternatives you've considered**
I was thinking about some kind of "mode" for noobs that would show more than just tooltip, but tbh it seems like a lot of work.

**Comment by raithos** [comment]
Ok, i can do this for game text, doing it everywhere is going to be a lot of work, and even what I've done, its going to be a pain in the ass to translate. So this is about as good as you're going to get for now.

**Comment by RKopczynski** [comment]
Hey, noticed it today messing around with new squad. Thanks a lot, works like a charm!
