### ISSUE TITLE
Mising Gauntlet Fighter faction restrictions

### ISSUE THREAD

**Issue by JediOswald** [raithos/xwing#1278]
**Describe the bug**
The Gaunlet Fighter Titles are missing their faction restrictions.

**To Reproduce**
1. Add a Gauntlet Fighter pilot with a title slot to your list (no matter the faction).
2. Click the pilot dropdown.
3. See that you can equip a title from a different faction.

**Expected behavior**
The Republic and Separatists should only be able to equip the Gauntlet title and Rebels and Scum the Nightbrother title.

**Screenshots**
![image](https://github.com/raithos/xwing/assets/87926233/f4c6db3a-bea0-47a7-b145-12400ef1814c)
![image](https://github.com/raithos/xwing/assets/87926233/f9c955c6-7b37-4292-8621-905958297850)
![image](https://github.com/raithos/xwing/assets/87926233/d5880f80-8f90-4ca7-a2cc-8e7be00df37b)
![image](https://github.com/raithos/xwing/assets/87926233/1206c562-4823-4785-b08c-1f185157c5dc)
![image](https://github.com/raithos/xwing/assets/87926233/86ae83c0-90c2-448a-ba1d-ee05149022c2)

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by raithos** [comment]
Points doc states they no longer have faction restrictions. Until the doc is updated it stays

**Comment by JediOswald** [comment]
You are right that the points document no longer lists faction restrictions on Nightbrother within the list, and no longer has a faction restriction for Gauntlet in Republic within the list, but they are still only listed within the respective factions that can equip them and not in the generic upgrades, as well as the Gauntlet title being listed as Republic and Separatist only in the Separatist section, not to mention that the restrictions are printed on the cards themselves and no errata was issued for those.

![image](https://github.com/raithos/xwing/assets/87926233/e93ab511-7d1e-40d4-bbb0-9023b2f4b4c5)
![image](https://github.com/raithos/xwing/assets/87926233/7928dbda-f30c-47ee-8e3c-5cad0f28a960)
![image](https://github.com/raithos/xwing/assets/87926233/9f6e24ef-741f-4405-80a1-ab63bc155fc7)
![image](https://github.com/raithos/xwing/assets/87926233/01e57461-aa72-4ecc-ad24-158f8b4e3de3)

I do not know how this would affect your decision but I wanted to notify you of the full information.
