### ISSUE TITLE
Maul crew points

### ISSUE THREAD

**Issue by NightHoundTyr** [raithos/xwing#1280]
Hello there! 

No really a bug or anything like that, but it looks like Maul single crew upgrade has different points in the doc for scum than rebels. Rebels has him listed at 12 points like you have him, but 10 points for scum. And yes I've made sure it is the same Maul card as the other one is listed with the two crew slots further down in the document.
![image](https://github.com/raithos/xwing/assets/62049086/c64ccf4f-220d-488c-8e4b-20eaeff3dab8)

**Comment by raithos** [comment]
not going to address this until amg releases an update.
