### ISSUE TITLE
XWS Export for SSP pilots has product code capitalized

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#1283]
**Describe the bug**
XWS Export for SSP pilots has product code capitalized

**To Reproduce**
Exported XWS of SSP Vader/Maarek:
{"description":"","faction":"galacticempire","name":"Unnamed Squadron","pilots":[{"id":"darthvader-SWZ105","name":"darthvader-SWZ105","points":6,"ship":"tieadvancedx1"},{"id":"maarekstele-SWZ105","name":"maarekstele-SWZ105","points":5,"ship":"tieadvancedx1"}],"points":11,"vendor":{"yasb":{"builder":"YASB - X-Wing 2.5","builder_url":"https://yasb.app/","link":"https://yasb.app/?f=Galactic%20Empire&d=v9ZhZ20Z630X204W101W105Y631X119W126W105&sn=Unnamed%20Squadron&obs="}},"version":"06/09/2023"}

**Expected behavior**
Expected value: darthvader-swz105 and maarekstele-sqz105

Looks like rebel swz106 pilots have the same issue.

**Comment by raithos** [comment]
this is your fault, i asked you and you said it was fine

**Comment by chrisalleng** [comment]
probably guilty as charged
