### ISSUE TITLE
For the Imperial faction, the TIE Bomber is not available in the Standard ship list creation, though the PDF lists them as a standard ship

### ISSUE THREAD

**Issue by Eruletho** [raithos/xwing#1285]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
dude the docs just came out give me a minute to do the updatse

**Comment by Eruletho** [comment]
Sorry, I hadn't been around since last week and didn't know that they were updated again today, I thought this update was from last Friday

**Comment by mugen93** [comment]
Hey,
@raithos Major Rhymer (TIE/sa Bomber) lost one of his Payload slots so should have only 1.
