### ISSUE TITLE
The cost for the TIE/sa Bomber “Major Rhymer” does not match the current X-Wing Points document.

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#1289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
https://puu.sh/JI5xp/b89a3c4724.png

looks right to me

**Comment by ObVus** [comment]
My mistake! Perhaps I had an old version of the app open or something. Sorry!
