### ISSUE TITLE
I can't print squadron lists

### ISSUE THREAD

**Issue by Kafitrar** [raithos/xwing#129]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

I was trying to print my squadron list either as a pdf or an actual printout.

### Actual Behavior

The pdf or print preview comes up as a blank page. I'm using Mac OSX10.14 with Safari 12.

### Language

English.

**Comment by raithos** [comment]
Can you post the link the the squad? I want to see since I cant replicate it here.

**Comment by raithos** [comment]
HI, I will close this for the time being. Please provide a link to the squad in question and I will reopen.
