### ISSUE TITLE
Card Browser Filter Bug

### ISSUE THREAD

**Issue by sirloinsandvich** [raithos/xwing#1290]
**Describe the bug**
In Card Browser mode, filtering by Rebel Alliance or Scum and Villainy and changing the Point Cost field to anything but 0-20 causes all pilots to disappear from the list.

**To Reproduce**
1. Go to Card Browser
2. Click on the faction filter and select "Rebel Alliance" or "Scum and Villainy"
3. Set a minimum point cost not equal to 0 or a maximum point cost not equal to 20
4. Pilots will not be displayed in the card browser

**Expected behavior**
Using these filter options should filter only Rebel or Scum ships within the designated point limits. The pilots should display in the right-hand card browser as normal.

**Screenshots**
https://imgur.com/s9IJxA4

**Desktop (please complete the following information):**
 - OS: Mac OS (also reported on Windows by another user)
 - Browser: Google Chrome
 - Version: 113.0.5672.92

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 13
 - Browser: Google Chrome
 - Version 113.0.5672.162

**Comment by Patschke** [comment]
I'll look into that. Guess maul with his different points depending on faction is breaking things...
