### ISSUE TITLE
Major Rhymer (again)

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#1292]
So, I just looked again. Major Rhymer is listed at a cost of 3 with a Loadout Value of 12 in YASB2. I actually think that’s probably correct, but I figured out that my confusion arose from the AMG points doc, which lists him at a cost of 3 with a Loadout Value of “N/A,” which would seem to imply that he’s a Standard Loadout card (obviously a mistake on their part).

**Comment by Patschke** [comment]
Not sure where you read that he has cost 3 and N/A loadout in the documents. For me it seems like everything is just fine?

![rhymer](https://github.com/raithos/xwing/assets/17853362/90a10723-d65f-4844-a324-c6d008944247)

That's what I see in the [latest point document](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/646e499599233b36007508ba/1684949400287/Ship_Points_06.09.23_v2.pdf) from the [AMG X-Wing Documents page](https://www.atomicmassgames.com/xwing-documents)

**Comment by ObVus** [comment]
![image](https://github.com/raithos/xwing/assets/82635168/054ee717-2b07-4cf1-a71b-7798939af8e0)

**Comment by ObVus** [comment]
Until this morning, the above pic is what I saw when loading the points document. As of today, I’m seeing the same thing you do, with the 3/12, full upgrade bar, etc. I have no idea why this happened! But, issue resolved.
