### ISSUE TITLE
I am not seeing a save option in chrome, Mozilla, edge.  I also didnt see a way to open a saved squad.

### ISSUE THREAD

**Issue by bert524** [raithos/xwing#1293]
Windows 10
I am not seeing a save option in chrome, Mozilla, edge.  I also didn't see a way to open a saved squad.
Confirmed updated ver of each browser.

![Screenshot 2023-06-03 214531](https://github.com/raithos/xwing/assets/99442334/fec8b04f-bf36-45ea-9fd7-442de39f83a4)
![Screenshot 2023-06-03 214531](https://github.com/raithos/xwing/assets/99442334/b0a0b9d2-e9b1-4c40-8095-95a705ce943f)

**Comment by Patschke** [comment]
Please Log In to see those options. There is a button on the top right to do so.
