### ISSUE TITLE
Gauntlet title restrictions, maul crew point correction

### ISSUE THREAD

**Issue by jchurchman** [raithos/xwing#1296]
These are based on the points doc here: https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/646e49bf182ca91ad7077c00/1684949441475/Upgrade_Points_06.09.23_v2.pdf

Gauntlet title is only listed under Republic or Seperatists. It does not appear under other factions or the generic list.
Nightbrother title is only listed under Scum or Rebel. It does not appear under other factions or the generic list.

Original Maul crew (single crew slot) only went up to 12 pts for Rebels. In Scum it is still listed for 10 points.

**Comment by jchurchman** [comment]
Found another: 
Kuill (Scum) should only be allowed on Medium or Large bases. Currently I am able to equip him on a HWK

**Comment by jchurchman** [comment]
Nom Lumb in the jumpmaster should get another mod slot (for fucking what?)

**Comment by jchurchman** [comment]
Tracking Fob (Illicit) restriction changed to 
<img width="696" alt="Screen Shot 2023-06-09 at 1 57 44 PM" src="https://github.com/raithos/xwing/assets/26889677/724a0ef0-5c80-4053-8b32-4833cf78d5b7">

**Comment by raithos** [comment]
just because its listed under the faction doesnt mean that it shouldnt include the restrictions for the faction in the list. until theres a clarification, it will stand. the maul crew was fixed like a week ago. everything else will be fixed
