### ISSUE TITLE
Expert Handling Points

### ISSUE THREAD

**Issue by Hobologist** [raithos/xwing#13]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

Expert Handling should cost 2, 4, 6 for Small, Medium, Large bases.

### Actual Behavior

Expert Handling costs 3, 6, 9 for Small, Medium, Large bases.

### Language

English

**Comment by raithos** [comment]
will be fixed in the next update
