### ISSUE TITLE
Tracking Fob not Scum only but Bount 

### ISSUE THREAD

**Issue by Brachinus** [raithos/xwing#1300]
The Expansion "...Tracking Fob" has the limitation of "Bounty Hunter", but it is programmed as "Scum only".

Some Pilots of the Separatists (with the Bounty Hunter Keyword such as e.g. Durge and Cad Bane) can equip it, but currently YASB doesn't show this expansion.

**Comment by raithos** [comment]
current points doc changed the restrictions, this is not a mistake
