### ISSUE TITLE
Del Meeko Pilot of TIE/LN has a missing Upgrade

### ISSUE THREAD

**Issue by DaingerMan** [raithos/xwing#1301]
**Describe the bug**
Del Meeko Pilot of TIE/LN has a Modification Slot missing in the List Builder.

**To Reproduce**
1. Go to 'Empire Faction'
2. Click on 'TIE/LN'
3. Scroll down to 'Del Meeko'

**Expected behavior**
Please Add.

![Screenshot 2023-06-22 163234](https://github.com/raithos/xwing/assets/137451892/6e175cc8-c77e-48fa-909f-25fc8f319f5e)

**Comment by Patschke** [comment]
Thanks for the note, will be fixed
