### ISSUE TITLE
Tracking Fob is listed as Scum only

### ISSUE THREAD

**Issue by DeployerOfMajesty** [raithos/xwing#1304]
**Describe the bug**
The Tracking Fob Illicit Upgrade is listed as Scum Only instead of Bounty Hunter Only.

**To Reproduce**
1. Go to YASB
2. Click on Separatists
3. Add Cad Bane to squad
4. See that Cad Bane cannot add the Tracking Fob Illicit

**Expected behavior**
Tracking Fob should be assignable to Bounty Hunters like Cad Bane, regardless of faction.

**Screenshots**
Card reference: https://xwing-miniatures-second-edition.fandom.com/wiki/Tracking_Fob

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 16.5.1
 - Browser safari
 - Version unsure but should be current

**Comment by Patschke** [comment]
See #1300

This is not a bug but has actually been changed to be scum only in the latest points document. 
![fob](https://github.com/raithos/xwing/assets/17853362/f71adfcc-a0b4-4411-bbc6-93bf6a4eeef9)

**Comment by DeployerOfMajesty** [comment]
AMG confirmed this was an error and it should not be Scum only:
https://forums.atomicmassgames.com/topic/11623-tracking-fob-changes/
