### ISSUE TITLE
Gauntlet Ship Titles

### ISSUE THREAD

**Issue by bluejell0** [raithos/xwing#1305]
**Describe the bug**
The Gauntlet ship titles should be faction specific according to faction restrictions on the physical cards. See: 

https://forums.atomicmassgames.com/topic/11206-gauntlet-ship-titles/

**Comment by Patschke** [comment]
It's interesting that the restrictions have been dropped in the 5/18/2023 points update according to the pdfs, there is a forum post from a week later stating that this was a mistake to be cleared up, but yet it is still the same for the 06/09/2023 update. 

In other cases the pdf seems to intentionally change the restrictions of cards, so I don't see how any player (or tournament organizer) is supposed to know what the actual rules are: a) the card or b) the pdf or c) some forum post. 

Given that there are a bunch of other cards lacking the proper restriction in the pdf (e.g. Grappling Struts or Agent Terex) I'd vote to reintroduce the faction restrictions. This has also been pointed out in #1278 but not fixed on purpose, as there was no link to the clarification from the forum post. 

@raithos  I'll reintroduce the faction restrictions in #1302, but feel free to ignore that commit if you prefer to wait for an updated pdf. If we do not add the restrictions for the Gauntlet we should consider removing it for the other cards as well, just to have a consistent way to go.

**Comment by bluejell0** [comment]
For what it's worth, the old Upgrade Points PDF I have on hand (06/20/22) also does not have faction restrictions in the "Restrictions" column for the Gauntlet titles. Seems like AMG might have noticed that it was an issue and their fix was to move the Titles from the Generic section to the corresponding Faction specific sections (without adding actual faction restrictions). 

![Open SWZ_Upgrade_Points_062022](https://github.com/raithos/xwing/assets/138175176/27c16ec6-99fa-4c26-878a-ad1ce26ee2c1)

**Comment by raithos** [comment]
Basically because the changes to prices for Maul, I took the position of the pdf takes priority over all, especially with multiple changes to the pdf over cards with no update on whether those are intentional or not. I'm glad that the rulings have been clarified so will update the builder accordingly
