### ISSUE TITLE
R2 Astromech doesn't show in upgrade drop-down 

### ISSUE THREAD

**Issue by duelinmarkers** [raithos/xwing#1307]
**Describe the bug**
R2 Astromech doesn't show in upgrade drop-down 

**To Reproduce**
1. Create new Rebel squadron
2. Select ship T-65 X-wing
3. Select pilot Luke Skywalker
4. Open Astromech upgrade menu.

**Expected behavior**
Should see R2 Astromech along with other options.

**Smartphone:**
 - OS: Android 
 - Browser Firefox 114.2

**Comment by Patschke** [comment]
You need to choose "Extended" as gamemode (drop down menu on the top left) to have R2 Astromechs show up. They are banned from standard play: 
![R2_banned](https://github.com/raithos/xwing/assets/17853362/b0b5448e-bea4-49ec-ae8a-c9ba8a1994fd)
For me everything works as expected.

**Comment by duelinmarkers** [comment]
Sorry for the noise. Didn't occur to me.
