### ISSUE TITLE
tie v1 and x1 bug will not load

### ISSUE THREAD

**Issue by CloakerCobra** [raithos/xwing#1308]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
I need more information on what is happening, or i will have to close this, it looks like the x1 and v1s are working just fine

**Comment by raithos** [comment]
your images didnt load. 

Here's what I see:
https://puu.sh/JLAEd/4df174170d.png

https://puu.sh/JLAEk/e94149ee0a.png


Signs point to some sort of cache issue. have you tried doing a hard refresh, or clearing out your cache/cookies?

**Comment by CloakerCobra** [comment]
![image](https://github.com/raithos/xwing/assets/57611952/ec4b183f-cb80-40e1-9277-85d7c80a4a21)

**Comment by CloakerCobra** [comment]
the issue seems to be on multiple devices- i tried from my laptop and my desktop.

**Comment by CloakerCobra** [comment]
also, even when I use randomizer, x1 and v1 do not come up. 
![image](https://github.com/raithos/xwing/assets/57611952/d984a8ff-53c7-4b59-843d-8f2717e635fd)

**Comment by CloakerCobra** [comment]
When i view in incognito mode, however, they are accessible.

**Comment by raithos** [comment]
One other thing to ask. Can you try making another account and logging in that way? This sounds like a problem with your account specifically... and may require you to reset your collection.

**Comment by CloakerCobra** [comment]
I found the error. It is the AdLock https://adlock.com/adlock-for-chrome/
extension. I removed it and now it all works fine!

**Comment by raithos** [comment]
ah ok i see. you can also make an exception for login.yasb.app and that may also help. glad we could resolve this
