### ISSUE TITLE
Allow for loadouts values to be exceeded

### ISSUE THREAD

**Issue by jasonmbautista** [raithos/xwing#1310]
**Is your feature request related to a problem? Please describe.**
Webapp does not allow you to have the loadout values to be higher than the maximum value for any given pilot. There are variations of games eg Aces High where it is common to have a lower Ace value be offset with additional loadout points. ie Aces High 6pt Aces, a 5pt Ace will be allowed to play with a +10 loadout value. 

**Describe the solution you'd like**
A setting/option to allow loadouts to exceed maximum loadout values of a pilot. Maybe a section to support "special" game types or just a popup that says "loadout value is exceeded, this is not a tournament legal squad" and you can dismiss it and still print the list.

**Describe alternatives you've considered**
I have not seen anyway for this to happen in the current solution. I thought about trying to cut/paste in an image  editor but it is a cumbersome process.

**Additional context**

**Comment by Patschke** [comment]
We already had this request earlier (https://github.com/raithos/xwing/issues/1257). I'm still not a fan of it, so it will need more people to request this before I consider actually implementing it. There are just too many custom/szenario/fan modes with different rules. What if someone wants ships to have arbitrary slots available? What if someone wants to allow multiple uniques? 

For now I'd rather stick with only supporting the main game modes, which makes it somewhat easier to verify that a list is legal.

**Comment by raithos** [comment]
I have the same opinion as @Patschke, this is the kind of thing that goes outside the scope of what yasb is doing. I understand how this would be helpful, I just think that it's not that YASB should be doing. Going to mark this as will not implement for the time being.
