### ISSUE TITLE
Google authentication failure 8/1/23 

### ISSUE THREAD

**Issue by Disemboweled** [raithos/xwing#1313]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** You might notice some of your loose ships are missing from your collection. This is a known issue from a recent update regarding ship names. Unfortunately you will have to reenter the missing ships. Sorry for the inconvenience.

### Expected Behavior
google sing in resulting in all saved squads showing up

### Actual Behavior

authentication flashes then the log in symbol shows no change. No saved squads show up.  reload page, same results. this has been happening for 24 hours now since 7/31/23 at 10pm central time (0200 UTC 8/1/23) 

I checked YASB 2.5 and the authentication behaves normally.  

### Language

The affected language(s).  English, USA 

https://raithos.github.io/?f=Galactic%20Empire&d=v8ZsZ200Z&sn=Unnamed%20Squadron&obs=

Thank you for the use of the site over the years.  My friends and i still play 2.0 regularly and are very happy with 2.0 
Jason

**Comment by Patschke** [comment]
For me the log in in YASB 2.0 still works (tested using Firefox and Chromium). There are some errors popping up in the console. Some related to language choice, and also some CORS warnings that might cause some sort of issues for the interplay with the backend login server. However, as I was unable to see an obvious cause for your issues within a few minutes, I am not willing to dig deeper or provide support for YASB 2.0 anymore - as long as it works, fine. If it breaks - so be it. 

Perhaps as a workaround for you: Saving bookmarks for your squads and using your browser for list management should be possible without requiring any login. This will of course not restore the squads you already have saved within YASB...

**Comment by Disemboweled** [comment]
Thanks for checking!

I understand not wanting to spend any time on the old 2.0 YASB.

I was using Chrome on a work issued Microsoft surface pro. My phone using
chrome still worked fine for fetching lists, that's why I was perplexed.
Especially since I was able to log into 2.5 fine. 🤷‍♂️

I did scrub my catch and delete my browser history on my chrome account.
But I didn't get any improvement.

Thanks again for looking, I realy do appreciate it!

Jason

**Comment by raithos** [comment]
have you checked if your browser allows for 3rd party cookies to be used on the site? that is an actual issue that necessitated our move to yasb.app...  I think chrome recently changed the default to block all 3rd party cookies. this isnt an issue for yasb.app since everything is on the same domain now.

**Comment by Disemboweled** [comment]
I will look into that.

My home chrome worked fine. And I tried whatever browser Microsoft had
loaded on my work computer and i was able to log in there too.  Its just
the work computer chrome. 🤷‍♂️

I'm on vacation this week and I'll try the 3rd party cookies setting. Work
might have locked it down

Thanks once again!

JB
