### ISSUE TITLE
Horton slam (rebel y-wing) missing talent slot

### ISSUE THREAD

**Issue by raymondliong123** [raithos/xwing#1314]
**Describe the bug**
Horton slam (rebel y-wing) missing talent slot

**To Reproduce**
1. Go to 'rebel faction'
2. Click on y-wing
3. Scroll down to 'horton slam
4. See error - no talent slot

**Expected behavior**
Should have talent

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
I don't think that he is supposed to have a talent slot:

![image](https://github.com/raithos/xwing/assets/17853362/d4172b55-7a1c-43c9-8d88-964775271a41)


According to the latest [point document](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/646e499599233b36007508ba/1684949400287/Ship_Points_06.09.23_v2.pdf) from the [X-Wing documents page](https://www.atomicmassgames.com/xwing-documents), there is no talent slot. 

From what I can see everything is as intended.
