### ISSUE TITLE
Vectored Cannons XWS export name incorrect

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#1324]
I deleted the template because I'm a monster. Vectored Cannons (RZ-1) is exporting as `vectoredcannons-configuration`, but should be `vectoredcannonsrz1`
Example:
https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z51XWW371&sn=Unnamed%20Squadron&obs=
xws snippet:
`"rz1awing","upgrades":{"configuration":["vectoredcannons-configuration"]}}]`

...At least, I'm reasonably confident. It seems weird this hasn't been caught before, and there's been some issues with XWS lately, but as far as I can tell `vectoredcannonsrz1` is the actual correct xws id.

**Comment by Patschke** [comment]
I guess you're correct. Will be fixed.
