### ISSUE TITLE
Add option to display card images in builder and card browser 

### ISSUE THREAD

**Issue by Hikomo** [raithos/xwing#1326]
Add images of the pilot art, like how the builder for X-Wing Legacy does, and the option to view the full card image when searching the image in the card browser.

**Comment by Patschke** [comment]
I'm not sure if I like that. Sure, it looks neat, but it also occupies screen space. Especially for pilots, that additional image may move the maneuver chart out of view. For upgrades that's usually less of a concern.

**Comment by raithos** [comment]
Yeah, i saw what they did, I have no intention to do so in the list builder, though I may consider it for the card browser.
