### ISSUE TITLE
Deathfire” (TBE)

### ISSUE THREAD

**Issue by Innkeeper16** [raithos/xwing#1331]
Deathfire TBE SL card on YASB has the initiative listed at a 3, but I think it should be a 2.

Can you please look at this?

Thanks for all you do for the community.

**Comment by Innkeeper16** [comment]
It looks like the custom Deathfire was updated but not the SL Deathfire.

**Comment by raithos** [comment]
no, please be patient, closing the issue doesnt mean its goin glive right away, just that the issue is solved in the code

**Comment by Innkeeper16** [comment]
Thanks, I thought closed meant it was resolved... Happy you are working on
it.  Thanks.
