### ISSUE TITLE
Unrestricted Squad Builder

### ISSUE THREAD

**Issue by sirloinsandvich** [raithos/xwing#1333]
Sometimes I like to make a list of all the ships in a faction that I feel are strong options at different points values. It helps to be able to look at a list like this when list building. However, since you can't have more than one copy of a pilot in a list it's impossible to add a pilot and their Standard Loadout version to the same list. It's also impossible to have multiple ships with the same crew, etc.

I'd like to propose a feature where you can check a box (maybe next to the format selector) that would set the list builder to "unlimited mode" which then ignores the limited pips on pilots and upgrades. That way we could build lists of pilots and different builds all in one place as a way to theory-craft.

**Comment by raithos** [comment]
sorry not interested in implementing something like this.
