### ISSUE TITLE
Obstacle choices not updating link

### ISSUE THREAD

**Issue by DeployerOfMajesty** [raithos/xwing#1335]
**Describe the bug**
When I build a list in YASB and go to add obstacle choices, the URL no longer updates to include those choices. This differs from past behavior where it would update the URL accordingly.

**To Reproduce**
1. Go to yasb.app
2. Click on Select a Ship, choose the top option (Rebel ARC-170 Garven)
3. Scroll down and click on Choose Obstacles, then select Core Asteroid 0, and hit Close 
4. The URL should update to https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z79XWWWWW&sn=Unnamed%20Squadron&obs=coreasteroid0 but it is instead still https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z79XWWWWW&sn=Unnamed%20Squadron&obs=

**Expected behavior**
The URL should update to https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z79XWWWWW&sn=Unnamed%20Squadron&obs=coreasteroid0 but it is instead still https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z79XWWWWW&sn=Unnamed%20Squadron&obs=

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 - Version 16.6 (I think?)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS16.6.1
 - Browser stock browser safari
 - Version 16.6 (I think?)

**Additional context**
This has worked in the past, including in the 1.0 YASB, the original 2.0 YASB, and this version of YASB. I don’t know when it stopped working.

**Comment by DeployerOfMajesty** [comment]
Sorry, I shouldn’t have filled out the desktop section with my mobile information

**Comment by raithos** [comment]
reworked.
