### ISSUE TITLE
Add standardized loadout and slot info when selecting pilot from the dropdown

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#1336]
**Is your feature request related to a problem? Please describe.**
When looking through pilots in the dropdown, you don't see what's on standardized loadouts until after you select them.  

For the non-standardized loadout most all the information you needed to pick a pilot (name, ship, initiative, cost, loadout) is available in the side bar.   Slots are not.

**Describe the solution you'd like**
Add the names, and perhaps the text of the standardized loadouts to the side bar.

**Describe alternatives you've considered**
"Ghost" in the slots and any standardized loadouts, so they change as you go through the drop-down, not when you select in drop-down.  But also keep an upgrades selected there?  Where possible?

**Additional context**

**Comment by raithos** [comment]
this would be a LOT of work to do as requested, which i am very much not interested in doing. best i could offer is listing the standard upgrades in the side bar but even then im not sure that its something i would do.

**Comment by XPav** [comment]
If I win 4 Worlds will you add this feature?

**Comment by raithos** [comment]
Nope. If you could win worlds 4 times clearly the feature is not needed.

**Comment by raithos** [comment]
ive done the sidebar thing. doing the full request would require an entire system that would have to save your equipped  upgrades and then reload them for other pilots, its really not worth doing.
