### ISSUE TITLE
Some text not converting from english to spanish

### ISSUE THREAD

**Issue by GameBot2022** [raithos/xwing#1339]
I am trying to use the squad builder in Spanish to print consolidated descriptions.

Most, but not all of the text is correctly displaying in Spanish on the print-out.

The following are displaying English text on the printout even though the rest of the text is correctly displaying in Spanish.

Advanced Targeting Computer
Advanced Fire Control
Auto Thrusters
Deadeye Shot
The Malice force power is displaying English text on the printout.
TIE Defender Elite

The tool-tip that you see when you hover over the upgrade on the webpage has the same problem with the same items.

I'm sure there will be others... is there any way to check if you have Spanish text versions for all English text that you have?

Thanks for a great site :)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
The last update to the Spanish localisation was in April by @ajtudela (after we had no updates on the Spanish files for 3+ years). There is only one chassis ability (e.g. ship ability that is independent of the pilot) translated to Spanish, so they'll show up in English instead. Contributions to add more translations are welcome, so feel free to help us! We don't have anything like official translations available, so there is not much I can do to change this without the help of people like you who actually play the game and have Spanish content available...

**Comment by ajtudela** [comment]
Hi all!

I've been very busy this last months. I'll try to continue translating next week. 

@GameBot2022 If you want to help me to translate, please, let me know so we can organize us.

**Comment by ajtudela** [comment]
I just did a full spanish update here: #1344

If there is something wrong, please let me know: @GameBot2022
