### ISSUE TITLE
Please add spanish text versions to the quick build deck page on your site

### ISSUE THREAD

**Issue by GameBot2022** [raithos/xwing#1340]
As per the subject line - the current quick build page only shows english text.  Please allow it to show spanish text too as you are already supporting spanish text on other parts of the site.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raithos** [comment]
Im going to close this as a duplicate of the core issue in #1339
