### ISSUE TITLE
Support Extended with Ban List in Effect

### ISSUE THREAD

**Issue by BeautyNova** [raithos/xwing#1341]
A good chunk of local communities are doing extended format with the ban list active to remove some power combos but encourage their community to fly the ships they want to fly.

Players with limited screen real estate are either working off memory or swapping back and forth with a pdf which is clunky.

Either a dedicated "Extended with Ban List" mode or a toggle to enable Ban List options would be appreciated.

Here's a screenshot of a player just oopsieying that Composure was banned.

![Screenshot_20231004_112826_Discord](https://github.com/raithos/xwing/assets/101352721/84723678-9c55-485f-b942-a34f653a393c)

**Comment by raithos** [comment]
historically yasb has not supported any unofficial alt formats. i'll have to think about this one

**Comment by raithos** [comment]
ive added a button to add the ban list to extended, its in the misc. settings menu in the red arrow dropdown.
