### ISSUE TITLE
Wrong ship ability in German for Shazam szaro resistance y-wing

### ISSUE THREAD

**Issue by surfing-fin** [raithos/xwing#1342]
The English version states correctly:

After you defend, you may choose a friendly ship in your  at range 0-2 and 1 of your green tokens. If you do, that ship gains a matching token.

it shows the rear 180 degree radius for the rear firing arc

the German version shows only a 90 degree rear firing arc.

regards
Daniel

**Comment by raithos** [comment]
@Patschke

**Comment by Patschke** [comment]
Thanks for the note, will be fixed with #1343
