### ISSUE TITLE
Independent Calculations on Rogue Class

### ISSUE THREAD

**Issue by WmThelen** [raithos/xwing#1346]
**Describe the bug**
Unable to take Independent Calculations on Rouge-Class Starfighter for ships with Networked Calculations.

**To Reproduce**
1. Go to Separatist Rogue-Class Starfighter
2. Click on Modifications
3. Scroll down to Independent Calculations

**Expected behavior**
Since it has networked calculations, be able to select independent calculations. It works on Smart Phone

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 10.0.19045

**Comment by Patschke** [comment]
I am unable to reproduce this bug using my system (Firefox on Arch Linux). I'll try to see if I can find a Windows machine to check if Edge is messing up something (given that it is also working using your phone makes that somewhat likely).

**Comment by WmThelen** [comment]
I’m not sure what happened. Now I am able to select! Maybe it was my
internet connection not registering the change from Cad or Durge. Sorry for
the time waste!
