### ISSUE TITLE
C-Roc Corsair Refit

### ISSUE THREAD

**Issue by TimTheITGuy** [raithos/xwing#1347]
**Is your feature request related to a problem? Please describe.**
Thank you for being willing to post points for huge ships. The problem I am hitting is when trying to put together a CRoc Cruiser with Corsair Refit: there just aren’t enough points.

**Describe the solution you'd like**
Do you think it would be wise to split the std confit from the Corsair config in the same way the Delta-7 & Delta-7B are split?

**Describe alternatives you've considered**
The only other options I have looked at involve scaling load out points higher and that hasn’t balanced well in the past. I think you guys will/have done a better job than I have.

**Additional context**
I really appreciate the work you are doing on this app. AMG should subsidize you.

**Comment by raithos** [comment]
unfortunately i dont take feedback on epic points.
