### ISSUE TITLE
German translation for "Tag", under Squad Notes

### ISSUE THREAD

**Issue by Zweihaender9** [raithos/xwing#1349]
"Tags" would make more sense.

**Comment by Patschke** [comment]
Hmmm. I have to admit that the Duden actually lists the word `Tag` in the sense of `marker`, not just in the "German" sense of `day`. However, it is still somewhat just an English word that is now used in German? I prefer "real" German translations (and think `Kategorien` is fine?), as I believe that the target audience for the German translation are people, who are not speaking English and are rather not familiar with the use of `Tag` in this sense (e.g. from my experience some older players in our community). Another options could perhaps be `Stichwörter`?
