### ISSUE TITLE
Login not possible - "Internal Server Error" Error Message after Authentication

### ISSUE THREAD

**Issue by Boardbender** [raithos/xwing#1350]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** You might notice some of your loose ships are missing from your collection. This is a known issue from a recent update regarding ship names. Unfortunately you will have to reenter the missing ships. Sorry for the inconvenience.

### Expected Behavior
A successful login after authentication to google or discord
State what you expect to happen here.

### Actual Behavior
Login was not successful, after credential authentication to google or discord  a "Internal Server Error" from "https://yasb-backend.herokuapp.com/" was returned.
State what actually happens here.

### Language
English, German; happens on two different Win10 Systems using Edge and Firefox Browser
The affected language(s).

**Comment by Patschke** [comment]
Sorry, we don't support 2.0 anymore. This repository is for [YASB 2.5](https://yasb.app). The last state of the 2.0 squad builder may stay around, but most likely won't receive any bug fixes. If you are looking for an updated version of 2.0 squad builder, I recommend the [X-Wing Legacy](https://xwing-legacy.com) fan project.

**Comment by Boardbender** [comment]
ok, thank you.
