### ISSUE TITLE
Your Collection Idea

### ISSUE THREAD

**Issue by matthewlauletta** [raithos/xwing#1353]
**Is your feature request related to a problem? Please describe.**
When adding cards to "Your Collection" it is difficult when multiple cards have the same name. 

**Describe the solution you'd like**
It would be great to add the card type icon and more descriptive in parenthesis. 

For example; 
*Astromech symbol R2-D2 (Rebel)
*Astromech symbol R2-D2 (Republic)

Or

*Pilot Symbol Chewbacca
*Crew Symbol Chewbacca

**Additional context**

Here is a screenshot of this issue. How do I know which Ahsoka Tano card I have because there is no differentiation. 

<img width="480" alt="Screenshot 2024-01-10 at 15 01 36" src="https://github.com/raithos/xwing/assets/77907092/38c2de93-4635-4e75-b458-7cb010607271">

**Comment by matthewlauletta** [comment]
I'm sorry, This is only the case in the Pilot section. I want to make sure I am adding the correct pilot card.

Thank you

**Comment by Patschke** [comment]
Hmm. What's easy to fix is adding all those missing icons: 

![image](https://github.com/raithos/xwing/assets/17853362/71f5b9e2-16ef-47e3-b467-d93e90fceb14)

Often this is already enough to tell which one is which, e.g. it's clear which of the many Ezras one wants to select: 

![image](https://github.com/raithos/xwing/assets/17853362/c4027338-8137-406f-9b4b-c3658b7be0a2)


I don't have a good idea on how to differentiate between multiple pilots on the same ship (or almost the same ship, like it is here the case for Delta-7 vs Delta-7b).

**Comment by matthewlauletta** [comment]
Ok. I understand the issue. I have a few ideas.

1. On hover, show the card text.
2. Maybe part of the fix would be stating which edition it is from. I think that is the issue with Dash Rendar.
3. Link to a wiki that has the image of the card.

I want you to know that I really appreciate YASB and thank you for doing what you do.

**Comment by raithos** [comment]
This fix will have to wait until after Feb as I have a number of unpushed changes due to the battle over endor stuff. Sorry!

**Comment by raithos** [comment]
never mind, i had to fix the facebook thing so i stashed all my changes for now, this is resolved via @Patschke's fix. I am issuing a seperate fix for dash, I am renaming the scum one to not be confused with the rebel one.

**Comment by Patschke** [comment]
There are no different icons for Delta 7 and Delta 7b. Also, only half of them really exist, while the other one is only available as print out. I guess for tournaments, the Delta 7 card is the one technically required for both options? So I am somewhat fine with leaving that as is?

**Comment by raithos** [comment]
yeah for delta 7b you cant buy it in product so you just have it, so people can do whatever they want there. So there's basically 1 edge case that the existing solution doesn't solve, and it's not enough for me to do anything about it, you need the same pilot, and same ship, different factions. pilots in the same ship and same faction are differentiated anyway so none of that is a problem, and different ships are already taken care of. there's exactly 1 case that i am aware of there and its durge and both pilots come in the same pack so i dont care.
