### ISSUE TITLE
Resistance Leia points wrong 

### ISSUE THREAD

**Issue by Hamdamcwa** [raithos/xwing#1357]
**Describe the bug**

**To Reproduce**
1. Try to create a resistance list
2. Click on millennium falcon with 2x crew slots
3. Select Leia Organa
4. Be sad when you see it is advertised at 16 points when it's really 14

**Expected behavior**
Leia should be 14 points

**Comment by raithos** [comment]
huh?
https://puu.sh/JZfm9/cb3e03749b.png

What url are you using, i bet its not yasb.app, its probably yasb.app/old

**Comment by Hamdamcwa** [comment]
Thought it was here on the site...

https://yasb.app/?f=Resistance&d=v9ZhZ20Z246XWWWWWWWWW&sn=Unnamed%20Squadron&obs=

But just checked again and it's fine.

Probably just use error! Thanks and sorry!

D


Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
