### ISSUE TITLE
QR codes not working

### ISSUE THREAD

**Issue by GoldSquadronPodcast** [raithos/xwing#136]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Scanning Qr code of squad should bring up squad on browser

### Actual Behavior

Old 1st edition squad shows up

### Language

The affected language(s).

**Comment by raithos** [comment]
yes. i will get to this soon

**Comment by GoldSquadronPodcast** [comment]
great, I am working on my review video for YASB 2.0 and wanted to make note of it. Thanks!

**Comment by raithos** [comment]
should be good to go now.

**Comment by GoldSquadronPodcast** [comment]
great thank you!
