### ISSUE TITLE
Chewie and Engine Upgrade

### ISSUE THREAD

**Issue by Buddhha** [raithos/xwing#1361]
**Describe the bug**
Modified YT-1300 Light Freighter with Chewie pilot is unable to use Engine upgrade. 

**To Reproduce**
1. Choose Modified YT-1300 Light Frighter
2. Choose Chewbacca pilot
3. Click on Modifications
4. Engine upgrade is gray

**Expected behavior**
If Chewbacca card is proper, then you would be able to choose Engine upgrade

**Screenshots**
![image](https://github.com/raithos/xwing/assets/6568119/04dae1be-61ab-43af-aebd-1e18d3d9c68a)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 121.0.6167.161

**Comment by Patschke** [comment]
Well, given that you've already spend 16 out of Chewies 18 upgrade points on Bistan and the Copilot, you only have 2 points remaining. That's not enough for an Engine Upgrade. You can't have everything you want, but I guess that's the rules fault not ours...

**Comment by Buddhha** [comment]
What a blame for me... :)

Sorry for disturbing!

Cheers!
I'm hard as a rock, and wise as a mountain!

---> http://franyoland.myminicity.com/ <---

---> http://buddhha-hun.mybrute.com <---


Patrick Mischke ***@***.***> ezt írta (időpont: 2024. febr.
16., P, 12:09):
