### ISSUE TITLE
Add a toggle to allow multiple of the same unique name in a squad

### ISSUE THREAD

**Issue by JediOswald** [raithos/xwing#1362]
**Is your feature request related to a problem? Please describe.**
It can be difficult to compare different loadouts for a pilot in a list without being able to see those loadouts next to each other on the same page as each other.

**Describe the solution you'd like**
Add a little checkbox toggle next to the standard/extended/epic dropdown to allow multiple unique cards in a list.

**Describe alternatives you've considered**
Using Launch Bay Next which I try to avoid because it crashes often for me, pen and paper, multiple YASB tabs open simultaneously, and copy/pasting the XWS for a pilot over and over into the list to bypass the restriction.

**Additional context**
When sharing my XWS code find on discord others mentioned wanting this feature too.

**Comment by Patschke** [comment]
Having multiple tabs open does not seem to bad to me. We prefer to only allow building legal squads. 

The main issue for allowing illegal lists in any way: People will forget that they had that setting turned on and end up with lists that are still illegal after removing the disregarded pilot variants. I can easily see a list that e.g. contains two copies of something like lone wolf or Electron-Proton-Bombs, where it is not obvious that they are unique.

**Comment by raithos** [comment]
I checked and  you cannot import via xws the same name currently, so I am going to close this. I have no intention of allowing illegal lists in any capacity at this time.
