### ISSUE TITLE
Rouge Class Starfighter (Separatist and Scum) doesn’t list its pilots for quick build

### ISSUE THREAD

**Issue by Dr-D12345** [raithos/xwing#1366]
**Describe the bug**
The Rouge Class Starfighter lists no pilots under a quick build squad. This appears under both Scum and Separatist

**To Reproduce**
1. Create a new Separatist Squad
2. Select Quick build
3. Add a Rouge Class Starfighter ship
4. Select Pilot will display nothing found
**Expected behavior**

The correct pilot and value should be available. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] IPad Pro 12.9 2021
 - OS: [e.g. iOS8.1] IOS 17.4
 - Browser [e.g. stock browser, safari] Safari
 - Version [e.g. 22] 17

**Additional context**
Just noticed this happen to me, figured it would be a quick fix so I would mention it.

**Comment by Patschke** [comment]
Yep, that's right. Nobody added them to YASB yet. I do not own any Scum/Separatists, so I have no idea whats written on those Quickbuilds. All i could find in the [Wiki](https://xwing-miniatures-second-edition.fandom.com/wiki/Rogue-class_Starfighter_Expansion_Pack) is that there are "Rogue-class starfighter Quick Build Cards (x4)". 

Feel free to add the missing quickbuilds yourself. Perhaps look here for how to do that https://github.com/raithos/xwing/issues/1194#issuecomment-1310149233

I'm happy to help if you have any questions!
