### ISSUE TITLE
First, thank you! Can you make the stat lines easier to read?

### ISSUE THREAD

**Issue by sparkerwon** [raithos/xwing#1368]
Your site is excellent!  I just wish the fancy PDFs were easier to read.  It's really just the stat lines for me that are hard to read.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't read the stats.

**Describe the solution you'd like**

Please enlarge the stat lines and use a high-contrast background color.

Thank you so much!

**Comment by raithos** [comment]
is this a printing problem? the pds are generally really easy to read since theyre color coded. if youre having trouble, try printing the pdfs off in black and white

**Comment by sparkerwon** [comment]
It may be an eyesight problem.  I'm getting old.  I'll try the B&W thing. I think it will help. Thank you.  I'm attaching a PDF in case you would like to confirm that it's working as intended, or I'm not shrinking the font on my end.

In any case, thank you, thank you, thank you...!!!

[YASB - Luke Han and Wedge Black White.pdf](https://github.com/raithos/xwing/files/14474643/YASB.-.Luke.Han.and.Wedge.Black.White.pdf)
[YASB - Luke Han and Wedge.pdf](https://github.com/raithos/xwing/files/14474644/YASB.-.Luke.Han.and.Wedge.pdf)

**Comment by raithos** [comment]
that looks right to me. hopefully the B&W versions work for you
