### ISSUE TITLE
BTL-NR2 Y-wing Shasa error

### ISSUE THREAD

**Issue by schdarr** [raithos/xwing#1373]
The BTL-NR2 Y-Wing of the Resistance faction pilot, Shasa Zaro, does not have a Talent slot, according to AMG's ship points document. But on YASB she loads with a Talent. 
![screenshot-cdn svc asmodee net-2024 03 05-11_44_01](https://github.com/raithos/xwing/assets/162369972/3d6a3cac-b7c6-4dd8-8846-5727bff61c65)
![screenshot-yasb app-2024 03 05-11_43_21](https://github.com/raithos/xwing/assets/162369972/1a371e5d-3d36-4b68-afe5-9536ad247dc8)

**Comment by raithos** [comment]
okie, i fix
