### ISSUE TITLE
Export "Your Collection" as .csv

### ISSUE THREAD

**Issue by TheRobDob** [raithos/xwing#1374]
A feature to export "Your Collection" as a .csv. Include the same counts and information under: 
Expansions
Ships
Pilots
Upgrades
Inventory

**Comment by Patschke** [comment]
This has been suggested in the past. Look at #1227 and #585. Unless you have a new reason why this is required, I'm personally not going to implement it. 

TLDR: https://login.yasb.app/collection holds a json version of your collection.

**Comment by raithos** [comment]
agreed. this is to fringe to implement as a feature. please use the collection link to rip your collection info from json
