### ISSUE TITLE
Allow "restrict by collection" to ignore sections with no cards

### ISSUE THREAD

**Issue by meat-and-breath** [raithos/xwing#1375]
**Is your feature request related to a problem? Please describe.**
I'm just getting back into the X-Wing TMG after some time away, so I have conversion kit pilots and upgrades plus a bunch of 1.0 ships. I want to be able to generate random squads from my collection and I don't want to have to populate all the pilot snd upgrade sections.

**Describe the solution you'd like**
I can imagine two possible solutions:

1. For each collection "page" (e.g., pilots, upgrades, inventory), have a separate toggle for whether to enforce inventory check for that card type. So, for example, I'd like to enforce it for ships, or maybe ships and expansions.

2. Cause adding an expansion to a collection to automatically include all the pilots and upgrades for that expansion when limiting to collection.

**Describe alternatives you've considered**
The alternative is to add every pilot and upgrade card from all the conversion kits and expansions, in addition to adding all of the ship models. This is certainly possible, but it's kind of a PITA.

**Additional context**
Maybe I'm missing something about how the system currently works. Currently, I have entered all my ship models and the Resistance and First Order conversion kits, but if I "limit to collection" and do a quick build, I pretty consistently get an MG-100 in my squad, which is not a model that I have. (So maybe all of this is actually just a bug?)

**Comment by raithos** [comment]
So you're asking for this?
https://puu.sh/K3QrA/dab28298db.png

**Comment by raithos** [comment]
or let me be more specific. if you state you own a conversion kit, and then add your loose ships, when  you randomize, it should do exactly what you want.

**Comment by meat-and-breath** [comment]
Hmm, I think I had at least one random squad that included a ship I don’t own, but it’s possible that’s user error. I’ll close this issue and see if I can reproduce it for a big report.
