### ISSUE TITLE
Missing Command Upgrades

### ISSUE THREAD

**Issue by Everlasting428** [raithos/xwing#1376]
**Describe the bug**

YASB is Missing the “Bounty” and “In it for the Money” command Upgrades when selecting the EPIC feature 

**To Reproduce**

**Expected behavior**
 
 I was expecting the afore mentioned upgrades to be there.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  - iPhone 12
 - OS: [e.g. iOS8.1] - iOS 17.4
 - Browser [e.g. stock browser, safari] - Safari

**Additional context**

Could the two command upgrades (“Bounty” & “In it for the Money”) please be re-added

**Comment by Patschke** [comment]
I can't reproduce this issue.

![image](https://github.com/raithos/xwing/assets/17853362/75347570-3a2e-487f-a209-4fa9df453240)

Both upgrades show up just fine for me. Note that they are Scum only and limited pilots only. 

If something you did makes them disappear, I need a more detailed description of your issue. Otherwise I don't know what to fix so I can't fix it.

**Comment by Everlasting428** [comment]
![IMG_7878](https://github.com/raithos/xwing/assets/105462618/93ea73a1-8889-4904-bc4f-5b1038ee9e57)

**Comment by Everlasting428** [comment]
I’m using YASB on my phone (sorry, I should have included this information when sending the screenshot file) and still not seeing it. Is there a way to fix it on my end?

**Comment by Patschke** [comment]
Again, I'm unable to reproduce that. On my phone (running Android with Firefox 124.1.0) everything works just fine. If I scroll down, there are all the command upgrades including Bounty & In It For The Money. I've never noticed, that there are screen width for which the right box is not yet moved down but the text doesn't fit either, so perhaps we should look into that. But this seems to be unrelated.

Given that you closed the issue I assume, that you resolved this?
