### ISSUE TITLE
Feature Request - Card Totals

### ISSUE THREAD

**Issue by dmz-uk** [raithos/xwing#138]
Under "Your Collection", listing card totals for each category / overall would help plan sleeve / folder purchases.

**Comment by Patschke** [comment]
I'll have a look at this

**Comment by Patschke** [comment]
Done in #139 

As soon as this PR goes live, you will be able to check the requested totals in the inventory tab (scroll down to the bottom).

**Comment by dmz-uk** [comment]
Absolutely brilliant, thanks!
