### ISSUE TITLE
Hello, was looking at the SCUM faction, extended and if you look at the Starviper "prince xizor" the the (microthruster) is actually listed twice (2 times) on the ship data.

### ISSUE THREAD

**Issue by Lybo24** [raithos/xwing#1381]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raithos** [comment]
duplicate
