### ISSUE TITLE
Hello, was looking at the SCUM faction, extended and if you look at the Starviper "prince xizor" the the (microthruster) is actually listed twice (2 times) on the ship data. I'm using Win10 64bit and chrome.

### ISSUE THREAD

**Issue by Lybo24** [raithos/xwing#1382]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.
