### ISSUE TITLE
List Export options.

### ISSUE THREAD

**Issue by redFarreg** [raithos/xwing#1386]
Under the 'Text' option, could we have the ship type included on the same line?

Is it also possible to add a Discord option?

In short you would be using the 'Text' option but putting putting 2 stars ( ** ) at the beginning and end of any line that is to be bold (Name of Pilot) and 1 star ( * ) at the beginning and end of any line for italics (Ship cost line) 

So a list for Discord may look something like:

**"Chopper" - VCX-100 (6)**    
    Dorsal Turret (2)    
    Saw Gerrera (9)    
    Veteran Turret Gunner (3)    
    Ghost (0)    
    
*Ship Cost: 6  Loadout: (14/14)  Half Points: 3  Damage Threshold: 7*
    
**Ezra Bridger - Gauntlet Fighter) (6)**
    Hera Syndulla (4)    
    Contraband Cybernetics (3)    
    Nightbrother (0)    
    Swivel Wing (0)    
    Magva Yarro (5)    
    
*Ship Cost: 6  Loadout: (12/12)  Half Points: 3  Damage Threshold: 5*
    
**"Leebo" - TY-2400 (YLF-SL) (6)**   
    Efficient Processing (YLF) (0)    
    Seeker Missiles (YLF) (0)    
    Outrider (0)    
    
*Ship Cost: 6  Loadout: (0)  Half Points: 3  Damage Threshold: 5*    
    
**Sabine Wren - TIE Fighter (2)**   
    Beskar Reinforced Plating (3)    
    
*Ship Cost: 2  Loadout: (3/3)  Half Points: 1  Damage Threshold: 1*    
    
    
**Total: 20**    
    
View in YASB: https://yasb.app/?f=Rebel%20Alliance&d=v9ZhZ20Z63XW137WWW58W90WW148Y520XWW35WWW92WWW448W449W51Y652X499W500W157Y13XW445&sn=Big%20ships%20little%20ship&obs=

**Comment by raithos** [comment]
i dont mind doing this, but is it really needed? a) the normal text version does the same thing without the bold and italics, b) a lot of discords are using r2d7, and c) those that dont just tend to post the link anyways. anyways, counterpoint me as you wish

**Comment by redFarreg** [comment]
Not really, the only thing it doesn't show in is DMs, and I figured this was just an opportunity to optimise. 

Having said that, listing the ship type would be nice. :)

**Comment by Patschke** [comment]
I like that.
