### ISSUE TITLE
Incorrect Info on YASB 2.5

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#1389]
Hi! Not so much a bug, as an error... the standard loadout Imperial TIE/ln Fighters from Battle Over Endor (BoE) (namely, Lieutenant Hebsly, Major Mianda, and Scythe 6) are all listed in YASB as having [Target Lock] on their action bar, but they don't, actually. 

Thanks for all you do. I really enjoyed using LaunchBayNext for a good long time, but I found that YASB is updated and corrected much more frequently, and I almost never find errors like this. Cheers!

-Jeremy

**Comment by Patschke** [comment]
Thanks for the catch, will be fixed with the next update!
