### ISSUE TITLE
Multifaction to allow ships to have upgrades from other factions.

### ISSUE THREAD

**Issue by jamesrhum** [raithos/xwing#1391]
When you attempt to create a multifaction list
e.g.: https://yasb.app/?f=All&d=v9ZsZ20Z81XWWWWWWWY605XWW191WWWWWW&sn=Unnamed%20Squadron&obs=

The crew option of IG88-D isn't there for Lando, only the resistance and generic crew options.

**Comment by raithos** [comment]
This is working as intended. There are no rules around this so I made a conscious decision not to allow cross faction upgrades, only cross faction ships. I have no intention of ever changing this as it would require a huge rework for what is effectively a feature for 1 upgrade card in epic.
