### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by brunoip** [raithos/xwing#1392]
Hello, I have seen a few issues with the Spanish translations and I would like to help with that.

**Comment by Patschke** [comment]
Sure, any help is always welcome! Just fix the issues in the Spanish translation file (`coffeescripts/translations/cards-es.coffee`) and send us a PR. If you need any help on how to do so feel free to ask. 

The last person working on Spanish translations was @ajtudela about half a year ago (pinging just to make sure that there aren't two persons working on the same thing).

**Comment by ajtudela** [comment]
Yeah, no problem. Make a PR and I'll review it!

**Comment by raithos** [comment]
closing this since i saw the PR and approved
