### ISSUE TITLE
Alternative X-wing format with Epic ships

### ISSUE THREAD

**Issue by Greedypirat3** [raithos/xwing#1397]
**Is your feature request related to a problem? Please describe.**
I listened to your podcast and heard your were working on a format with Epic ships. I made a format during Covid I called "Task Force" and ran a small tournament in 2021. Its fun and games, but as you are doing something similar,  I thought I would share to give some input. You may ofcourse use whatever you like or discard it entirely :-).

I have made a doc in pdf (link below), you can also have acces to the Google doc if you would like ;-).
If you would rather have me send the pdf just e-mail me thorbjoern.nielsen@gmail.com, and I will send it (if you distrust links).
https://drive.google.com/file/d/1YTnnNdwpLbLfzk1L8vOxv3FxNQFuZdK6/view?usp=sharing

I am looking forward to the community driven X-wing

Cheers from DK

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raithos** [comment]
XWA is working on new stuff for epic, so my homebrew epic will soon be coming to a close.
