### ISSUE TITLE
Ships missing from collection list

### ISSUE THREAD

**Issue by randy-ja** [raithos/xwing#14]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

Expected all ships to be listed under the "Ships" tab when entering collection information.

### Actual Behavior

Several are missing, including Arc-170, Atttack Shuttle, Auzituck, Scurrg, and Sheathipede.  Potentially more, I didn't do a thorough check of all ships.  These are just the ones I own that I didn't see listed.

### Language

English

**Comment by raithos** [comment]
Ships should now correspond correctly to the conversion kits
