### ISSUE TITLE
YT-2400 Pilots still not showing in Discord

### ISSUE THREAD

**Issue by BuddyHG** [raithos/xwing#1400]
Describe the bug
When posting YASB links in Discord, YT-2400 pilots still do not show

To Reproduce

Create a Rebel list that includes a CL YT-2400 pilot
Post the link in a Discord server that uses the R2D7 feature
Screenshots
![Screenshot 2024-06-28 114518](https://github.com/raithos/xwing/assets/166346263/32a91aa1-7d7b-4527-8b52-eb67db615d1b)

**Comment by raithos** [comment]
this is an r2d7 issue. the xws is now outputting the correct values.

**Comment by Apollonaut13** [comment]
Actually a Pattern-analyzer API issue. R2-D7 queries their API when handed a YASB URL.
Here's the API GET request URL: https://pattern-analyzer.app/api/yasb/xws?f=Rebel%20Alliance&d=v9ZsZ20Z648XWWWWWWY651XWWWWW&sn=Unnamed%20Squadron&obs=
