### ISSUE TITLE
B-Wing Title 

### ISSUE THREAD

**Issue by dschu2** [raithos/xwing#1404]
**Describe the bug**
I can't find a way to add the B-Wing Title to B-Wings with both Epic and non-epic cards. In epic mode, I see the upgrade in the list, but when I click on it, it does not get applied to the ship

**To Reproduce**
1. Go to Rebel Faction, 
2. Click on Add Ship, B-Wing
3. Scroll down to any pilot
4. No title card slot available

****** for Epic play, the command upgrade list contains the B-6 Prototype, but when I click on it, it closes the list without adding it to the ship

 
**Expected behavior**
I expect to see a title upgrade slot

**Screenshots**

**Desktop (please complete the following information):**
 - 14.5 (23F79)
 - Browser : Safari 
 - Version 17.5 (19618.2.12.11.6)

Thanks for all your work

**Comment by raithos** [comment]
This is working as intended. I believe hera is the only pilot that can take a title upgrade.

**Comment by dschu2** [comment]
Understood. Thank you for the clarification
