### ISSUE TITLE
Countdown has Mod Slot

### ISSUE THREAD

**Issue by Aeriic** [raithos/xwing#1408]
**Describe the bug**
Countdown in the TIE/sk still has a mod slot, but it was removed in the pdf.

**To Reproduce**
1. Go to Empire
2. Click on TIE/sk Striker
3. Scroll down to "Countdown"

**Expected behavior**
Countdown to not have a mod slot.

**Screenshots**
![image](https://github.com/user-attachments/assets/ee2203ee-4d13-492d-8764-b40714845420)
![image](https://github.com/user-attachments/assets/7959b3b3-9741-49cc-8a72-5a94589d5440)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by raithos** [comment]
thank you for providing screenshots, saves so much time
