### ISSUE TITLE
Translated display names are not used in card browser

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#141]
### Expected Behavior

When selecting a language other than English, english card names (eg. "Academy Pilot") are used.

### Actual Behavior

Selected language's names (eg. "Pilot der Akademie" in german) should be used.

### Language

At least german and french.

![capture d ecran 2018-10-04 a 14 02 26](https://user-images.githubusercontent.com/5627688/46473359-290b2c80-c7e0-11e8-8d4f-98c8188fb165.png)

**Comment by Patschke** [comment]
I'll fix that.
