### ISSUE TITLE
Errors on last AMG update

### ISSUE THREAD

**Issue by filipealvesdefreitas** [raithos/xwing#1417]
There are a couple of errors added on the last AMG points update, which also added Standard Loadout cards for the Tie Phantom and Alpha Class Star Wing.

1- Han Solo (YT-1400, Scum) was changed to **5 points / 10 loadout** on the PDF, but is still at old value on YASB. This is a change that was not highlighted on the PDF, which might explain why it went unnoticed.
2- Heavy Plasma Missiles (from Major Vynder's new Standard Loadout card, Alpha Class Star Wing, Empire) actually is a **Front Arc** attack (and not a Full Front Arc attack, as shows on YASB), and it has a **Lock requirement** in the text (no requirement is shown on YASB). It appears there's some mix up with Lt Karsabi's Saturation Rockets there.

**Comment by Patschke** [comment]
Thanks for the note, will be fixed with the next update
