### ISSUE TITLE
Boba Fett and Onyx Squadron Scout

### ISSUE THREAD

**Issue by Eggmanthrowaway** [raithos/xwing#1418]
**Describe the bug**
For XWA points, Boba Fetts loadout is 18 but should be 13 according to the XWA points doc. Also the tie/ag aggressor Onyx Squadron Scout, when you try to add a modification it says no matches found.

**To Reproduce**
Go to empire tab, add tie/ag aggressor, try to add a modification.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: android Samsung Galaxy s24
 - Browser: chrome
![Screenshot_20240908_222602_Chrome](https://github.com/user-attachments/assets/63dc38dc-3cd4-498f-b5fe-b6f3cc2da7ab)

**Comment by Patschke** [comment]
Thanks for the note, will be fixed with the next update
