### ISSUE TITLE
Shared Collections

### ISSUE THREAD

**Issue by JasonBriggs86** [raithos/xwing#1427]
Hi,

I wondered if YASB2.5 is still being actively updated with the discontinuation of the product line?

As I did have an idea, we have a small gaming group with a pool "collection", would it be possible to have a feature to share your collection with other users, either by being able to setup a group so users can pick units from the overall collection, or being able to download the collection and email it to other users so they could upload it to their account?

Having a shared collection would be the best overall as that means different players could not double book a unit!

**Comment by Patschke** [comment]
Yes, YASB is still actively maintained and we have no intention to stop doing so. Points will continue to be updated supporting the XWA community project. 

Regarding export/import of collections: This has been asked before (see #1374). A simple import/export is not enough: As soon as some new ship is added to your group pool, everybody still has to update the collection. Supporting synchronization of collections (or even multiple currently selected lists) is not an feature we intend to implement. Linking accounts sounds error prone and like a lot of work to maintain.

**Comment by raithos** [comment]
Yes, sorry about that but the work required to connect and sync accounts and collections would be a massive undertaking, not even considering the frontend rework. unfortunately YASB is built on a legacy database, so theres just stuff that isnt realistic to do without major disruptions
