### ISSUE TITLE
XWA ship add

### ISSUE THREAD

**Issue by dorpheos** [raithos/xwing#1428]
**Describe the bug**
With XWA format i cant add all the yt2400 with 4 attack dice. According to XWA points list and it is available as it is on launch bay next in XWA ruleset.

**To Reproduce**
1. Set XWA beta ruleset /rebel faction
2. Add yt2400 ship
3. View list, dash /leebo / generic pilot with 4 attackbdice doesnt appear...

Alt : also cant add by importing squad.

**Comment by Patschke** [comment]
I can't reproduce this issue.

**Comment by dorpheos** [comment]
When you set
1 Ruleset to XWA
2 Ship yt2400
3 How many pilots do you have in the list. According to xwa ship point there are 7 pilots (3 dash, 3 leebo, 1 generic)?
But for me only 4 pilots appears (2 dash, 2 leebo) with xwa ruleset

**Comment by dorpheos** [comment]
![SmartSelect_20240919_130610_Adobe Acrobat](https://github.com/user-attachments/assets/1cf6e37d-a7cb-4021-b449-c00d72c1babf)

XWA screenshot for référence

**Comment by Patschke** [comment]
![Screenshot_2024-09-19-13-06-06-835_org mozilla firefox](https://github.com/user-attachments/assets/351a70a0-110f-4b99-8f05-c66fbecf23bc)

I do see all 7.

**Comment by dorpheos** [comment]
Its very disapointing, i cant see where is the difference, i m also on smartphone...
![SmartSelect_20240919_131151_Chrome](https://github.com/user-attachments/assets/cbde1d00-dc18-40a6-a973-8f002081990c)

**Comment by dorpheos** [comment]
I've found the problem, in miscs settings "enable banlist (not standard)" was ticked...
I didnt mind to check this before since xwa doesnt have any banlist yet.

**Comment by Patschke** [comment]
Ah, well. The purpose of that never was to restrict XWA ships. It was used because people would want the standard ban list to be applied to extended. So there is actually a bug we need to fix, thanks for helping to spot this!

**Comment by raithos** [comment]
Not true, there are people who want to apply the banlist to xwa points as well or to epic. The solution here is just to uncheck the box, which is checked off by default.
