### ISSUE TITLE
XWA Feedback

### ISSUE THREAD

**Issue by TimTheITGuy** [raithos/xwing#1434]
**Is your feature request related to a problem? Please describe.**
I’d like an easy way to give XWA feedback from YASB. For instance, death fire has 2 torpedoe slots, but only 7 load out points - which is impossible.

**Describe the solution you'd like**
A link to the XWA points feedback would be ideal - especially if it included the build data.

**Describe alternatives you've considered**

**Additional context**

ps: would love to hear a new podcast episode and thank you for your involvement!

**Comment by raithos** [comment]
its unlikely that we will be doing this. while closely connected with XWA, yasb is its own entitiy. Additionally, right now xwa points are in beta mode, but once amg points are released that system may change, so it doesnt make sense to implement this at this time regardless.
