### ISSUE TITLE
Missing Pilot - Dash Rendar Hotshot Mercenary

### ISSUE THREAD

**Issue by Gabriel-Avelar** [raithos/xwing#1436]
I am trying to build a squad with Dash Rendar Hotshot Mercenary, but the option of the card does not appear. 
![Captura de tela 2024-11-11 111931](https://github.com/user-attachments/assets/f2029bf4-7268-471d-8d74-d273c31763d4)

**Comment by Patschke** [comment]
It seems like you've selected standard. Dash Hotshot Mercenary is not legal in standard. You'll need to select XWA or extended to have him show up. From what I can tell, everything works fine. 

![image](https://github.com/user-attachments/assets/cced69d2-9c3f-4ef8-81aa-5a80432e9e7d)

**Comment by Gabriel-Avelar** [comment]
Didn't know this. Thank you!
