### ISSUE TITLE
Auzituck Gunship has wrong number of shields

### ISSUE THREAD

**Issue by andrewdschmidt** [raithos/xwing#15]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

The Auzituck Gunship should only have 2 shields.

### Actual Behavior

Auzituck Gunship is listed as having 3 shields.

![image](https://user-images.githubusercontent.com/15370404/44162719-1c474380-a08f-11e8-8455-3583f7881afd.png)

**Comment by raithos** [comment]
TY fixed. why u gotta go mess up my wookies

**Comment by andrewdschmidt** [comment]
I'm not happy with it either lol. Was playing Lowhhrick.
