### ISSUE TITLE
Feature Request: Card Search

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#150]
I'd love to have a card search available for the card browser. As we have the required data available (and the data set is small enough to allow simple searching through all elements), it should not be too hard to get a search function up. 

Possible criterias could be: 
* ~~faction (advanced: factions)~~ ✓
* ~~type (pilot/upgrade, advanced: specific slot(s))~~ ✓
* ~~text (title/text/flavor)~~ ✓
* ~~for ships: available slots~~ ✓
* stats (~~ini, base size, hull, shield~~, attack, ~~agility, force,~~ ...)
* ~~point costs~~ ✓
* ~~uniqueness~~✓
* available maneuvers
* available actions
* range/attack value of secondary weapons
* ~~collection status~~✓
* ...

Don't think that I'll find the time to implement that myself soon, so I'd be happy if anybody else is interested in doing so. 

That would allow to answere questions like "what is the cheapest way to get a crew slot", "which turret carriers are available", "I got 40 points remaining, what pilot options do I have for <40 points".

**Comment by iwazaru** [comment]
I would love that ! I think a first, simpler version could just be a text input that would filter cards by title and text. 

Also, it would be great to search in currently selected language, but also English. A lot of X-Wing resources and discussions are English so I might be searching for an « Outmaneuver » card without knowing that the French name is « Manœuvre improbable ».

**Comment by Patschke** [comment]
I've done an example for the text search, so anybody interested can easily add all the other possible criterias. 

To add a criteria simply do the following steps (in browser.coffee): 
* Add some html for the actual input
* Store the input field itself (e.g. the checkbox, but not a lable in front) as some variable, and invoke the render method on input change
* Add logic to filter cards according to the input. card.data is available and contains all the needed information

All the above steps are marked as "TODO" in the browser.coffee code. 

Additionally, anyone who is better in making stuff looking nice than I am, may add some css to make stuff look nice ;-)

> Also, it would be great to search in currently selected language, but also English. A lot of X-Wing resources and discussions are English so I might be searching for an « Outmaneuver » card without knowing that the French name is « Manœuvre improbable ».

I've included that for the name (as this is easy to do, and I've previously done it for the search bars in the builder), but it is more tricky for the texts. English names are always available, but texts are only loaded for the currently selected language. Thus I am not aware of an easy way to access the english texts.

**Comment by raithos** [comment]
changes are live!

**Comment by Patschke** [comment]
That does not close this PR.

I'd like to have a powerfull search tool on hand when building squads, and did just start the very basics.

**Comment by Patschke** [comment]
I'll start implementing search criteria one by one. 

Faction is done, 10+ criteria to go. 

Currently faction is interpreted as exactly one faction only, or factionless otherwise. So e.g. 0-0-0 is considered factionless, as it is scum or squad containing vader. 

Feedback is welcome, the layout will probably become awful. If anybody wants to do some nice css, I'd appreciate that very much.

**Comment by raithos** [comment]
I'm too busy right now to dive right into formatting, but I'll do a visual pass on it eventually.

**Comment by raithos** [comment]
@Patschke i added some cleanup formatting so it would be a little cleaner. Just remember to add the extra tags for the options as you add more of them.

**Comment by Patschke** [comment]
Next option (filter by available slots) will be available with #178 

It is another type of input option (in fact it is no `<input>` at all, but a `<select>` instead), so the layout is (as always) some sort of whatever it looks like by default.

**Comment by raithos** [comment]
I will push all these changes on Monday. This weekend is just too packed to focus on it.

**Comment by Patschke** [comment]
Adding to my ToDo List: Filter for game mode (second edition, extended, hyperspace)

**Comment by raithos** [comment]
It's not a big percentage compared to the rest of the site, but we do get a few hundred visits to the browser a week.

**Comment by Patschke** [comment]
Only somewhat like 2 minutes of testing, seems to work and does not break anything. If one (probably you? :D) somewhen feel like implementing more, one may just look at that commit - it points you to the places where addidtions are needed.
