### ISSUE TITLE
Feature Request: QR-Code input

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#151]
If somebody has too much free time, it would be awesome to have QR-Code import from camera available for mobile devices. Export to xws already allows displaying a QR-Code, so one could add an import by QR-Code to the import part of it as well. It would be a nice to have to allow import from ffg-QR-Codes as well, but that would probably be a 2nd step. 

There exist quite a few QR-Code scanning packages for java script, so one could e.g. include https://github.com/nimiq/qr-scanner

Again, I'm unfortunately not having the time to have a closer look at this myself anytime soon.

**Comment by raithos** [comment]
I think this idea has merit, but really only makes sense if we make the whole app layout more approachable for people who use mobile. not many people on desktop use qr code scanners. I kind of want to do a mobile overhaul, but it might be really intense.

**Comment by Patschke** [comment]
If you want to do a mobile overhaul, I'd be joining you. Currently I got [this mobile version](https://build.phonegap.com/apps/3337047/download/android) up.

If we do the following things, I'd upload it to the play store, so we have some feedback on the number of users on mobile devices:
* update UI that is not beeing displayed properly on mobile version
* add a local save option

Acually that app already has some significant advantage over the official squad builder right now: It is usable without internet connection. The official app won't even start up if you are offline...

**Comment by LordVorKon** [comment]
I would just like to say that I, and many others in my local group, have had no difficulties at all using YASB in a mobile browser.  I suppose the capability to work offline could be nice, but probably not enough for me to install an app.

**Comment by raithos** [comment]
@Patschke is the apk being rebuilt into some app package or is it a shell of a browser with the site inside?

**Comment by Patschke** [comment]
The latter. It just uses the /app folder of YASB and puts it into an apk. Actually I think that is what one wants to do, as rebuilding YASB directly into an apk may cause issues when we decide to change stuff for the regular browser version. However the result is still a stand alone version, that is able to run offline - which I want it to do. 

I'm using Adobe PhoneGap, which is based on Cordova. There is actually a QR Code Plugin for Cordova, so it should be possible to get native QR Code support for an app relatively easy. 

If the app: 
* is less ugly in showing you the card information (mouse-over is probably not the best approach for an app?)
* allows you to save/load squads

It would be worth publishing it. 

If it would be able to scan QR Codes (maybe even the official ones? Did not check what kind of data format they use), it would be really awesome (as it would allow e.g. TOs to check if lists are valid with the most recent rules/point costs).

**Comment by raithos** [comment]
Cool, that's how I was hoping it would work myself. 

If we wanted to to work offline, it would be a significant departure from the standard build for two reasons:
- We would have to simulate or create a separate version of yasb.herokupp.com which houses all the account info/list data. 
- We would have to create an entirely separate UI for mobile (which we would probably use for the online version of the site anyways).

The other side is that as soon as we add a save feature, we would have to make it so you could sync it to your existing yasb account. I don't have an issue with that, but its additional work that needs to be done. and probably whenever we have an update we would want to push those updates to the app as well.

So I believe the official QR code is a permalink which would not help us at all,

**Comment by Patschke** [comment]
If we'd just don't have all the stuff from yasb.herokupp.com, so we'd omit the following features: 
* everything collection related
* saving/syncing your lists online

That would be fine for me, if there is a way to save&load lists offline. I'd not change the entire UI, but maybe try to get the mouse-over information merged into the drop-down menus - so we still have the basic layout of slots that trigger menus, an add ship button, and the faction selection on top. 

Of course, it would be a nice-to-have to sync data with your existing yasb account, but that would not be highest priority for me (=I'd be happy to release an app, that lacks that feature).

**Comment by Patschke** [comment]
I think LaunchBay Next is doing a good job in providing a nice App, and is also able to process QR Codes. Therefore I don't think that I'll spend the time to add it to YASB. As I don't feel like anybody else is going to do so either, I'll close that Feature Request.
