### ISSUE TITLE
YT-1300 Han Solo pilots reversed

### ISSUE THREAD

**Issue by kkentium** [raithos/xwing#153]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Scum YT-1300 Han Solo ability should read "While you defend or perform a primary attack, if the attack is obstructed by an obstacle, you may roll 1 additional die." Rebel YT-1300 Han Solo should read "After you roll dice, if you are at range 0-1 of an obstacle, you may reroll all of your dice. This does not count as rerolling for the purpose of other effects."

### Actual Behavior

The abilities are reversed. 

### Language

English

**Comment by raithos** [comment]
should be updated shortly
