### ISSUE TITLE
Add information about exporting xws to the readme

### ISSUE THREAD

**Issue by AlexRaubach** [raithos/xwing#154]
## YASB 2.0 Bug Report

You should probably add a  link to https://yasb2-xws.herokuapp.com and a brief description of how to export squads.

**Comment by raithos** [comment]
I'll think about it. I'm super wary of adding any additional links or fields in the main page, as I want the site to remain as minimalist as possible. And it seems like anyone who might need to use the exporter would already know what to do. its not a general public kind of thing. Maybe theres somewhere else on the site where that kind of link would make sense.

**Comment by AlexRaubach** [comment]
Sorry, I was unclear in where I was suggesting you add it. You should add it to this repo's readme and possibly the about page on YASB2 but just the repo would be great. I wanted to start using the xws export and couldn't find the url anywhere

**Comment by raithos** [comment]
sure. is there already a write-up you could link me or would you be able to just provide a short one here?

**Comment by Patschke** [comment]
If you update the readme, you may want to delete the Test section. The unit tests are outdated and do not work anymore. The better aproach would of course be, to update the unit tests ;-)
