### ISSUE TITLE
Feature Request: Ability to reduce number of ships/pilots/upgrades in collection

### ISSUE THREAD

**Issue by haukurv** [raithos/xwing#156]
## YASB 2.0 Feature Request

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Currently you can add to the number of components you have in your collection, which can be very handy if you acquire some extra bits. The reverse is however not possible, i.e. if you loose or trade away components from for example conversion kits, you currently have no way of adjusting those numbers in your collection. A workaround is to manually insert all the numbers, subtracting what you no longer have, but in cases where you have many components from one set (example: conversion kits) this is rather inconvenient :)

### Extra Comment

Damn fine work btw, works much better than the official app/webapp.

**Comment by Patschke** [comment]
Sounds like a reasonable feature request. 

However, we need to be careful with allowing arbitrary negative numbers, as removing more components than you have in the selected expansions, might result in always having "you cannot field that squad" errors. Checking against the currently available numbers when removing stuff one traded away is not sufficient to prevent that, as one might remove the expansion from the collection later on. 

If we don't want to handle that properly, we could still allow entering negative numbers and display a warning like "don't remove stuff you don't have, as that might be a stupid idea". 

I may look into doing so later, if anybody else wants to do so just leave a note here. I did not look into any code related to that Feature Request yet.

**Comment by raithos** [comment]
based on how we do the collection and checks, negative numbers would be the best the way to go. Delineating the upgrades from the collection will break a number of other things in the collection. I think we would just need to add a code check to cap out the value displayed or checked for at 0 (there aren't so many endpoints where this would be a huge issue I think).

**Comment by raithos** [comment]
if we do do negative numbers we'd probably have to show that in the css as well, like a red highlight instead of green when we have a negative value.

**Comment by Patschke** [comment]
Started working on that feature request. 

> 
> 
> if we do do negative numbers we'd probably have to show that in the css as well, like a red highlight instead of green when we have a negative value.

Did you know, that we explicitly set the background to red if one has more than 12 of a kind? I own quite a lot of TIEs and was quite surprised when that happened at some point ;-)

**Comment by raithos** [comment]
> Did you know, that we explicitly set the background to red if one has more than 12 of a kind? I own quite a lot of TIEs and was quite surprised when that happened at some point ;-)

I had no idea. that's actually pretty funny. I guess while were at it we could just remove the upper limit too. Or set the upper limit at some really high number

**Comment by Patschke** [comment]
Funny is almost what comes to my mind when reading any code in here. That YASB code is so awful. I think that every time I have a look at functions I've not inspected before. There is actually a for loop pushing every card into your collection one by one, and having "-2" as value will cause for(0...-2) to push two addidional copys on top. The count is later determined by checking the length. So having -2 whatever, will actually increase the number of copies showen...

I've of course removed that limit while I was on it

**Comment by raithos** [comment]
shhh we don't talk about that.  geordanr is love,  geordanr is life

**Comment by Patschke** [comment]
Well at least it was easy to adapt to the coding style of yasb. Simply do not comment any code you write, and use public variables and functions everywhere. Search for the data you want to access by any method you can imagine, and just leave unused code hanging around in not called methods. There are hundreds of lines of code for some random-squad-generator, that I cannot remember beeing a feature of YASB since I play X-Wing. Some of them are still beeing executed, doing nothing usefull for sure. But hey, people seem to consider this mess "much better than the official app/webapp" and believe there is any "damn fine work" included in here somewhere. Maybe that fine work is just well hidden? ^^

Anyway, implemented this in #159.

And hey, you know, I do like YASB, too.

**Comment by haukurv** [comment]
Thanks! That was quick.
Oh, comparison with the official app still stands.  At least you seem to have slightly shorter release cycles :-D
