### ISSUE TITLE
Black One title is available on all ships with a title slot

### ISSUE THREAD

**Issue by johndeboer** [raithos/xwing#16]
### Expected Behavior

Black One title is available only on T-70 X-Wing

### Actual Behavior

Black One title is available to all ships with title upgrade slot.
![image](https://user-images.githubusercontent.com/2186710/44182670-eaa59b00-a0d5-11e8-9617-4d8761a1796c.png)
![image](https://user-images.githubusercontent.com/2186710/44182686-f2653f80-a0d5-11e8-9616-2da4a63f62a1.png)

### Language

English

**Comment by raithos** [comment]
oops. Solved
