### ISSUE TITLE
Card browser search does not work in french

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#163]
### Expected Behavior

Searching for "Luke" should return two "Luke Skywalker" (pilot and gunner) cards. This is working in English and German.

### Actual Behavior

Searching for "Luke" returns nothing.

### Language

Only french seems to be affected. I guess I broke something when translating to french, but I can't figure what.

**Comment by Patschke** [comment]
The french translation is missing the following cards, which will cause issues: 

Finn
Paige Tico
Rey
Special Forces Gunner
R2-HA
Integrated S-Foils
C-3PO (Resistance)
Captain Phasma
Chewbacca (Resistance)
General Hux
Han Solo (Resistance)
Kylo Ren
Petty Officer Thanisson
Rose Tico
Supreme Leader Snoke
Ahhav
Backdraft
Blackout
Captain Seevor
Chewbacca (Resistance)
Finch Dallow
Han Solo (Resistance)
Kylo Ren
Lieutenant Bastian
Lieutenant Dormitz
Longshot
Lulo Lampar
Major Stridan
Midnight
Mining Guild Surveyor
Muse
Poe Dameron
Quickdraw
Rey
Tallissan Lintra
Hardpoint: Cannon
Hardpoint: Missile
Hardpoint: Torpedo
Fanatical
Heroic
Advanced Optics
Hyperspace Tracking Data
Primed Thrusters
Targeting Synchronizer
Black One
Rey's Millenium Falcon

This will cause any access of the text attribute of those cards to fail. I assumed that every card will always have a text attribute, and did not check for the existance before accessing it. All other languages use the english texts, as long as no official translation is provided. French will currently show empty cards in the squad builder. 

I'll still fix the errors beeing introduced by the assumption, that every card will always have a text.

**Comment by Patschke** [comment]
#164 will prevent unchecked .text access. This will allow everything to work properly again. 

However, I'd still suggest to add the english information while no french is available.

**Comment by raithos** [comment]
I agree here. Alternatively running your own translation is fine. #164 is now live, going to close this.
