### ISSUE TITLE
View Second-Edition only cards in Card Browser mode

### ISSUE THREAD

**Issue by andrewdschmidt** [raithos/xwing#168]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

In card browser mode, I'd like to be able to filter by Second-Edition only cards.

**Comment by Patschke** [comment]
Sure, thats easy to implement. I'm planning a few other features as well, you may find a list at #150
