### ISSUE TITLE
Feature Request: Sub-List

### ISSUE THREAD

**Issue by Rob-Fletcher** [raithos/xwing#173]
After loading a list, have another drop down somewhere that contains "sub-lists" or alternate versions of the list. Sometimes I cant decide between a few different configurations of the same set of ships. Would be nice to have a way to associate these alternate builds without having to save it as a completely separate list.

**Comment by Patschke** [comment]
I am not sure, how you picture that feature to be an actual improvement. Maybe you can explain that in more detail? 

I think it is hardly possible to generally tell whether a list is an alternate version of another list - e.g. one might consider swapping out a 34 points TIE-Interceptor for a 34 points TIE-Striker the same list, while swapping ships should not be considered a minor alternation in general. Thus, it is not possible to automatically detect whether a list is an alternate version of another, and we would require you to manually select the associated list. One would probably still want, to give that sub-list some kind of name, so there is no time saving advantage on that after selecting the main list, too. 

If all you want to have is list variants beeing grouped together, you may just use names like "Super cool List - Dorsal" and "Super cool List - Ion Turret"?

**Comment by raithos** [comment]
I'm going to close this for now. There is no real desire on my part to implement this feature as it would require a significant rework on how we save and add lists. That being said, if we do in the future do a major rework of the backend, I will revisit this.
