### ISSUE TITLE
Feature Request: expanded hull & shields.

### ISSUE THREAD

**Issue by Laurvin** [raithos/xwing#180]
Would it be possible to add a checkbox to expand the hull and shield icons to equal the number of hull and shields for the ship. This was an option on the old Squadron Builder; example [here](http://xwing-builder.co.uk/view/789283/mission-28#view=full&health=all).

The advantage is that you can just cross off shield and hull damage (yes, there are builds that can repair damage but unfortunately my friends only want to play with 'simple' builds).

I do realise that this will often mean the text will be on two lines now.

BTW; I love that the maneuver dial is now on the sheet but I think it could be a little smaller (see the example above again). Should I open a separate issue for this?

Thanks!

**Comment by Patschke** [comment]
Whatever. Just implemented it in #178. Leave me some feedback if that is what you wanted. (Not online yet)

**Comment by Laurvin** [comment]
Thanks for implementing this!

I've found one bug: ships with 0 shields get 2 shields when expanding.

Unfortunately I haven't had much time to look into the dial and the lighter bar. I'll try and get a local copy to work so I can test stuff more easily.

**Comment by Patschke** [comment]
Whoops, I tend to always forget, that for loops in coffeescript will indeed count backwards. So counting from 1 to 0 added 2 shields... Will be fixed.
