### ISSUE TITLE
Mismatched movement

### ISSUE THREAD

**Issue by K25velo** [raithos/xwing#182]
Please take a look at the movement charts for the E-Wing. There's a discrepancy between the dials of Corran Horn and Darklighter. Corran has a white 2 turn while Darklighter shows it being blue.
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Did you equip an R4 mech to Darklighter? 

I can not reproduce that bug. It sounds quite strange, as we are actually storing maneuvers per ship and not per pilot. 

Can you give us some screenshot and a link to the affected list?

**Comment by K25velo** [comment]
That's exactly what happened. I didn't catch the fact one had R4 and the other didn't. Found that out when I looked at the actual dial. I apologise for jumping the gun and bugging you, no pun intended.

Sincerely,

Jim

Patrick Mischke <notifications@github.com> wrote:


Did you equip an R4 mech to Darklighter?

I can not reproduce that bug. It sounds quite strange, as we are actually storing maneuvers per ship and not per pilot.

Can you give us some screenshot and a link to the affected list?
