### ISSUE TITLE
Outrider Title errata

### ISSUE THREAD

**Issue by jedskywalker** [raithos/xwing#194]
## YASB 2.0 Bug Report

Outrider Title has errata:

Changed "obstructed attack" to "an attack that is obstructed by an obstacle."

It should read: 
While you perform an attack that is obstructed by an obstacle, the defender rolls 1 fewer defense die.

After you fully execute a maneuver, if you moved through or overlapped an obstacle, you may remove 1 of your red or orange tokens.

Rules Reference 1.0.0 (released August 2, 2018)

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Thanks, added that to #192
