### ISSUE TITLE
Fetching Squads does not work at all

### ISSUE THREAD

**Issue by bugsb77** [raithos/xwing#195]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Fetching Squads should present all my squads of the selected faction.

### Actual Behavior

Nothing happens. Turning Wheel shows up:

![grafik](https://user-images.githubusercontent.com/44870637/48203707-7db64000-e368-11e8-96d2-40c40b927f80.png)

### Language

German.

**Comment by knight-captain** [comment]
Ditto, but in English. 

EXPECTED: "Load Squad" should pull a list my squads for the current faction. For Scum or Resistance, these lists should be empty.

ACTUAL: See above. I get the eternal turning wheel, and no list. This happens for all factions, even those with no squads to list.

**Comment by Patschke** [comment]
I am unable to reproduce that bug using my google login. Could you provide some more information, so I can try to find the issue: 

Which auth provider do you use (google/facebook/twitter)?
Which browser are you using?
Are there any errors showing up in the console (using Firefox you can check the console using Strg+Shift+k)?

Thanks for reporting that issue, beeing unable to load/save squads is of course something we should fix as fast as possible.

**Comment by raithos** [comment]
I also cannot reproduce. Have you tried saving a new list and then trying to load it?

**Comment by knight-captain** [comment]
AUTH PROV: fb
BROWSER: Chrome

When I F12'ed I told it to pause on caught exceptions and got: 

"DOMException: failed to execute 'matches' on 'Element': ':visible' is not a valid selector."

Name: Syntaxerror
Code: 12

I'm certainly an amateur, but it looks like a misplaced colon?

**Comment by bugsb77** [comment]
Console output:
Logging system initialised at Fri Nov 09 2018 10:24:48 GMT+0100 (Mitteleuropäische Normalzeit) common.js:206:17
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. jquery.min.js:3:3704
Leerer String an getElementById() übergeben. jquery.min.js:2:24214
Leerer String an getElementById() übergeben. jquery.min.js:2:24214 

---
maybe one or more corrupt squads?

**Comment by Stinger07** [comment]
Observed Behavior: When fetching squads, 1.0 squads are appearing next to 2.0 squads:

![image](https://user-images.githubusercontent.com/13785712/48564475-7fca5280-e8c4-11e8-9d93-30c0872de5ed.png)

**Comment by raithos** [comment]
@Stinger07 this is a known issue, at this time we have no plans to do anything about it since we share accounts with YASB 1.0 for various reasons

**Comment by raithos** [comment]
this may be a lot to ask but @bugsb77 and @knight-captain when you log into YASB, can you in a seperate tab go to the following link https://yasb-backend.herokuapp.com/squads/list and save the contents into a document and attach it here so we can review the contents of your saved lists?

**Comment by bugsb77** [comment]
No problem. I am helping as good as i can, because i don't like the idea of using the official sb ;-)

When i follow the link (using ff) i only get:
Internal Server Error

**Comment by raithos** [comment]
really? you cant access it at all? uhhhhhhhhhhh... are you behind a firewall that blocks that page? that would be why you cant access your squads.

**Comment by bugsb77** [comment]
No, not that i know... 14 days ago everything was working fine and i didn't change anything in my network. My friend has no problem to access his squads in my network with his tablet pc.
I have the same problem to fetch the squads from my cell phone and at work...
Maybe it would help to delete the last 4 or 5 created squads from my profile? Or maybe all of them? The last squad i created before the problems began was a resistance squad. Can you do that? My gmail address: bjoern.buschmeier@gmail.com, my password: just kidding... ;-)

**Comment by raithos** [comment]
Ok guys, I found the issue, but it will take a few days to get the fix in. Hold tight for now!

**Comment by knight-captain** [comment]
So, 
I haven't had any problems logging in with Google instead of Facebook, and haven't been having problems. I haven't remade any of my First Order squads out of superstition that that's why it broke.

**Comment by raithos** [comment]
It should be resolved now. you shoudl also be able to save lists from the new factions
