### ISSUE TITLE
Chopper droid

### ISSUE THREAD

**Issue by DavinFelth23** [raithos/xwing#196]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Regen doesn't mention non-recurring charges only.

### Actual Behavior

Regen says just spend a charge.

### Language

The affected language(s).

**Comment by raithos** [comment]
will be fixed in next push
