### ISSUE TITLE
Display cards I don't own in red in cards browser

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#197]
I would love an option to filter cards in the browser based on whether I own them or not, using the "My Collection" feature. Two ways this could work:
- A "Show only cards in My collection" checkbox
- Or (maybe better) display the cards I don't own in red, as they are in the squad builder

**Comment by Patschke** [comment]
I've already implemented that. There are two number inputs for "Owned copies". 
I may look into coloring not owned cards red in addidtion.

**Comment by iwazaru** [comment]
I'm not sure what you mean by "two number inputs". I can't see anything different between cards I own and others in the browser, but maybe this is a bug.

**Comment by Patschke** [comment]
The third line of the advanced search options is "owned copies", which should check for the number of cards in your collection
![search](https://user-images.githubusercontent.com/17853362/48258701-11921580-e416-11e8-8099-250c765c4438.png)

**Comment by iwazaru** [comment]
Never mind, I found the number input in advanced search you were talking about. Great work.

I've changed the issue to "Display cards I don't own in red in cards browser". If I'm looking for an astromech, I think would be be useful to be able to clearly see cards I own without hiding the cards I don't have.

I had a doubt whether you could change the colors of options in a multiple select input, but I just tried it with the inspector and it works, at least in Chrome.

**Comment by Patschke** [comment]
It's no problem to do so. 

However, the collection seems to be loaded after the card list is created the first time, so to cards will only be colored after you do something in the card browser (enter search term, hit advanced search...)
