### ISSUE TITLE
Feature request: TTS Export

### ISSUE THREAD

**Issue by rat167** [raithos/xwing#199]
Hi,

Is it possible to implement a feature to export the list to this text format:

Pilot 1 + Upgrade 1 + Upgrade 2 / Pilot 2 / Pilot 3 + Upgrade 1
Example: "Whisper" + Juke + Collision Detector + Darth Vader + Stealth Device / Soontir Fel + Predator + Stealth Device / "Vizier" + Director Krennic /

All it needs it exactly those -> " " <- captions, not the fancy MS Word ones.
All double Pilots and stuff is handled by the in-game spawner.

**Comment by Patschke** [comment]
So, is your goal to make YASB a more barrier free website by improving text to speech support, or are you about to develope another application that would use this as import format? If it is the second, I would recommend to use the xws format instead, as this allows you to work together with more apps.

I don't understand what you want to express with

>All double Pilots and stuff is handled by the in-game spawner.

**Comment by rat167** [comment]
There's already official FFG app import, I don't work on TTS mod so I can't
implement anything :( nor do I have the skills for it. But I managed to
convince Launch Bay Next creator to implement TTS export feature, and now
everybody on TSS discord is using Launch Bay, so I thought that if YASB had
TTS export it would be even more awesome :)

wt., 20 lis 2018 o 12:27 Patrick Mischke <notifications@github.com>
napisał(a):

**Comment by Patschke** [comment]
I think Launch Bay Next has XWS export, so you ask every squad builder to implement a special export, instead of asking the TTS devs to allow XWS import? That sounds like more work to do in total. 

However, it should not be a hard task to get the desired export for YASB. Could you give some more formal spec of the output format? Does the format allow for special characters of other languages? Is there a trailing / like in the example required? How are pilots that exist for multiple ships supposed to be handled (e.g. Ezra Bridger + Hull Uprade is ambigious, as Ezra is flying more than one ship)?

**Comment by rat167** [comment]
Text format is exactly what is written on the card i.e. "Redline"
or Captain Jonus.

Captain Jonus + Barrage Rockets / Scimitar Squadron Pilot + Barrage Rockets
/ "Redline" + Proton Torpedoes + Advanced Sensors / Soontir Fel + Predator
/
Like i wrote in github:
Pilot 1 + Upgrade 1 + Upgrade 2 / Pilot 2 / Pilot 3 + Upgrade 1/

/ indicates that there are no more cards to add for that pilot.
Pilots of multiple ships are spawned with a menu to choose which ship you
want, and should Darth Vader appear not as a First entry (Pilot X) it will
be treated as an upgrade

On your part it's only important to retain "" <- these captions when
captions are used. The rest is up to spawner to handle.



wt., 20 lis 2018 o 12:43 Patrick Mischke <notifications@github.com>
napisał(a):

**Comment by rat167** [comment]
Only English language is supported by TTS mod.

wt., 20 lis 2018 o 12:49 Szymon Koczowski <szymon.koczowski@gmail.com>
napisał(a):

**Comment by Patschke** [comment]
Exactly written like on the card would be “Zeb” Orrelios not "Zeb" Orrelios. I can change the captions, are there any other characters where TTS is using somewhat simpler versions than the ones written on the card?

I've implemented TTS export in #201, will be live as soon as that PR goes live. Leave me some feedback to let me know if it works (or a proper spec. That is different from a few examples...), as I do not use TTS.

**Comment by Patschke** [comment]
![grafik](https://user-images.githubusercontent.com/17853362/48777547-1d61bf80-ecd3-11e8-8cc6-318fd1e6f254.png)

**Comment by rat167** [comment]
Perfect :)

>
