### ISSUE TITLE
YASB 2.0 wont Load Squads

### ISSUE THREAD

**Issue by Mega-Silver** [raithos/xwing#202]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

After logging in using Google Plus, when I go to load squads it should load my saved lists.

### Actual Behavior

After logging in using Google Plus, when I go to load squads all is see is the fetching squads load screen. Refreshing the page and logging out and in again does not work. So i do not have access to my saved squads.

### Language

English.

**Comment by raithos** [comment]
Hi, I think I've found the issue but it will take a day or two to get it resolved. Sorry for the inconvenience

**Comment by Mega-Silver** [comment]
Thanks!

**Comment by raithos** [comment]
Issue should be resolved now
