### ISSUE TITLE
Card collection doesn't work

### ISSUE THREAD

**Issue by johnlop** [raithos/xwing#207]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Have ships and cards I don't have show as red and display the number of cards I have.

### Actual Behavior

Collection management seems broken since this afternoon:
- Everything shows as black even if I don't have the card
- The number of cards in my possession doesn't show
- The button to edit my collection has disappeared 

There are some console errors, maybe something broken with new wave 2 cards:
![image](https://user-images.githubusercontent.com/18294057/49255680-bfcc2200-f3fa-11e8-973c-4d86155d0940.png)

### Language

N/A

**Comment by Patschke** [comment]
Thanks for the note, I am able to reproduce this error and am working on a fix.

**Comment by Patschke** [comment]
We forgot to add the actual ship to the database, but added it to the expansion. This would of course cause errors. Will be fixed when #209 goes live

**Comment by Patschke** [comment]
Well, actually noticed a while later that we by mistake named it B/SF-17 Bomber for the conversion kit, but should've named it MG-100 StarFortress...

Nevertheless, will be fixed ;-)
