### ISSUE TITLE
Andrasta missing full text reload is a gained action when you buy it

### ISSUE THREAD

**Issue by mirranspy2011** [raithos/xwing#21]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by raithos** [comment]
fixed
