### ISSUE TITLE
Can't equip duplicate tech.

### ISSUE THREAD

**Issue by FendleyFire** [raithos/xwing#212]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Equip 2 Hyperspace Tracking Data on Upsilon-class shuttle.

### Actual Behavior

Can only equip 1.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Good to know that feature still works. 

In 2nd edition the "limited" keyword was removed, as all cards are limited. You may not equip the same two crew, bombs, missiles, torpedos - or tech upgrades - on one ship.

The behaviour you reported is indeed correct.
