### ISSUE TITLE
FO icon hard to read

### ISSUE THREAD

**Issue by slimfitcasual** [raithos/xwing#214]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior
FO hex icon is hard to read on web and mobile, suggest using the FO TIE pilot variation:

![fo-shoulder-logo](https://user-images.githubusercontent.com/30913812/49303637-13804f00-f47f-11e8-9200-f62320fe1c26.png)

Mock ups:
![yasb-fo](https://user-images.githubusercontent.com/30913812/49303883-bdf87200-f47f-11e8-9e83-6dd81769535f.PNG)
![yasb-fo-selected](https://user-images.githubusercontent.com/30913812/49303886-c0f36280-f47f-11e8-9208-3a77a15c07cb.PNG)

I can provide working assist if necessary.
Thanks!

**Comment by raithos** [comment]
The best way would be to submit this as a new icon in https://github.com/geordanr/xwing-miniatures-font I am pulling geordanr's fonts for the icons.

**Comment by slimfitcasual** [comment]
Awesome, will do!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by raithos** [comment]
I'm going to close this for now, I'm going to also be going onto the font github to see if we can get some updates going myself, I'll be sure to watch for this push as well.
