### ISSUE TITLE
Special Forces Gunner Text

### ISSUE THREAD

**Issue by ImagineeringMan** [raithos/xwing#215]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Special Forces Gunner should say "While you perform a primary attack......" for both effects.

### Actual Behavior

Special Forces Gunner currently says "After you perform a primary attack......" for both effects.
### Language

The affected language(s).

**Comment by raithos** [comment]
should be fixed now
