### ISSUE TITLE
Bug on RZ-2 A wing chassis text - it says you can boost or barrel but it should be boost or rotate arc

### ISSUE THREAD

**Issue by mattcogg** [raithos/xwing#217]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
It is already boost or rotate arc for all pilots that I checked (english). Could you name a pilot where it is wrong?

**Comment by mattcogg** [comment]
The ps5 one can't remember which one sorry not at home to check

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LordVorKon** [comment]
All RZ-2 Awings show correct text for me.

**Comment by raithos** [comment]
marking this as closed as the bug does not appear to be present.
