### ISSUE TITLE
Hi Steven 

### ISSUE THREAD

**Issue by vonmonkhouse** [raithos/xwing#22]
Why is whisper 3atk (4)?

**Comment by johndeboer** [comment]
Phantoms in 2E are 3 attack

**Comment by vonmonkhouse** [comment]
Then why is there a (4) next to it?

D.

**Comment by johndeboer** [comment]
Can you provide a screenshot or details on how you got that to come up?  I'm seeing Whisper as 3 attack in Chrome, Firefox, and Edge.
![image](https://user-images.githubusercontent.com/2186710/44299782-5b150d80-a2ca-11e8-9073-b393d3bb89da.png)

**Comment by vonmonkhouse** [comment]
replicated on my desktop chrome


*Devon Monkhouse*| Sales Representative


*Landlord Property & Rental Management Inc.*515 Logan Ave, Toronto, ON M4K
3B3

T 416.961.8880 <(416)%20961-8880>  F 416.462.1461 <(416)%20462-1461> C
647.393.3655 <(647)-393-3655>
-------------------------------------------------------------------------

www.landlord.net | www.landlordrealty.net



This message is being sent to you by Landlord Property & Rental Management
Inc. or Landlord Realty Inc. If you would like to provide your express
consent to receive commercial electronic messages from us, or you no longer
wish to receive commercial electronic messages from us, then you can manage
your preferences by clicking here.
<http://landlord.nationbuilder.com/sign_up> Please note that we will still
have the right to send you commercial electronic messages that are in
compliance with Canadian Anti-spam laws.

**Comment by johndeboer** [comment]
There appears to be an issue with the Grand Inquisitor crew - I've been able to replicate this issue on all Phantom, Lambda, and Reaper pilots when GI crew is included.  Is that consistent with what you were seeing?

![image](https://user-images.githubusercontent.com/2186710/44338675-a6572980-a44c-11e8-9d26-fb78cbce33e1.png)

**Comment by raithos** [comment]
found the problem
