### ISSUE TITLE
Loading saved list with 0-0-0

### ISSUE THREAD

**Issue by DavinFelth23** [raithos/xwing#224]
## YASB 2.0 Bug Report
When loading a saved list that has 0-0-0, if the ship with 0-0-0 is "above" the ship with vader, then 0-0-0 is removed from the build.  however if the saved list has 0-0-0 below the ship with vader, then 0-0-0 stays.

### Expected Behavior
Since vader is in the saved list, I would expect 0-0-0 to stay on the ship/list regardless of if the ship containing vader is above or below 0-0-0.

### Actual Behavior

See above.

### Language

EN

**Comment by raithos** [comment]
Unfortunately this is a known issue and a problem with card dependent upgrades since 1.0. Recommend you save ships in sequence of their requirements.

**Comment by Patschke** [comment]
I am not sure why this was closed, as it clearly is an Issue and has not yet been fixed. Beeing an old issue does not change anything on that, right? 

However, I felt like I still want to fix that issue, and have done so in #229
