### ISSUE TITLE
XWS naming conflict Resistance YT-1300

### ISSUE THREAD

**Issue by nexusno2000** [raithos/xwing#225]
## YASB 2.0 Bug Report

Trying to make lists with Han (Resistance) or Chewie (resistance) fails.

https://github.com/guidokessels/xwing-data2/blob/master/data/pilots/resistance/scavenged-yt-1300.json

Has Han as "xws": "hansolo-scavengedyt1300",

and Chewie as "xws": "chewbacca-scavengedyt1300",

The last 2 pilots are not in conflict.

Who is right?

### Expected Behavior

List should spawn.

### Actual Behavior

Vassal throws an XWS spawn exception.

### Language

Not language dependent.

**Comment by raithos** [comment]
I'm right but I'll conform to guidokessels.
