### ISSUE TITLE
Add Hyperspace filter? 

### ISSUE THREAD

**Issue by rashktah** [raithos/xwing#227]
Hi! Would it be possible to add a function to show only the cards allowed for the Hyperspace format? 

Thanks for all of your hard work! 

## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
As there already is such a function, we'll probably just keep it ;-) 

There is a drop down menu allowing you to change between extended, second edition and hyperspace mode. If you need more help to find it, just leave a note
