### ISSUE TITLE
Saving and loading lists take forever

### ISSUE THREAD

**Issue by mirranspy2011** [raithos/xwing#23]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by johndeboer** [comment]
Any details would be helpful - what browser are you using?  Does the save/load ever complete?  Is this affecting all lists or only lists containing certain ships/pilots/upgrades?  Thanks!

**Comment by mirranspy2011** [comment]
google chrome and every ship list i try gets a loading screen but it will stay there for hours

**Comment by raithos** [comment]
Unfortunately I need more information. Does it only happen on chrome or other browsers as well? Is it once in a while or all the time? Please provide more info

**Comment by raithos** [comment]
Hi I'm going to close this since I haven't heard a response. if you still have the issue submit a new ticket
