### ISSUE TITLE
Scavenged YT-1300 missing missile slot.

### ISSUE THREAD

**Issue by peterkejser** [raithos/xwing#240]
### Expected Behavior

All versions of the Scavenged YT-1300  on the Resistance should have a missile slot. This was updated the 13th of December 2018.

![image](https://user-images.githubusercontent.com/14195245/50089375-f7fa9f80-0205-11e9-92ac-9435cba26a5f.png)

### Actual Behavior

The Scavenged YT-1300 does not have a missile slot.

![image](https://user-images.githubusercontent.com/14195245/50089478-3b550e00-0206-11e9-9a0d-79566cb3af1f.png)

### Language

English.

**Comment by Patschke** [comment]
Thanks, will be fixed with #241
