### ISSUE TITLE
Default Language appears to now be maygar

### ISSUE THREAD

**Issue by DavinFelth23** [raithos/xwing#245]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** If you have a resistance list with the falcon before the missile slot was added, and cant see it when you load it, please re-add your crew slots. This is a known issue when loading old lists into a  ship configuration that has changed, they will load upgrades into slots that dont belong there.

### Expected Behavior

English as default language

### Actual Behavior

Maygar is default language.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Sorry, this is a mistake introduced by updating the polish translation. Wil be fixed with #246
