### ISSUE TITLE
Black Squadron Ace (T-70) not added to collection with the Resistance Conversion Kit

### ISSUE THREAD

**Issue by haukurv** [raithos/xwing#253]
## YASB 2.0 Bug Report

The title pretty much says all thats needed :-)
I have the Resistance Conversion Kit added to collection, but the Black Sq. Ace shows up as not in collection in the dropdown.

### Expected Behavior

Adding Resistance Conversion kit to collection should add one Black Sq. Ace (T-70)

### Actual Behavior

Adding Resistance Conversion kit to collection does not add one Black Sq. Ace (T-70)

### Language

The affected language(s).

**Comment by zacharyp** [comment]
Oops, yes it is in there in the separate plastic bag.  Fix incoming https://github.com/raithos/xwing/pull/256
