### ISSUE TITLE
Modal Body Size too big

### ISSUE THREAD

**Issue by wdrescher** [raithos/xwing#257]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** If you have a resistance list with the falcon before the missile slot was added, and cant see it when you load it, please re-add your crew slots. This is a known issue when loading old lists into a  ship configuration that has changed, they will load upgrades into slots that dont belong there.

### Expected Behavior

Open print modal fancy option and print

### Actual Behavior

Modal body is too large and does not allow users to click the print button 

### Language

English

**Comment by raithos** [comment]
The model is supposed to resize width with the window size, and the print button hides under certain window width (for mobile users). Are you viewing this page on mobile? 

If you're talking about the height, then yeah that is fixed, but your screen would have to be really small in order to not see that.

**Comment by raithos** [comment]
From my testing it seems pretty satisfactory. I am going to close this for now, @wdrescher if you feel its still not working send a reply and I will reopen the issue

**Comment by wdrescher** [comment]
Great! This issue was noticed on a mac using chrome, it is working great now, thank you
