### ISSUE TITLE
Hate

### ISSUE THREAD

**Issue by vonmonkhouse** [raithos/xwing#259]
### Expected Behavior

Hate should only be available to fo and empire force users 

### Actual Behavior

It's available to all force users.

### Language

Hi Stephen.

**Comment by Patschke** [comment]
I am not sure if FFG will ever publish official rules about that, or if they believe it's clear who belongs to "Dark Side"... Obviously all those terrorists from scum and rebel are pretty dark, right?

**Comment by raithos** [comment]
since I haven't seen them change how hate works and still no update on which factions can take it, I'll match the app for now as much as i dont like this.
