### ISSUE TITLE
Agility Values for UT-60D U-Wing appear incorrect for Saw's Renegades

### ISSUE THREAD

**Issue by rjbrill** [raithos/xwing#26]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

The four "Saw's Renegades" U-Wing pilot cards should have an Agility Value of 1. However, note the four "standard" U-wing pilots have the correct Agility Value of 2.

Saw's Renegade UT-60D U-Wings (Agility Value is 1)
1) Saw Gerrera (FFG card image attached below)   
2) Magva Yarro (FFG card image attached below)
3) Benthic Two-Tubes (FFG card image attached below)
4) Partisan Renegade
![swz02_a1_saw-gerrera](https://user-images.githubusercontent.com/42294835/44304941-5ed37f00-a320-11e8-9251-8bda1fbfb4c0.png)
![swz02_a1_magva](https://user-images.githubusercontent.com/42294835/44304944-68f57d80-a320-11e8-97b0-ecc0269c55a4.png)
![swz02_a1_benthic-tt](https://user-images.githubusercontent.com/42294835/44304947-7f033e00-a320-11e8-9783-b230cf6c774e.png)

"Standard" UT-60D U-Wings (Agility Value is 2)
1) Bodhi Rook
2) Cassian Andor
3) Heff Tobber
4) Blue Squadron Scout

### Actual Behavior

All the UT-60D U-Wing pilot cards have the same Agility Value of 2.

### Language

English

**Comment by rjbrill** [comment]
Sorry. Ignore above posting just looked at an unboxing video and the Saw's Renegades U-Wing pilot cards have been updated to the "standard" Agility Value of 2. The above images do not match the published cards.

**Comment by raithos** [comment]
Thanks for keeping an eye out!
