### ISSUE TITLE
"Your Collection" is not very usable when there are multiple types of that item

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#260]
There are 3 Ezra Bridger pilots, but it's not clear in the "Collection" list which one they are.

Ditto Zeb, Sabine, Lando, etc....

**Comment by Patschke** [comment]
That is actually an issue with the english language file. Going to fix that. 

As a workaround you may just change the language to anything but english, and set the collection as required. The cards should be easily distinguishable in any other language. 
![grafik](https://user-images.githubusercontent.com/17853362/51084231-92c39c80-1726-11e9-8afc-45979d48cace.png)

**Comment by raithos** [comment]
this should be improved in the same way that the other languages are working with the latest push.
