### ISSUE TITLE
FO/Resistance Conversion Kit contains more stuff

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#268]
As for the first three conversion kits, there is stuff in an extra bag that is not listed in the content list...

**Comment by haukurv** [comment]
I was just about to file a duplicate issue of this when I noticed this as potential duplicate.

The pilots missing are:

TIE/fo Fighter Edit
•Commander Malarus
•TN-3465
•Lieutenant Rivas

Upsilon-class Command Shuttle
•Captain Cardinal
•Petty Officer Thanisson

These all appear red with pilot count 0 when you are selecting pilots for the ships in question.

**Comment by Patschke** [comment]
Yep, those are the cards not listed in the content that comes in the extra bag. I'll add them. Thanks for the list.

**Comment by Patschke** [comment]
I am not sure if all numbers are correct yet, e.g. the number of black squad pilots (T-70) in the resistance kit, but at least I've added the missing ones in #272

**Comment by haukurv** [comment]
There is just one Black Sq. Ace in the resistance kit and that looks spot on now.
The TIE/fo ones (listed above) still don't show up for me but the Upsilon ones look correct.

**Comment by Patschke** [comment]
#272 is not live yet...

**Comment by haukurv** [comment]
Ah rgr, sorry for the immpatience :-)
