### ISSUE TITLE
Collection Issues

### ISSUE THREAD

**Issue by Damo1701** [raithos/xwing#27]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

When selecting ships to pre-build lists, I would expect just ships I have previously indicated having possession of to appear in black as opposed to red.

### Actual Behavior

When selecting a Galactic Empire Conversion Kit, YASB adds possession of all ship models, at least twice, rather than just accounting for the fact that the conversion kits only apply to cardstock.

### Language

English

**Comment by raithos** [comment]
This is working as intended. Basically this builder does not account for whatever you had in your collection for 1.0. Adding the conversion kit gives you all of the legally playable ships you would have in your possession for 2.0 only. At this time I have no intention of merging 1.0 collections.
