### ISSUE TITLE
missing title and cost summary in fancy print

### ISSUE THREAD

**Issue by mkrannich** [raithos/xwing#271]
### Expected Behavior

I want to print this list:
https://raithos.github.io/?f=Resistance&d=v5!h!250:114,-1,-1,-1,-1,69,71,-1:;244:-1,-1,173,188,174,-1,107,193:&sn=Finnrey-Finch%233&obs=

### Actual Behavior

When I print (fancy) the list above I miss the title and the cost summary at the YT-1300

### Language

German fails. English works

**Comment by Patschke** [comment]
Vielen Dank für den Hinweis, wird mit dem nächsten Update (#272) behoben werden. Es gab einen Fehler in der deutschen Version von Engine Upgrade, der dafür gesorgt hat, dass alles folgende ausgeblendet wird (der Titel fehlte auch).
