### ISSUE TITLE
Points Update Information on Printout

### ISSUE THREAD

**Issue by judgeender** [raithos/xwing#280]
Since points will change periodically, is it possible to have printouts identify the date through which points updates were included for the list.  That way it will be easier to see if a list predates a points change.

**Comment by Patschke** [comment]
Sounds like a usefull thing to do

**Comment by raithos** [comment]
I'm going to include something for this now

**Comment by judgeender** [comment]
Thanks.  Will just make it easier to quickly see if a list might be out of date points-wise.

**Comment by raithos** [comment]
for now printouts will have a note saying that its from this version of the build. If a printout doesnt have that note it wont have the correct points. Will work on a more permanant solution once everything is good

**Comment by raithos** [comment]
its live now

**Comment by judgeender** [comment]
Looks good.  In the future, you may want to also add the Points version number along with the date, but for now, this will help.
Thank you.

**Comment by raithos** [comment]
Im going to leave this as resolved actually for now. i dont think im going to do anything to it for a while at least until the next points update
