### ISSUE TITLE
I am current working on the points update

### ISSUE THREAD

**Issue by raithos** [raithos/xwing#281]
So thats a thing

**Comment by Patschke** [comment]
I just came home, if you want some help just let me know. A comprehension of the changes may e.g. be found here https://docs.google.com/spreadsheets/d/1ZFG9hsvY1CyT2KmEcTrShXcZ3723U7S1hdvAHAg7li4/edit#gid=1698086566

I thought about introducing a point_cost_func similar to restriction_func, which may be added to an upgrade instead of all the different variants of variable point costs (size, agility, initiative). That would allow the processing of all those variable costs in the same manner.

**Comment by raithos** [comment]
@Patschke im basically done except for trying to solve initiative. Right now im stuck on trying to get the pilot data when the getPoints function is called

**Comment by raithos** [comment]
also, they changed it so that individual upgrades scale differently within a type of variable point cost, so it just makes more sense to have an array of points per upgrade with the type of variablity listed as well.

**Comment by Patschke** [comment]
I believe you should be able to access ship.pilot.skill just fine in the getPoints method of the GenericAddons class

**Comment by raithos** [comment]
yeah i tried that but it comes up as undefined

**Comment by raithos** [comment]
its fine in the console log though.

**Comment by Patschke** [comment]
Weired. If I add an `return ship.pilot.skill` as first line in that method as a test case, it will display every upgrade nicely with the currents pilot initiative as point cost. Works without any problems...

**Comment by raithos** [comment]
`    getPoints: (data = @data, ship = @ship) ->
        # Moar special case jankiness
        if data?.variableagility?
            data?.pointsarray[ship.data.agility]
        else if data?.variablebase?
            if not (ship.data.medium? or ship.data.large?)
                data?.pointsarray[0]
            else if ship?.data.medium?
                data?.pointsarray[1]
            else if ship?.data.large?
                data?.pointsarray[2]
        else if data?.variableinit?
            data?.pointsarray[ship.pilot.skill]
        else
            data?.points ? 0`

**Comment by raithos** [comment]
oh wow, it started working on its own. solid

**Comment by Patschke** [comment]
well, then I don't need to insert all the line breaks in the above code ^^

**Comment by Patschke** [comment]
Which was missing the interesting variable ini part anyway

**Comment by raithos** [comment]
if you want to add the info on printouts for versioning lists, that would be hugely appreciated while i check everything

**Comment by raithos** [comment]
i have a clever solution for the notes bit that doesnt require large rework :D

**Comment by Patschke** [comment]
Well, so maybe one wants to put a version information, listing the latest rules_reference and point_lists at some common place, so both print outs can simply display those information. 

As long as it is displayed at all, we can make it nice later ;-)

**Comment by raithos** [comment]
I'm going to force a line in the notes indicating which version of the list on printouts, old lists wont have that, all the new lists will default to that info. We can do a more solid version later

**Comment by Patschke** [comment]
Storm squad ace should be 40 points, you reduced it to 38

**Comment by Patschke** [comment]
Tempest Squad should be reduced to 38, you did not change that one (probably skipped a line)

**Comment by raithos** [comment]
thanks!

**Comment by Patschke** [comment]
Grand Inquisitor (upgrade) should go down to 14 points

**Comment by Patschke** [comment]
"Leebo" as YT-2400 pilot lost his crew slot

**Comment by Patschke** [comment]
I added the note on Leebo when you wrote "both" updated.

**Comment by Patschke** [comment]
Lando Rebel Crew should be reduced by 3, down to 2 instead of increased by 3

**Comment by raithos** [comment]
ok updated and committed

**Comment by Patschke** [comment]
So far I've checked empire, rebel and scum.

**Comment by Patschke** [comment]
Static Discharge Vanes have increased to 8 points

**Comment by raithos** [comment]
cool.

**Comment by Patschke** [comment]
Trick Shot increased to 2 points

**Comment by Patschke** [comment]
Everything else looks fine (I did not check the variable point stuff, but all the fix point changes are looking good).

**Comment by raithos** [comment]
ty will be pushing it live shortly

**Comment by Patschke** [comment]
How often are they going to do that? I wonder if it is worth the time setting up a script, that will automatically update the point costs from the api_exports we have on the translation_helper...  They have the data available. Even if it's not, it would be more fun to set up a script, than doing that manually for sure...

Maybe I should add those api_exports to the .gitignore, as they are relatively large and there is a jsonDownloader script that will actually download them.

**Comment by raithos** [comment]
i believe they are running it every 6 months for points updates. its not really worth setting up a script
