### ISSUE TITLE
Lowhhrick and Wullffwarro have been mixed up in the german translation.

### ISSUE THREAD

**Issue by Taloncor** [raithos/xwing#286]
### Bug Description

Lowhhrick and Wullffwarro have been mixed up in the german translation.

### How to reproduce

Start in english and select Auzituck and Wullffwarro as a pilot. 
Change language to 'Deutsch'.
Wulffwarro is now Lowhhrick (but still costs 56 points)

### Language

German

**Comment by Patschke** [comment]
I blame ffg for that. Use the Card Search of the official app and search for one of them. It will show the wrong one...

**Comment by Taloncor** [comment]
Yeah, would never had noticed but someone posted a german list and I was wondering why the link showed a different ship (Low instead of Wullff). Another reason to stick with English everywhere. ;-)
