### ISSUE TITLE
Engine Upgrade wrong points in description

### ISSUE THREAD

**Issue by kierheyl** [raithos/xwing#288]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** If you have a resistance list with the falcon before the missile slot was added, and cant see it when you load it, please re-add your crew slots. This is a known issue when loading old lists into a  ship configuration that has changed, they will load upgrades into slots that dont belong there.

### Expected Behavior

Points in upgrade description should match actual upgrade cost.

### Actual Behavior

Description still reads: This upgrade has a variable cost, worth 3, 6, or 9 points depending on if the ship base is small, medium or large respectively.

### Language

English

**Comment by Patschke** [comment]
I'll add an automatically generated statement displaying the different values, as variable point costs seem to be more common.

**Comment by Patschke** [comment]
Done and part of #289, will go live as soon as that PR is merged in.
