### ISSUE TITLE
Fonts not loading properly on IE/Edge

### ISSUE THREAD

**Issue by goforfold** [raithos/xwing#293]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** If you have a resistance list with the falcon before the missile slot was added, and cant see it when you load it, please re-add your crew slots. This is a known issue when loading old lists into a  ship configuration that has changed, they will load upgrades into slots that dont belong there.

### Expected Behavior

View correct actions for Quickdraw, to include barrel roll

### Actual Behavior
Missing barrel roll, shows move turret linked to move turret
### Language
English
![qd](https://user-images.githubusercontent.com/47275442/52165158-0b38d000-26cb-11e9-9cb9-a0d3db1906d3.PNG)

**Comment by Patschke** [comment]
As there is a bunch of other icons that seem wrong on that screenshot (Evade is not an Upgrade slot, the requirement is for missiles not for upgrades, ...), I guess you are using Edge or Internet Explorer? 

There is an issue of loading the icon font properly for Edge. I am currently not sure on how to fix that, and if it actually is an issue of yasb or if just raithos.github.io is not configured to allow importing fonts from third party servers. 

Maybe @raithos can have a look at the issues reported by Edge? 

![grafik](https://user-images.githubusercontent.com/17853362/52220110-6a9b0980-289e-11e9-85e5-4f682476c576.png)

I am so non-familiar with edge, that I don't even know how to set it to english to get some helpfull error messages..

**Comment by raithos** [comment]
It seems to be an issue that is also present on the 1.0 YASB. You're probably right that it's something about edge not loading fonts in correctly. I'll look into it

**Comment by raithos** [comment]
just as an update, I still havent solved the issue but it appears to me that microsoft edge and IE specifically have trouble distingishing between capital and lowercase letters for custom fonts it seems. Not sure how to solve that issue specifically but thats where i am currently. Meantime, use firefox or chrome to display the correct fonts.

**Comment by goforfold** [comment]
Thanks

Cheers,
NDT

--sent from mobile--

On Feb 5, 2019, at 1:48 PM, raith <notifications@github.com<mailto:notifications@github.com>> wrote:


just as an update, I still havent solved the issue but it appears to me that microsoft edge and IE specifically have trouble distingishing between capital and lowercase letters for custom fonts it seems. Not sure how to solve that issue specifically but thats where i am currently. Meantime, use firefox or chrome to display the correct fonts.

**Comment by Patschke** [comment]
Could we rename that Issue to "Fonts not loading properly on IE/Edge"?

**Comment by raithos** [comment]
So I'm going to close this. I am convinced this is a font related problem, and there's nothing I can do programatically to solve it. There is actually also a thread in the font github about the same issue.

**Comment by raithos** [comment]
Hey remember this? I might have solved it.

**Comment by goforfold** [comment]
I just ditched Edge, problem solved haha. I admire the hustle and follow up though, thanks!

Cheers,
NDT

On Jun 14, 2020, at 5:31 PM, raith <notifications@github.com> wrote:

﻿

Hey remember this? I might have solved it.
