### ISSUE TITLE
List Names, saving, and formats

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#295]
### Expected Behavior
1) When saving an old list with a new name, we should be able to change the name in the "Save As" dialog.
2) When changing from Extended to Hyperspace or vice versa, either clear the list name or allow saving over the list.

### Actual Behavior

1) When using the "Save As" option to save an existing list with a new name, even though the dialog gives the option to change the name, it does not check to see if the entered name is available, but rather continues to complain that there is already a list with that name.
2) When you change formats, all of the ships are removed from the list, but the list name is not cleared.  "Save" will not replace the old list with the new list.

### Language

English, but probably irrelevant?

**Comment by Patschke** [comment]
>     1. When saving an old list with a new name, we should be able to change the name in the "Save As" dialog.

Well, you may change the name - it will save the list using the new name. It will just not delete the previous version, so it is not "renaming" the list, if that is what you'd like to achieve? However, I don't think that I'd want it to delete the old list, as one may have created an different version (not just an updated version), and wants to keep the original as well. 

>     2. When changing from Extended to Hyperspace or vice versa, either clear the list name or allow saving over the list.
> 

Yep, going to fix that. Thanks for the note!

**Comment by LordVorKon** [comment]
No, I mean if you have a saved list, load it, change something, and then attempt to "save as", the original name is in the name textbox and it complains that you already have a list with that name.  Even if I change the name in the box, it does NOT check to see if a list with the new name exists; instead it just refuses to save.

**Comment by Patschke** [comment]
Ah, ok. I'll have a look at that as well. Thank you.
