### ISSUE TITLE
Rey’s Millennium Falcon "rotate" icon not rendering properly

### ISSUE THREAD

**Issue by elistevens** [raithos/xwing#300]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** We're working on adding quickbuild functionality, but its not complete.

### Expected Behavior

The rotate icon will render, as the boost icon does.

### Actual Behavior

The icon is missing. The HTML renders as:

```
maneuvers and perform <i class="xwing-miniatures-font xwing-miniatures-font-boost"></i> and&nbsp;<rotate> actions even while stressed.</rotate>
```

### Language

English. Probably all?

**Comment by raithos** [comment]
Are you using Microsoft Edge or IE? I'm not seeing it on firefox or chrome. It's a known issue that the icons dont work properly on edge and IE

**Comment by raithos** [comment]
http://puu.sh/CI808/1d780db6c0.png

I am straight up not seeing that. I've checked the code and it looks correct. this sounds silly but maybe clear your cache and see if it loads correctly?

**Comment by elistevens** [comment]
Now I feed dumb!  Ctrl+shift+R did the trick.  Sorry!
