### ISSUE TITLE
2 dot and 3 dot ship restrictions not implemented

### ISSUE THREAD

**Issue by raithos** [raithos/xwing#302]
Anyone have any suggestions on how I should do this? I've tried a few things and they haven't worked the way I want it to.

**Comment by Patschke** [comment]
I guess I've missed something. What are 2 dot and 3 dot restrictions supposed to do? Only 2/3 of that ship type per squad?

**Comment by raithos** [comment]
correct. like how single dots denote only 1 of that card per squad, same with 2-3 dots

**Comment by LordVorKon** [comment]
If all else fails, you could just have forex, "Hadr Chall Prototype A" and "Hadr Chall Prototype B" listed separately as unique pilots.  Not exactly an elegant solution, but it'd probably work.

**Comment by Patschke** [comment]
> 
> 
> If all else fails, you could just have forex, "Hadr Chall Prototype A" and "Hadr Chall Prototype B" listed separately as unique pilots. Not exactly an elegant solution, but it'd probably work.

That sounds awful and would not work if some of the two dot things exist on more than one card (like uniquie pilots having different ships). 

> 
> 
> Anyone have any suggestions on how I should do this? I've tried a few things and they haven't worked the way I want it to.

I can't see where the problem would be? It would work almost exactly like the `max_per_squad` for upgrades that already exist. Just give the pilots a `max_per_squad` value, write a `countPilots` method similiar to `countUpgrades`, maybe use an additional `.getXWSBaseName()` for comparing (so it is possible to have two different cards beeing restricted to two dots). Basically put a check for that everywhere a uniqueness check is, but make sure it is only invoked when the `max_per_squad` property is set if you care about fast code, as it will always iterate over the whole squad to count. If those multi dot mechanic is supposed to work across pilots/upgrades (e.g. a crew member is two-dotted together with a pilot), count pilots and upgrades instead. 

If it keeps not working the way you want it to, I can try writing a proper any-numer-of-dot handling method. Right now I can't see why it would not work, so maybe you could also specify the problems you encountered...

**Comment by raithos** [comment]
@Patschke  I would love to do it the way you stated, that was basically my though process as well (using restricted instead of max_per_squad, but it seems like a countPilots function doesnt seem to work as you cant access the builder info (or im missing something and being stupid). I've been trying to find different ways to make ti work and I'm kind of giving up on it. 

Now I'm thinking instead of modifying @uniques_in_use to have a seperate array that handles restricteds and has seperate logic that handles them

**Comment by Patschke** [comment]
Well, everything should work like in `countUpgrades`:

```
    countUpgrades: (canonical_name) ->
        # returns number of upgrades with given canonical name equipped
        count = 0
        for ship in @ships
            for upgrade in ship.upgrades
                if upgrade?.data?.canonical_name == canonical_name
                    count++
        count
```
So I'd expect somewhat like that to work fine? What else would I need to access?
```
    countPilots: (canonical_name) ->
        # returns number of pilots with given canonical name
        count = 0
        for ship in @ships
            if ship?.pilot?.canonical_name == canonical_name
                count++
        count
```

**Comment by raithos** [comment]
thats exactly what i did but it didnt work for me. maybe I'm doing it wrong?

**Comment by Patschke** [comment]
f2fa106d4baaac013e958f4dd163e17a0c75ef15 works fine.

**Comment by raithos** [comment]
super weird, i must have made a mistake somewhere, the code looks almost the same.

**Comment by Patschke** [comment]
Well, those are usually the bugs that are hardest to find... Stuff that looks alright and should work, but simply doesn't.
