### ISSUE TITLE
YASB on Discord mobile app is blank

### ISSUE THREAD

**Issue by Kieransi** [raithos/xwing#304]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** We're working on adding quickbuild functionality, but its not complete.

### Expected Behavior

In Discord mobile, there's a built-in web browser which I want to access YASB through

### Actual Behavior

The list loads as blank for all factions except Resistance. This is a common problem that a lot of people have commented on. I believe the reason is that the Resistance has a one-word faction name. The "%20" between the parts of the faction names is creating this problem. 

### Language

I believe this is the same for all languages

**Comment by raithos** [comment]
I've opened links in discord on both the app and desktop and haven't had that issue. There is a issue with the link in discord if part of the link is converted into emojis as a part of formatting, but there's nothing I can do about it except make a shortlink. something I might want to do but its not on my radar atm.

**Comment by raithos** [comment]
If you could share an example link that would be helpful

**Comment by Kieransi** [comment]
![71ba6468-1328-414e-88d1-6eb43674512a](https://user-images.githubusercontent.com/47514252/52661043-52d70d00-2ebe-11e9-9b6f-030babf1c176.png)
So in this first picture, a Scum list was loaded. YASB seems to have defaulted to the basic page (Rebel, blank). All the factions do this except Resistance:
![64d7b19d-0f25-470d-8d12-9e5d66681a1b](https://user-images.githubusercontent.com/47514252/52661117-84e86f00-2ebe-11e9-8e41-23f3f69d879c.png)
I think the problem is that the Discord web browser doesn't understand the %20 used to indicate spaces. It's not a big problem and only affects this one app as far as I know so don't worry about it, but it would be cool if the faction part of the URLs was shorter so all of the factions worked here.
But I totally understand that you have other stuff to work on and Discord users can still print/screencap their lists and post that or some other workaround.

**Comment by raithos** [comment]
can you give me the actual link that would be helpful

**Comment by Kieransi** [comment]
I mean, sure, it's any link, but it only happens when they're opened in the Discord mobile app integrated web browser (I use iPhone). 

Here's one that opens:
https://raithos.github.io/?f=Resistance&d=v5!s!231:117,196,165,175,206,171,170:U.102;295:-1,32,192,189,93,166,193:&sn=Random%20Squad&obs=

All of these don't
https://raithos.github.io/?f=Rebel%20Alliance&d=v5!s!43:126,99,-1,37,-1,164,-1,-1:;17:-1,-1,-1,-1,-1,68,-1,-1:;15:-1:;57:-1,-1:&sn=Random%20Squad&obs=
https://raithos.github.io/?f=Galactic%20Empire&d=v5!s!216:134,49,37,-1,-1,-1,-1:;184:-1,-1,-1,-1:;185:-1,33,-1:&sn=Random%20Squad&obs=
https://raithos.github.io/?f=Scum%20and%20Villainy&d=v5!s!107:-1,-1,100,30,69,93,103,161:U.-1;154:-1,10,-1,-1,-1,-1,94,110,-1:;93:-1,55,-1:&sn=Random%20Squad&obs=
https://raithos.github.io/?f=First%20Order&d=v5!s!242:181,202,102,-1,-1,105:;287:-1,202,134,-1:;261:-1,-1:;235:-1,178,109:&sn=Random%20Squad&obs=

**Comment by Kieransi** [comment]
I'm going to close this issue because the new copy feature is really nice for Discord users and we can just get used to using that. Thanks Raith!
