### ISSUE TITLE
Error loading FO list

### ISSUE THREAD

**Issue by Sycho11** [raithos/xwing#305]
Having errors opening this list link:

https://raithos.github.io/?f=First%20Order&d=v5!s!236:74,186,136,-1:;289:186,206,-1,-1,184,-1,-1,-1:&sn=Supreme%20Commander%20Ren&obs=core2asteroid1,core2asteroid3,core2asteroid4

I even deleted it and recreated it and now same error

https://raithos.github.io/?f=First%20Order&d=v5!s!236:74,186,136,-1:;289:186,206,-1,-1,184,-1,-1,-1:&sn=Supreme%20Commander%20Ren&obs=core2asteroid1,core2asteroid3,core2asteroid4

thoughts?

## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** We're working on adding quickbuild functionality, but its not complete.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
very weird. seems to be snoke only that does this. also, if you switch factions and then switch back it loads fine. I'll look more into it

**Comment by raithos** [comment]
@Patschke @zacharyp could use a consult on this, I cant find anything wrong

**Comment by Patschke** [comment]
I'm back from vacation now and will have a look at this.

**Comment by Sycho11** [comment]
List appears to be loading and updating properly now.  Impressive work!
