### ISSUE TITLE
Longshot is double entered

### ISSUE THREAD

**Issue by sirjorj** [raithos/xwing#312]
Longshot is ids 234 and 263.  I'm guessing the solution is to set skip:true on one of them.  I'll let you handle it.

**Comment by Patschke** [comment]
Yep, thanks for the note. 

I checked which one was entered when I selected longshot (id 263) and removed the other one. If somebody has the removed one in a saved list, it will sadly simply disappear from the list. This might be the case, if somebody created a list before the 2nd longshot entry was added.
