### ISSUE TITLE
Quick Build Black Squadron Ace (T-70)

### ISSUE THREAD

**Issue by iwerts** [raithos/xwing#319]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** We're working on adding quickbuild functionality, but its not complete.

### Expected Behavior

Selecting Black Squadron Ace (T-70) as a quick build generates a build for the T-70 X-Wing Black Squadron Ace.

### Actual Behavior

Selecting Black Squadron Ace (T-70) as a quick build generates a build for the TIE/ln Fighter Black Squadron Ace.

### Language

The affected language(s). 
English

**Comment by Patschke** [comment]
Thanks for the note, I associated the wrong Black Squadron Ace with the T-70. Will be fixed with the next PR

**Comment by raithos** [comment]
i got it
