### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rowen3** [raithos/xwing#320]
I would first like to say that your YASB 2.0 squad builder is awesome!

Something I would like to see, perhaps I am the only one, is a side by side ship comparison screen.

I think this would be a good addition since I have found myself wanting to find ships that do similar things or fly similar ways both in faction and across factions. For example, the Kihraxz fighter is said to be a worse X-wing. I would like to view a side by side of their abilities and dials to compare.

Thank you for your time.

**Comment by Patschke** [comment]
Maybe that is a stupid question, but what exactly would you like to be compared? To compare stuff like dials, you could simply open two windows beside each other, right? So do you picture some, kind of table listing stats, points and abilities of all pilots of a given ship, to be able to compare multiple pilots from different ships at once? I am not sure if I understand your request correctly, or if I am just missing some point about it.

**Comment by rowen3** [comment]
Here again, I would like to state that this is just a suggestion, I might
be the only person on the face of the earth who even would use or want it
and consequently it would be a waste of time making it happen, but yes a
table that lays out dials, abilities, and stats side by side would be nice.
I currently do this to compare two versions of the same ship that I have
created as well as filler ships that could work in a list. I have attached
two jpegs illustrating what I mean. Right now I do open two windows next to
each other, but it is a bit of a hassle to open a new screen, resize both,
and then when you're finished resize the first screen to original size. I
appreciate you considering my suggestion.

**Comment by Patschke** [comment]
If you attached images to that reply, github ate them - at least I don't see any. I believe you have to reply on github instead of answering via mail to include pictures properly.

**Comment by raithos** [comment]
Hi Rowen, thanks for your input. At this time doing side by side comparisons is not something I'm interested in adding to the builder functionality. Basically doing anything comparative is just not something that needs to be added to the game, especially cross-faction. While there is no doubt a comparison ability would be useful, I am hesitant to add any new feature that could potentially add feature bloat to the main site. As @Patschke mentioned, for direct comparisons you can always open two windows (or even just switch between tabs, your builds are saved as long as you don't refresh the page).
