### ISSUE TITLE
Chancellor Palpatine available as crew for other factions than Republic/Separatists

### ISSUE THREAD

**Issue by haukurv** [raithos/xwing#321]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** We're working on adding quickbuild functionality, but its not complete.

### Expected Behavior

Chancellor Palpatine should be selectable as crew for Separatists/republic only.

### Actual Behavior

Chancellor Palpatine can be selected as crew for any faction.

### Language

The affected language(s).

**Comment by raithos** [comment]
fixed

**Comment by haukurv** [comment]
Chancellor Palpatine can't be selected as crew for Seperatists now.

**Comment by raithos** [comment]
ty, thats fixed now as well
