### ISSUE TITLE
Moving Ship abilities to the Chassis instead of on specific cards

### ISSUE THREAD

**Issue by raithos** [raithos/xwing#323]
So I've been thinking about it, and I was thinking that maybe it would be good to move the ship abilities to their own section in the translation page, rather than having to retype it on every single ship card that uses it. That would be a non-trivial reduction in file size i think. But I'd like to get feedback as this may be a big change to the translation system as well as potentially a lot of work. It's not required, just a thought.

**Comment by Patschke** [comment]
I don't think that this is useful. I am just reading in the data provided by FFG, and they have it included in each pilot - so I am currently not retyping anything at all, it is just an automated import...

**Comment by raithos** [comment]
Ok, cool. I'll leave this alone for now then
