### ISSUE TITLE
Feature Request - Inventory List

### ISSUE THREAD

**Issue by Cerender** [raithos/xwing#325]
## YASB 2.0 Feature Request
Under "Your Collection" -> "Inventory"
Could the upgrades show upgrade type also? (Device, Crew, Gunner, etc.)

I'd like to export and use the lists in Excel. Adding that additional info to the list would be a huge time saver for me.  Thank you for a great product.

### Expected Behavior
Upgrade
0-0-0 - Crew - 1
4-LOM - Crew - 1
Ablative Plating - Modification - 10

### Actual Behavior
Upgrade
0-0-0 - 1
4-LOM - 1
Ablative Plating - 10

### Language

English

**Comment by Patschke** [comment]
That would be possible for sure. However, I am not sure if I see a reason for doing so. I don't want to offend you - any kind of feedback is always welcome and helps us to improve yasb - but I don't feel like I want to spend my time adding a feature, that will only safe some time for a single person. I don't think that exporting stuff to Excel is what people commonly use the "collection" view for, so as long as I cannot see how a larger number of users would benefit from that change, I am not going to add that.

**Comment by Cerender** [comment]
Understood.  Right now though all inventory upgrade items are listed as one even though they are different types.  It seems like they should be separated into different categories.  More like the card browser section. 

"Sent from my iPhone"
- Randall Munroe
    http://xkcd.com/1942/

**Comment by raithos** [comment]
I will leave this as closed, but if there are enough other people who also want this we will revisit it. Thanks for your feedback!
