### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by vonmonkhouse** [raithos/xwing#33]
Random list generator for Randomized Matches.

**Comment by vonmonkhouse** [comment]
What's random?

**Comment by Patschke** [comment]
More random!
#165

I've kept the "original" position of the random button at the print/collection. We may want to move it to the save/load/new section? The Random-icon besides the text keeps dissapearing, I am not sure why.

**Comment by Patschke** [comment]
I may or may not somewhen implement the following enhancements:
* remove Maximum randomization Iterations from UI settings. User do understand a maximum time, but probabaly not a max iteration option. 
* add slider: more upgrades <-> less upgrades
* add option: use only collection

**Comment by vonmonkhouse** [comment]
No way.

How can I test it?

*Devon Monkhouse*| Sales Representative


*Landlord Property & Rental Management Inc.*515 Logan Ave, Toronto, ON M4K
3B3

T 416.961.8880 <(416)%20961-8880>  F 416.462.1461 <(416)%20462-1461> C
647.393.3655 <(647)-393-3655>
-------------------------------------------------------------------------

www.landlord.net | www.landlordrealty.net



This message is being sent to you by Landlord Property & Rental Management
Inc. or Landlord Realty Inc. If you would like to provide your express
consent to receive commercial electronic messages from us, or you no longer
wish to receive commercial electronic messages from us, then you can manage
your preferences by clicking here.
<http://landlord.nationbuilder.com/sign_up> Please note that we will still
have the right to send you commercial electronic messages that are in
compliance with Canadian Anti-spam laws.

**Comment by Patschke** [comment]
If you want to test it right now, you probably need to clone my repo and build YASB yourself. I do not recommend doing so, unless you have some basic understanding of what you do. Unfortunately, we do not have an online available beta/test server of YASB. 

To clone and build on a UNIX system, you need to execute the following commands:
`git clone https://github.com/patschke/xwing/`
`sudo npm install -g grunt-cli`
`cd xwing`
`npm install`
`grunt`
You can then open the `app/index.html` in your browser and test the random generator. 

If building YASB is no option for you, you'll probably need to wait until the feature becomes public available (usually within the next day(s)).

**Comment by vonmonkhouse** [comment]
Half of that was gibberish.

I can wait Hahaha.

D.

**Comment by vonmonkhouse** [comment]
Amazing.

Someone on reddit pointed out that static discharge vanes appear in almost
every squad.

D.

**Comment by Patschke** [comment]
I've now pointed out on reddit that the appearance of static discharge vanes is random - as one might guess for a random genearted squad.

**Comment by vonmonkhouse** [comment]
Hahaha

**Comment by raithos** [comment]
I'm pretty satisfied with how this works now. Closing this thread
