### ISSUE TITLE
Variable points for Mod's on Deltas

### ISSUE THREAD

**Issue by n112221** [raithos/xwing#332]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

Mod slots on the delta should decrease in points after attaching the D-7b Config to match their now 2 agility

### Actual Behavior

Mod slot is still basing point values as though the ship were 3 agility.

### Language

![For bug report](https://user-images.githubusercontent.com/48773204/54718355-8b9a7f80-4b17-11e9-8659-26b3d446fc5d.png)

**Comment by raithos** [comment]
The official app works the way as it is now. So this is working as intended
