### ISSUE TITLE
Random Wave 3 mistakes

### ISSUE THREAD

**Issue by AxisofeviI** [raithos/xwing#333]
Barriss should have 1 force, not 3.
Barriss should be init 4, not 6.

104th Battalion Pilot shouldn't have an EPT.
Jag shouldn't have an EPT.
Sinker shouldn't have an EPT.
Swoop shouldn't have an EPT.

Servants of Strife is called Servants of Strike in the collections menu.

**Comment by raithos** [comment]
barriss is already updated, you should refresh. the other changes are being pushed shortly
