### ISSUE TITLE
Buttons not cklickable

### ISSUE THREAD

**Issue by L0ric0** [raithos/xwing#336]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior
Every Button should be usable
### Actual Behavior
Everything from the the field to select mode of play to the second left upgrade of the first ship including the first ships copy and delete button can't be clicked
### Language
I could only test english and german because of this bug

**Comment by Patschke** [comment]
The problem has resolved after reloading the page. 

If it encounters again leave a note (check the error log, and include it if possible).
