### ISSUE TITLE
Target Lock --> Lock

### ISSUE THREAD

**Issue by nexusno2000** [raithos/xwing#34]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times.

### Expected Behavior

Pilot action list say "Target Lock"

### Actual Behavior

Should just be "Lock" now.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
thats a bit nitpicky, but ok, going into the next push
