### ISSUE TITLE
XWS Import

### ISSUE THREAD

**Issue by diablodiablo** [raithos/xwing#341]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior
Import XWS from Lauchbay Next

State what you expect to happen here.

### Actual Behavior

State what actually happens here.
It is loading for a really long time then times out

### Language
English
The affected language(s).

**Comment by Patschke** [comment]
Thanks for your bug report. I'd like to ask you for some additional information:
Could you post some example xws that is exported from Launchbay Next and fails to be imported in YASB?
Is the other direction working (export from YASB, import to Launchbay)?

**Comment by diablodiablo** [comment]
I just imported this list to LaunchBay with no problem
https://raithos.github.io/?f=Galactic%20Empire&d=v6!s=200!201:123,,,:;201:123,,,:;201:123,,,:;201:116,,,:&sn=2.1%20Sigma%27s%20w%2F3%20Juke%201x%20Crack&obs=

This list is the one I was trying to import to YASB but it just keeps saying loading

Thanks for all your hard work and especially getting the new points uploaded so quickly so we didn’t  have to use the FFG squad builder!

PS digging the quick build feature too!

Tim

{"name":"Tie Swarm V1","points":199,"faction":"galacticempire","pilots":[{"id":"academypilot","ship":"tielnfighter","upgrades":{},"points":23},{"id":"blacksquadronace","ship":"tielnfighter","upgrades":{"talent":["swarmtactics"]},"points":26},{"id":"nightbeast","ship":"tielnfighter","upgrades":{},"points":26},{"id":"wampa","ship":"tielnfighter","upgrades":{},"points":30},{"id":"lieutenantsai","ship":"lambdaclasst4ashuttle","upgrades":{"crew":["admiralsloane"],"sensor":["advancedsensors"],"cannon":["jammingbeam"]},"points":47},{"id":"obsidiansquadronpilot","ship":"tielnfighter","upgrades":{},"points":24}]}

Sent from my iPhone

On Mar 25, 2019, at 8:20 AM, Patrick Mischke <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your bug report. I'd like to ask you for some additional information:
Could you post some example xws that is exported from Launchbay Next and fails to be imported in YASB?
Is the other direction working (export from YASB, import to Launchbay)?

**Comment by Patschke** [comment]
Ah well. We relied on a xws version number beeing specified, to reject 1.0 squads. However, the version parameter is optional and it seems as if Launchbay is no longer providing it. PR #342 will fix this, so if no version is specified we just assume that you try to load a 2.0 squad.

Thanks for the note
