### ISSUE TITLE
YASB 2.0

### ISSUE THREAD

**Issue by Heuersmith** [raithos/xwing#346]
I would like to say your squad builder is amazing. Also thank you for making it and putting it out there for free.

I have found a few things in wave 3 that are not right. The title Scimitar for the Sith Infiltrator says its unreleased.  Also the crew upgrade card Chancellor Palpatine says its only included in the ARC-170 expansion pack. It is also in the Sith Infiltrator expansion.

If you are already aware of these issues sorry to restate them. Again thank you so much for the site. Its sooooooooooooooooooooooo much better then the official site.

Have a great day.

**Comment by Patschke** [comment]
Thanks, will be fixed with PR #347
