### ISSUE TITLE
OAuth logins only work on Edge browser

### ISSUE THREAD

**Issue by MohnJadden** [raithos/xwing#349]
### Expected Behavior

Clicking Log In and selecting an OAuth provider (Google in my case) should log me into my YASB account.

### Actual Behavior

Clicking  Log In and going through OAuth just returns me to the page where I started the process.  I do not log in.  The issue only occurs on Chrome 73 and IE.  Edge is not affected.

### Language

English

**Comment by raithos** [comment]
Can you verify that closing the browser and reopening it after a hard refresh does not resolve this issue? As well, clearing your cookies and cache?

**Comment by MohnJadden** [comment]
Tweaked a bit more and I found the issue for Chrome: I have Edit This
Cookie as an extension and it didn't display an option to allow the backend
url. I allowed it in the extension and normal functionality returned. Not
sure why it didn't work in IE but I'll clear cookies and cache on it
tonight to see if it works there.

**Comment by Patschke** [comment]
I think this issue can be closed.

**Comment by MohnJadden** [comment]
Agreed. So far so good!
