### ISSUE TITLE
Incorrect ship counts

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#35]
### Expected Behavior

StarViper should show 2 ships per conversion kit
Kihraxz Fighter should show 3 per kit

### Actual Behavior

Both ships show '0 ship model' when selected in a list.
Note: In the collection editor, StarViper is spelled with a lower-case v, and Kihraxz Fighter does not appear at all.

### Language

**Comment by raithos** [comment]
will update in the next push
