### ISSUE TITLE
Not all symbols (side-arcs) showing up

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#351]
"Jag"'s text, nor dedicated, t have sidearc symbols.

![image](https://user-images.githubusercontent.com/10382630/55599518-14ffa380-570d-11e9-8de8-831f9838e7fd.png)

![image](https://user-images.githubusercontent.com/10382630/55599592-57c17b80-570d-11e9-8f3a-788567405f31.png)

**Comment by Patschke** [comment]
Thanks, going to fix that.
