### ISSUE TITLE
Cad Bane has incorrect icon in text

### ISSUE THREAD

**Issue by Chaotix** [raithos/xwing#355]
Cad Bane states you can perform a bonus BOMB action.

It should show a BOOST action.

**Comment by Patschke** [comment]
It shows the correct icon for me. Are you using Edge or Internet Explorer? This might be a duplicate of #293 as those browser simply fail to load the icon font properly. Are the icons shown correctly here https://geordanr.github.io/xwing-miniatures-font/ ?

Currently I am not aware of a fix for that problem, if it is the same issue.

**Comment by Chaotix** [comment]
Seems to be showing the correct icon for me now - i was using IE you're correct.

**Comment by raithos** [comment]
As its a duplicate im going to close this.
