### ISSUE TITLE
Soulless One

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#358]
## YASB 2.0 Bug Report

"Soulless One" title for Belbullab not functioning properly.

### Expected Behavior

"Soulless One" title should increase ship hull value

### Actual Behavior

"Soulless One" title does not add hull value

### Language

![image](https://user-images.githubusercontent.com/38739187/55910388-2c1e1580-5b93-11e9-8f73-2167242fee81.png)

**Comment by Patschke** [comment]
It will show correctly on the print out, just the tooltip is not showing stat changes at the moment. This will be fixed with #353

**Comment by raithos** [comment]
huh actually didnt have the +2 to hull on the card. super weird. this will be updated shortly
