### ISSUE TITLE
Card Browser

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#36]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times.

### Expected Behavior

Pilots should have a stat entry for Charges/Force Charges, if appropriate

### Actual Behavior

No Charges/Force Charges are shown for pilots.  (The squad builder displays this information correctly; only the card browser omits it.)

**Comment by raithos** [comment]
fixed
