### ISSUE TITLE
Quickbuild Pilots with Multiple Builds

### ISSUE THREAD

**Issue by dbldown11** [raithos/xwing#360]
## YASB 2.0 Bug Report

Quickbuild Pilots with multiple versions of the same pilot have awkward behaviour.

I think this was sort of alluded to in https://github.com/raithos/xwing/pull/303#issue-251070362, so if this is known and accepted, feel free to close this out. As that issue mentions, this would be a nice QoL thing but it's a mild nuisance at most and it's causing only low to moderate amounts of mental distress for me.

### Expected Behavior

With one quick build version of a pilot with multiple quick build versions, I would expect that I would be able to switch from one version of the pilot to another directly.

### Actual Behavior

For ships with multiple versions of the same pilot, when one is selected, you can't select the other without first selecting a different pilot. For example, if I've got Trick Shot Blackout in my list, I can't switch him to Elusive Afterburners Blackout without switching to a different pilot first, as both Blackouts are grayed out while one is selected.

This (unsurprisingly) only happens with unique pilots; you can switch right from one Black Squadron Ace TIE Fighter to another, but selecting one Iden Versio means you're stuck with her until you select another TIE Fighter first (i.e. you belatedly realised you foolishly didn't take the dope Proton Torpedo Iden).

### Language

English.

**Comment by Patschke** [comment]
Yep, thanks for the note. Currently I am basically checking "Is it allowed to add that quickbuild" when selecting any pilot, which obviously will return "no" for changing between multiple versions of a pilot. The correct check would be "Is it allowed to exchange that quickbuild", which is harder to implement as it may require checking multiple ships in case of quickbuild cards containing more than one ship. Probably the main reason to use the "wrong" check was, that the used version is just the same check like for usual not quickbuild squad building, and therefore already existed. 

So yes, I was already aware of that issue. I may nevertheless revisit it, and add some easy to handle special cases like changing between different versions of the same pilot. So we'll keep that issue open for now. I usually feel more motiavated to implement stuff properly, if I receive feedback telling me that people indeed use that stuff - and I wasn't sure how frequently the quickbuild builder would be used at all.

Thanks for reporting a bug in an actually usefull way (proper description, examples how to reproduce it,...). Most people don't even manage to read the other open issues, but you spend the time to search through comments on PRs ;-)

**Comment by Patschke** [comment]
Should be fixed with #364
