### ISSUE TITLE
Chancellor Palpatine

### ISSUE THREAD

**Issue by riselin** [raithos/xwing#361]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

He should only appear as option for separatists or republic. The card correctly says so in the description ("Separatist Alliance or Galactic Republic only"

### Actual Behavior

He appears as option for all factions.

### Language

English

**Comment by Patschke** [comment]
I cannot reproduce that bug. For me Palp is not selectable as crew member in any faction other than separatists or republic. Could you give an example of a list where you were able to select palp in a wrong faction?

**Comment by riselin** [comment]
I see, I was unclear. He is not selectable, but he appears as greyed-out option.
He shows up it in both hyperspace and extended, for both rebels and imperials on several ships.

**Comment by Patschke** [comment]
Hmm... Should 0-0-0 be allowed for the republic if I field Anakin? 

Will be fixed in #364

**Comment by raithos** [comment]
@Patschke afaik Anakin and Vader are considered separate personas for the purpose of uniqueness
