### ISSUE TITLE
Shield-Upgrade-Cost für the Delta-7B?

### ISSUE THREAD

**Issue by Paladin69** [raithos/xwing#363]
It's not a bug report, but a question...
The Shield Upgrade costs 6 points on ships with 2 agility and 8 on ships with 3 agility.

If you upgrade the Delta-7 Aethersprite (agility 3) to the Delta-7B (agility 2) - does the shield upgrade cost 6 points (because of the 7B modification) oder 8 points (because that is what's printed on the ship card)?

**Comment by Patschke** [comment]
From the [Rules Reference](https://images-cdn.fantasyflightgames.com/filer_public/be/e0/bee0c351-8d22-4f77-b6f4-101e6fa8ca8e/swzrulesreference_v103-compressed.pdf) (p.26):

> Q: If a ship equips an upgrade that alters one of its values (such as agility), how does this affect variable cost upgrades? 
>A: Other upgrades are ignored when calculating variable costs, and the base values of the ship are used.
