### ISSUE TITLE
Gas Clouds on Prints

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#365]
Gas Clouds need to be added to the print out (obstacle list to mark the used ones)

**Comment by raithos** [comment]
OK i will make a new image when i have time, I never liked the one we had anyway

**Comment by Patschke** [comment]
I wonder if we should consider removing `images` from the `.gitignore`. As they usually don't change, it should not be that much of an issue adding those binary files to the git repository.

**Comment by Patschke** [comment]
![uwing](https://user-images.githubusercontent.com/17853362/59293353-4d78ac00-8c7f-11e9-969c-797d74d04021.png)
This is a very ugly version, as you said you wanted to rework it anyway. It does contain the gas clouds, so it is better then the current version. 
Should I remove `images` from `.gitignore` or make a PR directly against raithos.github.io?

**Comment by raithos** [comment]
lol sorry i just have been caught up with a shit ton of other stuff. I can take care of this tonight, no need to add it to images

**Comment by Patschke** [comment]
https://github.com/raithos/raithos.github.io/blob/master/images/xws-obstacles.png

Does still not contain gas clouds...
