### ISSUE TITLE
Scum Quickbuild issues

### ISSUE THREAD

**Issue by gmodos** [raithos/xwing#367]
1.) Z-95 Kaa’to Leeachos & N’dru Suhlak 2x in pilot list, one of each with wrong upgrades

2.) When choosing Firespray and G1-A select2 says "searching"  (TypeError: Cannot read property 'unique' of undefined" javascript error)

**Comment by Patschke** [comment]
1) As far as I know, there exist 2 versions for N'dru Suhlak and Kaa'to. One is from the official pdf (basically the quick build for the conversion kit) and one is from the 2nd edition Z-95 expansion. FFG just fails to include both into their pdf, but actual quickbuild cards do exist.

2) Yep, that is a bug. Going to fix it (it's trying to add "Seismic Charge" as upgrade, but they are named "Seismic Charges". Thanks for reporting!

**Comment by gmodos** [comment]
Thanx.
Don't waste your time. I'll make the bugfix. 
(I found quickbuild settings in cards-common.coffee.)
