### ISSUE TITLE
Uniqueness Violation

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#37]
### Expected Behavior

Unique cards with the same name but in different ships  or different card types should block one another.

### Actual Behavior

Hera Syndulla in the Attack Shuttle and Hera Syndulla in the VCX-100 do not properly lock out.

**Comment by LordVorKon** [comment]
Also, Norra Wexley (ARC-170 and Y-Wing)

**Comment by LordVorKon** [comment]
"Chopper" (VCX-100 pilot, crew, and astromech)

**Comment by raithos** [comment]
should be good. post a reply here and reopen if it still doesnt work or if you find any others

**Comment by LordVorKon** [comment]
R2-D2 is still not locking.  The others all look good.
