### ISSUE TITLE
XWS imports wrong falcon

### ISSUE THREAD

**Issue by Svelok** [raithos/xwing#370]
Launchbaynext XWS import of a Scum list (Han/Teroch/Fenn) loads the wrong (Rebel) Han instead. The XWS specifies "customizedyt1300lightfreighter", which should(?) be correct. 

XWS & screenshot attached.

https://pastebin.com/MTHDcpkY
https://i.imgur.com/efWVNEV.png

**Comment by Patschke** [comment]
I'll have a look at this.

**Comment by Patschke** [comment]
db55a14a3fdaaa963edae6618482becbb21d7549 should fix this (part of #371)
