### ISSUE TITLE
Fractions labels

### ISSUE THREAD

**Issue by fangirsan** [raithos/xwing#375]
Hi,
Can I ask to add some labels to fractions?
This icons are so small.

BR
Grzegorz

**Comment by Patschke** [comment]
Just to be sure we are talking about the same icons: Are you concerned about the faction selection buttons at the top menu? I never heard about anybody having issues with those before, and I personally think their size is fine. 

Could you maybe add a picture how large they are rendered for you? I believe they should just have your default font size, which is fine for me.

**Comment by raithos** [comment]
Ive increased the size of the icons in the top bar. I think this should make them a easier to click/tap. Im not really sure i can make them any bigger than they are now without it starting to look really weird
