### ISSUE TITLE
OAuth login not working in Chrome

### ISSUE THREAD

**Issue by ThisIsStupidGitHub** [raithos/xwing#379]
### Expected Behavior

Clicking Log-in brings up a prompt to pick which service to log in with. Google, Facebook, Twitter. 

### Actual Behavior

Attempting to log in with Google though Chrome does not log in. Just refreshes the window, showing its not logged in. Seems to work fine in Firefox. Attempted to clear cookies, no luck. 

Chrome ver.  74.0.3729.157 (Official Build) (64-bit)

From my experience, this issue is fairly old with chrome. 

### Language

English

**Comment by raithos** [comment]
I've seen this issue but normally it just clears up if i close the tab and reload the page in a new tab. Does this not work for you?

**Comment by ThisIsStupidGitHub** [comment]
Unfortunately, not. Even restarting the browser doesn't help. And its only been happening in Chrome.

**Comment by ThisIsStupidGitHub** [comment]
Unfortunately, not. Even restarting the browser doesn't help. And its only
been happening in Chrome.

**Comment by raithos** [comment]
just one more thing, did you not only delete cookies but also cached data as well?

**Comment by ThisIsStupidGitHub** [comment]
I did, and just did again. Annoying as it makes using other sites. Doesnt seem to have resolved the issue. I just checked it on two other machines that i barely use chrome, and the site google auth seems to work ok on those machines. Not sure why is preventing me from authenticating with Google on this computer on Chrome only.

**Comment by Isbiten** [comment]
I have the exact same problem. Cannot login with chrome :(

**Comment by raithos** [comment]
@ThisIsStupidGitHub  @Isbiten can you both verify for me that "Block third-party cookies" is not enabled in your settings? They should be under content->cookies, or going to chrome://settings/content/cookies directly

**Comment by Isbiten** [comment]
> @ThisIsStupidGitHub @Isbiten can you both verify for me that "Block third-party cookies" is not enabled in your settings? They should be under content->cookies, or going to chrome://settings/content/cookies directly

There we go. It helped.
Thanks for the help

**Comment by ThisIsStupidGitHub** [comment]
That does appear to be the issue. However when i allow them for that site,
it still blocked, so the redirect is not getting unblocked. I'd really
rather not turn off blocking browser wide for one web site. What other
sites does the log-in auth connect to so i can add them to the white list
as well?

**Comment by raithos** [comment]
You can set whitelisted sites in Chrome. Pretty standard stuff. Here's the instructions:

1. Open the More action menu at the top right of the screen and select Settings in the drop-down menu.
2. Scroll down and press Advanced. 
3. Open the Content Settings. 
4. Open the Cookies settings.  
5. Under Allow, press Add.
6. In the Add a site pop-up, copy and paste one of the URLs in the table above in the Site field.
**The sites to add is yasb-backend.herokuapp.com and raithos.github.io**
7. Press Add.

**Comment by ThisIsStupidGitHub** [comment]
That did the trick. Thank you for your help.
