### ISSUE TITLE
Shield/Hull upgrades wrong costs

### ISSUE THREAD

**Issue by dreadangel** [raithos/xwing#380]
### Expected Behavior

Shield upgrade for Initiative 2 ship to be 6pts
Hull upgrade for Initiative 2 ship to be 5pts

### Actual Behavior

Shield upgrade for Initiative 2 ship is 8pts
Hull upgrade for Initiative 2 ship is 7
![2019-05-22 17_33_46-YASB 2 0 - v2 0 Drea Renthal + 2x Guild Tie + 2 Y-Wing](https://user-images.githubusercontent.com/1151809/58183342-e0917800-7cb7-11e9-919e-254c9341be8f.png)
pts

### Language

The affected language(s).

**Comment by Patschke** [comment]
The point cost for those upgrades scales with agility, not initiative. The costs are displayed correctly.
