### ISSUE TITLE
Brilliant Evasion on Aethersprite 7B

### ISSUE THREAD

**Issue by Archangelspiv** [raithos/xwing#382]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

Brilliant Evasion on an Aethersprite 7B is 6 points

It should be 4 points because of the reduced agility

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
No, it shouldn't. It's always using the base value. There is a FAQ for this.
