### ISSUE TITLE
Mining Guild TIE expansion missing Hull Upgrade

### ISSUE THREAD

**Issue by Beatpeitsi** [raithos/xwing#384]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

I expected to have a total of 3 Hull Upgrades from Scum and Villainy Conversion Kit + Mining Guild TIE Expansion

### Actual Behavior

Mining Guild TIE expansion does not increase the total amount of Hull Upgrades by 1

### Language

The affected language(s).

**Comment by raithos** [comment]
will be fixed in the next update
