### ISSUE TITLE
Soontir Fel Quickbuild price error

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#386]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

Soontir Fel Quickbuild is mis-priced.  He displays at 2 Threat.

### Actual Behavior

Soontir Fel should cost 3 Threat.

### Language

n/a

**Comment by Patschke** [comment]
Thanks for the note, will be changed with ea9c6c9e4570ab0ef4e65c77309d1912e174d6b0

**Comment by raithos** [comment]
will be fixed in the next push
