### ISSUE TITLE
"Solitary" Keyword on every ship

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#388]
### Expected Behavior

Having "solitary" only where it is expected.

### Actual Behavior

Apparently every single ship has the "solitary" keyword under it's name. It doesn’t effect anything but could confuse new players.

### Language

All of them.

**Comment by raithos** [comment]
I don't see that. Can you show me a screenshot?

**Comment by Patschke** [comment]
You need to select some tactical relay first, the "solitrary" treat will not be hidden on ship selection. I can fix that
