### ISSUE TITLE
Loading Squad

### ISSUE THREAD

**Issue by BlitzWulff** [raithos/xwing#39]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times.

### Expected Behavior
I expected to revisit a squad build I had been working on. After clicking Galactic Empire, Load, then my team "Inferno Run", I expected to see the full list,

### Actual Behavior
Only one pilot and ship slot showed up, not allowing for another slot to be added.

**Comment by raithos** [comment]
Hi, can you confirm that this is still an issue?

**Comment by BlitzWulff** [comment]
I can confirm that the bug is fixed. Thank you
