### ISSUE TITLE
Angled Deflectors incorrect information

### ISSUE THREAD

**Issue by WrathOfThrawn** [raithos/xwing#393]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

Only has flavor text on the card. 

### Actual Behavior

States "After you fully execute a blue maneuver, remove all of your stress tokens". 

I believe this is a resistance crew card's ability.

### Language

English for sure.

**Comment by raithos** [comment]
will remove this text and update
