### ISSUE TITLE
Hyena Bomber DBS-32C action bar

### ISSUE THREAD

**Issue by SneakyGitau** [raithos/xwing#394]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

Hyena Class Droid Bomber DBS-32C has a red jam action instead of red reload

### Actual Behavior

Shows red reload action instead of red jam action

### Language

The affected language(s).

**Comment by Patschke** [comment]
Thanks, will be fixed in PR #395
