### ISSUE TITLE
Facebook appends random junk as a part of cookie tracking

### ISSUE THREAD

**Issue by raithos** [raithos/xwing#398]
From my research it looks like we need to add a canonical link tag (<link rel="canonical" href="" />)in order to prevent fbclid tags from messing up our links. I tried to add a window.location.href variable in index.jade but got compile errors. I'm not able to spend a lot of time on this right now, but does anyone have any suggestions on how to get this to work?

**Comment by Patschke** [comment]
As I don't have a facebook account, I am not sure what facebook does to poor yasb links in order to track user. I might be able to have a look at it, if you can provide a more detailed description. However, I am not sure if I want to spend time on this either.

**Comment by raithos** [comment]
so crates solved this a different way so were good
