### ISSUE TITLE
Scum Y-wing listed as hyperspace legal in card browser

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#399]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

State what you expect to happen here.

I expected the scum Y-wing to not be listed as hyperspace legal

### Actual Behavior

State what actually happens here.

![image](https://user-images.githubusercontent.com/8730661/60313397-ee788f80-992c-11e9-89e7-0b527ff82946.png)

### Language

The affected language(s). English I guess?

**Comment by Patschke** [comment]
Thanks, will be fixed with my next PR. 
This issue was caused, since the Y-Wing is a hyperspace legal ship - for Rebels. If you limit the search to Scum, the pilots will no longer be shown. This bug will be fixed, thanks for reporting it.
