### ISSUE TITLE
Saber with juke points increase issue

### ISSUE THREAD

**Issue by vonmonkhouse** [raithos/xwing#40]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times.

### Expected Behavior

Points to increase 

### Actual Behavior

When I use the  clone pilot on a saber squadron with Juke it doesn't increase the points. 

### Language

Check spelling 
  I
  I
 \/  contrubuting / contributing 

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
Is this still an issue, I was unable to replicate it

**Comment by vonmonkhouse** [comment]
Nope. No longer an issue.

On Aug 27, 2018 11:28 AM, "raith" <notifications@github.com> wrote:

Is this still an issue, I was unable to replicate it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/raithos/xwing/issues/40#issuecomment-416265350>, or mute
the thread
