### ISSUE TITLE
squad builder does weird things when the points limit is null

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#403]
### Expected Behavior

I don't really know what I expected. I reached the squadbuilder via a bookmark and didn't notice that my points limit was null. (this is a new behavior since a couple days ago). Changing between hyperspace and extended fixes the issue, it would appear. Changing factions without changing format does not appear to fix the issue for the null limited squadron

### Actual Behavior

State what actually happens here.
![image](https://user-images.githubusercontent.com/8730661/60375173-f17b8a80-99d5-11e9-8131-23df430f6086.png)

I don't know if it needs to assume 0, 200, panic more, or just start autopopulating when the field is empty.

### Language

State what language translation you use.

**Comment by raithos** [comment]
this issue only occurs on really older lists, ive adjusted the logic to account for that. this should be fine now
