### ISSUE TITLE
old version link dead / not working

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#405]
### Expected Behavior

I don't know what I expected
### Actual Behavior

State what actually happens here.

![image](https://user-images.githubusercontent.com/8730661/60404515-98e3f300-9b77-11e9-80d5-93aad8dc59db.png)

### Language
 English?

**Comment by Patschke** [comment]
Use https://raithos.github.io/old/ directly. It should work.

The button is probably broken since the latest change to squad serialization...

**Comment by raithos** [comment]
im going back to the hard link for the time being, i forgot about the serialzation breaking the link
