### ISSUE TITLE
Can't see the contents of a loaded Quickbuild list.

### ISSUE THREAD

**Issue by biffindy** [raithos/xwing#407]
## YASB 2.0 Bug Report

Can't see the contents of a loaded Quickbuild list.  Loading Extended format lists works just fine.

### Expected Behavior

When loading a previously saved Quickbuild list, all contents are displayed (including ships and equipped upgrades).

### Actual Behavior

When loading a previously saved Quickbuild list, the contents (ships and upgrades) are not displayed.  The list's title and TL total are displayed, but none of the other contents.

### Language

I don't know what to put here, sorry.  I have tried to load my Quickbuild lists using the Chrome and IE browsers, both browsers behaved in the same way as described above.

**Comment by Patschke** [comment]
I can confirm that bug. It will also occur if one simply hits F5 while building a Quickbuild squad. 

Did anybody pay attention to quickbuild serialization when doing c3a0ade5cc0cc52cee59f69acac0c8598955be74 (@zacharyp)? Knowing what change caused quickbuild loading to fail would probably make fixing that easier.

**Comment by raithos** [comment]
This should be fixed now. Unfortunately any lists you made while this bug was active will still not load. Recommend you remake those lists, sorry for the inconvenience

**Comment by biffindy** [comment]
Thank you for addressing this and everything else the group does to provide
the squad builder!
