### ISSUE TITLE
Electro-Proton Bomb on Punisher

### ISSUE THREAD

**Issue by frankgrimes4f19** [raithos/xwing#408]
The Electro-Proton Bomb can't be added to the Tie Punisher when the ship meets all the requirements (bomb+mod slot/reload action). As far as I have seen every other ship that meets the requirements can add it on just fine.

**Comment by raithos** [comment]
https://raithos.github.io/?f=Galactic%20Empire&d=v8ZsZ200Z193XWWWWW235WW&sn=Unnamed%20Squadron&obs=

I'm not exactly sure what the issue is.

**Comment by Patschke** [comment]
Works fine for me, too. Maybe @frankgrimes4f19 tried to add it to multiple punisher and dit not notice it is unique?

If you can provide exact steps how to reproduce this bug, we'd be happy to fix it. Otherwise I'd consider this bug non-existent, and the issue could be closed?

**Comment by frankgrimes4f19** [comment]
Ya sorry didn't notice it was unique.
