### ISSUE TITLE
Collection Tracker Counts TIE/SF as TIE/VN

### ISSUE THREAD

**Issue by twzoom** [raithos/xwing#413]
### Expected Behavior

When adding a TIE/SF Fighter Expansion Pack to your collection you should get TIE/SF ships in your inventory.

### Actual Behavior

Adding TIE/SF Fighter Expansion Packs to your collection adds TIE/VN ships to the inventory instead of TIE/SF ships.

### Language

English

**Comment by raithos** [comment]
will be fixed within the hour
