### ISSUE TITLE
In

### ISSUE THREAD

**Issue by diablodiablo** [raithos/xwing#416]
### Expected Behavior

Be able to import lists from LaunchBay Next

{"name":"Caleb H. ","faction":"rebelalliance","version":"2.4.12","pilots":[{"ship":"t65xwing","upgrades":{"configuration":["servomotorsfoils"],"modification":["hullupgrade"]},"id":"thanekyrell","points":53},{"ship":"t65xwing","upgrades":{"configuration":["servomotorsfoils"],"modification":["hullupgrade"]},"id":"jekporkins","points":51},{"ship":"t65xwing","upgrades":{"modification":["hullupgrade"],"talent":["marksmanship"],"configuration":["servomotorsfoils"]},"id":"redsquadronveteran","points":49},{"ship":"t65xwing","upgrades":{"modification":["shieldupgrade"],"configuration":["servomotorsfoils"]},"id":"bluesquadronescort","points":47}],"points":200,"vendor":{"lbn":{"builder":"Launch Bay Next","builder_url":"https://launch-bay-next.herokuapp.com","link":"https://launch-bay-next.herokuapp.com/print?lbx='Caleb%20H.%20'.200.1.0.(33.3.(18.333).(14.297)).(33.5.(18.333).(14.297)).(33.10.(14.297).(1.239).(18.333)).(33.11.(14.299).(18.333))"}}}

M
State what you expect to happen here.

### Actual Behavior

Get error message

“(200 left) 
 It appears that you followed a broken link. No squad could be loaded! 
 A tournament legal squad must contain 2-8 ships!”

State what actually happens here.

### Language
English 
State what language translation you use.

**Comment by Patschke** [comment]
Fixed in #419, thanks for the note!
