### ISSUE TITLE
Quickbuilds of  Naboo Royal N-1 Starfighter missing

### ISSUE THREAD

**Issue by Nehekharan** [raithos/xwing#417]
Not really a bug, but missing content.

The quickbuild cards for the Naboo Royal N-1 Starfighter are missing.
They can be found here:
https://xwing-miniatures-second-edition.fandom.com/wiki/Quick_Build_/_Naboo_Royal_N-1_Starfighter

Same for the Hyena-Class Droid Bomber.
They can be found here:
https://xwing-miniatures-second-edition.fandom.com/wiki/Quick_Build_/_Hyena-class_Droid_Bomber

Thanks !

**Comment by Patschke** [comment]
Going to add them. Thanks for the note.
