### ISSUE TITLE
Galactic Republic: all Y-wing pilots have had their skills revealed

### ISSUE THREAD

**Issue by LeoTheWookiee** [raithos/xwing#418]
![image](https://user-images.githubusercontent.com/54655664/63908323-31221b00-c9f5-11e9-9bee-84b30ca48e36.png)
![image](https://user-images.githubusercontent.com/54655664/63908373-5d3d9c00-c9f5-11e9-9822-b68de2a8cab5.png)
![image](https://user-images.githubusercontent.com/54655664/63908389-6a5a8b00-c9f5-11e9-8508-470a72a05072.png)
![image](https://user-images.githubusercontent.com/54655664/63908397-70e90280-c9f5-11e9-9d29-90bfdc179a97.png)
![image](https://user-images.githubusercontent.com/54655664/63908423-7c3c2e00-c9f5-11e9-9a7d-f6728e1d6ef6.png)
![image](https://user-images.githubusercontent.com/54655664/63908439-852cff80-c9f5-11e9-80aa-9a2cc455f9c4.png)

**Comment by raithos** [comment]
Thanks, ill be looking at these this week
