### ISSUE TITLE
2.0 Scum bug with escape craft

### ISSUE THREAD

**Issue by starslinger72** [raithos/xwing#42]
## YASB 2.0 Bug Report

In the scum tab of the 2.0 builder after you add the escape craft (currently using lando pilot) The points stop updating for the whole squad.  This persists even if you remove the escape craft.

Thanks, 

Starslinger72

**Comment by raithos** [comment]
Is this still an issue. I'm unable to replicate it

**Comment by starslinger72** [comment]
Looks to be good now?  I noticed it on all factions in the last hour
though.  (Empire was messing with RAC first then added Vader pilot and it
stopped updating again)

**Comment by raithos** [comment]
ill close this for now. submit a new ticket if it comes up again.
