### ISSUE TITLE
VT-49 Decimator is not displaying all upgrades

### ISSUE THREAD

**Issue by friseb** [raithos/xwing#420]
### Expected Behavior

The VT-49 Decimator displays all possible Upgrades.

### Actual Behavior

The VT-49 Decimator is missing his Crew Slots while hovering over the base ship. They are displayed on the specific pilots though.

https://imgur.com/CjjqcYk

**Comment by Patschke** [comment]
Good catch. Will be fixed with df0138c9a2f836cc378e027f822f1ee3c8995aa3
