### ISSUE TITLE
Action filter in Cardbrowser doesn't work for all pilots with Calculate action

### ISSUE THREAD

**Issue by rune-b** [raithos/xwing#422]
### Expected Behavior

When going to Card Browser and selecting action "Calculate" under "Ships and Pilots" I expect all pilots with the calculate action listed

### Actual Behavior

Pilots like "Leebo","Chopper" and "O-66" are not shown. It seems only pilots in ships where Calculate is standard for all pilots are listed (Separatist droids and Agressor)

### Language

English

![image](https://user-images.githubusercontent.com/11047987/64080027-7beeac00-ccef-11e9-886a-7c09357a7db0.png)

**Comment by Patschke** [comment]
Yeah, it was only checking standard actions associated with the ships. Pushed a fix in e7b5f7aef933b91f98c3fd14bd2a64002870660d (part of PR #421). 

It will not add the ship itself to the search results, but will show the pilots in the list. Not sure if it is more confusing to display a ship, that has the required action only for a single pilot, or to not display it...
