### ISSUE TITLE
Angled deflectors has wrong language in ability text

### ISSUE THREAD

**Issue by rune-b** [raithos/xwing#426]
### Expected Behavior

Ability text should match selected language (English in my case)

### Actual Behavior

Ability text is shown in some other language:
![image](https://user-images.githubusercontent.com/11047987/64647815-033bce00-d41a-11e9-8731-f1ff7793bc0e.png)

I also tried switching to German but then the text was correct, in German

### Language

English

**Comment by raithos** [comment]
This should already be solved
