### ISSUE TITLE
Hyperspace ship for several factions stuck at loading

### ISSUE THREAD

**Issue by Pazmar** [raithos/xwing#436]
### Expected Behavior

When selecting hyperspace from drop down and trying to sect ship dropdown, I get the searching message on dropdown, it happens for most factions including scum and rebel. If I load an existing list first then the drop down works. 
### Actual Behavior

Ships for the Faction show be displayed that are hyperspace legal. 

### Language

English

**Comment by Pazmar** [comment]
![Screenshot_20190918-124509_Chrome](https://user-images.githubusercontent.com/22250275/65172339-51e8f980-da12-11e9-8057-758b2c223464.jpg)

**Comment by starjoe4** [comment]
I also am experiencing this bug.

**Comment by Patschke** [comment]
Oops, my bad. Broke this when adding the phantom title to hyperspace. Going to be fixed with #438 

Sorry and thanks for leaving a note!

**Comment by raithos** [comment]
push is live
