### ISSUE TITLE
Decoyed should be Limited

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#437]
### Expected Behavior

The "Decoyed" condition that comes from Naboo Handmaiden is Limited-1, and as such, should display the "Limited" dot in its title.

### Actual Behavior

The "Decoyed" condition appears to be UN-Limited, implying that multiple copies can be used on different ships.

### Language

All languages.

**Comment by Patschke** [comment]
You are right, will be part of #438

**Comment by raithos** [comment]
push is live
