### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by TimboSlic3** [raithos/xwing#439]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** I have been told from someone at FFG that the 0-0-0 and BT-1 are actually Hyperspace legal for scum as well. Don't @ me.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s). 

Hey Stevie, any chance you can upload the framework of Epic ahead of the points being released for worlds?

**Comment by raithos** [comment]
Im working on epic but doing it offline. Whenever the points are implemented and everything is revealed ill be updating that seperately
