### ISSUE TITLE
Build issues from fresh checkout

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#445]
When building a fresh install, get the following error on grunt:

Running "bower:install" (bower) task
grunt[2756]: c:\ws\src\node_contextify.cc:626: Assertion `args[1]->IsString()' failed.

Locally, this worked: 

> "Solution is delete node_modules dir and package-lock.json.
> Then run sudo npm install --unsafe-perm=true"

Don't want to submit a pull request as that updates a huge number of dependencies, issue appears to be at natives@^1.1.0

**Comment by Patschke** [comment]
I am able to reproduce this behavior on Arch-Linux, using a fresh` Node-js`/`grunt` install. Guess we run some deprecated and possible vulnerable packages for our build, so we should consider updating those anyway. 

Thanks for sharing a fix as well, that did work for me, too. I think it should be fine to update `package.json` and `package-lock.json` accordingly. I'll create a PR once the huge-ship stuff is done. 

> Running "bower:install" (bower) task
> grunt[6083]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: 0x8fa0c0 node::Abort() [grunt]
>  2: 0x8fa195  [grunt]
>  3: 0x92e5be node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [grunt]
>  4: 0xb8d2db  [grunt]
>  5: 0xb8f272 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [grunt]
>  6: 0x2dd7e0cdbe1d 
> Abgebrochen (Speicherabzug geschrieben)
>
