### ISSUE TITLE
Black font on dark border from Firefox, Light font on dark border from Chrome or iPad?

### ISSUE THREAD

**Issue by wiles01** [raithos/xwing#448]
## YASB 2.0 Bug Report

Just curious.  When I print off a list from my PC using Firefox browser, the title of the list appears as a black font on a dark gray banner.

When I print off a list from my iPad or from Chrome on PC, the banner is a white font on dark gray banner (much easier to read).

Have you heard of this situation before?  Do you know if there is a fix for the printing on Firefox or is it something isolated to my computer or something?

### Expected Behavior

Printing from PC Firefox browser, should print with the title as a white font on the dark gray background banner.

### Actual Behavior

Printing from PC Firefox browser, prints a black font on dark gray background banner.

### Language

English
![image2](https://user-images.githubusercontent.com/50473155/66716707-79737d80-ed96-11e9-87e0-f4d5e00212c3.jpeg)
![image3](https://user-images.githubusercontent.com/50473155/66716710-7d070480-ed96-11e9-90e2-37c2149f7375.jpeg)

**Comment by raithos** [comment]
So, I've researched this, and its a Firefox issue, not a YASB issue. To solve this:
In the browser menu bar, go to Firefox and select Page Setup.
On the Format & Options tab, check the “Print Background (colors & images)”
Click OK.
Print as usual.

Doing this should save the setting and it will show up correctly.
