### ISSUE TITLE
Well shit, I'm Dee Yun and I guess it's working as intended then...

### ISSUE THREAD

**Issue by MynockDee** [raithos/xwing#45]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. Unless you're Dee Yun, in which case it's wholly intentional.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
I'm sorry to hear that you're Dee Yun. Unfortunately at this time we can't do anything about that.
