### ISSUE TITLE
Typo in discord missiles

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#450]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** I have been told from someone at FFG that the 0-0-0 and BT-1 are actually Hyperspace legal for scum as well. Don't @ me.

### Expected Behavior

Discord missile spelling

...you and that ship each suffere 1....

### Actual Behavior

...you and that ship each suffere 1  damage.

### Language

English

**Comment by Patschke** [comment]
I can't see the difference. Of course, our way to display a remote is pretty ugly, as it has no proper way to show Hull and Agility - but apart from that the text should be fine?

![grafik](https://user-images.githubusercontent.com/17853362/67681870-78de0800-f98e-11e9-80b8-345e1ba72263.png)

![grafik](https://user-images.githubusercontent.com/17853362/67681908-87c4ba80-f98e-11e9-9310-93c543cfbb39.png)

**Comment by chrisalleng** [comment]
It's a type in the last  sentence in the middle:
"... you and that ship each suffer**e** one <hit> damage, should be "suffer"

**Comment by raithos** [comment]
fixed, will be uploaded soon
