### ISSUE TITLE
R5-X3 not labelled unique/limited

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#452]
### Expected Behavior

Only one copy of R5-X3 should be legal in a squad

### Actual Behavior

No limit to R5-X3, example squad: https://raithos.github.io/?f=Resistance&d=v8ZsZ200Z258X205WW175WWWY258X205WW175WWW&sn=Unnamed%20Squadron&obs=

### Language

Glorious American

**Comment by Patschke** [comment]
Thanks for the report, will be fixed with #443
