### ISSUE TITLE
Nien Nunb Rebel crew should reduce difficulty of 0-bank maneuvers on Epic ships

### ISSUE THREAD

**Issue by Apollonaut13** [raithos/xwing#456]
### Expected Behavior

Nien Nunb Crew (Rebel) equipped to an Epic ship with red 0-bank maneuvers should reduce the difficulties to white.

### Actual Behavior

0-bank maneuvers in the maneuver grid are so far visually unaffected by Nien crew,

**Comment by raithos** [comment]
will be fixed shortly
