### ISSUE TITLE
Initiative Indicator by Pilot Name

### ISSUE THREAD

**Issue by jimonarrez** [raithos/xwing#458]
### Initiative Indicator

It could be helpful to have the Initiative listed next to the pilot name in the drop down menu. It would make comparing Initiatives easier by viewing them at a glance rather than having to hover over each pilot name to get the sidebar to display it.

**Comment by LordVorKon** [comment]
This feature already exists.  At the top right of the page, in the blue bar with "Print/View", etc, there is an arrow button.  Under that menu, in "Misc Settings", you can select to "Put INI as prefix..."
