### ISSUE TITLE
Random squad generator creates illegal lists

### ISSUE THREAD

**Issue by balindamood** [raithos/xwing#460]
Not sure how this happened:

![Untitled-1](https://user-images.githubusercontent.com/57555735/68524503-3bbe2380-0274-11ea-8fd8-577d8afa263a.jpg)

Just and FYI

**Comment by raithos** [comment]
I think the randomizer doesn't consider disabled slots in its algorithm. I'll look into it but its probably something we cant fix very easily

**Comment by Patschke** [comment]
It should be easily fixable - just don't add occupied slots to the upgrade list.
