### ISSUE TITLE
Request: Print Fancy Layout in Landscape

### ISSUE THREAD

**Issue by SharpEdgeSoda** [raithos/xwing#461]
An odd request maybe, purely for QOL, but I discovered as I have pages of YASB printouts in a binder now, that if I could print them in landscape I could just lay my binder on the table sideways and be able to more easily read and use tokens on my print out while taking up a more reasonable amount of table space in some cases.

![yasb fancy landscape suggestion](https://user-images.githubusercontent.com/53732107/68538844-6d042580-0340-11ea-8501-518b926ab298.png)

I've done a very basic quick mock up of how a Fancy Layout could look in landscape.  
2 Columns for upgrades is entirely optional and probably not worth the additional complexity, but it may ease usability for casual use when you put charge tokens on the like on the list. 

Edit: Please tell me if I'm dumb and there's a way to print landscape that I'm just missing it and wasting your time. I tried with the system printing and it just didn't work.

**Comment by Patschke** [comment]
I am free to select the orientation I want. Special landscape-features like two columns side by side are not implemented, so I personally simply print two pages on one page - but that will of course also half the font size. 

![grafik](https://user-images.githubusercontent.com/17853362/68542903-01a66c00-03b1-11ea-9435-e2dd36e97da4.png)
[printout.pdf](https://github.com/raithos/xwing/files/3828340/tmp2.pdf)

**Comment by SharpEdgeSoda** [comment]
Ah, the problem seems to be with Chrome. Chrome's print dialog decides to remove the Layout options when you print out something it sees as a PDF. 

Chrome removing landscape. Advanced options provide nothing.
![chrome no landscape](https://user-images.githubusercontent.com/53732107/68546822-8210a100-03a0-11ea-8290-48d60ec45373.PNG)

Chrome allowing landscape printing on another site.
![chrome landscape](https://user-images.githubusercontent.com/53732107/68546834-9e144280-03a0-11ea-8f86-94e63a1f74e3.PNG)


Windows Print Dialog straight up doesn't work when you select landscape, it will print a PDF sideways, which is just still portrait.


Hilariously, Microsoft Edge allows landscape and gives me my desired results more or less. 
![Edge landscape](https://user-images.githubusercontent.com/53732107/68546846-bd12d480-03a0-11ea-9162-4140149c035a.PNG)

I can solve the problem by using other browsers, so I'll consider the issue closed, but I don't know if you want to look into why Google Chrome refuses to let your users print in landscape.

**Comment by Patschke** [comment]
Apparently there are some CSS settings that would provide an orientation for printing. As this setting might be ignored by some browsers, it would be confusing to include a landscape checkbox, if one is using a browser that ignores the corresponding css. We'd therefore need to add a check which browser one is using, to decide whether we need to display a orientation checkbox or the browser is able to handle that on its own. 

I am not sure if I want to do that, as it sounds like more work than what it is worth - especially as long, as there is no "real" landscape support that would arrange stuff intelligent depending on the choosen orientation...

**Comment by raithos** [comment]
I think i fixed it.
https://puu.sh/EHea8/755cf1d31b.png

Confirm on your end?

**Comment by SharpEdgeSoda** [comment]
> I think i fixed it.
> https://puu.sh/EHea8/755cf1d31b.png
> 
> Confirm on your end?

Beautiful! Looks great. Thanks for looking into this you legend.
