### ISSUE TITLE
Wing / Huge ship quick builds

### ISSUE THREAD

**Issue by therealppa** [raithos/xwing#464]
It would be nice to have the huge ship and wing quick builds available either in Quickbuild mode or maybe in a separate "Epic Quickbuild" mode.

**Comment by Patschke** [comment]
I've been a bit lazy in adding quickbuilds at all lately. If you feel like you want to help us by crunching in some quickbuild data you are welcome to do so ;-)

**Comment by therealppa** [comment]
@Patschke I'll see if I can help out :) Should I add it in xwing-data2? https://github.com/guidokessels/xwing-data2/tree/master/data/quick-builds - if not, where is the correct file?

**Comment by Patschke** [comment]
We've never actually included any external database, all Quickbuilds are found in yasb in https://github.com/raithos/xwing/blob/master/coffeescripts/cards-common.coffee from line 11000 - 15400.

**Comment by raithos** [comment]
Oh, this is going to be more complicated than I thought. Wings are variable cost based on how many ships you add, and they dont use the same scale for points that normal quickbuilds use. hmm. :/

**Comment by Patschke** [comment]
As we got multiple requests for that by now, I'll try to find some time to implement it...

**Comment by Patschke** [comment]
I've completed the code to handle wings now, so it's just a matter of crunching in the data.

**Comment by therealppa** [comment]
This is really cool, thank you so much! One thing I notice is that the Kylo wing quick build doesn't show up in the dropdown for the TIE/vn...
