### ISSUE TITLE
Folders for lists

### ISSUE THREAD

**Issue by ChaosHat** [raithos/xwing#465]
With the release of Epic and multiple point levels or match types (Aces High) would be nice to be able to sort or organize with some user created folders. Epic 500 pts, Epic 300 pts, etc.

Thanks!

**Comment by raithos** [comment]
This will probably not happen. User generated folders would require updating and saving new profile info to the yasb backend, but that is controlled by geordan and would not be easily developable. Doing prebuilt folders would be possible but since there are so many options I don't think its a good idea to implement.

**Comment by ChaosHat** [comment]
What about just making epic lists only visible when the squad builder is
set to epic format?

**Comment by Patschke** [comment]
> This will probably not happen. User generated folders would require updating and saving new profile info to the yasb backend, but that is controlled by geordan and would not be easily developable. Doing prebuilt folders would be possible but since there are so many options I don't think its a good idea to implement.

Actually afaik we are basically able to store arbitrary data in additional_data - so adding a folder structure in there should be quite doable without any changes to the backend...

**Comment by raithos** [comment]
Ah so you're suggesting we store the folder info in the list directly? So then we would be creating more like filter tabs based on all of the tabs we find.. ok, thats different than what i was thinking but should work

**Comment by Patschke** [comment]
It should work for filter tabs as well as for folder like structures. We could either add a "path" variable to the list, which would allow it to be presented in a folder like way. We could also add a "tags" variable to the list, which contains a list of user defined tags and allow filtering for those, which would result in a filter tab like solution.

**Comment by XPav** [comment]
This type of solution could also answer #570

**Comment by raithos** [comment]
Ok a tag system is in. This is about as far as I want to go with this. There may be some bugs but it does work.
