### ISSUE TITLE
Epic Bug

### ISSUE THREAD

**Issue by Remketh** [raithos/xwing#469]
### Expected Behavior

On the Iphone Safari
click drop down for  hardpoint, select turbolaser adds points

### Actual Behavior

unable to select tubolaser battery, other options available

### Language
Iphone X  web access, safari

**Comment by Patschke** [comment]
Unfortunately I can't test this, so I can not reproduce this bug or try to find a reason for it. I am able to add turbolasers just fine on my computer... 

Are you able to give us any information like error logs?

**Comment by raithos** [comment]
Are you using a any ship that doesn't have enough energy? Turbolasers require 5 or more energy to be used, it wont show on the list

**Comment by raithos** [comment]
I haven't heard back so I'm closing this until a response is given
