### ISSUE TITLE
Sheathipeade Ezra incorrect ship ability

### ISSUE THREAD

**Issue by thomedwards** [raithos/xwing#47]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. Unless you're Dee Yun, in which case it's wholly intentional.

### Expected Behavior

Ezra Bridger on the Sheathipeade shows Comm Shuttle as the ship ability. 

### Actual Behavior

Ezra Bridger on the Sheathipeade shows Locked and Loaded as the ship ability. 

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
got it
