### ISSUE TITLE
Card browser - cards in collection count issue

### ISSUE THREAD

**Issue by molotov681** [raithos/xwing#470]
### Expected Behavior

In card browser, card count in collection should accurately reflect count based on collection in card browser.

### Actual Behavior

Search for cards based on keyword, examples 'darth' or 'flip'.

In card browser, system indicates 'you have 0 in your collection' when if fact that is not true, and not reflected in inventory or deck building pages.

Also note that color coding is correct (grey for in collection and red for not in collection) but the count does not reflect this accurately.

Appears to be isolated to certain areas and not others. Noted specifically in crew upgrades and configuration upgrade but specifically not an issue in pilot, as a few examples. You will have to check all categories for this issue.
### Language

The affected language(s). 

Found in English, not sure on others.

**Comment by Patschke** [comment]
Thanks for the note. Will be fixed with #474
