### ISSUE TITLE
point capacity is editable but ignored

### ISSUE THREAD

**Issue by molotov681** [raithos/xwing#471]
### Expected Behavior

edit total points on squad building page, hit random, get a new random squad up to the newly entered point total value

### Actual Behavior

on squad building page, points x/200, the '200' is editable, but is ignored when 'random' is selected. One must go into random settings to adjust the points used for random generation.

Either the field should not be editable, indicating that the setting is found elsewhere, or it should use the value entered by the user.

### Language

English

**Comment by Patschke** [comment]
Yeah, you are probably right on this one. Going to simply remove the field from the random generator, and use the selected points instead. Those point fields developed independently from each other...

**Comment by molotov681** [comment]
Also note that when switching to quick build the 200 carries over and it tries to generate 200 ships. Suggest a lower default value when switching to quick build, like 8.

**Comment by Patschke** [comment]
It will just use whichever value is set on the main page.
