### ISSUE TITLE
Feature request - allow for random to be limited to cards in collection

### ISSUE THREAD

**Issue by molotov681** [raithos/xwing#472]
### Expected Behavior

hit random, get a random squad using only cards that are in my collection

### Actual Behavior

random cards are drawn from all sets. I understand that you can go into random settings and select individual sets to restrict card selection, but this is cumbersome, and it is desirable for there to be a check box to restrict random to select from only cards in collection. This would be great! And should be doable given the logic everywhere else indicating what cards are/not in collection.

I would suggest that this be default behavior, and that one should have to go into settings and uncheck this setting to have it generate random from all sets including cards not in ones collection, as I imagine that most people want squads generated using cards they have.

Also note that randomizer settings appear to be unique to each faction tab, but with this setting it should carry over into all faction tabs by default, unless this setting is unchecked and the user wants to limit randomization to a specific expansions.

### Language

English

**Comment by Patschke** [comment]
Sounds good, will add that feature.

**Comment by molotov681** [comment]
That would be great! Thanks. A few more points I thought of. Random would have to use all cards if no collection is defined. Also I noted that even when I restrict the expansions used, random will still potentially build collections I cannot field, by using ships I do not have in my collection. Suggest random restrict to cards AND ships in collection only. 

Thanks again for this wonderful tool!  Great job.
