### ISSUE TITLE
left  bid to stop randomizing is ignored

### ISSUE THREAD

**Issue by molotov681** [raithos/xwing#473]
### Expected Behavior

'left bid to stop randomizing' value should be subtracted from total points and randomizer should not generate a squad with more points than 'max - bid'

### Actual Behavior

randomizer generates a squad with a max point value somewhere near the max value, sometimes at max value, apparently ignoring the 'left bid' value

suggest removing this feature, as one can specify a max value of, e.g. 195 instead of 200 points to get a 5 point bid

if feature remains after fix, suggest renaming or adding an info popup/bubble icon since it took me days to figure out what this feature meant.

### Language

English

**Comment by Patschke** [comment]
Uhm, no. That is simply not how this feature works. If you want to have a max of 195 points, simply set the max to 195 points. The max bid sets a lower bound: If max bid is 10 points, the randomizer will aim for 190-200 points. If you set it to 5 points, it will aim for 195-200 points. Therefore the name seemed appropriate to me - it is the actual maximal bid the randomizer aims for. 

If you have a suggestion on how to rename that feature, or make it clearer, that would of course be very welcome. It was (and still) is the best name I came up with, but I am happy to change it to an even better one.

**Comment by Patschke** [comment]
Oh, I see. I did not name it max bid. Maybe that would be the better name? :D

**Comment by molotov681** [comment]
That would good. Perhaps something along the lines of 'max random bid amount'.
