### ISSUE TITLE
Support for multi-squad randomisation 

### ISSUE THREAD

**Issue by Widzy5** [raithos/xwing#478]
I’m the only person out of my friends who collects X-Wing.  We use only my collection when we play.

We want to create a random 200 v 200 point match up each time we play using only the cards from my collection.  

All I can do right now is generate a random squad for each faction individually, the trouble with this is both squads will often choose the same upgrade cards, but I don’t have enough of these cards to dish out to both squads.  

It would be great if the random squad builder could be done for multiple factions at once. 

Ideally It wouldn’t generate an entire faction in one go before moving on to the next faction, because that means the first faction that is generated will always have first choice of all the upgrade cards that I only have 1 copy of - it’d be much better if each faction took it in turns to add ships/upgrades, so there is a better chance of my upgrade cards being evenly distributed between the two squads.

**Comment by raithos** [comment]
At this time we have no plans to do this. Multi-faction lists are both unsupported by FFG and would require a huge rework to how we implement the card sorting in the builder. Sorry about that, but thank you for your feedback!

**Comment by Widzy5** [comment]
ah that's disappointing :(  I don't suppose there's a simpler solution that's not quite as complex as the one i suggested?  

If I randomly generate a rebel squad, then click the galactic empire icon and randomly generate a squad for them too, I can then switch between these two randomly generated squads by clicking the rebel/galactic empire buttons - i.e. it's caching the results of those squads somewhere and reloading them when you click the icon.

The code that works out how many of each card is remaining in your factions currently only takes the current faction's used cards into consideration... would it not be possible for that to include all cached factions?
