### ISSUE TITLE
When printing in black and white, add text or symbol to signify a Red action

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#479]
I have a black and white printer.   After I print something from YASB, I have to go and manually mark various actions as red.

It would be great if text like (RED) was placed next to those actions.

**Comment by raithos** [comment]
Will look into this. I'm still working on a good layout for red actions in black and white printing. Alternatively we could make the text white with black borders which would make it really obvious

**Comment by raithos** [comment]
Ive done that so it should be very obvious when printing in black and white which actions are red.
