### ISSUE TITLE
Rader-Class Corvette Crew Upgrade missing

### ISSUE THREAD

**Issue by zachydoo** [raithos/xwing#480]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** When switching between Epic and other formats, the Command upgrades stay on the ships, though no new upgrades are selectable. Please note that in your list building, I am aware and working on a fix for that issue.

### Expected Behavior

The crew upgrade should have a dropdown of every crew available to this ship

### Actual Behavior

There is a grey box for where the crew upgrade should be, but it does not respond to clicking.

### Language

The affected language(s).

**Comment by raithos** [comment]
Did you have a command in the slot? Epic ship command upgrades also consume the crew slot in case you weren't aware.

**Comment by raithos** [comment]
Closing this due to lack of response. If I hear back I can reopen it.

**Comment by zachydoo** [comment]
Yeah you got it right, I was an absolute dingus!👌🏻
