### ISSUE TITLE
Enforcing Tournament Format Selection

### ISSUE THREAD

**Issue by mojavejoe** [raithos/xwing#483]
## YASB 2.0 Bug Report

First, congratulations on being the author of the go-to list builder for xwing!

The issue I describe seems only to apply to the mobile app.

### Expected Behavior

After creating a list and saving it as Extended, when I return to the list and change the tournament format from Extended to Hyperspace, I expected the selected format requirements to be enforced. Enforcement could include a notification to the user which elements are not [selected format] legal by highlighting in red or simple text notification.

### Actual Behavior

After creating a list and saving it, when I return to the list and change the tournament format from Extended to Hyperspace, a Hyperspace non-legal list will be labelled as Hyperspace as requested even if elements of the list are not Hyperspace legal and there is no indication of conflict. In this case, I can make any number of non-Hyperspace legal lists in Extended mode, save them, then go back into each list and change their format to Hyperspace and never know they're not legal. As a player who is not familiar enough with what ships/upgrades are legal/illegal in any given format, I am easily confused. :)

### Language

I only use the app in English.

**Comment by raithos** [comment]
When you change from Extended to hyperspace, any non-legal cards are automatically removed from the list. Are you saying that this is not happening? If so I am not able to replicate the error.

**Comment by mojavejoe** [comment]
Yes. I’m using the mobile app on an android device.

 

Steps to recreate:

1.       Create new Empire list with Extended as default format.

2.       Add TIE Phantom – Whisper (no upgrades)

3.       Add Lambda shuttle - Captain Kagi (no upgrades)

4.       Add Adv. TIE x1 - Darth Vader (no upgrades)

5.       Name list “Test”

6.       Navigate back to main menu of lists

7.       Open “Test” list

8.       Change format to Hyperspace.

 

It is my understanding that the TIE Phantom is not Hyperspace legal, but the Phantom is still in the list with no indication of the conflict. Exiting the list and re-opening behaves the same way.

 

Hope this helps.

 

Joe

**Comment by raithos** [comment]
Following your instructions, every time I change the format to Hyperspace, it removes both Whisper and Kagi. Those changes will not stay with the list until you press save, so if you're reloading the list, it will remain extended until you save after changing the format.

**Comment by mojavejoe** [comment]
Are you testing the moblie app? Using the app in a browser (where there are save/load buttons) works fine for me. What I’m describing only happens in the mobile version (where saving/updating seems evoked on navigation, not on an explicit save button). 

 

Joe

**Comment by raithos** [comment]
Yes I'm testing on mobile. There is no functional distinction between mobile and desktop, they run off of the same code

**Comment by mojavejoe** [comment]
I assumed they ran off the same code. The visible difference is there are no SAVE buttons on the mobile version so it’s possible there is a difference in execution path for saving/enforcing format requirements.

 

Here’s a screenshot just so I can assure you I’m not hallucinating. :)

 

Joe

**Comment by Patschke** [comment]
I guess you need to post it directly on github to attach screenshots - at least I can't see them with this mail reply.

**Comment by mojavejoe** [comment]
I’ll try it…

**Comment by raithos** [comment]
![Screenshot_20191209-162516](https://user-images.githubusercontent.com/25230261/70474486-b3b08100-1aa0-11ea-8c23-34ae0e87c83c.png)

Btw. That's off my phone

**Comment by raithos** [comment]
Also the save button will now show up if youre not logged in. That's the only situation I can think of that would cause it to not show.

**Comment by Patschke** [comment]
> 
> 
> Following your instructions, every time I change the format to Hyperspace, it removes both Whisper and Kagi. Those changes will not stay with the list until you press save, so if you're reloading the list, it will remain extended until you save after changing the format.

same for me - all not hyperspace legal ships are removed as expected.

**Comment by Patschke** [comment]
@mojavejoe just to give you the reason why this is closed: The app you mention is LaunchBayNext - which is not related to YASB. Sorry, we can't help you here...
