### ISSUE TITLE
Rebel Squad mistakes

### ISSUE THREAD

**Issue by LeoTheWookiee** [raithos/xwing#485]
Hello! Your squad builder is awesome!

I noticed some minor errors in the Rebel ships.
On the text bar on the right side, The Sheathipede appears to have a "Focus" upgraden and a Calculate upgrade, when it should have an Astromech upgrade instead. 

On the text bar on the right side, the VCX Ghost should have a Reinforce action, not an Ilicit.

When searching for ships, the VCX appears to have the figure of an Attack Shuttle instead of a VCX.

The rebel Tie Fighter appears to have a Rotate Arc and Talent action instead of a Barrel Role and Evade.

Thank you!

**Comment by raithos** [comment]
are you using microsoft edge?

**Comment by LeoTheWookiee** [comment]
Indeed, At work it's all i have available

Em seg, 16 de dez de 2019 14:23, raith <notifications@github.com> escreveu:

**Comment by raithos** [comment]
So that's a known issue. Fonts dont work properly on microsoft edge, but there's nothing I can do about it as the issue is the font itself. Know that wherever the font is wrong, it will show up properly on chrome and firefox.
