### ISSUE TITLE
Echo Base Evacuees missing?

### ISSUE THREAD

**Issue by squaduser** [raithos/xwing#486]
### Expected Behavior

In Epic builder rules for Rebels, the GR-75 "Echo Base Evacuees" appears to be missing.

### Actual Behavior

GR-75 is not available as a selection in Rebel Epic builder.

### Language

English.

**Comment by raithos** [comment]
It appears for me, are you sure your mode is set to Epic and not Extended?

**Comment by squaduser** [comment]
Yes - from Chrome on Mac. Not list for Rebel, but listed for Resistance:



Checked on my iPad and on Chrome, none of the Huge ships are showing for Rebel, but the GR-75 shows for Resistance and the other factions look correct too.
Let me know if I can give you other feedback.
Thanks,Steve
    On Monday, December 23, 2019, 05:23:43 PM EST, raith <notifications@github.com> wrote:  
 
 
It appears for me, are you sure your mode is set to Epic and not Extended?

**Comment by raithos** [comment]
I don't know if I can help without more information. I've had several people check on different platforms and they all can add it fine. Is there anything else you can provide that's unique about your setup?

**Comment by squaduser** [comment]
So I was just about to send the sentences below and I checked Chrome once more on my Macbook and now it is there. Browser cache maybe? Weird. I have no idea what made it finally show up.
What should I look for? Same issue on Chrome, Firefox, and Safari. Logged in or logged out. I'm running Catalina 10.15.2 on my Macbook. iPad showing the same thing on Chrome and Safari. Nobody else on iOS running into this?
Chrome on my PC running Windows 10 is fine - I can see the GR-75 in Rebel. I get how tough this can be, but if there is anything else I can do to help figure it out, I'm willing. When I need to use that ship in epic, I'll just use my PC, but I usually use my iPad at the table.
 

    On Monday, December 30, 2019, 07:30:16 PM EST, raith <notifications@github.com> wrote:  
 
 
I don't know if I can help without more information. I've had several people check on different platforms and they all can add it fine. Is there anything else you can provide that's unique about your setup?

**Comment by raithos** [comment]
Cache is the most likely culprit based on what you stated. I would go into your phone settings and clear your cache and see if that does it. As for our end, with everyone I've checked with that has an apple product has indicated to me that it works as normal. I'm going to close this for the time being, if we find more information that requires a change to the code, I will reopen this issue
