### ISSUE TITLE
Upgrades show up in random when not in collection

### ISSUE THREAD

**Issue by Widzy5** [raithos/xwing#487]
I don’t have stabilised S foils listed in my collection, yet if I try to generate a random large squad of 400 points using only my collection, my b-wing is always added, and it always adds stabilised s foils to it... for a whopping 200 extra points!

It does this every single time I randomly generate.  It’s always the only thing that is added to my randomly generated squad that doesn’t exist in my collection, plus it’s points cost seems ridiculous, so I’m guessing there must be some bug going on here regarding this particular upgrade card?

**Comment by raithos** [comment]
I have confirmed the bug. it doesn't always trigger. It probably has something to do with how we assign upgrades in randomizer and the check on collections, but I would have look into it more

**Comment by Widzy5** [comment]
just to update this, I've noticed it's also doing it for 'Passive Sensors'.  I don't have any passive sensor cards (i actually have no sensor cards whatsoever), yet passive sensors is being assigned to sometimes multiple ships during randomisation

**Comment by raithos** [comment]
This is a different issue now

**Comment by Patschke** [comment]
going to fix that.

**Comment by Patschke** [comment]
Should be fixed with #506 as it turned out to be a fairly easy bug. There was a check that no upgrade is selected for a given slot, if the list of available ones is empty - but not selecting anything just meant that the upgrade that has been checked last was used, as the for loop for the checks used the same variable name. Explicitly unsetting the variable in case of the empty list solved it.

**Comment by Widzy5** [comment]
Just tested this - so much better, thanks!

I’ve just spotted one remaining edge case from my testing of this that’s still causing the same type of bug:

If the randomiser uses up all of the upgrades I have for a particular type of upgrade, then the same thing happens again - it starts picking upgrade cards that I don’t have.

For example, if I have just one missile upgrade in my entire selection, and the randomiser picks two ships with missiles, the one ship is correctly assigned missiles, but then the other ship is incorrectly assigned missiles too (even though the option for it is now coloured red if you tried to add the 2nd lot of missiles manually)
