### ISSUE TITLE
Track ship dials for random list builder.

### ISSUE THREAD

**Issue by ChobitsCrazy** [raithos/xwing#490]
Wanted to see if it was possible to implement the option to track what ship dials you have to determine what options you have while building a randomized list.

This is the example situation I have:
I own the Rebel conversion kit that comes with multiple dials for Rebels on the ARC-170 however I only own one of the ship so the other dial is not used. However I have just picked up the resistance ARC-170 and found that I can use this in addition to the current one so I can use both dials. However if I have two of the ship it also will be picked up that I have two of the ship for Resistance however I only have the one ship dial for it so I cannot have two of the ship since I do not have two dials.

Amazing work on this squad builder! Thanks for the hard work so us nerds can spend more time playing the game!

**Comment by Patschke** [comment]
It should be possible to change your collection accordingly. You may seperately specify number of ships (and not only number of expansions)
