### ISSUE TITLE
Quickbuild Iden with Proton Torpedo missing Lock action on bar

### ISSUE THREAD

**Issue by dbldown11** [raithos/xwing#493]
### Expected Behavior

The card that Iden Versio's quickbuild with Proton Torpedo and Lone Wolf is printed on adds the Lock action to her action bar. However, in YASB, she does not get the TL action added to her bar.

https://vignette.wikia.nocookie.net/xwing-miniatures-second-edition/images/d/d0/Iden_versio_eqb.png/revision/latest?cb=20190120070608 (note the TL icon in the bottom right)

### Actual Behavior

In YASB, ProTorp Iden doesn't get a Lock. She therefore never gets to shoot her torpedo and feels empty and unfulfilled.

### Language

English

**Comment by therealppa** [comment]
Maybe this could be fixed in a simple way by adding a "Targeting Computer" to the quick build

**Comment by Patschke** [comment]
That sounds like a good idea, I'll do that. 

In case FFG continues modifying Quick Builds without using existing cards, I'll have to come up with a way to actually implement that at some point.

**Comment by Patschke** [comment]
Note that this fix will not display the Lock icon while hovering over the pilot in the pilot selection, but will put it on the print out.
