### ISSUE TITLE
Hyperspace non legal pilots shown in Hyperspace format

### ISSUE THREAD

**Issue by scanham** [raithos/xwing#494]
### Expected Behavior

When in hyperspace format I expect non hyperspace legal pilots to be filtered.

### Actual Behavior

I see all pilots listed, hyperspace legal and not. For example - Republic ARC-170 still shows the 104th Battalion Pilot and the Rebel T-65 still shows Wedge and Biggs. 

### Language

English

**Comment by raithos** [comment]
This is resolved. I was fixing another issue regarding hyperspace and accidentally caused this.

**Comment by scanham** [comment]
Thanks!
