### ISSUE TITLE
issue with format and lists

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#495]
### Expected Behavior

List get loaded with pilots/ship or even upgrades which are not appropiate for the format (HS/EXT), red highlighted for instance...

### Actual Behavior

List get loaded but those not legal elements are not loaded, so I cannot recognise which list it was since things are missing.
This result in loading saved squads and then empty squad is shown or missing upgrades or pilots (this means my list/squad is lost... ). If know what is wront I can fix the list to fit the new format requirements.

**Comment by raithos** [comment]
Is this for hyperspace?

**Comment by negroscuro** [comment]
HS squads get "deleted" once you load them since several things are not legal now on HS.
Answer is yes, but could happen in the opposite way as well.

**Comment by raithos** [comment]
Ok cool. So I can't do anything about the deleting of ships when in hyperspace because lots of people rely on this for printouts for tournaments. What I can do, is that the old version of the builder can be accessible for a limited time so you can convert your old hyperspace lists to extended and resave them if you wish to preserve them. thats available at https://raithos.github.io/old

**Comment by negroscuro** [comment]
That is nice but for some reason I cannot load squads from this:
https://raithos.github.io/old
Popup opens ans says loading but it does not load...

**Comment by raithos** [comment]
Go into the current builder and delete all the undefined lists you made. You should be able to load the lists in the old builder now

**Comment by negroscuro** [comment]
undefined? you mean squads not valid for new points adjustment in january 2020?
the idea is to be able to load squads not valid to not lose them and try to adapt them to the new point costs.

**Comment by raithos** [comment]
No any new lists made in the last day we're bugged and were undefined so just open your saved lists and browse through them in the new builder and delete them

**Comment by negroscuro** [comment]
Ah ok now i noticed them. Thank you, now it is working as you pointed.
