### ISSUE TITLE
We need a button for Patreon donations

### ISSUE THREAD

**Issue by eloc95** [raithos/xwing#496]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
I don't actually have a patreon. is providing monthly support really important?

**Comment by eloc95** [comment]
It's just something that most of the community uses and you're so fantastic at keeping things updated I (and plenty of other people) wouldn't mind tossing you even a small donation as a thank you. Even if most people only give 1-5 dollars a month it could compensate you for your time spent on it.
________________________________

**Comment by alberttwong** [comment]
github also has a sponsor feature.

**Comment by raithos** [comment]
@alberttwong that is basically the same as the donate button on the site itself. I'd still have to link it to a payment option which is in this case paypal. 

I think at this time we're not going to create a patreon. Let's say things get more intense and I'm spending lots of time on this then maybe, but I just don't think its something thats necessary. If you feel you want to donate, u can do so via the paypal link.
