### ISSUE TITLE
Ronith Blario (RZ-2 A-Wing, Resistance) appear twice in list

### ISSUE THREAD

**Issue by peterkejser** [raithos/xwing#497]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.

### Expected Behavior

Ronith Blario should only appear on the list once, with correct point value.

### Actual Behavior

Ronith Blario appears twice, once with correct point value, the other time at a cost of 200.
![Ronith Blario](https://user-images.githubusercontent.com/14195245/72142119-5310ae80-3394-11ea-9495-5cdc58ebfa96.png)

### Language

The affected language(s).

**Comment by raithos** [comment]
will be updated soon
