### ISSUE TITLE
FO - Silencer - Rush

### ISSUE THREAD

**Issue by Siopnos** [raithos/xwing#498]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.

### Expected Behavior

Rush should have "Autothrusters" instead of "Heavy Weapon turret"

### Actual Behavior

Rush has the same ship ability ("Heavy Weapon turret") as TIE/SF

### Language

English

**Comment by raithos** [comment]
will be updated soon
