### ISSUE TITLE
Rush - Ship Ability

### ISSUE THREAD

**Issue by XW-J** [raithos/xwing#499]
![Screen Shot 2020-01-10 at 12 45 39](https://user-images.githubusercontent.com/59733870/72154265-1d75c080-33a8-11ea-8fb2-fb8dfa3b747d.png)

The new "Rush" ship ability should be Autothrusters but is currently showing as a Heavy Weapon Turret.

Thanks for all your hard work. 
Jason

**Comment by raithos** [comment]
will be updated soon
