### ISSUE TITLE
After points changes, saved lists show old point totals until re-saved

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#501]
### Expected Behavior

When I go to "load list" I expect the drop-down to show the correct point totals of the lists I have saved, even if the official points values for ships and upgrades have changed since I last visited the list.

### Actual Behavior

The total points for the lists are the values as they were when the list was last saved, and do not get re-calculated until the list is saved again. This is true even if the list is opened, but not saved. When a list is opened, the main page shows the updated point total but the saved list still shows the old point value. The list can not be saved without the user making a change, and the new point total will not be saved unless the list is re-saved. 

### Language

US English

**Comment by Patschke** [comment]
As yasb is made of java-script, it operates almost entirely client-side. The lists are only stored server side, but there is no processing done at all by the server side. So to show updated information in the list overview, your browser would need to do that update. This would result in your browser always loading all lists you have, check if they are still legal, and update points - every time you open yasb. As people might have dozends of lists, this would be incredibly slow. Therfore, we are not going to do this. 

There is however the "reload all lists" button, that will trigger excatly this. Simply hit it once after each point update, and you are ready to go.

**Comment by Gdsimms** [comment]
Ah, I see. I was unaware of the behavior of "reload all lists," and I will use that as necessary. Thank you!

**Comment by Patschke** [comment]
Any suggestion on how to make the behaviour easier to understand, or on a place where this should be explained, is, of course, welcome. I can see that this is not intuitive, but am unable to find a better solution myself...
