### ISSUE TITLE
Hyperspace verification

### ISSUE THREAD

**Issue by Nightsyded** [raithos/xwing#505]
Hey guys, I'd like to suggest a feature for future tournaments to kind of make things easier on the TO's and other players.  
Print on the list somewhere that it is a current hyperspace list.  To make things easier you can just title how it was made ie hyperspace, extended or epic for ALL lists.  
The reason I think this feature is important now more than ever is because Hyperspace is a damn mess of ships that are in and out based on pilot name alone.  I am  sure some people are going to show up to hyperspace tournaments with the wrong list, and it would be easier for everyone if your site could just say what category the list was made in.  

THanks!

**Comment by raithos** [comment]
all lists that are printed on pdf or paper has the current version of the points listed under the notes section

**Comment by Patschke** [comment]
I think the request is not about the point version, but a statement that this list was created in hyperspace mode/extended mode. I received this request a while ago (probably from somebody else), and forgot about it.

**Comment by Nightsyded** [comment]
Yes exactly this. Would love to see that.

**Comment by raithos** [comment]
Not sure what I wanted to do so for now, I'm adding an icon to the title when the list is hyperspace (and also an icon for when its energy). It's pretty easy to notice, but not such a big deal that people are going to get distracted by it.
