### ISSUE TITLE
Veteran Tail Gunner sources error

### ISSUE THREAD

**Issue by chatsubo** [raithos/xwing#507]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

In *Sources* for the upgrade card *Veteran Tail Gunner*, the Arc 170 Expansion should be listed. People who have that expansion as part of their collection should have a copy of this upgrade added to their inventory.

https://xwing-miniatures-second-edition.fandom.com/wiki/Veteran_Tail_Gunner

### Actual Behavior

The Arc 170 expansion is not considered a 'source' for this upgrade card and therefore people who own this expansion have fewer copies available for list building than they should.

### Language

English

**Comment by raithos** [comment]
ok will go up shortly
