### ISSUE TITLE
Unable to gets points to refresh Chrome/iPad

### ISSUE THREAD

**Issue by squaduser** [raithos/xwing#509]
## YASB 2.0 Bug Report
Have cleared cache multiple times and even deleted and reinstalled Chrome. Same squad loads with correct points on laptop, but point updates with not refresh on iPad. Strategic Commander and Dreadnought Hunter remain 6 points instead of 10. 

### Expected Behavior

Cache clear, log out, reload all squads - something should cause the points metadata to refresh. 

### Actual Behavior

Old points remain

### Language

English

**Comment by raithos** [comment]
thats really weird. Only on ipad? your phone is also correct?

**Comment by squaduser** [comment]
I had never opened this on my phone before. I didn’t log in, just set to Epic and checked points. This is what it shows (Safari on iPhone): 
Definitely weird. Trying to understand how it works - seems like the points should be metadata loading with the page. I could understand it being cached, but not how it doesn’t clear when the cache is cleared. Truly bizarre.

**Comment by raithos** [comment]
If you're replying by email, pictures do not show up, you have to go to the github page to attach an image

**Comment by squaduser** [comment]
﻿
Sorry - the strategic commander card is 6 on my iPhone too.

**Comment by raithos** [comment]
I should have checked this first. The prices at 6 points are correct for both cards. They were adjusted in the recent points update. If you want to build using the old points go to raithos.github.io/old

**Comment by squaduser** [comment]
Wow - I’m really sorry. I pulled up a document from FFG before I opened the case because I wasn’t sure about the change. I must have had the old points for epic because the document I referenced showed 10. It made me believe these cards were increased not decreased. Sorry about the confusion.
