### ISSUE TITLE
U-Wing generic flagged as limited

### ISSUE THREAD

**Issue by incard-matts** [raithos/xwing#51]
## YASB 2.0 Bug Report

The Blue Squadron Scout, initiative 2 U-Wing, is flagged as limited.

### Expected Behavior

The Blue Squadron Scout is meant to be a generic ship.

### Actual Behavior

Users are unable to add more than one Blue Squadron Scout to a squad as a result of the error.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
fixed
