### ISSUE TITLE
Star Wars: X-Wing Second Edition - RZ-1 A-Wing Expansion Pack

### ISSUE THREAD

**Issue by princejonn** [raithos/xwing#510]
The following ship pack is missing: 
Star Wars: X-Wing Second Edition - RZ-1 A-Wing Expansion Pack

https://www.fantasyflightgames.com/en/products/x-wing-second-edition/products/x-wing-second-edition-rz-1-wing-expansion-pack/

**Comment by raithos** [comment]
this is not available yet i dont add new expansions until after they release
