### ISSUE TITLE
Star Wars: X-Wing Second Edition - TIE/in Interceptor Expansion Pack

### ISSUE THREAD

**Issue by princejonn** [raithos/xwing#511]
The following ship pack is missing: 
Star Wars: X-Wing Second Edition - TIE/in Interceptor Expansion Pack

https://www.fantasyflightgames.com/en/products/x-wing-second-edition/products/x-wing-second-edition-tie-interceptor-expansion-pack/

**Comment by raithos** [comment]
This is not available yet, i dont usually add new packs until after they release
