### ISSUE TITLE
Can't open my First Order lists

### ISSUE THREAD

**Issue by KingmanHighborn** [raithos/xwing#519]
### Expected Behavior

Open my saved First Order lists

### Actual Behavior

The pop-up that has the lists just has a black dot circle spinning saying 'fetching squads' but it just spins and spins never loading. I waited for 15 minutes. No other faction has this issue. 

### Language

English

**Comment by negroscuro** [comment]
It happens the same to me, in spanish language. I was trying with Empire saved lists...

**Comment by raithos** [comment]
duplicate of #514
