### ISSUE TITLE
x wing shield upgrade cards

### ISSUE THREAD

**Issue by lojedi2b** [raithos/xwing#523]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by lojedi2b** [comment]
using yasb 2.0 why does it not let you use the upgrade card, modification upgrade there is no shield upgrade that you can put on any ship?

**Comment by raithos** [comment]
you'll have to provide more info, shield upgrade is available for any ship that has a modification slot. not all ships have modification slots.

**Comment by lojedi2b** [comment]
Yasb 2.0 does not have the upgrade card for that slot

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 23, 2020 at 8:08 PM, raith<notifications@github.com> wrote:   
you'll have to provide more info, shield upgrade is available for any ship that has a modification slot. not all ships have modification slots.

**Comment by raithos** [comment]
https://puu.sh/F34ZC/01c439ac13.png
Example of shield upgrade in use.

You're going to really give me more than it doesnt have it in that slot for me to help you here.

**Comment by lojedi2b** [comment]
do not have shields up grade slot in Hiperspace,  Expanded does have the option.
thanks

**Comment by raithos** [comment]
Oh. That's working as intended. Shield upgrade is not hyperspace legal
