### ISSUE TITLE
lists failing to load/ breaking functionality 

### ISSUE THREAD

**Issue by TZMCKP** [raithos/xwing#524]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

SAVE FILES ARE CURRENTLY BROKEN! IM WORKING ON IT DO NOT SUBMIT A NEW REQUEST

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

Hitting the load button loads a squad that has been saved, and allows me to edit it with point costs being updated as i do.
![image](https://user-images.githubusercontent.com/60365350/73210472-fd683000-410f-11ea-925c-86bc7ef85b4b.png)

### Actual Behavior

Squad fails to load, lists as "undefined" or does load, but if a ship is removed or altered, the point costs will not update. the cost of the ship that is changed is removed from the list, but adding or removing other ships and upgrades don't alter the point cost. This seems to only happen to variants of the following list

"Holo" (54)    
    Proud Tradition (2)    
    
Ship total: 56  Half Points: 28  Threshold: 2    
    
"Muse" (30)    
    Proud Tradition (2)    
    
Ship total: 32  Half Points: 16  Threshold: 2    
    
Omega Squadron Ace (28)    
    Proud Tradition (2)    
    
Ship total: 30  Half Points: 15  Threshold: 2    
    
Omega Squadron Ace (28)    
    Proud Tradition (2)    
    
Ship total: 30  Half Points: 15  Threshold: 2    
    
Epsilon Squadron Cadet (25)    
Ship total: 25  Half Points: 13  Threshold: 2    
    
Lieutenant Rivas (27)    
Ship total: 27  Half Points: 14  Threshold: 2    
    
    
Total: 200    
    
View in Yet Another Squad Builder 2.0: https://raithos.github.io/?f=First%20Order&d=v8ZsZ200Z382X319WWWY235X319WWY267X319WWY267X319WWY269XWY265XW&sn=holo%20swarm&obs=

The one above was manually created, but we've reprodced the indicient twice after chris (brunas) sent me the link to the list, i launched and saved it, then tried to load it at a later date, encountering the issues above. 

note: did some digging on my phone while submitting this bug to find the actual link used to induce the aforementioned bug, it is below.

https://raithos.github.io/?f=First%20Order&d=v8ZhZ200Z382X319WWWY265XWY235X319WWY267X319WWY267X319WWY269XW&sn=Unnamed%20Squadron&obs=

### Language

The affected language(s).

**Comment by raithos** [comment]
I'm not able to replicate this based on your instructions. Is the issue still occuring?

**Comment by raithos** [comment]
I'm going to close this as I havent been able to reproduce the error and I haven't heard back. Undefined lists will not load and should be deleted.
