### ISSUE TITLE
Load Squad can not be filtered to "Epic"

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#525]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

SAVE FILES ARE CURRENTLY BROKEN! IM WORKING ON IT DO NOT SUBMIT A NEW REQUEST

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

When I click on "Load Squad" The bottom of the dialog box should allow filtering by all supported modes (all/hyperspace/extended/quickbuild/epic)

### Actual Behavior

There is no "Epic" filter button

### Language

The affected language(s).

**Comment by Patschke** [comment]
Should be implemented with #527
