### ISSUE TITLE
Request - Quick Build for Epic

### ISSUE THREAD

**Issue by heychadwick** [raithos/xwing#526]
Hello,

If at all possible, can you add the Quick Builds for the Huge ships and the Wings? The Huge ships probably aren't too hard.  The Wings might be harder to implement.   There is only one Wing QB per faction, but options to add the number of ships.  Probably can add a ship type called WING and have the number of ships in the wing as the different pilots.  For example, with the Imperials you have Vader and 2,3,4,or 5 Tie Fighters.

**Ship Type:  Wing**
- Vader w/ 2 Ties - 6 Threat
- Vader w/ 3 Ties - 7 Threat
- Vader w/ 4 Ties - 8 Threat
- Vader w/ 5 Ties - 9 Threat

No pressure!  It just would be nice for doing Epic Battles and Huge Ships.  If you need the QB cards, I can send picks from heychadwick@gmail.com

Thanks so much for your website!

-Jim Chadwick

**Comment by Patschke** [comment]
This is on my ToDo list, yes. 

Duplicate of #464

**Comment by heychadwick** [comment]
You are awesome.   I appreciate your effort.
