### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by mjjeter** [raithos/xwing#529]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

State what you expect to happen here. This only happens on my iPhone. My desktop works fine.

I expect to login and have my lists saved.

### Actual Behavior

State what actually happens here.

When I select google login it takes me to a page that just says “authentication failed”

### Language

The affected language(s).

**Comment by raithos** [comment]
Just being through, you cleared your cache and cookies and tried to log in again?

**Comment by mjjeter** [comment]
Hi Raithos,

Yes I cleared my cache and same results. Tried chrome instead of safari
with same results.

Here is some more context. I signed into YASB a long time ago on both my
desktop and phone. The account was the same account. I was never prompted
to login again so I forgot how I logged in originally.

At some point I got logged out on my phone. I tried getting in through my
google and facebook accounts but get the same message again and again:
"authentication failed."

I have remained logged in on my desktop and am afraid of logging out. I
have manually entered a ton of card, models etc. into my collection and I'd
really like to not lose that information.

Is there any way I could send you more helpful information? I am still
logged into the correct account on my desktop, but I'm unable to see any
account information there.

**Comment by raithos** [comment]
Ok last bit of tedious checking... Can you make sure your account credentials are correct, aka log into them on their respective site.

After you confirm that can you check to see that safari and chrome on your phone have been updated to the latest version?

**Comment by mjjeter** [comment]
Done and done. I just installed chrome a couple of days ago to address this
issue. Just logged into my google and facebook accounts. Credentials are
correct.

Is there some way for me to share my account information from my desktop?
Like I said, I'm currently logged into the correct account there (my
collection is available), but I'm not seeing any account information to
share with you.

**Comment by raithos** [comment]
There isn't a way to share your credential info from your desktop. One last test, on your desktop, but on a different browser, can you attempt to log in?

**Comment by raithos** [comment]
Another cause may be that your cookies settings may be set to strict, and not allowing the cookies to be created. You can also try whitelisting https://yasb-backend.herokuapp.com/ to see if that helps

**Comment by mjjeter** [comment]
So I was able logout and login on my desktop using my facebook credentials.

The login worked in both firefox and in chrome.

On my iphone, I went to my safari settings and turned off cookie blocking.
Same result, failed authentication. I downloaded chrome and got the same
result again. Failed authentication.

So I have figured out that my login credentials through facebook are good,
but for some reason, my iPhone will not allow me to login to YASB.

**Comment by raithos** [comment]
Just to let you know I am still looking into this, but the issue is very weird

**Comment by mjjeter** [comment]
Oh thanks! I've just gotten in the habit of pasting hyperlinks to lists to
a note on my phone. Or I just print lists out more, or memorize them. It's
strange, always works on my computer, never works on my phone now. Reset
everything, changed phone settings, tried new apps, nothing worked.

Don't lose any sleep over it, if this issue is unique to my ancient iPhone
then that's fine.

**Comment by raithos** [comment]
what version of iPhone do you use?

**Comment by mjjeter** [comment]
iPhone 6s i believe.

**Comment by raithos** [comment]
So now im curious of which version of safari and chrome is installed on the phone

**Comment by mjjeter** [comment]
The newest versions of each. I just reinstalled recently.

**Comment by raithos** [comment]
I mean the actual version numbers. Usually you can check the about page in settings for the browser and it will tell you the number

**Comment by mjjeter** [comment]
My chrome version is 80.0.3987.95

I wasn’t seeing the Safari version number.

**Comment by raithos** [comment]
Well I am now officially out of ideas. The last thing, have you tried logging into your account on another phone? if its successful, it must be something specific to your phone by which I don't know if there's anything I can do to help.

**Comment by mjjeter** [comment]
Hi Raithos,

Thanks for everything, I appreciate you giving it your all.

I was able to log in using my wife’s phone just now. There must be some issue with my phone in particular. If I’m able to ever figure out what that is, I’ll let you know. Thanks again!
