### ISSUE TITLE
Wave 6 & 7 expansions missing

### ISSUE THREAD

**Issue by ianbecker** [raithos/xwing#532]
Wave 6 & 7 ships don't appear in the collection list

### Expected Behavior

When I look under "Your Collection => Expansions", I would expect to see the expansions from wave 6 & 7 (e.g., the RZ-1 A-Wing for the Rebels)

### Actual Behavior

The list appears to contain the expansions through wave 5

### Language

English

**Comment by raithos** [comment]
yeah ill get to that soooooon, its just been busy lol

**Comment by ianbecker** [comment]
Totally understandable :)  Thanks for the quick reply!

**Comment by raithos** [comment]
is done
