### ISSUE TITLE
CR90 Corvette Missing Info

### ISSUE THREAD

**Issue by FatHammer** [raithos/xwing#533]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

The CR90 Corvette for the Rebels is supposed to show the attack stats and arc on the printout.

### Actual Behavior

It doesn't show it.

### Language

English
![YASB Bug](https://user-images.githubusercontent.com/26124957/74030314-c0f0cb80-497c-11ea-9e0c-edaf7546b838.JPG)

**Comment by Patschke** [comment]
Thanks for the note, going to fix it
