### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Steve3586** [raithos/xwing#536]
Hi,
I can't log in.
I open the web page and got to the page, click log in, select any of the options and it says verified then goes back to the original page. Popups are enabled. I can't save any lists or anything and just get a very basic front page.

**Comment by Steve3586** [comment]
Amendment, I have it fine on my phone but I can't log in on PC to print etc.
Many appologies - I'm a troglodyte!

**Comment by raithos** [comment]
What browser are you using on pc?

**Comment by raithos** [comment]
I haven't heard anything in a while, is this still an issue?

**Comment by raithos** [comment]
I'm going to close the issue for now, if it resurfaces please respond and I'll reopen.
