### ISSUE TITLE
Unable to add "Dreadnought Hunter" in Epic

### ISSUE THREAD

**Issue by aShorty21** [raithos/xwing#540]
### Expected Behavior

Add "Dreadnought Hunter" to an Epic list while "Veteran Wing Leader" is on another ship.
and
Add "Dreadnought Hunter" to an Epic list while "Dreadnought Hunter" is on another ship.

### Actual Behavior

The option to select "Dreadnought Hunter" is grayed out and not selectable in the same way that would happen if I tried to add "Lone Wolf" on two ships.

### Language

The affected language(s).

**Comment by raithos** [comment]
Hi, have you checked that your ships are not I3 or less? Dreadnaught hunter requires that ships be initiative 4 or higher

**Comment by aShorty21** [comment]
Dang it, that is probably it. Reading is hard. :(
