### ISSUE TITLE
Point Defense Battery does not show all information in print view

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#542]
### Expected Behavior

A Huge ship equipped with "Point Defense Battery" hardpoint in "fancy" print view should show the turret icon and number of dice for that item

### Actual Behavior

The hardpoint item and text description is in the print view, but no turret icon or number of dice.

State what actually happens here.

### Language

English 
<img width="445" alt="Screen Shot 2020-03-02 at 8 20 52 AM" src="https://user-images.githubusercontent.com/8623189/75689654-c3360500-5c5e-11ea-9059-129546dd3bf9.png">

**Comment by Gdsimms** [comment]
This is what I expect, and what you see with other hardpoint upgrade types: Range, Dice, and Turret icon:
<img width="445" alt="Screen Shot 2020-03-02 at 11 53 58 AM" src="https://user-images.githubusercontent.com/8623189/75707779-c9d37500-5c7c-11ea-8173-5d2bde3a2224.png">

**Comment by Gdsimms** [comment]
Found the issue but I can't push the commit. 
in cards-common.coffee, line 10892 has the typo "attackdt" instead of "attackt"

**Comment by Gdsimms** [comment]
The difference between this and the ones that work is that Point Defense Battery is a double turret. I wonder if that is relevant.

**Comment by Gdsimms** [comment]
I think I found it: In xwing-print.sass, line 82:

"xwing-miniatures-font-doublearcturret"

should be:

"xwing-miniatures-font-doubleturretarc"

**Comment by raithos** [comment]
Thanks, will get to this today. this is maybe the best submission ive ever got
