### ISSUE TITLE
B-wing Stabilized S-Foils coming up as 200 points rather than 2

### ISSUE THREAD

**Issue by RebelJP** [raithos/xwing#543]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by RebelJP** [comment]
Expected: In Hyperspace Format, B-wing stabilized S-foils come up as 2 points

Actual: comes up as 200 points

**Comment by raithos** [comment]
That shouldn't even be possible. When was the last time you refreshed the page?

**Comment by raithos** [comment]
I haven't heard anything about this and cant reproduce it. I'm going to close this for now, if the issue does restart, please respond and I'll reopen the issue
