### ISSUE TITLE
IG-RM Droids Card Text Typo

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#544]
### Expected Behavior

IG-RM Text description should show the "HIT" font symbol

### Actual Behavior

IG-RM Card Text displays the literal text "%HI%"

### Language

The affected language(s).

**Comment by Gdsimms** [comment]
Perform a text search for "%HI%"

2 locations: 
cards-en.coffee, line 2224, should be replaced with %HIT%
cards-hu.coffee, line 2006, should be replaced with %HIT%

**Comment by raithos** [comment]
resolved.
