### ISSUE TITLE
Feature Request: Missions

### ISSUE THREAD

**Issue by TimTheITGuy** [raithos/xwing#547]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior
I'd love to be able to configure builds to match specific missions. For example, the escape pod mission Jump to Subspace doesn't allow the attacking player to field large ships & limits them to 75% points, but they also get a reinforcement.
A full list of missions can be found on https://xwing-miniatures.fandom.com/wiki/Category:Missions

### Actual Behavior
I can choose from Extended, Hyperspace, Epic & Quickbuild - it is awesome.

### Language
English

**Comment by Patschke** [comment]
The page you cite is for 1st edition. I am not aware of any missions that came with 2.0.

I could imagine a more universal format selection at some point (basically allowing user-created black-/whitelists), but that is not currently on the todo list. I might look into something like that, if it is more common for tournaments to have individual rules-sets apart from hyperspace/extended.

**Comment by raithos** [comment]
There are scenarios for second edition, but since you can select any points limit, I don't see a need for this feature to be developed. Thanks for your feedback though!

**Comment by TimTheITGuy** [comment]
I appreciate you looking into it. Thanks for an awesome squadbuilder.
