### ISSUE TITLE
Obi-Wan Cost

### ISSUE THREAD

**Issue by aShorty21** [raithos/xwing#548]
Obi-Wan's points are listed as 47. I believe it should be 48.

**Comment by aShorty21** [comment]
https://raithos.github.io/old/?f=Galactic%20Republic&d=v8ZhZ200Z364XW138WWWW71WY333X126WWWY312XWW200WY278XWW200W&sn=TTS%20Give%20it%20a%20try&obs=

Was my link. I don't know how I got "/old" in the url.

**Comment by aShorty21** [comment]
Sorted. It is the link from a google search. Can you adjust that, so it doesn't happen?
![Yasb2-OLD-](https://user-images.githubusercontent.com/61035861/77495195-41309a80-6e1e-11ea-89d0-6d19d4857ec7.jpg)

**Comment by aShorty21** [comment]
It is the link "YASB for X-Wing 2.0" in the picture

**Comment by raithos** [comment]
Yeah the old link is done as a courtasy to people who want the previous meta's costs, its not supported. Recommend you click the main link instead of sub-links when searching via google.

**Comment by Patschke** [comment]
We could try to change the title tag on the /old version to something like `YASB (old point list)` and try if google catches that. This would prevent people from clicking it unless they explicitly want to.
