### ISSUE TITLE
Incorrect XWS export

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#549]
'upsilonclasscommandshuttle' should be 'upsilonclassshuttle' to match xwing-data2.

**Comment by Patschke** [comment]
According to the spec and card, our xws name is correct: 

> 
> XWS ids are generated using the following steps:
> 1. Take the English-language name as printed on the card
> 2. Lowercase the name
> 3. Convert non-ASCII characters to closest ASCII equivalent (to remove umlauts, etc.)
> 4. Remove non-alphanumeric characters
> 5. Check for collisions, and add expansion suffixes until there is no more collision
> 

![Image](https://sb-cdn.fantasyflightgames.com/card_images/en/41f6d936f14a058ed1c5e6ac12de37c2.png)

The ship is named  "upsilon-class shuttle" in the official squad builder, and for some reason xwing-data2 copied that version. As long as the spec for xws does not change, this is (in our opinion) simply wrong. You may create an Issue at xwing-data2. 

See also #301, https://github.com/guidokessels/xwing-data2/pull/213#pullrequestreview-193486989 and https://github.com/guidokessels/xwing-data2/pull/243

**Comment by raithos** [comment]
Oh, I was going to reply to this and then @Patschke decided to write it way more comprehensively. Yeah this is a long standing issue with xws-data2, and afaik everyone else has simply worked around us.

**Comment by XPav** [comment]
Didn't realize it was such a controversial issue!   I totally get it, and I just worked around it.
