### ISSUE TITLE
Dorsal Turret being allowed for a Hyperspace build on BTL-B Y-Wing "Broadside"

### ISSUE THREAD

**Issue by Quatapus** [raithos/xwing#552]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

Dorsal Turret upgrade shouldn't be an allowed selection in a Hyperspace build on BTL-B Y-Wing "Broadside"

### Actual Behavior

Dorsal Turret is allowed to be selected

### Language

English

**Comment by raithos** [comment]
I just added Broadside and a turret in hyperspace and was unable to add dorsal turret. can you show me a screenshot of the bug happening?

**Comment by Quatapus** [comment]
Man I swear it was selectable, but you are right, it's not happening today.
I didn't grab a screenshot at the time. I guess consider this case closed.
If I can replicate it again I'll let you know. Sorry for the confusion

Chris
