### ISSUE TITLE
Mobile login: Authentication Failed

### ISSUE THREAD

**Issue by aaronreini** [raithos/xwing#556]
### Expected Behavior
Login successfully to YASB 2.0 on phone using OAuth (Facebook account). 

### Actual Behavior

Get automatically redirected to the YASB 2.0 page without having been successfully logged in. Desktop logins with the same Facebook account are successful.

### Language

English

**Comment by raithos** [comment]
I need the model of your phone and the version number and make of the browser  you are using.

**Comment by aaronreini** [comment]
iPhone 7 Plus, iOS 13.4.1, mobile Safari browser. Thanks for checking on this!

**Comment by raithos** [comment]
Have you tried opening it on a different browser on your phone?

**Comment by rkukuchka** [comment]
I'm seeing similar issues on Desktop Safari on latest Catalina, though Chrome is working for me.

**Comment by aaronreini** [comment]
I am able to login with Chrome browser on mobile.

**Comment by raithos** [comment]
Ok. You may want to try updating your version of safari to the latest version. that sounds like to me like a cookie related issue. we made a change to the way cookies are processed to be in line with chromes new guidelines, but the downside is that it affects older browsers

**Comment by aaronreini** [comment]
Got it—thanks for your help!!

**Comment by raithos** [comment]
let me know if updating the version helped. for now im going to close this issue, as there is nothing further we can do unless theres some new information.
