### ISSUE TITLE
Problem with having two ships with Bossk.

### ISSUE THREAD

**Issue by frankgrimes4f19** [raithos/xwing#557]
### Expected Behavior

If I make a squad with Bossk as a pilot on the YV-666, then I wont be able to add on a Z95 Headhunter with Bossk as a pilot (regardless of the Hound's Tooth title).

### Actual Behavior

The squad builder is allowing a single squad to have Bossk on both the Z95 and YV-666.

**Comment by Patschke** [comment]
Thanks for committing this issue. 

Confirmed and will be fixed with the next PR.
