### ISSUE TITLE
Can't log in on MacBook Catalina 10.15.4

### ISSUE THREAD

**Issue by Niels111** [raithos/xwing#560]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

I expect to click on log in and be taken to t app-up which lets me log in via facebook, after a couple of clicks i am in to YASB 2.0

### Actual Behavior

I click on facebook (and I've also tried google and twitter), and it takes me to Facebook, I click OK, and then it returns me to YASB but not logged in. Its been doing this for a few of weeks - I've restarted but no change. It still logs me in via facebook on my iPhone just fine. Not sure if this is something I am getting wrong.

### Language

I am using English.

**Comment by raithos** [comment]
which browser are you using, and have you tried updating it to the latest version?

**Comment by Niels111** [comment]
Hi Raithos,
thanks - I’m using safari and I haven’t tried updating - I’ll try updating and try a couple of other browsers :)
Niels

**Comment by Niels111** [comment]
Thanks, that’s great - its working on firefox,
Niels

**Comment by Niels111** [comment]
Hi Raithos,

sorry to bother you and thanks for your help - I’m noticing the points are not updated from the last points change - Obi-Wan is 47 not 48, and R2 is 6 not 9,
many thanks, Niels

**Comment by raithos** [comment]
Is the background of the site red?

**Comment by Niels111** [comment]
yup - very dark red

**Comment by raithos** [comment]
That's the old points version. you need to go to https://raithos.github.io/ or remove the /old from your link

**Comment by Niels111** [comment]
Ah,

thanks very much, my bad! Really appreciate all your hard work on this,
Niels
