### ISSUE TITLE
We're technically producing invalid html

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#561]
### Expected Behavior

Produce non-malformed html

### Actual Behavior

Produce malformed html. Of course, most modern browser can cope with this. It's still not nice ;-)

### Language

html

### Actual Report
See: https://validator.w3.org/nu/?doc=https%3A%2F%2Fraithos.github.io

**Comment by raithos** [comment]
ok im fixing up some of that bad stuff now

**Comment by raithos** [comment]
All fixed except for the image alt tab which i think is not really a big deal.
