### ISSUE TITLE
Log in issue.

### ISSUE THREAD

**Issue by Steve3586** [raithos/xwing#564]
Hi,
I'm having trouble logging in, but just on one PC.
I log in and it accepts everything and says logged in. But when it redirects back it's still not logged in.

Thanks,

Steve

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** If you can't log in, try updating your browser to the latest version, and if you're not using Chrome or Firefox, try them. There was a change to how cookies are stored and we updated to be in line with that but that breaks compatibility with some older browsers.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
Try updating your browser to the latest version

**Comment by Steve3586** [comment]
Hi,I've tried that and it still won't log in. SteveStay safe and have a magical day! 
-------- Original message --------From: raith <notifications@github.com> Date: 30/04/2020  18:54  (GMT+00:00) To: raithos/xwing <xwing@noreply.github.com> Cc: Steve3586 <stevewkirtley@gmail.com>, Author <author@noreply.github.com> Subject: Re: [raithos/xwing] Log in issue. (#564) 
Try updating your browser to the latest version

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/raithos/xwing/issues/564#issuecomment-622007935",
"url": "https://github.com/raithos/xwing/issues/564#issuecomment-622007935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by raithos** [comment]
can you provide which browser you're using and which platform?

**Comment by Steve3586** [comment]
I've done a rebuild of the machine and it now seems to work. No idea what was up. Thanks for your time though. SteveStay safe and have a magical day! 
-------- Original message --------From: raith <notifications@github.com> Date: 02/05/2020  06:18  (GMT+00:00) To: raithos/xwing <xwing@noreply.github.com> Cc: Steve3586 <stevewkirtley@gmail.com>, Author <author@noreply.github.com> Subject: Re: [raithos/xwing] Log in issue. (#564) 
can you provide which browser you're using and which platform?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/raithos/xwing/issues/564#issuecomment-622671210",
"url": "https://github.com/raithos/xwing/issues/564#issuecomment-622671210",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
