### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Bavok** [raithos/xwing#565]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** If you can't log in, try updating your browser to the latest version, and if you're not using Chrome 
or Firefox, try them. There was a change to how cookies are stored and we updated to be in line with that but that breaks compatibility with some older browsers.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

When i try to print my squad from Firefox, it shows the ranges on rockets, torpedos, etc as black bars

[Squad.pdf](https://github.com/raithos/xwing/files/4557791/Squad.pdf)

**Comment by raithos** [comment]
When printing from Firefox, select in the page setup Print Background (colors and images)

https://puu.sh/FEzmF/ac7c2bc5ca.png
