### ISSUE TITLE
Copy/Paste to TTS (Table Top Simulator) not working.

### ISSUE THREAD

**Issue by darktomatoe** [raithos/xwing#566]
### Expected Behavior

Copy/Paste to TTS (Table Top Simulator) will work.

### Actual Behavior

Does not work. Tried multiple times.

### Language

English.

**Comment by Patschke** [comment]
Please provide a link to the squad you are unable to import.

Also note that FFG currently seems to be removing all FFG content from TTS anyways, so we might consider removing that export as well.

**Comment by raithos** [comment]
can you share the actual text thats not working so we can verify it as well as the list in yasb?

**Comment by darktomatoe** [comment]
My apologies, please close this issue. I was not importing it correctly. It  works great.
