### ISSUE TITLE
Can no longer 'save' squads...must use save as function

### ISSUE THREAD

**Issue by pcrpg7254** [raithos/xwing#567]
## YASB 2.0 Bug Report

Great tool. Thank you very much!

### Expected Behavior

When I hit save while tweaking a squad or creating a new one, it saves it for me to browse later.
### Actual Behavior

I try to tweak an existing squad or create a brand new one and I get an never ending twirling icon stating saving squad.

Only way to save my squads now is to hit Save As.

**Comment by raithos** [comment]
oh i probbably broke something. one sec

**Comment by raithos** [comment]
this is fixed,. sorry it took so long, github-pages wasnt updating properly
