### ISSUE TITLE
Card Browser Search for Double Slots

### ISSUE THREAD

**Issue by quall3** [raithos/xwing#569]
It would be awesome if you added a way to search for pilots or ships that have a double Device or double Missle Slot. Or even Tripple Crew slots etc.

Also searching for Cards that require double slots like Barrage Missles or Death Troopers.

**Comment by Patschke** [comment]
Unfortunately the select2 backend we use for the UI does not support selecting the same element more than once. So I'd have to either add entries like "double missile" (which I probably consider more confusing than helpful) or have to write code for managing the entries myself (which I don't feel like it is worth the effort). 

So I can see how this would be a nice feature (and I really like to see people like you useing my card browser search), but I am not sure if there is a clean and straightforward way of implementing this.

**Comment by raithos** [comment]
There is one way to do it for upgrades... but its not what i'd call clean. any upgrade that has multiple slots includes the fields also_occupies_upgrades... if we added a filter that filtered based on whether upgrades took up a second slot and then let you choose the slot it took up, then you could search the array for that upgrade and you have your filter.

For pilots and ships, I agree it would be quite difficult to do that, I would say that's not something we would do.

**Comment by raithos** [comment]
I've addressed both issues in the latest push. there's a checkbox that lets you decide if you want to filter by multiple slots. its limiting in functionality, but at least achieves what you were looking for
