### ISSUE TITLE
Conversion kits adding ships to inventory when they should not.

### ISSUE THREAD

**Issue by Plammi** [raithos/xwing#57]
### Expected Behavior

Main page - > Your Collections -> Expansions:
When I add an Upgrade kit (tried Empire and Rebels) it should add pilots and upgrade cards to my inventory

### Actual Behavior

When I add an Upgrade kit (tried Empire and Rebels) it adds a bunch of ships to my inventory in addition to what it is supposed to be doing.
Since I don't have an upgrade kit myself, I am not 100% certain that it does not contain said ships, but I am fairly certain they do not come with the upgrade kits.

Kind regards
Plammi

**Comment by randy-ja** [comment]
I'm seeing this issue also.

Example: In my collection I have 1 2.0 Core, 1 Rebel Conversion and 2 X-Wing Ship models but my count is 6. (4 actual + 2 from conversion?)

Example 2: In my collection I have 1 Rebel Conversion Kit and 2 Z-95 models but my count is 6. (2 actual + 4 from conversion?)

Example 3: In my collection I have 1 Rebel Conversion Kit, 1 Y-Wing Expansion, and 2 Y-Wing models but my count is 5. (3 actual + 2 from conversion?)

**Comment by raithos** [comment]
This a known issue. Basically i have to add ships to the conversion kits even though ships are not in there otherwise you cant add loose ships. No timeline right now on when I will fix this because I have to overhaul how the collection system works

**Comment by raithos** [comment]
ships are now decoupled from conversion kits
