### ISSUE TITLE
"Frequent" list ...

### ISSUE THREAD

**Issue by wilder3jw** [raithos/xwing#570]
I'd love to see a checkbox on normal list-building pages that would designate a list as "Frequently Referenced," and then have "Frequently Referenced" presented on the main page (just as the factions are) for quicker finding/loading.

**Comment by Patschke** [comment]
I don't think that I like the idea of adding a lot of stuff to the main page. You can access lists by simply storing the URL, e.g. by placing a bookmark if your intention is to have quick access during tournaments etc? 

Or what is the reason you would frequently want to load the same list?

**Comment by raithos** [comment]
we created a tag system so you can now add any tag you want and quickly filter through it from the load menu.
