### ISSUE TITLE
Collection check

### ISSUE THREAD

**Issue by Paladin1127** [raithos/xwing#571]
The website doesn’t read out ships that you don’t have or pilots that you don’t have there also doesn’t seem to be anything to say if you’ve accidentally put in a ship or a pilot you don’t have or more cards than you have so I don’t know if there’s any kind of validation I seem to remember there used to be

**Comment by raithos** [comment]
???
https://puu.sh/FQwTc/badf38ecbc.png

**Comment by raithos** [comment]
https://puu.sh/FQwTx/2b97dfa1cb.png

**Comment by Paladin1127** [comment]
Its working for me now, must have just gliched on me
