### ISSUE TITLE
R1-J5 pilot data

### ISSUE THREAD

**Issue by EGNMX5** [raithos/xwing#572]
### Expected Behavior

when the mouse passes over the pilot you should be able to display it on the right part of the tool

### Actual Behavior

As soon as Han Solo is equiped in the Fireball piloted by R1-J5, you can not see Pilot data
![image](https://user-images.githubusercontent.com/63339804/83815365-5482a080-a6c0-11ea-9311-58fdc149df4d.png)

### Language

French

**Comment by raithos** [comment]
what language are you using

**Comment by EGNMX5** [comment]
French

**Comment by raithos** [comment]
fixed
