### ISSUE TITLE
Quickbuild in galactic republic

### ISSUE THREAD

**Issue by EGNMX5** [raithos/xwing#573]
### Actual Behavior
It's impossible to select Anakin or Odd-ball on Y-wing BTL-B

when you select Anakin on Y-wing, result is anakin on delta7
when you select odd-ball on Y-wing result is Odd-ball on torrent

![image](https://user-images.githubusercontent.com/63339804/83816070-e343ed00-a6c1-11ea-8911-d4ad6102d44a.png)

### Language

french

**Comment by raithos** [comment]
fixed
