### ISSUE TITLE
won't save or load squad

### ISSUE THREAD

**Issue by SkyRaptor62** [raithos/xwing#58]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. Unless you're Dee Yun, in which case it's wholly intentional.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
Hi, can you provide more info as to what you specifically did to not be able to load lists? are the lists old or new ones? Thanks

**Comment by SkyRaptor62** [comment]
Sorry, I used the previous version. and recently noticed it was now in 2.0. I was able to create a new squad and save it (apparently). However, when I go to load that squad or another previously saved squad, the window pops up looking and just keeps spinning.

**Comment by LordVorKon** [comment]
Refresh the page and then re-login.

**Comment by SkyRaptor62** [comment]
Did that.  Still attempting to Fectch Squads and just stays there. However, when I do a "Save as.." it tells me when the name is already taken, the data is stored somewhere, but just cannot retrieve it.

**Comment by raithos** [comment]
are you naming the list the same as one of your 1.0 lists? account info is shared between the 1.0 and 2.0 YASBs

**Comment by raithos** [comment]
I haven't had an update in a few days, so I'm going to close this for now. Please reply if there's an issue still and I'll reopen the issue

**Comment by SkyRaptor62** [comment]
Will I tried a different browser using my Son's FB account and it worked until now.  I just got the same error after creating and load several different names...  Now I am afraid it is all lost.

**Comment by raithos** [comment]
can you try logging in and out. I'm sorry youre having this problem, its very odd

**Comment by raithos** [comment]
to clear out the local files, you would need to delete your cookies and cache in the browser. Everything in YASB is stored in the browser. Also, which browser are you using?

**Comment by SkyRaptor62** [comment]
I was using Edge originally, then switched over to chrome after having issues.

**Comment by SkyRaptor62** [comment]
Well, I cleared all history, cookies, etc. on Edge and it still hangs on "Fetching Data"...

**Comment by raithos** [comment]
@SkyRaptor62 can you do something for me? I'd like you to log into YASB 2 as normal, and then in a separate tab, go to the link https://yasb-backend.herokuapp.com/squads/list (only works if you're logged in). Can you then paste all of the text into a response here so I can look at your saved list data? Thanks

**Comment by raithos** [comment]
Since I haven't heard anything in a while, I'm going to close this again. If you provide the requested info, I can reopen this
