### ISSUE TITLE
Can’t see what expansions upgrades are found in

### ISSUE THREAD

**Issue by johnpalumbo** [raithos/xwing#586]
### Expected Behavior

I used to see what expansions an upgrade was available in. Was this removed?

### Actual Behavior

Upgrade info shows card text, and how many in my collection, but not what expansions provide it. This is the case for upgrades I own and don’t own.

Love the site! Many thanks!

### Language

State what language translation you use.

**Comment by Patschke** [comment]
Thanks for the note. I can confirm this behavior, it was not intended to remove displaying this information. I'll find out where it got lost, and add it again.
