### ISSUE TITLE
Printing all black/gray pages from iPad browsers and PC Firefox browser

### ISSUE THREAD

**Issue by wiles01** [raithos/xwing#588]
### Expected Behavior

Print out cleanly like it used to.

### Actual Behavior

Prints black text on extremely dark gray background for entire page, not readable.  I think there was some fix you could do somewhere with how it handled images or something?  But now it is doing it on iPad as well, not sure I can make those adjustments on iPad if that is the fix here?

### Language

English
[test.pdf](https://github.com/raithos/xwing/files/4798327/test.pdf)

**Comment by Gegh** [comment]
same here

**Comment by Patschke** [comment]
Yep, going to fix it. It inherits the background-color from the body rule of the xwing.css, as there is no rule in xwing-print.css. 

Thanks for the note
