### ISSUE TITLE
Titles dont show squad names after reload

### ISSUE THREAD

**Issue by friseb** [raithos/xwing#589]
### Expected Behavior

If I reload an existing tab, I expect the squad name to appear in the title of the tab.

### Actual Behavior

If I reload an existing tab, or load an existing tab in a newly opened browser, the squad name disappears in the title and I have to click into the squad name field to get the sqaud name in the tab title.

**Comment by raithos** [comment]
Can you provide additional details on how you created this bug? I can't seem to replicate this on my machine in Chrome or Firefox.

**Comment by friseb** [comment]
Hi, i made a short video:
https://www.youtube.com/watch?v=cqVfmA8iaic

I use Firefox an a Win 10 machine.

If you need more information, ask along.

**Comment by raithos** [comment]
Perfect, thank you for the video, above and beyond what i normally get for feedback, should be solved now

**Comment by raithos** [comment]
ok I have a better solution in there now.
