### ISSUE TITLE
Collection Errors

### ISSUE THREAD

**Issue by diablodiablo** [raithos/xwing#59]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. Unless you're Dee Yun, in which case it's wholly intentional.

### Expected Behavior

State what you expect to happen here.

My collection from YASB 1.0 transferring over to this version cleanly 

### Actual Behavior

State what actually happens here.
Numerous errors in my collection in YASB 2.0

I guess I could just log in under a different account and start fresh but I'd rather not

Thanks for all your hard work!

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
i suspect this is the conversion kit issue. If you are seeing extra ships in your collection its because the conversion kits add ships for each ship it has bases for whether or not you have those ships

**Comment by raithos** [comment]
ships are now decoupled from conversion kits
