### ISSUE TITLE
Printout wonky

### ISSUE THREAD

**Issue by pcrpg7254** [raithos/xwing#591]
## YASB 2.0 Bug Report
Good afternoon/evenning

Printout has been compressed when I attempt to print.
### Expected Behavior
Printout squad in readable format.

State what you expect to happen here.
Printout Squad in readable format.
### Actual Behavior

State what actually happens here.
When I try to printout my squads, now it is in 'compressed mode'. No change in printer nor cpu.
Could this have something to do with the new Chrome update?

As always, thanks for such a great site/app.

Merci

**Comment by raithos** [comment]
Could you provide some more info? Not sure what the issue is here

**Comment by raithos** [comment]
without any more info I cant do anything to help here. If more info is provided i will reopen
