### ISSUE TITLE
Can't open my saved lists

### ISSUE THREAD

**Issue by Talhoffer** [raithos/xwing#594]
I can't open any of my saved lists. I'm running YASB 2.0 in Chrome on an old Macbook Pro.

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
so you're able to log in and able to see your lists but not able to load them?

**Comment by Talhoffer** [comment]
I can load them now! I used to be able to simply click on the name of the
squad to load them but now I need to press the load icon. They are a little
slow loading (although that could be my computer) but they will load.
Thanks
