### ISSUE TITLE
Quickbuild options for TIE Advanced v1 do not match cards

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#598]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

The Quickbuild cards I have that came in the TIE Advanced v1 expansion pack provide the following options:

(Threat 3) Seventh Sister, Predictive Shot, Proton Rockets, Afterburners, Hull Upgrade

(Threat 2) Inquisitor, Heightened Perception, Proton Rockets

(Threat 3) Grand Inquisitor, Hate, Proton Rockets, Shield Upgrade

(Threat 2) Baron of the Empire, Elusive, Outmaneuver, Afterburners

### Actual Behavior

The available options are all different from these.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Well, they match the official Quickbuild pdf, right? You can find it at FFGs website here: https://images-cdn.fantasyflightgames.com/filer_public/d5/1e/d51e0dd7-b793-4a1d-bac5-b92945510cb2/wave3_quick-build-empire.pdf

Unfortunately FFG does not provide a nice list of the quickbuilds they actually print on cards - some are even only available on quickbuild promo cards. As I am not going to buy 2nd edition ships that have been available via conversion kits (I simply have all ships from 1.0), I am not having those quickbuild cards available. There are probably non-official sources, but I have been to lazy to search for those. 

Thanks for the feedback, going to add the quickbuils listed by you - I'll just assume that they are correct.
