### ISSUE TITLE
Battle Meditation Wrong values

### ISSUE THREAD

**Issue by Takko550** [raithos/xwing#601]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Points supposed to be 4/6/8/10pts for Ini 3/4/5/6
### Actual Behavior

Points are old ones 0,2,4,6,8,10,12 when initiative is 0,1,2,3,4,5,6

### Language

English

**Comment by Patschke** [comment]
They are not highlighted in the new points document as "changed", so we either missed the change cause it was not visible, or the points did not change and were wrong the whole time. 

Thanks for the note, will be fixed.
