### ISSUE TITLE
Map background Covers UI

### ISSUE THREAD

**Issue by goforfold** [raithos/xwing#605]
### Expected Behavior

Interacting with UI doesn't cover up menus/screen

### Actual Behavior

This has occurred consistently for weeks at this point. Uninstalling and reinstalling doesn't fix the bug. After playing a match, the map background will start to cover every screen and anything I do. It will spread to my player window and cover everything. The right click menu will be covered and mousing down through the menu exposes the options. It almost looks like everything freeze with the map background covering everything, but no functions are actually frozen and I can keep playing. Minimizing the screen resets the screen back to how it should look, but the problem comes back. I can't figure out a trigger and once it starts, it won't stop. It doesn't happen in any particular screen until I click it.

### Language

English

**Comment by Patschke** [comment]
I am not sure for which game this bug report is supposed to be, but I can't help you here. This is the github repo of YASB 2.0, a squad builder for the X-Wing miniatures game by FFG. We don't have a map, nor can you install our squadbuilder or play matches within it ;-)

**Comment by goforfold** [comment]
Oh man, sorry about that! Meant to post a bug for vassal X-Wing

Cheers,

--sent from mobile--

On Aug 2, 2020, at 11:39 AM, Patrick Mischke <notifications@github.com> wrote:

﻿

I am not sure for which game this bug report is supposed to be, but I can't help you here. This is the github repo of YASB 2.0, a squad builder for the X-Wing miniatures game by FFG. We don't have a map, nor can you install our squadbuilder or play matches within it ;-)
