### ISSUE TITLE
Nantex status bar.

### ISSUE THREAD

**Issue by Steve3586** [raithos/xwing#606]
Hi, I'm just wondering if it would be possible to add the bullseye feature for the nantex to the icon status bar on the printout option.
I'm fairly new and still learning and I love to watch games on stream with the printed list in front of me. I was a little lost because of the two forward arc options not being both there on the printout.

Thanks in advance, keep up the good work it's really appreciated.

Steve

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
solution is done, will be pushed later tonight

**Comment by Steve3586** [comment]
Fabulous, thank you.Stay safe and have a magical day! 
-------- Original message --------From: raith <notifications@github.com> Date: 11/08/2020  21:12  (GMT+00:00) To: raithos/xwing <xwing@noreply.github.com> Cc: Steve3586 <stevewkirtley@gmail.com>, Author <author@noreply.github.com> Subject: Re: [raithos/xwing] Nantex status bar. (#606) 
solution is done, will be pushed later tonight
