### ISSUE TITLE
B-Wing 3-straight has wrong colour.

### ISSUE THREAD

**Issue by peterkejser** [raithos/xwing#61]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** If you find your collection has extra ships, this is expected. In order to allow loose ships I have added ships for each kit based on what the kit can convert. This has to be done right now otherwise you would not be able to add loose ships. Until I have time to overhaul the collection system, or all the existing ships are released in their own blister packs, this is the only way to allow loose ships being added.

### Expected Behavior

The B-Wing should have a 3-straight BLUE.

From the Fantasy Flight Rebel Conversion Kit Unboxing Stream:
![ffg rebel unbox video](https://user-images.githubusercontent.com/14195245/45555671-b7bc0780-b839-11e8-8b9d-7b204d6801b4.PNG)

Personal Image from own Rebel Conversion Kit:
![img_20180914_161541](https://user-images.githubusercontent.com/14195245/45555742-e6d27900-b839-11e8-957c-f4da6eada6a4.jpg)

### Actual Behavior

In the system, the B-Wing haves a 3-straight WHITE.

Screenshot:
![error](https://user-images.githubusercontent.com/14195245/45555787-09649200-b83a-11e8-963e-0d6ecf26bbbb.PNG)

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
that was way more proof than i needed to execute the fix. i like you. will update and push shortly
