### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by DavinFelth23** [raithos/xwing#614]
can't scroll to more mods on republic y-wing (anakin)  Was trying to get to afterburners but can't get it by scrolling or searching.

**Comment by DavinFelth23** [comment]
note I was in extended format.

**Comment by Patschke** [comment]
Everthing works fine for me, so you need to be more specific - please provide enough information that we can follow it to reproduce this behaviour. Otherwise I am unable to fix this issue. 

E.g. which browser are you using, mobile or desktop version,...

**Comment by DavinFelth23** [comment]
On chrome on desktop.  works fine for me on mobile.

**Comment by DavinFelth23** [comment]
![image](https://user-images.githubusercontent.com/22262021/90263085-c68c0a00-de14-11ea-9cc6-d1c6c261aa64.png)

**Comment by Patschke** [comment]
Thanks for the additional information. 

Is this specific for this list? Can you open the dev console (CTRL+SHIFT+J) and tell me if there are any bugs showing up?

**Comment by DavinFelth23** [comment]
![image](https://user-images.githubusercontent.com/22262021/90263747-b3c60500-de15-11ea-9e5c-662d0c85634c.png)

**Comment by DavinFelth23** [comment]
all republic y wings are doing this for me.  the issue might actually be that format shows extended but when I click on it hyperspace shows selected... I click back off it and it shows extended again.

**Comment by DavinFelth23** [comment]
![image](https://user-images.githubusercontent.com/22262021/90263893-e66ffd80-de15-11ea-8aa7-84cd319581ba.png)

**Comment by Patschke** [comment]
The mod list shown actually contains only hyperspace legal upgrades (electronic baffle, tactical scrambler, ... are missing as well) - so there is not an issue with afterburnes specifically (or not beeing able to scroll), but rather with mode selection. 

After playing with game mode selection a bit I noticed that the german version acually shows the header only, and no mode at all. We should probably fix the translation typos from feb16dbad4223d5bdbc3b7e1a2ba53a66cb6b725 first and see if this helps. 

At least we have an idea where to look now, thanks for reporting this bug!

**Comment by raithos** [comment]
After pushing this change, I don't seem to see the issue anymore. Can you confirm?

**Comment by DavinFelth23** [comment]
Still not working for me.

@raithos 

Take this hyperspace list and paste it into chrome.  

https://raithos.github.io/?f=Galactic%20Republic&d=v8ZhZ200Z359XWW136WWWWY312XW6W200WY278XW6W200W&sn=Unnamed%20Squadron&obs=

when you paste and load it the format dropdown swaps to say extended, but if you click the dropdown you see that hyperspace is actually selected and only the hyperspace mods are available.

**Comment by raithos** [comment]
ok thanks for the instructions, able to find it now, it should be fixed
