### ISSUE TITLE
Wrong points for agile gunner

### ISSUE THREAD

**Issue by Lunar-Sovereign** [raithos/xwing#616]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Agile gunner should be 4 points on a huge ship.

### Actual Behavior

It comes up as 7 points which would be the cost on a small ship.

### Language

English.

**Comment by raithos** [comment]
solved
