### ISSUE TITLE
Quick-Release Locks wrong text

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#623]
### Expected Behavior

Quick-Release Locks should read "During the System Phase, you may spend 1 Charge to place 1 cargo crate drift in your Rear Arc at range 0. It cannot overlap a ship this way."

### Actual Behavior

It reads "During the System Phase, you may spend 1 Charge to drop 1 cargo crate drift using the [2 ], [2 ], or [2 ] template." I have no clue, where this comes from.

### Language

All of them

**Comment by Patschke** [comment]
Thanks for the note, will be fixed. I've also added the "This card's charge cannot be recovered." part.
