### ISSUE TITLE
Error on the Resistance Transport calculator

### ISSUE THREAD

**Issue by DruMau5** [raithos/xwing#624]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

I went to put the quick build together of the resistance transport as described by the quick build guide.  I expect to be able to add leia organa and korr sella to the ship.

### Actual Behavior

State what actually happens here.

Leia Organa locks out the other crew upgrade slot.  

### Language

The affected language(s). 
 English

**Comment by Patschke** [comment]
To use quickbuilds please change from extended to quickbuild in the drop down menu on the upper left. The build rules for quickbuild break the rules for "usual" squad building, so you are often not able to put a ship together with the same load out as given on the quickbuild cards while using normal squad building rules. 

After selecting the quickbuild mode, the crews will automatically be added as soon as you select Cova Nell. For extended mode the behaviour you describe is correct: Leia does occupy two crew slots. This is also indicated on the Leia card.

**Comment by raithos** [comment]
This is working as intended. Quickbuilds do not follow the standard loadouts.
