### ISSUE TITLE
Concussion Bomb Effects

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#625]
### Expected Behavior

Concussion Bombs don't have the bomb effects listed yet.

### Actual Behavior

The effect was described at the end of the most recent article, found here:
https://www.fantasyflightgames.com/en/news/2020/9/9/rule-skies/

### Language

"When this device detonates, each ship and remote at range 0–1 is dealt a facedown damage card. Then, each ship at range 0–1 must expose a damage card unless it gains a strain token."

**Comment by Patschke** [comment]
Yep, thanks for the note. Weired, a spoiler article with information in the text (not just the images)...

**Comment by raithos** [comment]
I agree that's how it works, but that's not the confirmed text for how it appears on the card. So I'm going to wait until we see the condition before applying it.
