### ISSUE TITLE
Misspelled card(s). 

### ISSUE THREAD

**Issue by TobbyZ** [raithos/xwing#628]
The new wave seems have some card(s) spelled wrong.
- Multi-Missle Pods (unreleased)

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
will be updated in the next push
