### ISSUE TITLE
Can't switch out gunner/crew combo card with another gunner/crew combo card if a ship's other gunner slot is full

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#629]
To reproduce:

1) Select a LAAT/i
2) Put Wolf Pack in the ship
3) Note how you can switch it out with Ghost Company
4) Put something in the other gunner slot
5) You can no longer switch between Ghost Company and Wolf Pack

Using Firefox 81.0 (64-bit) on Windows.

**Comment by raithos** [comment]
Yeah that is unfortunately a limitation on how the occupied slots work. the same thing would happen with death troopers and palpatine. There's no plan to resolve it.

**Comment by XPav** [comment]
Probably related is that switching between LAAT/i pilots drops those Crew/Gunner upgrades.

**Comment by raithos** [comment]
This somehow got resolved when i did the restrictions update. Palpatine/Death Troopers still doesnt work but I can consider this resolved

**Comment by raithos** [comment]
Actually Im dumb it still isnt fixed

**Comment by raithos** [comment]
HOWEVER, the new stuff i did did make it possible to make a solution, which i implemented so this is actually totally fixed
