### ISSUE TITLE
Collaborating on importing from 2.0 XWS?

### ISSUE THREAD

**Issue by danielElopez** [raithos/xwing#63]
Hey there!  I'm working on a project of my own for allowing exporting XWS from the FFG Squad Builder.  If you'd like, you can totally have any of that code for adding into your own builder.  You can find the project here: https://github.com/danielElopez/X-Wing-Squad-JSON-Exporter.  It's still a work in progress, but it works for simple squads (some of the ship names are different in the FFG builder from what I'd expect).

**Comment by raithos** [comment]
Thanks ill look into it!
