### ISSUE TITLE
Commander Malarus Typo (minor)

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#630]
## YASB 2.0 Bug Report
Xi-Class Light Shuttle
Commander Malarus

### Expected Behavior
"While a friendly ship at range 0-2 performs a primary attack, if it has 1 or more blank results, that ship must gain 1 strain token to reroll 1 blank result, if able."

### Actual Behavior
"While a friendly ship at range 0-2 performs a primary attack, if it has 1 or more blank results, that ship must gain 1 strain token to reroll 1 bank result, if able."

The word "blank" is missing an L near the end of the ability.

### Language
Ship ability text.

**Comment by raithos** [comment]
will be fixed in the next push
