### ISSUE TITLE
Xi-Malarus and Xi-Gideon exporting incorrect in XWS

### ISSUE THREAD

**Issue by dbldown11** [raithos/xwing#632]
### Expected Behavior

Exporting XWS for lists with Xi-Shuttle Commander Malarus or Gideon Hask should (I think?) output them with name/id of "commandermalarus-xiclasslightshuttle" and "gideonhask-xiclasslightshuttle"

### Actual Behavior

Exporting XWS for lists with Xi-Shuttle Commander Malarus or Gideon Hask currently outputs them with name/id of "commandermalarus" and "gideonhask". Unfortunately this means they load incorrectly in other applications (for instance, VASSAL's XWS squadbuilder gives me silly TIE/fo Malarus). 

This can be worked around by manually editing the XWS for now (in case someone else is reading my bug report before YASB is corrected, hahaha just kidding normal people don't read bug reports they just @raith in Discord)

(Also, this might be unrelated but incidentally I the URL squadbuilder in VASSAL also can't process lists with Malarus, obviously VASSAL is Mu0n and not you but I thought I'd mention it in case the two issues are related.)

### Language

I've always used language!

**Comment by raithos** [comment]
My normal response to this is to wait until I hear from other sources about XWS conflicts because XWS is full of exceptions that I don't agree with, however, in this case since you memed the @ mentions, I will fix this just for you.

**Comment by dbldown11** [comment]
@raithos our memes are the ties that bind (and don't you dare say you doubt it).

Thanks for the fix, turns out I lost with Malarus once and I so hate Malarus now and it's all for nothing and I'm sad. But thanks!
