### ISSUE TITLE
XWS issues? 

### ISSUE THREAD

**Issue by FTFup** [raithos/xwing#633]
Sorry if this is redundant for something you're already aware of... didn't see it in the other open/closed issues. 
Thanks for all your work <3

### Expected Behavior

This is the list i was attempting to load into TTS with the XWS spawner. 
https://raithos.github.io/?f=Separatist%20Alliance&d=v8ZsZ200Z411X101WWWW221WW323Y411X209WWWWWW323Y325X114W71WW236W237Y325X114W71WW236W237Y279XW208W&sn=Unnamed%20Squadron&obs=coreasteroid5,core2asteroid1,core2asteroid5

### Actual Behavior

it was giving me an error about a nil value. and not loading. I was able to successfully load the same list from FFG Spawner. so that lead me to believe it's a YASB error rather than TTS or the Mod I think? there were some others who seemed to have the same issue on the Xwing unified mod's trouble shooting discord. so maybe it's already in the next update. 
(i tried to paste screen shot of error, but i'm not sure if that works here...)
![image](https://user-images.githubusercontent.com/52437093/94327907-eebe6b00-ff73-11ea-8ac6-dc9f550992cf.png)

### Language

English?

**Comment by raithos** [comment]
I can't speak to XWS there might be issues, but did you know if you go to the print button there is a tab for a TTS format that you can use to import lists directly?

**Comment by Patschke** [comment]
I can see that it is not intuitive to search for an TTS import behind a print button. We could consider merging the XWS and print modal to the same thing - just add XWS as another tab to the print modal, and make the export xws button open the print modal with that tab active? This should be easy to do, no changes to the UI are needed, and it makes access to all functionality easier?

**Comment by FTFup** [comment]
Nope i did not know that one! thanks for sharing the info though! 
the idea from @Patschke sounds like a solid way to keep them all together. though maybe i'm the only one who didn't know it was in the print option...
