### ISSUE TITLE
Wolfpack Crew/Gunner Card needs to be one word.

### ISSUE THREAD

**Issue by rc38-delta-lead** [raithos/xwing#639]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Wolfpack should be one word to allow copy and paste into TTS,

### Actual Behavior

It is two words and will not load squads properly into TTS

### Language

The affected language(s).

**Comment by Patschke** [comment]
Thanks for the note, will be fixed with #637 on the next update.
