### ISSUE TITLE
Add BTL-S8 K-Wing to Collection Options (YASB 2.0)

### ISSUE THREAD

**Issue by VA-Norm** [raithos/xwing#640]
## YASB 2.0 Bug Report
BTL-S8 K-Wing missing as option to Add to Collection; otherwise, seems to be present.

### Expected Behavior

Should be able to add BTL-S8 K-Wing to Collection

### Actual Behavior

Not on Add to Collection pick list.

**Comment by Patschke** [comment]
Works just fine for me. To fix this issue for you, I need to be able to reproduce it. Please provide some more information on how I could try to experience this bug myself - e.g. which browser are you using, are there any error messages showing up in the logs (CTRL+SHIFT+K in firefox or CTRL+SHIFT+J for chrome), ...?

![grafik](https://user-images.githubusercontent.com/17853362/95206037-7e6edf80-07e6-11eb-9656-b7adcc1d4616.png)

**Comment by raithos** [comment]
closing this until its reproduceable, i have the same experience as Patrick
