### ISSUE TITLE
Constantly pops keyboard on iPad 

### ISSUE THREAD

**Issue by DeployerOfMajesty** [raithos/xwing#642]
### Expected Behavior

When using YASB on iPad, I should be able to use the Interface’s dropdowns to quickly select between ships, pilots, & upgrades, just as I do on desktop/mobile phone. 

### Actual Behavior

When using YASB on iPad, any tap on the Interface’s dropdowns will cause the keyboard to pop up. This blocks much of the screen, makes the interface unresponsive, and forces me to close the keyboard before I can make the next tap. Listbuilding is possible but onerous.

### Language

Only tested English

**Comment by Patschke** [comment]
There is a search option alongside the dropdown. That is the reason for the keyboard popping up. I do like the seach option for desktop use quite a lot (especially as it is able to understand english and german at the same time, so if I only come up with the english name of a card, but have my UI in german, I can quickly find it), so I don't want to disable it entirely. 

I understand, that this feature may be annoying on tablets, so the question is probably, when to switch between mobile and desktop view? Maybe we can add an option, that enforces mobile view regardless of screen size (just like we have an option for the ini-prefixes). Or we just implement a check for tablets by checking the userAgent.

**Comment by raithos** [comment]
This is how its supposed to work based on how its coded. I'll have to look at it more carefully but from the logic it should already work like it does for mobile.

**Comment by raithos** [comment]
WOW. ok, so iOS 13 completely changed what comes out of useragent.navigator so it doesnt work the way it used to. I added in extra code to fix it, should be good when i push the next update.
