### ISSUE TITLE
Wolfpack for the new Republic released cards.

### ISSUE THREAD

**Issue by KvaNfield** [raithos/xwing#643]
## YASB 2.0 Bug Report
Wolfpack from the new release is wrongly spelt as "Wolf pack"

### Expected Behavior

Wolfpack is properly spelt and TTS import works properly.

### Actual Behavior

Export to TTS does not generate a proper squad/

### Language

English

**Comment by raithos** [comment]
the space was resolved yesterday. refresh your browser?

**Comment by KvaNfield** [comment]
Hi.

Yes it works now, I forget to refresh it before the ticket. I'll do it next
time. Thanks.
_____________________
Pozdrawiam
Łukasz "KvaN" Poczęsny


śr., 7 paź 2020 o 20:09 raith <notifications@github.com> napisał(a):
