### ISSUE TITLE
"Builder Keyword" support

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#645]
The recent points list have a "Builder Keywords" columns.   Each pilot can have 0 to N keywords, upgrades can require keywords.  

Current keywords in the points list are below, those with known upgrades being released are in bold:

- **A-Wing**
- B-Wing
- Bounty Hunter
- Clone
- **Dark Side**
- Droid
- Freighter
- Jedi
- **Light Side**
- Mandalorian
- Partisan
- Sith 
- Spectre
- **TIE**
- **X-Wing**
- Y-Wing
- YT-1300

**Comment by raithos** [comment]
Eventually I will change the system to use a more generic term system, but right now a system like that is unnecessary

**Comment by Patschke** [comment]
At some point we should probably implement a "traits" property, which can be provided for ships/pilots (list of strings). This would allow them to be shown in the UI, searched for in the Browser, and referenced by from upgrade cards. But I agree, that seems to be a future ToDo.

**Comment by raithos** [comment]
I Hate this, I had to implement the system because I forgot that the V-Wing pretends its a tie so i needed the system in place. You don't need to add the keywords for ships, as it also parses the names directly first so just the keywords that dont appear in any name already.
