### ISSUE TITLE
TIE Heavy: zero shields

### ISSUE THREAD

**Issue by emeraldbeacon** [raithos/xwing#651]
### Expected Behavior

A TIE Heavy with a Shield Upgrade equipped should show a shield value of 1.

### Actual Behavior

The new TIE Heavy does not **have** a shield value (as opposed to other ships which have shield values of **zero**), so it does not reflect any change when a Shield Upgrade is equipped.

**Comment by Patschke** [comment]
Thanks for the note, going to be fixed.
