### ISSUE TITLE
Dead Eye Shot and Automated Target Priority not listed as being in the Heralds of Hope exspansion 

### ISSUE THREAD

**Issue by ReliableRoad** [raithos/xwing#654]
Not sure if this is helpfull or not  
### Expected Behavior
After adding the Heralds Of Hope squadren pack my to collection it contains 2 copies of the Talent card Deadeye Shot and the 2 copies of the Tech card Automated Target Priority. 

### Actual Behavior

The Talent card Deadeye Shot and the Tech card Automated Target Priority are not in my collection after adding the Heralds Of Hope squadren pack. 

Additinaly the Astromech R6-D8 is marked as unreleased but is in the same pack. 

### Language

The affected language(s). 
English

**Comment by raithos** [comment]
i dont have the actual pack contents yet, so its going to be inaccurate
