### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Lybo24** [raithos/xwing#655]
In the new update with the newly added ships, in the Empire ship list the new Tie/rb Heavy there are 2 modification slots. If you select "shield upgrade" as a modification it adds the points to the ship but it does not show up on the ship data.

**Comment by raithos** [comment]
did you refresh your page? this was resolved a few hours ago

**Comment by Lybo24** [comment]
I did that 2 times and nothing, now on the third refresh it works. Weird. Thanks that was a quick reply :)
