### ISSUE TITLE
Collection list of expansions lacking Lambda Shuttle, Imperial Aces and Imperial Veterans?

### ISSUE THREAD

**Issue by Aunevik-Berntsen** [raithos/xwing#656]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Expecting to be able to choose from all the expansions in the My collection section.

### Actual Behavior

Not finding Lambda Shuttle, Imperial Aces and Imperial Veterans.

### Language

The affected language(s). 
English

**Comment by Patschke** [comment]
Afaik those expansions are 1st edition. That beeing said, only the ships within those expansions are of interest for 2nd edition. As this is the case for all 1st edition expansions, there is no real need to list them as individual expansions. You can add individual ships in the ships tab of the collection section. 

If you have any further questions, feel free to ask. 

If you really want, you can add those expansions using the 1st edition squadbuilder at https://geordanr.github.io/xwing/. Note however, that using both squadbuilders with the same account is not well tested, and may result in all kind of errors and bugs. There is no support for doing that intended.

**Comment by Aunevik-Berntsen** [comment]
Ah, ok. Makes perfectly sende :)

søn. 1. nov. 2020, 16:23 skrev Patrick Mischke <notifications@github.com>:
