### ISSUE TITLE
Error identification 

### ISSUE THREAD

**Issue by FreemanBZH** [raithos/xwing#658]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior
On iOS devices
On chrome and safari
State what you expect to happen here.
Impossible to login using google account

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by FreemanBZH** [comment]
I received the email to confirm the connection with the Google account, but when I come back on yasb I never be connected

**Comment by Patschke** [comment]
I don't own any Apple devices, so I can't check this on iOS. The closest I can get is checking chromium using my desktop computer, and everything works fine there (including two-factor authentification). So I guess I need your help to attempt to fix this issue. The first question would be if there are any errors showing up in the log (visible via Command+Option+J in Chrome, I don't know how to open it in Safari)?

**Comment by FreemanBZH** [comment]
As  I have no problem on computer, I look for option in the settings of IOS. I found a new option “autoriser le suivi  intersite” in French. With this option in now working. Is a new iOS14 option.

Sorry to disturbing you
