### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by Widzy5** [raithos/xwing#660]
### Expected Behavior

Should be able to sign in using Facebook

### Actual Behavior

Whenever I try to sign in using Facebook, I am returned to the squad builder home page but I’m still not logged in.  If I try logging in again, the popup for the ‘login by Facebook’ briefly appears then immediately vanishes.  This has started happening on both iOS (Safari and Chrome) and PC (Chrome), after being able to log in just fine on both devices up till now

### Language

English

**Comment by FreemanBZH** [comment]
ON ios is due to a new security option,  you must authorize cross-site control in general apple settings of the app

**Comment by raithos** [comment]
I'm going to close this because its basically a duplicate of #641, Am still working on a long term solution
