### ISSUE TITLE
Nimi Chireen is spelled wrong

### ISSUE THREAD

**Issue by skywatcher1138** [raithos/xwing#661]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior
New Resistance pilot Nimi Chereen has her name spelled wrong in YASB 2.0.  It's causing issues when I try to import my squad into TTS.

### Actual Behavior

The correct spelling is Nimi Chereen.

### Language

English

**Comment by Patschke** [comment]
I think our spelling is correct: https://xwing-miniatures-second-edition.fandom.com/wiki/Nimi_Chireen
If TTS uses another name, that should be reported as a bug there...

**Comment by skywatcher1138** [comment]
Fascinating. I had checked another squad builder I sometimes use and it has
card images that show the spelling I suggested, which is why I thought you
were wrong, but then I checked my physical card and it shows the spelling
you have.

So I wonder if maybe FFG had the wrong spelling in a preview article at
some point and then corrected it?

Thanks for the reply and all your hard work!
