### ISSUE TITLE
General Hux

### ISSUE THREAD

**Issue by TobbyZ** [raithos/xwing#662]
![image](https://user-images.githubusercontent.com/71729430/98594605-35beb080-22d5-11eb-8ba2-167173e396a4.png)
Is there something wrong with Hux crew in FO?
The builder says he needs a white or red coordinate action, but it's not possible to put him on the Xi-shuttle (red coordinate) without Tactical Officer.

Works as intended on the Upsilon (white coordinate)

(Putting General Hux on a naked Xi-shuttle works in the official builder)

**Comment by Patschke** [comment]
yep, thats a bug. Thanks for noting, will be fixed.
