### ISSUE TITLE
Request quickbuilds for X-shuttle

### ISSUE THREAD

**Issue by SneakyGitau** [raithos/xwing#663]
Is it possible please to add the xi-shuttle quickbuilds, many thanks

**Comment by Patschke** [comment]
Sure, you're welcome to help. See also #580

**Comment by SneakyGitau** [comment]
Happy to give it a go if you can point me in the right direction.

**Comment by Patschke** [comment]
I've granted you access to https://github.com/Patschke/xwing/blob/master/coffeescripts/content/cards-common.coffee

You may just add the missing quickbuilds as described in the issue above. There should be an edit button that allows you to do so directly via the web-interface of github. If you have any questions feel free to ask.

**Comment by SneakyGitau** [comment]
Think I've submitted the changes correctly.

**Comment by Patschke** [comment]
Yep, works fine for me. Just needed a minor change (37738b924c911c677814a9b36ae2e24b40b5c852), as "Gideon Hask" was specifing the TIE-Pilot (basically the ship given just defines the drop-down it is in, but the pilot's name is not checking if that matches). 

Thank you, this will be live with the next update. 

![grafik](https://user-images.githubusercontent.com/17853362/98811298-ec7b7780-2420-11eb-8237-50852677d1fe.png)

**Comment by SneakyGitau** [comment]
Ah good, I was wondering how it worked out the difference between pilots and crew names.

**Comment by SneakyGitau** [comment]
Patschke would you like me to do the tie-br qb's ?

**Comment by raithos** [comment]
This is being updated now
