### ISSUE TITLE
Rebels unable to use Hate with Maul.

### ISSUE THREAD

**Issue by phantomfo** [raithos/xwing#665]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Equipping the Maul crew upgrade on Leia (Falcon) or Kanan (VCX) would allow me to equip Hate (Dark Side Force Talent) on the pilot. Ezra was used in the list to unlock Maul.

### Actual Behavior

Hate remains greyed out, and Leia/Kanan cannot take Dark Side upgrades.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Thanks for the note, will be fixed.
