### ISSUE TITLE
Import from Official Squad Builder

### ISSUE THREAD

**Issue by wedge1126** [raithos/xwing#673]
This is a feature request.

Please add the ability to import from the official squad builder.

You probably already know, but you can use squad2xws to generate XWS from a squad UUID and you already allow importing from XWS.
http://squad2xws.herokuapp.com/translate/{squadUUID}

Thanks.

**Comment by raithos** [comment]
I honestly have no interest in doing so. squad2xws already converts to xws which means you can import lists that way anyways. the UUID also is not reliable as its specific to each saved list, so if a list is deleted the UUID is no longer valid.

**Comment by wedge1126** [comment]
I know you can do it the way you just described. It would just be more convenient if the feature was in YASB.
I don't really understand your second point. I don't know why you would try importing a list that was deleted.

Well, if you're not interested, that's OK. Thanks for the nice squad builder.

**Comment by Patschke** [comment]
I like that. Part of PR #811
