### ISSUE TITLE
Hi! just wanted to mention that ETA-2 anikin can't equip patience, as it is a light-side upgrade. I use yasb in english. Thanks!

### ISSUE THREAD

**Issue by sadisticKitten** [raithos/xwing#674]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
This is working as intended. ETA-2 Anakin according to the pdf is both light side and dark side, so he can equip both hate or patience for whatever reason. Don't look at me, I don't make the rules.
