### ISSUE TITLE
Wedge not included in the 'second edition' mode

### ISSUE THREAD

**Issue by TLFJ** [raithos/xwing#68]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** If you find you are now missing ships, Conversion kits have been separated from your ship collection and no longer add ships. This was requested by several people in order to more accurately represent their collections. 
To fix the red issue, if you go into your collection and click on the ships tab, there is a list of all available ships and you can update the numbers accurately of all the 1.0 ships you had prior to the 2.0 launch. I am currently working on a setting to disable collection checking if but it wont be out until later.

### Expected Behavior

Wedge pilot for the t-65 in 'second edition' mode

### Actual Behavior

wedge is unavailable. He's in the x-wing expansion pack for 2.0.

### Language

HA there aren't any other languages yet. If you be interested in contrubuting to adding a language I would be your best friend <3

**Comment by raithos** [comment]
working now
