### ISSUE TITLE
Electro=Proton Bomb

### ISSUE THREAD

**Issue by Kleeg005** [raithos/xwing#680]
Greetings, good sir!
As ever, thank you for your hard work!
Sadly, I have encountered a minor bug - the Electro-Proton Bomb has the "Arc Rotate" action as a requirement to equip, rather than the "Reload" action.  Which means that it at present won't equip to, for example, the Andrasta-titled Firespray.  Which makes me sad.
Thanks!

**Comment by raithos** [comment]
fixed in next update
