### ISSUE TITLE
Nein Nunb crew (rebels) does not display card

### ISSUE THREAD

**Issue by SonOfShem** [raithos/xwing#681]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Nein Nunb (rebels, crew) should display "reduce difficulty of bank maneuvers"

### Actual Behavior

Instead shows whatever other card was looked at before

### Language

English

**Comment by raithos** [comment]
fixed
