### ISSUE TITLE
Diamond Boron Missiles handled incorrectly if added as the second missile

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#682]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Diamond Boron missiles, which require 2 missile slots, should remove the missile from the other missile if the slot is filled

### Actual Behavior

State what actually happens here.
![image](https://user-images.githubusercontent.com/8730661/100829579-af0e7680-342f-11eb-97bb-4f3ecf5ad374.png)

To set this up, fill either missile slot with <Not diamond Boron Missiles> and then fill the other with diamond boron missiles.

### Language

English?

**Comment by raithos** [comment]
should be fixed
