### ISSUE TITLE
Hyperspace checkbox does not work in card browser

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#683]
### Expected Behavior

The Hyperspace checkmark would filter all upgrade cards that are hyperspace legal

### Actual Behavior

When the hyperspace legal checkmark is checked, all of all of the cards are removed from the list

![image](https://user-images.githubusercontent.com/8730661/100829938-8935a180-3430-11eb-9503-eca2a8a93cd0.png)

### Language

English

**Comment by Patschke** [comment]
Yep, I can confirm that bug. Looking into it. For now, if you specify a faction (or multiple factions) the hyperspace selector will work.
