### ISSUE TITLE
One “Typo”

### ISSUE THREAD

**Issue by Nestyr** [raithos/xwing#69]
### Expected Behavior

To see “I” in the “Initiative” title in fancy displays/ printouts of lists.

### Actual Behavior

In the “fancy” display/ printout, “I” is still displayed as the (now non-existent) “PS”.

### Language

Here, I cannot help you.  Although I am tri-lingual, those three languages are English, English US (which isn’t a real thing, of course :) ), and English AU (which is also not a real thing).

Cheers from Down Under.

**Comment by raithos** [comment]
done
