### ISSUE TITLE
Nashtah pup has "undefined" costs for Afterburners and Intertial Dampeners

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#691]
![image](https://user-images.githubusercontent.com/10382630/101214879-9bcaf900-3631-11eb-9d3b-ae8ad4af1ee7.png)

**Comment by raithos** [comment]
That's because both of those cards are based on initiative, of which the pup does not actually have a value. I have to think about this. Also the official squad builder is also broke as fuck

**Comment by XPav** [comment]
I guess it'd be based off of the initiative of the pilot that the Hounds Tooth title was attached to but wow that's such an annoying corner case to code up.

**Comment by raithos** [comment]
going to assume that the builder is just wrong and that its based on @XPav suggestion.  this should auto update with points effectively
