### ISSUE TITLE
XWS/yasb link export for Aayla secure failing to load correctly in Vassal

### ISSUE THREAD

**Issue by casperionx** [raithos/xwing#693]
Based on what I see in vassal, it is expecting the following in XWS:

{"description":"","faction":"galacticrepublic","name":"New Squadron","pilots":[{**"name":"aaylasecura","id":"aaylasecura-eta2actis"**,"upgrades":{}}],"vendor":{"yasb":{"builder":"Internal Vassal Squad Builder","builder_url":"none","link":"none"}},"version":"2.0.0"}

However in yasb it is exporting:

{"description":"","faction":"galacticrepublic","name":"Unsaved Squadron","pilots":[{**"id":"aaylasecura","name":"aaylasecura","points":68,"ship":"eta2actis"**,"upgrades":{"force-power":["sense"],"talent":["marksmanship"],"cannon":["autoblasters"],"modification":["stealthdevice"]}}],"points":68,"vendor":{"yasb":{"builder":"Yet Another Squad Builder 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Galactic%20Republic&d=v8ZsZ200Z439X75W125W232WW166&sn=Unsaved%20Squadron&obs="}},"version":"2.0.0"}

Not sure if this should be fixed by you Raithos or from vassal's perspective...I've raised a case on both ends...

**Comment by sjohns37** [comment]
Yeah, TTT overlay has the same issue. It's exepecting "aaylasecura-eta2actis" but gets "aaylasecura" from YASB.

**Comment by raithos** [comment]
Actually yasb has it right vassal has it wrong.
