### ISSUE TITLE
Aayla XWS Fix

### ISSUE THREAD

**Issue by sjohns37** [raithos/xwing#694]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Aayla XWS id to be "aaylasecura-eta2actis" 

### Actual Behavior

Aayla XWS id is "aaylasecura"

### Language

The affected language(s).

**Comment by raithos** [comment]
No the xws is correct
