### ISSUE TITLE
Han Solo - Threat Level 5?

### ISSUE THREAD

**Issue by tpiros** [raithos/xwing#699]
### Expected Behavior

The quick build card that I got as part of the Millennium Falcon extension contains a Han Solo quick build card with a threat level 5, however there’s no such option in the builder.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by tpiros** [comment]
This was closed without an explanation.

**Comment by Patschke** [comment]
I'm sorry that you did not receive any feedback on this issue. For me there is a Han Solo threat 5 Quickbuild (Rebels):
![grafik](https://user-images.githubusercontent.com/17853362/103674768-69d5eb00-4f7f-11eb-86d2-90bd428c5b69.png)

Is this quickbuild different from the one that is listed on your quickbuild card?

**Comment by tpiros** [comment]
@Patschke thanks. When I opened the issue this wasn't there, so I suppose this must have been added recently? Thanks!
