### ISSUE TITLE
multiple tabs

### ISSUE THREAD

**Issue by chumpinski** [raithos/xwing#700]
Hey Raith.  Thanks again for everything you do, and as a Poe/Resistance fan I appreciate your theory craft on the Fly Better time and again.  So dumb question... I generally use Chrome on a Mac.  I used to be able to maintain several tabs with multiple squads open (one in each one) so I can compare more quickly when trying to narrow down/compare similar options on squads.  Recently however only one tab (usually the first opened) will keep the squad loaded, but any other tabs I have open will often just reset to the standard screen.  Just wondering if this is a Github issue with not liking me to be logged in on multiple windows at the same time, or if it's a Chrome thing..  No biggie, just an annoyance.

Thanks again.
Noah

**Comment by raithos** [comment]
That's weird because that doesn't happen for me. the list is retained in the urls, so can you see if the url is changing when you do stuff to it?

**Comment by chumpinski** [comment]
Ok, so I played around with it a bit...   I realized I'd recently discovered the "duplicate tab" function in Chrome.  I instead opened new tabs and loaded YASB again, and loaded squads separately and built new squads from scratch instead of just modifying existing squads and using "save as"  

I think that's the trick, don't use "duplicate tab"   just a quirk.. should be ok.

Thanks again.
