### ISSUE TITLE
Talent upgrade "Snap Shot" correction

### ISSUE THREAD

**Issue by Vellcrow** [raithos/xwing#702]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

The Talent upgrade "Snap Shot" should be included with Major Vonreg's TIE Expansion Pack.

### Actual Behavior

The Talent upgrade "Snap Shot" is not included with Major Vonreg's TIE Expansion Pack.

### Language

English, but possibly others.

**Comment by raithos** [comment]
will be updated shortly
