### ISSUE TITLE
Title "Composure" is missing errata

### ISSUE THREAD

**Issue by zatho-ger** [raithos/xwing#703]
### Expected Behavior

Errata should be added to tell it prevents another action this round.

### Actual Behavior

Errata is not shown, when choosing another language than English

### Language

All but English

**Comment by raithos** [comment]
Unfortunately I do not manage any of the other languages. Also, those languages do not have official errata translations anyways. I'm not sure if we can do anything here really. This might be a live with it kind of situation.

**Comment by zatho-ger** [comment]
Could you maybe just add the english errata text in english between the default text and availability section?

**Comment by Patschke** [comment]
I'll look into updating the translations.

**Comment by Patschke** [comment]
Just as a note why this is taking longer than expected: FFG changed the API I used to pull the card texts from, so I'll have to figure out how to handle the changes...

**Comment by raithos** [comment]
I'd say lets wait and see what AMG does, we don't even know if they're going to continue to use the same workflow for updating the app moving forward.

**Comment by raithos** [comment]
So I'm tempted to set this as will not fix, it seems too much work to manually update every language with the errata text, or we'd have to potentially make new fields for errata and rework the system a bit for it

**Comment by raithos** [comment]
So I've decided that this is an issue we will not fix. I've been thinking about it and in reality we should only provide errata text for text that has been officially provided, and as far as I know, official errata is only provided in English. If individually translators want to take the initiative to do so, that's up to them, but it's not something we'll mandate or keep up to date.
