### ISSUE TITLE
Copying from TTS print view on iPhone doesn’t work

### ISSUE THREAD

**Issue by DeployerOfMajesty** [raithos/xwing#705]
### Expected Behavior

On iPhone, I should be able to hit the print view icon, select the TTS option, and copy the presented text so I can paste it into other apps/programs. (This behavior works fine on desktop browsers; and on iPhone I can do this with, for example, Text view.)

### Actual Behavior

On iPhone, in portrait orientation, the TTS option is not presented at all in print view.

In landscape orientation, the option is presented, can be selected, and seems to show the desired output; but it is not possible to copy this out and paste it elsewhere.

I’ve tried several things in the hopes of making this work. The TTS output in landscape view gives the appearance that the output is auto-selected when first presented; but using the auto-popped Copy option does not grab it, and pasting elsewhere will not bring it over. It is also not possible to select the output manually on the screen—perhaps due to the very small size of the box that the output is presented in? But I’ve tried very hard to even select a single word of the output & copy it, and I cannot get even that to paste elsewhere.

### Language

English

**Comment by raithos** [comment]
this is actually working as intended, we didnt include tts for mobile devices because you cant run tts on a phone, so the copy functionality seemed useless

**Comment by DeployerOfMajesty** [comment]
> this is actually working as intended, we didnt include tts for mobile devices because you cant run tts on a phone, so the copy functionality seemed useless

While it’s true that you can’t run TTS on an iPhone, you can use the TTS output for other things. One example is saving that output into something like a Google Doc or Google Sheet as part of bookkeeping or prep for games. TTS output is very clean and easy to parse.

**Comment by raithos** [comment]
ooookay. I still have lots of doubts but i changed the setting anyway it'll be updated in the next push i do

**Comment by DeployerOfMajesty** [comment]
Thank you! It works beautifully!
