### ISSUE TITLE
Stealth Device should not give cloak action

### ISSUE THREAD

**Issue by eblingus** [raithos/xwing#706]
Stealth Device gives cloak action, and it should not.

**Comment by Patschke** [comment]
It does not do that for me. It is also looking very innocent in the code, so I would be surprised if there is something like a specific combination that triggers this bug. 

Could you provide any additional information on how to encounter this behaviour (e.g. specific ships, combinations of upgrades, browser, ...?). As long as I am unable to reproduce a bug, I cannot investigate or fix it.

**Comment by raithos** [comment]
are you using internet explorer/edge?

**Comment by raithos** [comment]
I'm going to close this until I get a response, as there is nothing in the code to suggest that this actually happens.
