### ISSUE TITLE
Is it possible for it to say whether a list is hyperspace, extended etc on print outs?

### ISSUE THREAD

**Issue by Archangelspiv** [raithos/xwing#708]
Sorry, it's not a bug report but a feature request.

Is it possible to have what format the list was created under when printed out? 

I make up a lot of lists and it would help me a great deal when i want to play X format i can go to my stack and go through what is viable. It would also help when I show my opponent my list, they can see that it is the format we agreed on playing.

maybe not a big feature, but it is one that would help me and hopefully others with organisation.

**Comment by raithos** [comment]
there's actually an icon beside the list name when the list is hyperspace so it already does that. its not explcitily clear that thats the case but its already implemented
