### ISSUE TITLE
Incorrect shield value

### ISSUE THREAD

**Issue by GrinchofGotham** [raithos/xwing#710]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Plo Koon only has 1 shield when the Delta-7 is not upgraded. When expanding the Shield on the print-out version it shows 3 symbols.

### Actual Behavior

It displayed 3 shields on the print out version however listed the correct shield value of 1.

### Language

The affected language(s).

**Comment by raithos** [comment]
will be fixed in the next push
