### ISSUE TITLE
CIS Tri fighter

### ISSUE THREAD

**Issue by darrelltmcd** [raithos/xwing#711]
### Expected Behavior

CIS Trifighter should be able to take Intercept Booster and Advanced SLAM

### Actual Behavior

Unable to equip both of the above upgrades.

The T65 is able to take S-Foils and Daredevil. as it should be able to. and this is the same thing essentially.

Darrell McDowell

**Comment by raithos** [comment]
will be fixed in the next push wehever i do it.
