### ISSUE TITLE
Zam Wessel Pilot shows as unreleased

### ISSUE THREAD

**Issue by direweasel** [raithos/xwing#712]
Zam Wessell pilot shows red when I mouse over it in the list despite owning 2 CIS fire sprays, and the rest of the material shows up fine.  When Zam is selected it says  This squad uses unreleased content! You cannot field this list with your collection!

Which is false.  Thank you.  Sorry if this is reported already, I've never used "github" before now, and have no idea how to navigate here.  I just made an account to post this.

**Comment by raithos** [comment]
i just missed it,. thanks will go out in the next push
