### ISSUE TITLE
Stealth Device

### ISSUE THREAD

**Issue by TheMushuMaster** [raithos/xwing#714]
### Expected Behavior

While you defend, if your charge is active, roll 1 additional defense die.

After you suffer damage, lose 1 charge .

### Actual Behavior

Adds: Agility (1)

While you defend, if your charge is active, roll 1 additional defense die.

After you suffer damage, lose 1 charge .

### Language

English

**Comment by raithos** [comment]
You are technically correct, but I have been told that people wanted to see their agility go up when this card is applied. thats why that's there. So not really sure if i want to actually fix this one.

**Comment by Patschke** [comment]
Well, if any other restriction checks for agility, this would cause the check to possibly return wrong results? But I am fine with both options, as I can see why it is useful to have a reminder of the effectively increased agility in the stats section...

**Comment by raithos** [comment]
This is thankfully not an issue. Points costs are always made off base stats and not modified stats (this is why r2 astromech is costed of off 3 agility and not 2 when Delta b is active)

**Comment by Patschke** [comment]
This is not what I was thinking about. E.g. a TIE Phantom with Stealth Device will allow you to select Precision Ion Engines (restriction: Keyword TIE, Agility = 3). Of course, as this will unequip the stealth device (as both are using the mod slot), it will immediately unequip itself again, so this is not a real issue. However, there might be future upgrades that have a restriction regarding the agility value, that would conflict with this.

**Comment by raithos** [comment]
I guess we have to fix it then. I'll just do it in the next push
