### ISSUE TITLE
Jedi Commander not restricted

### ISSUE THREAD

**Issue by quall3** [raithos/xwing#715]
### Expected Behavior

Jedi Commander can only be equipped to the Eta2 or the Delta7 in command slot.

### Actual Behavior

Jedi Commander can be equipped to every ship in the Command Slot.

**Comment by raithos** [comment]
Im taking your word for it but there is LITERALLY no images of this cards flip side online at all (text i grabbed from the offiical builder). very annoying. will be updated whenever i do my next push
