### ISSUE TITLE
Scum - Z-95 N'dru is not HS legal

### ISSUE THREAD

**Issue by Nutano** [raithos/xwing#716]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Noticed N'dru as an option in Hyperspace.  The ship is not HS legal according to the PDFs.

### Actual Behavior

N'dru is an option when 'Hyperspace' format is selected.

### Language

All it seems (tested 4 of them)

**Comment by raithos** [comment]
will be fixed in the next push
