### ISSUE TITLE
re: quick builds

### ISSUE THREAD

**Issue by maui-beard** [raithos/xwing#717]
Hi! I'm sure this is pretty much the lowest priority you have for YASB, but many of the quick builds are unavailable (e.g. Jake Farrell, most Rebel TIEs). I haven't done a complete audit or anything as I was only able to look through some of the Rebel faction this morning. I was hoping to use YASB to generate lists for an upcoming Random Quick Build tournament and was wondering if there was any way to have the complete roster of quick builds available..

The hard work you put into YASB is much appreciated! Thank you for your time!

**Comment by Patschke** [comment]
I guess the lack of quickbuilds is mostly my fault. Being unable to play any X-Wing for way too long now, I got sloppy in updating YASB as well... If you are interested in adding the missing quickbuilds, I'll happily provide you a how-to-contribute guide.

**Comment by maui-beard** [comment]
sure, i am a total noob when it comes to programming but if i can contribute i'd love to give it a try

**Comment by Patschke** [comment]
There are little to no programming skills required, it is basically just crunshing in data ;-)

I've granted you access to my fork of YASB (basically a fork is a working copy), once you accepted that you can edit https://github.com/Patschke/xwing/blob/master/coffeescripts/content/cards-common.coffee over there. The quickbuilds are listed within this file, currently ending at line 19,009. There should be an edit button on top of the file, so you are able to edit it right from the browser. It is just adding new entries in the way the existing ones are there: Increase the id with each quickbuild by 1, and put in the data in the same way. Don't worry, this is not the live version of YASB, so you can't break anything. One thing to note for persons not used to programming is, that whitespace characters are as important to dumb computers as all the other characters. So even if e.g. a tab may looks the same as a certain number of spaces, they will be treated different.

**Comment by maui-beard** [comment]
great! I'll get started on this asap! thanks

**Comment by maui-beard** [comment]
Sorry to bother: I've decided to start by cataloguing quick builds. I don't know of any good official source for this, because the official PDFs do not appear to include the quick builds from the expansions. So I'm sourcing this from the x-wing wiki (Fandom site), because I do not have all of the expansions in question, and double-checking wherever I can.

Does this seem reasonable to you? (I haven't made any edits in github yet)

**Comment by Patschke** [comment]
I know this issue. I am not aware of any structured official source of the quickbuilds. It is even worse than what you described, since there are three sources of quickbuilds: The pdfs for the conversion quickbuilds, the expansion and some quickbuilds on promo-cards - no idea how to collect those from official (online) sources. There is another open-source project which attempts to collect X-Wing data in a structured way: https://github.com/guidokessels/xwing-data2/tree/master/data/quick-builds - however, I am not sure how well maintained those quickbuilds are. I think the wiki is a good place to start looking...

**Comment by maui-beard** [comment]
I have photographic sources for the missing Separatists and personally own all the Republic expansions, so I'm fully confident that those will be correct when I enter them (they're not even in the wiki!). I've used the wiki to accumulate a list of all the other missing quick builds. If this is good enough for you, it's good enough for me, and I'll start plugging them in at the next available opportunity

**Comment by Patschke** [comment]
sounds fine

**Comment by raithos** [comment]
so is there a resolution to this? if this is going to be an ongoing thing, id rather close it so its not on my active radar of things to fix

**Comment by Patschke** [comment]
I am aware that there are probably still quick builds missing, and I doubt that I'll be fixing it until I can actually play some X-Wing again in person to lift up my motivation for doing so...

**Comment by Patschke** [comment]
I am adding some quickbuilds, let's see how far my motivation doing so gets...

**Comment by Patschke** [comment]
argh. I am correct, that there is a new Hera VCX quickbuild, that has two different kind of wingmates (a phantom and a bunch of A-wings)? 

Guess I'll have to write some code for that, currently we only support one damn kind of wingmate. Why are there always new structures for everything -.- ?
