### ISSUE TITLE
Card Browser: M3-A does not show up in searches for torpedo, missile, or cannon (or hardpoint).

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#719]
### Expected Behavior

When I search for Scum ships that are capable of carrying a torpedo, the M3-A does not show up. Same thing happens when searching for missile, cannon, or hardpoint. (I recognize that "Hardpoint" is the term used for the M3-A weapon mount, which conflicts with the use of "Hardpoint" for huge ships.)

### Actual Behavior

No M3-A in the results list.

### Language

English

**Comment by raithos** [comment]
should have a fix for this in the next push

**Comment by Gdsimms** [comment]
> should have a fix for this in the next push

Thanks! You’re awesome.

**Comment by Gdsimms** [comment]
I don't think this is fixed. Now I get *zero* results for *anything* with missile, cannon, or torpedo.

**Comment by Gdsimms** [comment]
I know you pushed an edit and closed this, but the current behavior is worse than before.

1. Go to "Card Browser"
2. In "Slots," type "Cannon"
3. Look at results. I keep seeing a completely empty list.

**Comment by raithos** [comment]
try now

**Comment by Gdsimms** [comment]
> try now

Looks good! Thanks. 

I have one little beef remaining, but I can't blame you for FFG using "hardpoint" to mean two different things...
