### ISSUE TITLE
R4-P17 isn't HS legal

### ISSUE THREAD

**Issue by KallahanR6** [raithos/xwing#722]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

R4-P17 should be removed from the Hyyperspace astromech drop down for Galactic Republic fleets

### Actual Behavior

R4-P17 is showing on the astromech drop list for Galactic Republic fleets even though R4-P17 isn't Hyperspace legal.

### Language

English at least

**Comment by raithos** [comment]
will be updated in the nex tpush
