### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by starjoe4** [raithos/xwing#723]
Hi, 
In the 'Your Collection' part of the site, under the Ships tab, would it make sense to add a non-editable field that shows the number of ships of that type that are present as a result of the values in the Expansions tab? 

Thanks for a great, really useful app!

**Comment by raithos** [comment]
Is this not covered in the inventory tab?

**Comment by raithos** [comment]
havent heard anything so im going to close this for now

**Comment by starjoe4** [comment]
Hi - sorry, I didn't see your response a few days ago.  This count is in the inventory but then you have to switch back and forth.  I meant it would be useful to also see the running total on the Expansions tab.   Admittedly it's my own fault but at first I didn't realize the expansions automatically added ships, so I was adding #s there after already having added ships.

Also... is there a way to purge your collection data & start over?
