### ISSUE TITLE
Shield Upgrade + Angled Deflectors

### ISSUE THREAD

**Issue by kksuke** [raithos/xwing#725]
### Expected Behavior

TIE Interceptor and TIE Heavy have 2 modification slots and their shield value is 0. 
These can equip Angled Deflectors with equipping Shield Upgrade simultaneously.

### Actual Behavior

1. choose TIE Interceptor or Heavy
2. equip Shield Upgrade
3. try to equip Angled Deflectors but cannot(grey out)

I fixed this problem but a bit ugly code.
Please review the PR.

### Language

all language

**Comment by raithos** [comment]
This is working as intended. The offiical squad builder also does not let you equip angled delfectors if shield upgrade is equipped.
