### ISSUE TITLE
Suggestion About the new multifaction Tab

### ISSUE THREAD

**Issue by DejaMoo** [raithos/xwing#728]
Hi,
I would think that it would really help the multifaction experience if you were able to mix different upgrades and crew of different factions on ships. This may be something that you are already working on. If so, great :),
Thanks

**Comment by raithos** [comment]
This is not going to happen at least not for my builds. the builder is legal upgrades only, and the only reason multi function is added at all is because of the recent upgrades that allow it. we're not going to remove restrictions
