### ISSUE TITLE
Inquisitor tie fighter is supposed to have force abilities

### ISSUE THREAD

**Issue by alphaEJ** [raithos/xwing#729]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** There is a minor problem with saving multi-faction lists that results in all your saved lists being inaccessible. it will be resolved in the next few days, sorry for the inconvience.

### Expected Behavior

inquisitor Tie fighter has force abilities

### Actual Behavior

it doesn't

### Language

English

**Comment by raithos** [comment]
https://puu.sh/HlFlE/471c81174f.png

I'm really confused

**Comment by raithos** [comment]
Since I haven't heard any response to this, I'm going to close. Please respond with more info if the issue is still there
