### ISSUE TITLE
Request: Multifaction but selectable...

### ISSUE THREAD

**Issue by Sycho11** [raithos/xwing#730]
YASB 2.0 doing great!  Multifaction is fun, specifically with the Randomize option.  Can we refine it by allowing us to select factions?  Rather than it being all 7 factions?

i.e. select only Empire and First Order.

This would be fun for list building and randomize option.

Thanks,
Sycho

**Comment by raithos** [comment]
Maybe one day, but right now I have no intention to pay any more attention to this feature then is required of me, I would actually like to forget it exists.
