### ISSUE TITLE
Maul on Scum ships in multi-faction mode

### ISSUE THREAD

**Issue by DeployerOfMajesty** [raithos/xwing#731]
### Expected Behavior

When building a multi-faction list including a Scum ship with a Crew slot, I expect to be able to add Maul to that slot directly.

### Actual Behavior

When building a multi-faction list including a Scum ship with a Crew slot, it appears that I cannot add Maul to that slot without including Ezra Bridger elsewhere in the list. And if I remove Ezra, Maul goes away too.

### Language

Only tested with English.

**Comment by raithos** [comment]
will be fixed in the next update
