### ISSUE TITLE
Incorrect ability description

### ISSUE THREAD

**Issue by ethereal64** [raithos/xwing#732]
### Expected Behavior

Hound's ability affects small ships only ("After a friendly small ship in...") 
![Hound](https://user-images.githubusercontent.com/17793721/110494348-7f59c380-812e-11eb-9afe-ebd7a4191591.png)

### Actual Behavior

The text implies it can affect all ships ("After a friendly ship in...")
![Hound-current](https://user-images.githubusercontent.com/17793721/110494355-808af080-812e-11eb-80b6-b9408b8d5397.png)

### Language

English

**Comment by raithos** [comment]
will be updated in the next update
