### ISSUE TITLE
Description box Scrolling 

### ISSUE THREAD

**Issue by echo9131** [raithos/xwing#733]
### Expected Behavior

Description Box on the right side of the screen scrolls down the page with you, regardless of list size 

### Actual Behavior

when selecting a pilot or ship, the box snaps back to the top of the page.

### Language

State what language translation you use.

**Comment by raithos** [comment]
This is working as intended. if the size of the box exceeds the size of the browser (as is the case with pretty much every ship), it does not stick to the top of the screen. this is because if it always stuck to the top you would not be able to scroll down to see the rest of the box.
