### ISSUE TITLE
Problem on cards texts

### ISSUE THREAD

**Issue by Thunderpombo** [raithos/xwing#736]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** There is a minor problem with saving multi-faction lists that results in all your saved lists being inaccessible. it will be resolved in the next few days, sorry for the inconvience.

### Expected Behavior

When choosing an upgrade for a ship a box shows the card reference with it's text.

### Actual Behavior

When choosing an upgrade card for a ship (notes most commonly on First perder and república, bit happens a few times on other factions). The box shows allthe informativo about the card, excepto for it's main text, It shows title, charges etc, bit the text telling what the card does dont show unless I reload the page, bit even If I do any New choosen upgrades haver the sane issue, needing constantly reloading
### Language

The affected language(s). 

Seen this problema in Portuguese and english

**Comment by raithos** [comment]
I can see that in portuguese many cards have not been kept up to date, which is why some cards are blanked on text. Unfortunately, I don't keep the languages up to date that are not enlgish, so its unlikely that anything will happen in the short term to resolve this.

**Comment by Thunderpombo** [comment]
It happen in english too

Em ter, 16 de mar de 2021 13:01, raith ***@***.***> escreveu:

**Comment by raithos** [comment]
what browser are you using, and can you provide more specific instructions on how to recreate it? because I can't reproduce it on my end.

**Comment by Thunderpombo** [comment]
On Chrome on Pc and on my phone I've had the sane issue.

There is nothing excepcional I Just choose an upgrade, and it's text dont
show. It happen sometimes with FO pilots

Em ter, 16 de mar de 2021 19:08, raith ***@***.***> escreveu:

**Comment by raithos** [comment]
Does this also happen on other browsers on your pc? Again I still cant reproduce it on my machine or anyone I've talked to. What version of Chrome are you using? Can you provide a screenshot of the issue?

**Comment by Thunderpombo** [comment]
It happens on Chrome too. I'm using the latest version. Can't send a
screenshot right now but I'll sendo tomorrow by the morning. But for what
you are saying I guess that problem is happening Just for me. Weird. And
thanks for your help

Em qua, 17 de mar de 2021 23:09, raith ***@***.***> escreveu:

**Comment by raithos** [comment]
I mean on a browser other than chrome. Edge or Firefox. Also, have you tried clearing your browser cache and cookies?

**Comment by Thunderpombo** [comment]
So on Pc i look like stopped having the issue. On my phone the problem
still. A few other people have been complaining about the sane issue. Bit
theu where using the portuguese language. And i dont know which browser. O
guess its a localization problem as you had said

Em sáb, 20 de mar de 2021 00:14, raith ***@***.***> escreveu:

**Comment by raithos** [comment]
ok! well glad its resolved
