### ISSUE TITLE
Defender Vader ability text

### ISSUE THREAD

**Issue by neuromechanik** [raithos/xwing#737]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Text should read You cannot spend (force) charges except while attacking.

### Actual Behavior

Instead reads You cannot spend (force) charges while attacking.

**Comment by raithos** [comment]
lol ill fix this soon
