### ISSUE TITLE
Cannot login with Discord

### ISSUE THREAD

**Issue by buckred5** [raithos/xwing#738]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

On my husband's 15 inch 2017 MacBook Pro running Big Sur 11.2.2 I have been able to log into YASB 2.0 using my Discord credentials using both Safari and Chrome. 

### Actual Behavior

Now on both my husband's MBP and my older 2010 MBP running High Sierra 10.13.6 I am unable to log in with my Discord credentials on both Chrome and Safari. I get a message that says "Authentication failed"  

https://yasb-backend.herokuapp.com/auth/failure?message=invalid_credentials&origin=https%3A%2F%2Fraithos.github.io%2F%3Ff%3DRebel%2520Alliance%26d%3Dv8ZsZ200Z%26sn%3DUnnamed%2520Squadron%26obs%3D&strategy=discord

I am able to log on using my Google and Facebook credentials but when I do none of my saved lists are available. I have followed the instructions regarding cross platform cookie tracking in safari and have set Chrome to allow all cookies and still cannot login. Please advise. 

### Language

English (as far as I know)

**Comment by raithos** [comment]
I was able to log in on discord on my machine so i have a few questions:
1) were you already logged in on discord on your browser before trying to log in or did you enter your credentials in after pressing the discord login button?
2) have you tried deleting all your cookies and cache on the browser?
3) have you tried logging in via discord on a windows based machine?

**Comment by buckred5** [comment]
Yes. Made sure to do all 3. Didn’t work on either of my two Mac laptops.
However, I tried again the next day and it worked on both. I have absolutely no idea what happened as I didn’t do anything different. 

Thanks

Chris

**Comment by raithos** [comment]
cool. phantom bug
