### ISSUE TITLE
long loading times

### ISSUE THREAD

**Issue by uliexox** [raithos/xwing#739]
Hi `Raithos,` I have a question. Did something changed in Yasb2.0? I'd say that it's been a month now that I have trouble with yasb. The charging/ selecting ships and upgrade takes so long that it makes the list building a jawring experience. My laptop is pretty old, but i've been using your page for years and never had a problem before. Idk if someone reported a similar issue before. 
thx for letting me know if there's something I can do on my side to bring down le loading time,

le pirate non binayre

**Comment by raithos** [comment]
There's an issue with the recent versions of firefox and this issue while you log in. no solution yet if youre using firefox, either log out to use it or load yasb on another browesr.

**Comment by uliexox** [comment]
Thx Raithos, that’s v helpful :)

**Comment by XPav** [comment]
As a long-time Firefox user, I've found that if you turn off "Autofill Addresses" this makes much of the problem go away.

![image](https://user-images.githubusercontent.com/10382630/112240946-8ab8ee80-8c06-11eb-9aba-2a178ae15261.png)

**Comment by raithos** [comment]
I COMPLETELY FORGOT ABOUT THIS FIX. THANK YOU @XPav 

@uliexox please try this and see if it fixes things

**Comment by uliexox** [comment]
Does not work for me, but I do my list building on safari and it works well
Thx for the tips tho

**Comment by raithos** [comment]
I'm going to close this as its a duplicate issue of #707 but I am still trying to figure this out
