### ISSUE TITLE
Translating ship names in pilot cards causes an error

### ISSUE THREAD

**Issue by iwazaru** [raithos/xwing#74]
I'm working on the french localization of cards texts (see [here](https://github.com/iwazaru/xwing/commit/eed087a424a484897cb70c6110665d6eb5d68992)).

While trying to translate ships name in pilot cards (eg. "TIE Fighter" is "Chasseur TIE" in french), I encountered an error.

To implement this I looked at how it was done in [YASB 1.0 source code](https://github.com/geordanr/xwing/blob/da8b23473ba4247f86bf48cd06f66f20f3e28969/coffeescripts/cards-fr.coffee#L166).

        "Academy Pilot":
            ship: "Chasseur TIE"
            name: "Pilote de l'académie"

When using the `ship` property and trying to display the Academy Pilot card in the cards browser, the card only partially shows and this error is thrown in the console:

> xwing.src.coffee:953 Uncaught TypeError: Cannot read property 'attack' of undefined
>     at a.renderCard (xwing.src.coffee:953)
>     at HTMLSelectElement.<anonymous> (xwing.src.coffee:934)
>     at HTMLSelectElement.dispatch (jquery.min.js?1537267819:3)
>     at HTMLSelectElement.r.handle (jquery.min.js?1537267819:3)

I'm not sure what causes this, but it seems that the localized name is used as a key, thus the ship is not found, whereas the original english name should be used.
https://github.com/raithos/xwing/blob/master/coffeescripts/xwing.coffee#L1597

**Comment by ManuelWittke** [comment]
Great reply, thanks!
Especially the name is a challenge. I too assume that the name has a key function since there is no other reference.

I will start translating the texts and then have a look into the reference issue.

**Comment by raithos** [comment]
Ok so this works now. However, there are two things you guys should be aware of. 1) theres a new field that translates the english ship names to your language. that must be in place before you add the ship tags
2) once those fields have been entered and changed, any pilot from that ship type without that tag WONT show up. so make sure you hit all the pilots and dont miss any
