### ISSUE TITLE
New RZ-1 pilots with incorrect number of talent slots

### ISSUE THREAD

**Issue by subhedgehog** [raithos/xwing#740]
## YASB 2.0 Bug Report
Three of the new RZ-1 A-wing pilots have an additional talent slot that is not present in the second PDF released March 22nd by AMG.

### Expected Behavior

* Wedge (RZ-1) should have 1 talent slot
* Sabine Wren (RZ-1) should have 1 talent slot
* Derek Klivian (RZ-1) should have 1 talent slot

### Actual Behavior

The 3 pilots listed above have 2 talent slots each.

### Language

N/A

**Comment by raithos** [comment]
https://puu.sh/HrMC0/516ab28033.png FYI

**Comment by subhedgehog** [comment]
😬 So... AMG updated the rebel PDF again in the morning of March 23rd.
All named RZ-1 pilots now have 2 talent slots, in addition to the green squadron pilot. Sorry for the extra work!
