### ISSUE TITLE
RA1 a-wing sabine and hera points

### ISSUE THREAD

**Issue by Gnbio** [raithos/xwing#744]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

RZ-1 A-wung Sabine Wren points cost is 36
RZ-1 A-wung Hera Syndula points cost is 41

### Actual Behavior

RZ-1 A-wung Sabine Wren points cost is 37
RZ-1 A-wung Hera Syndula points cost is 42
### Language

The affected language(s).

**Comment by raithos** [comment]
https://puu.sh/HrMC0/516ab28033.png FYI
