### ISSUE TITLE
Tie Defender Elite configuration

### ISSUE THREAD

**Issue by tcostanti** [raithos/xwing#750]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior
State what you expect to happen here.

Add or remove the Tie Defender Elite configuration to just 1 Tie Defender pilot

### Actual Behavior
State what actually happens here.

The Tie Defender Elite configuration adds and removes from all pilots

### Language

The affected language(s). 

English

**Comment by raithos** [comment]
the config is standardized, it must apply to al ltie defenders. this is working as intended

**Comment by tcostanti** [comment]
Do'h!  Thanks!!!
