### ISSUE TITLE
Sensitive Controls and Vectored Cannons listed as greyed-out config options for all Configuration Slots

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#751]
![image](https://user-images.githubusercontent.com/10382630/112556373-abf91680-8d8f-11eb-8453-cb99a06c97f9.png)

![image](https://user-images.githubusercontent.com/10382630/112556397-bc10f600-8d8f-11eb-9dea-d7fdb4c0a523.png)

![image](https://user-images.githubusercontent.com/10382630/112556435-d3e87a00-8d8f-11eb-9353-eb8cdd7ff259.png)

![image](https://user-images.githubusercontent.com/10382630/112556723-6557ec00-8d90-11eb-8a89-9a7742a07888.png)

**Comment by raithos** [comment]
this is working as intended. since the cards are not restricted by ship, they will just show up in every drop down
