### ISSUE TITLE
Error on Rebel Alliance Conversion Kit card number

### ISSUE THREAD

**Issue by gritche2** [raithos/xwing#760]
## YASB 2.0 Bug Report
When in user collection, Rebel Alliance Conversion Kit is added, the result in term of number of card available if not correct for some cards 
It is french edition of conversion kit

### Expected Behavior

Pilot
Blue Squadron Scout - 1 card
Wild Space Fringer - 2 cards

Upgrade
Seasoned Navigator - 2 cards	
Tactical Officer	- 2 cards

### Actual Behavior

Pilot
Blue Squadron Scout - 2 cards
Wild Space Fringer - 1 card

Upgrade
Seasoned Navigator - 1 card	
Tactical Officer - 1 card	

### Language

French and English.

**Comment by raithos** [comment]
the wiki says that its only 1 seasoned navigator and tac officer. the other cards ill update

**Comment by gritche2** [comment]
> the wiki says that its only 1 seasoned navigator and tac officer. the other cards ill update
@raithos 
Hello, thanks for answer
 I look to my french "rules" and also I found phto of rules of English pack :  https://i.redd.it/wdl90lho1c211.jpg
It confirm that for seasonned and tac there are 2 cards. 
Seems wiki is wrong I will ask modification on wiki (french wiki is good)

Regards

**Comment by gritche2** [comment]
Wiki is now up to date on seasonned and tac
Do I open a new ticket ?

@raithos 

Thanks for your help and your work !
