### ISSUE TITLE
Xws name incorrect

### ISSUE THREAD

**Issue by pakirby1** [raithos/xwing#764]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

After saving a squad with a specified name, when I export to xws, the name field in the xws should match the name I saved the squad with.

### Actual Behavior

After saving a squad with a specified name, when I export to xws, the name field in the xws is “Unamed Squadron”

### Language

English

**Comment by pakirby1** [comment]
![64F832E4-1BEF-43BF-80F9-A53DAEE0494E](https://user-images.githubusercontent.com/5995377/113533370-9ac7bb00-9582-11eb-8981-cb63771e61c1.jpeg)

**Comment by raithos** [comment]
should update in realtime now
