### ISSUE TITLE
Adding Ghost Company to R2-D2 results in erroneous Rotate->Red Calculate on action bar

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#767]
![image](https://user-images.githubusercontent.com/10382630/114221257-4e85cd80-992a-11eb-99c7-978207f83a36.png)

Ghost Company explicitly calls out Rotate -> Red Focus.

![image](https://user-images.githubusercontent.com/10382630/114222008-44b09a00-992b-11eb-8f0b-fc691289fe3c.png)

**Comment by raithos** [comment]
fuck.

**Comment by raithos** [comment]
ok fixed hopefully something else doesnt break.
