### ISSUE TITLE
Zam Wesell (pilot) Condition

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#772]
### Expected Behavior

When equipping Zam Wesell (pilot - seperatist) on the firespray, the condition card texts should be displayed, the same as when ZW is equipped as a Crew

### Actual Behavior

Condition Texts do not show up

Edit: they do show up, but shifted waaaaay down

### Language

All

**Comment by Patschke** [comment]
That issue does not seem to be specific to Zam Wesell: As soon as you hover over a pilot (the right info window shows pilot info) all condition texts are for some reason shifted down below the pilot info

**Comment by raithos** [comment]
So this is a working as intended situation. basically conditions and bomb text gets placed at the bottom of the formatting, and so if your preview changes size (going from an upgrade to a pilot for example), the area stretches down and so the preview for those conditions changes as well. putting them in the area to the right of the box ends up creating really weird interactions that I just don't want to bother dealing with, as you have to deal with now huge white zones on the preview area, OR I have to rewrite the entire visual setup for the page. I'm super not into that until necessary, so I accept that its like that.

**Comment by raithos** [comment]
to be clear, i was aware of this issue a long time ago and tried to come up with a simple fix, and i couldnt find one i was happy with at the time.

**Comment by tinitaet** [comment]
Ok, that makes sense. Thanks for your ongoing efforts to keep this site up and running!
