### ISSUE TITLE
Payload/Device upgrades sometimes have "Bomb" or "Mine" listed in their descriptions in bold text, and sometimes don't.

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#774]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
ive corrected the ones missing them, however, be advised that concussion bombs do not display this text nor does its errata, so i dont want a followup message about missing that. it'll go up in the next update.
