### ISSUE TITLE
Concussion Bombs are missing the bolded "Bomb" keyword in their description.

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#775]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment]
Nope, this is FFG/AMG's problem. they never wrote it on the card or errated it, so I cant put it in.

**Comment by raithos** [comment]
ALSO, DID YOU NOT READ WHAT I WROTE IN RESPONSE FOR THE OTHER TICKET YOU SUBMITTED? COME ON MAN
