### ISSUE TITLE
Republic R2-D2's cost seems to be incorrect when equipped to a Delta-7 when the "7B" configuration is equipped. 7B lowers the Delta's Agility by one... that should lower the cost of R2, but doesn't.

### ISSUE THREAD

**Issue by ObVus** [raithos/xwing#776]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Nah, it's working as intended. Here from the FAQ: 
```

Q: If a ship equips an upgrade that alters one of its values (such as agility), how does this affect variable cost upgrades?

A: Other upgrades are ignored when calculating variable costs, and the base values of the ship are used. 
```

**Comment by Salohza42** [comment]
Thanks, Patrick. Should have remembered that!.
