### ISSUE TITLE
Vader Defender Quickbuild?

### ISSUE THREAD

**Issue by diablodiablo** [raithos/xwing#780]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.
The new sky strike Academy quick builds

### Actual Behavior

State what actually happens here.
Not in there yet

### Language

The affected language(s). 

English

Thank you I love your builder especially the quick build function which is the main reason I use your builder over others. 

I know the sky strike academy is pretty new but I’m going to play my first game in over a year and thought I will do a quick build and I wanna use my new ship but it wasn’t in there yet. :)

Again thank you for all you do and no rush but just wanted to bring that to your attention. 

Thanks!
Tim

**Comment by SpaceMarineCMDR** [comment]
Hey, I'm not a developer but in the meantime you can use the quick build card that came with him since you said you own it. Here is a picture of it in the meantime.

![20210509_162531](https://user-images.githubusercontent.com/84064171/117930023-1b38b480-b2c3-11eb-99cc-5577016d9d92.jpg)

![20210509_162501](https://user-images.githubusercontent.com/84064171/117930102-34d9fc00-b2c3-11eb-9c7f-967ece3fa16d.jpg)

**Comment by Patschke** [comment]
All Quickbuilds from Wave 9 and 7 will be available with the PR on the next update. The [wiki](https://xwing-miniatures-second-edition.fandom.com/wiki/Quick_Build) does not yet list the quickbuilds from [Wave 8](https://xwing-miniatures-second-edition.fandom.com/wiki/Products_/_Wave_8). As I don't own them (yet), I could not add any Tri-Fighter, Eta-2, Firespray and V-Wing quickbuilds. 

If anyone bothers to add those to the wiki, create a PR adding them to YASB (it's not that hard!) or just post them in here, I'll also add them.

**Comment by SpaceMarineCMDR** [comment]
I tried adding the quick builds to the wiki but I don't really know what I'm doing. I have all the ships for Wave 8 except the Tri-Fighter so here's the quick builds.

![20210509_162611](https://user-images.githubusercontent.com/84064171/117992768-ca49b000-b304-11eb-81ba-91941e66404d.jpg)
![20210509_162638](https://user-images.githubusercontent.com/84064171/117992774-cb7add00-b304-11eb-880f-8e4fbcb0ce46.jpg)
![20210509_162658](https://user-images.githubusercontent.com/84064171/117992780-cc137380-b304-11eb-887b-b767f3bd4f4e.jpg)
![20210509_162753](https://user-images.githubusercontent.com/84064171/117992786-cd44a080-b304-11eb-8e86-901d2a0bd4d4.jpg)
![20210509_162827](https://user-images.githubusercontent.com/84064171/117992800-cfa6fa80-b304-11eb-9955-6462db3b9f84.jpg)

**Comment by Patschke** [comment]
Thanks, only Tri-Fighter Quickbuilds are missing now. Everything else should be up to date with the next update
