### ISSUE TITLE
Quickbuilds

### ISSUE THREAD

**Issue by SpaceMarineCMDR** [raithos/xwing#781]
I apologize if I'm leaving this comment in the wrong spot because this isn't really a bug. Im commenting on the state of quickbuilds. They don't appear to have been updated for about 6 months. I recently introduced new players to X-Wing and taught them how to use YASB for quickbuilds. I was surprised to see some ships are missing the quickbuilds entirely. I understand that this is a passion project so this isn't really a complaint as much as it is a request if you find the time. While I prefer 200 pt extended or 500-600 pt epic I know newer players are easily overwhelmed by list building so you guys providing the quickbuilds section is perfect.

**Comment by Patschke** [comment]
Hi SpaceMarineCMDR. Thanks for the feedback. I guess I am somewhat responsible for maintaining the Quickbuilds in YASB, as I've been adding them to the project in the first place. You are correct, that they are quite outdated by now. As I've not been playing any X-Wing for about a year now (I gave TTS a few tries, but for me it is not compareable to a physical game), I have been lacking motivation to update them... Sorry for that.

**Comment by SpaceMarineCMDR** [comment]
Oh no, I totally understand. I appreciate what effort you have put into quickbuilds considering how few people I know who use them. While I don't use them often I find them really great for new players so thanks for your help.
