### ISSUE TITLE
Gleb Errata

### ISSUE THREAD

**Issue by j-man04** [raithos/xwing#784]
### Expected Behavior

Protectorate Gleb errata: "After you coordinate **a friendly ship**, you may transfer 1 orange or red token to the ship you coordinated."

### Actual Behavior

non-errata text appears: 
After you coordinate, you may transfer 1 orange or red token to the ship you coordinated.

**Comment by raithos** [comment]
while i acknowledge the errata is valid, all errata will be done when the pdf is updated, as to be consistent with version updates.

**Comment by XPav** [comment]
There is an official errataed card PDF dated as of right now

https://images-cdn.fantasyflightgames.com/filer_public/e3/de/e3deb4bd-aeea-4333-bcb0-b8b2921b37bd/swz_errata_12.pdf

With the new rules forum stating:

https://forums.atomicmassgames.com/topic/1450-official-card-errata/

'''
These corrections replace the text of the existing card and are considered accurate, and overrides all other printings and will be deleted whenever the Rule Reference and Errata Reference are updated. 
'''
