### ISSUE TITLE
Ships with Configurations that add slots do not duplicate or change pilots correctly

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#789]
1. Take a Republic V-Wing
2. Add the Alpha-3B Besh Configuration
3. Add Thermal Detonators
4. Duplicate the ship -- the duplicate does not have Thermal Detonators
5. Change the pilot on the ship -- the Thermal Detonators disappear

This also happens with the Alpha-class Star Wing's 2 loadouts.  

I think those 3 Configurations are the only ones that this applies too -- the rest don't add slots or are limited anyway.

**Comment by raithos** [comment]
did a lot of reworking but the gist is that it should work as intended now. will update shortly
