### ISSUE TITLE
### Language

### ISSUE THREAD

**Issue by mpiftekius** [raithos/xwing#790]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
This bug report is missing the bug report. I guess something is wrong with some language, but I can't tell what. Would you mind to elaborate the issue further; I could then start to work on the issue instead of working out the issue ;-)

**Comment by raithos** [comment]
I'm going to close this for now. If there's a response I'll reopen the ticket
