### ISSUE TITLE
Obstacles and language issue

### ISSUE THREAD

**Issue by TobbyZ** [raithos/xwing#791]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

State what you expect to happen here.

I'm trying to choose obstacles and expect to see the name and picture of the obstacles.

Also expect the page to be in English when I change the language to "English". It has started to show up as German as a default sometimes when I make or open lists.

### Actual Behavior

When I try and preview the obstacles selection I can only see the first letter/number and not the actual name of the obstacles, or the obstacle picture.

Also the page tends to switch between German and English, and sometimes there is German AND English at the same time, even though the page is set to English.

Same issue in both Chrome and Firefox.
![YASB](https://user-images.githubusercontent.com/71729430/118865342-1dad9680-b8e1-11eb-8531-5d1f87fa6ca2.PNG)

### Language

The affected language(s). 
English(?)
![YASB](https://user-images.githubusercontent.com/71729430/118865227-08d10300-b8e1-11eb-93df-f7d7e1211d38.PNG)

**Comment by Patschke** [comment]
I can confirm that the obstacle names went missing and will look into that. 

It took me a while to find out how to reproduce the screen shot you shared, but I finally figured out how to do so. It will happen if one changes the language and then reloads YASB, I'll also try to look into why that is the case and attempt to fix it. 

Thank you for the bug reports.

**Comment by raithos** [comment]
This is the problem: <option class="coreasteroid0-select" value="coreasteroid0"><span class="translated" defaultText="Core Asteroid"</span>

the default text stuff you're using for the translations doesn't work in option boxes, AFAIK you can't apply html formatting in an options tag, its plaintext only. I'm thinking about a fix right now but the easy solution is to go back to how it was before for the obstacles or to do a large rework. for the time being, I'm going to revert it to how it was before for obstacles until there is a suitable alternative

**Comment by raithos** [comment]
so the asteroids part is back to how it was before. everything else follows the new translations
