### ISSUE TITLE
Hyperspace Legal filter in Card Browser not excluding pilots

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#793]
### Expected Behavior

No Hyperspace cards should appear in the Card Browser after selecting the "Hyperspace legal" checkbox

### Actual Behavior

Many pilots not legal in Hyperspace appear, some random examples:
O-66
Academy Pilot
Alpha Squadron Pilot

### Language

English

**Comment by raithos** [comment]
is fixed, will be updated shortly
