### ISSUE TITLE
Linked

### ISSUE THREAD

**Issue by cutecaleb** [raithos/xwing#794]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Building 2 Tie Interceptors in a new imperial list -- #1 is Turr Phennir, #2 is Lt Lorrir.  Want to add "Sensitive controls" to ONLY configuration upgrade on #1. 

### Actual Behavior

When "sensitive controls" is added on #1, it duplicates into #2 automatically.  If removed from #2, it also removes from #1 automatically.  

[b]Lieutenant Lorrir (41)[/b]
[i]Sensitive Controls (2)[/i]

[b]Turr Phennir (42)[/b]
[i]Sensitive Controls (2)[/i]

[b]Gideon Hask (48)[/b]
[i]Sensitive Controls (2)[/i]
[b][i]Total: 137[/i][/b]

[url=https://raithos.github.io/?f=Galactic%20Empire&d=v8ZsZ200Z467XWWW374Y180XWWW374Y456XWWW374&sn=Unnamed%20Squadron&obs=]View in Yet Another Squad Builder 2.0[/url]

### Language

English

**Comment by Patschke** [comment]
That is working as intended. Sensitive control is a "standardized" upgrade, This keyword implies, that you have to equip either all ships of that type with the upgrade, or none of them. Therefore YASB will kindly add/remove it from all your TIE Interceptors whenever you do so for one of them.

**Comment by Patschke** [comment]
If you are looking for a place to find what those keywords do: The Rules tab of YASB allows you to search for them!

**Comment by cutecaleb** [comment]
Hi Patrick,
Thanks for the response and for looking into it.  I’ve been playing for about 2 years, but never even knew that rule!!  I guess I learn something new everyday.  Thank you again & keep up the GREAT work! 

—Jason
