### ISSUE TITLE
No Illicit slots on Leevan Tenza or Kulbee Sperado

### ISSUE THREAD

**Issue by RiffGit** [raithos/xwing#8]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

Illicit slots on all pilots in Saw's Renegades

### Actual Behavior

No Illicit slot on Leevan Tenza and Kulbee Sperado (T-65 X-Wing)

### Language

English

**Comment by raithos** [comment]
will be fixed in next update
