### ISSUE TITLE
Import seems to be broken

### ISSUE THREAD

**Issue by rrdenicol** [raithos/xwing#801]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

I'm trying to import a CIS squad using XWS:

{"description":"","faction":"separatistalliance","name":"Unsaved Squadron","pilots":[{"id":"baktoiddrone","name":"baktoiddrone","points":47,"ship":"hmpdroidgunship","upgrades":{"missile":["magpulsewarheads"],"device":["drk1probedroids"],"configuration":["repulsorliftstabilizers"]}},{"id":"baktoiddrone","name":"baktoiddrone","points":50,"ship":"hmpdroidgunship","upgrades":{"missile":["discordmissiles","concussionmissiles"],"device":["thermaldetonators"],"configuration":["repulsorliftstabilizers"]}},{"id":"baktoiddrone","name":"baktoiddrone","points":50,"ship":"hmpdroidgunship","upgrades":{"missile":["discordmissiles","concussionmissiles"],"device":["thermaldetonators"],"configuration":["repulsorliftstabilizers"]}},{"id":"baktoiddrone","name":"baktoiddrone","points":53,"ship":"hmpdroidgunship","upgrades":{"missile":["diamondboronmissiles"],"tactical-relay":["kraken"],"configuration":["repulsorliftstabilizers"]}}],"points":200,"vendor":{"yasb":{"builder":"YASB 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Separatist%20Alliance&d=v8ZsZ200Z405X311WWWW221WW323Y405X224W99WWW339WW323Y405X224W99WWW339WW323Y405X238WW222WWWW323&sn=Unsaved%20Squadron&obs="}},"version":"2.0.0"}

### Actual Behavior

The builder hangs and eventually updates with blank selections for ships. Removing Kraken from the list seems to fix things.
Kraken on a Feethan Ottraw Autopilot also seems to be broken.

### Language

English.
![Screenshot at 2021-05-23 23-25-52](https://user-images.githubusercontent.com/930859/119288170-6a190f00-bc1e-11eb-8bb8-fa75c9ac6f5d.png)

**Comment by raithos** [comment]
ah a slight bug with the tactical relay. will be fixed in the next push
