### ISSUE TITLE
No Upgrade type displayed in French

### ISSUE THREAD

**Issue by EGNMX5** [raithos/xwing#802]
## YASB 2.0 Bug Report

You can't see anymore the types of upgrade you can select in drop menu in french language

### Expected Behavior

See wich kind of upgrade is linked to the drop down menu

### Actual Behavior

all kinds of upgrades show "Slot" rather than the corresponding ones, so you don't now which is wich.

![image](https://user-images.githubusercontent.com/63339804/119524352-d9f1db80-bd7d-11eb-8540-835080c99ae5.png)

### Language

French

**Comment by Patschke** [comment]
Will be fixed with the next update, thanks for the report!
