### ISSUE TITLE
YASB 2.0 is in German by default

### ISSUE THREAD

**Issue by susi** [raithos/xwing#803]
### Expected Behavior

When I open a YASB 2.0 link I expect the page to be in English, honouring my browser language preferences.

### Actual Behavior

I get the page in German. I send this accept-language header:
accept-language: en-GB,en-US;q=0.9,en;q=0.8,ja-JP;q=0.7,ja;q=0.6,fi;q=0.5,sv;q=0.4,de;q=0.3

Notice how the preference for German is only scored at 0.3 and English has a higher preference. Just the presence of a language in the accept-language doesn't mean I prefer it in English. It's a fallback of a fallback.

Further more when I select English from the language menu the page ends up in a mix of German / English.

### Language

The affected language(s). German, I didn't test others.

**Comment by Patschke** [comment]
Thanks for the note, I'm aware of the issue. I'll try to find some time to fix it this weekend. The UI-translation backend has been rewritten, and this did not pop up in my testing. We actually query the language preference using js from `navigator.languages` (YASB basically is completely client-side js, so you'll get the same respond regardless of http header), but it should have the same order there. For some reason we fail to select the first available language. Again, I will look into that as soon as possible. Sorry for the inconvenience.

**Comment by Patschke** [comment]
I did not yet find a real reason for this issue. Probably I'll add a system that prioritizes language choices (manual selection > logged in preference from previous selection > browser preference > english) at some point.
