### ISSUE TITLE
Incomplete XWS

### ISSUE THREAD

**Issue by luc-girod** [raithos/xwing#804]
### Expected Behavior

Get a complete XWS when wxporting the following list :
https://raithos.github.io/?f=Scum%20and%20Villainy&d=v8ZsZ200Z89X133WW336WWWWW152Y139XW232Y139XW232Y139XW232Y139XW232Y139XW232&sn=Unsaved%20Squadron&obs=

### Actual Behavior

The last M3-A doesn't get it's Autoblaster, and it's cost is computed as 25 (a naked Cartel Spacer). the complete list also gets pointed at 196 instead of the 199 on the page

### Language

All, probably.

**Comment by Patschke** [comment]
Can't reproduce this issue. When following your link and copying the xws I get: 
```xws
{"description":"","faction":"scumandvillainy","name":"Unsaved Squadron","pilots":[{"id":"hansolo","name":"hansolo","points":59,"ship":"customizedyt1300lightfreighter","upgrades":{"talent":["trickshot"],"crew":["zamwesell"],"title":["landosmillenniumfalcon"]}},{"id":"cartelspacer","name":"cartelspacer","points":28,"ship":"m3ainterceptor","upgrades":{"cannon":["autoblasters"]}},{"id":"cartelspacer","name":"cartelspacer","points":28,"ship":"m3ainterceptor","upgrades":{"cannon":["autoblasters"]}},{"id":"cartelspacer","name":"cartelspacer","points":28,"ship":"m3ainterceptor","upgrades":{"cannon":["autoblasters"]}},{"id":"cartelspacer","name":"cartelspacer","points":28,"ship":"m3ainterceptor","upgrades":{"cannon":["autoblasters"]}},{"id":"cartelspacer","name":"cartelspacer","points":28,"ship":"m3ainterceptor","upgrades":{"cannon":["autoblasters"]}}],"points":199,"vendor":{"yasb":{"builder":"YASB 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Scum%20and%20Villainy&d=v8ZsZ200Z89X133WW336WWWWW152Y139XW232Y139XW232Y139XW232Y139XW232Y139XW232&sn=Unsaved%20Squadron&obs="}},"version":"2.0.0"}
```

As expected, all M3-As are listed with autoblasters. Importing this list back into YASB also gives the correct squad. Where are you trying to use the xws? Maybe there is an issue with that application?

**Comment by luc-girod** [comment]
That was on Chrome / Windows 10.

I'll try again when I get home, but it was quite stubborn around 1200 UTC.

**Comment by luc-girod** [comment]
Ok, I tried again with another list today : https://raithos.github.io/?f=Galactic%20Republic&d=v8ZsZ200Z361X137W136WWWWY361X137W136WWWWY361X138WWWW69WY361X138WWWW69WY361X138WWWW69W&sn=XTC21%20-%20Torbj%C3%B8rn%20%C3%98stb%C3%B8%20-%20Norway%20-%20Galactic%20Republic&obs=coreasteroid5,core2asteroid4,core2asteroid5

And got a similar issue, with the last Y-wing not getting any upgrades in the XWS, it's point value being down to the naked value of 29, and the total list down from 200 to 191 :
`{"description":"","faction":"galacticrepublic","name":"XTC21 - Torbjørn Østbø - Norway - Galactic Republic","pilots":[{"id":"redsquadronbomber","name":"redsquadronbomber","points":43,"ship":"btlbywing","upgrades":{"turret":["dorsalturret"],"torpedo":["protontorpedoes"]}},{"id":"redsquadronbomber","name":"redsquadronbomber","points":43,"ship":"btlbywing","upgrades":{"turret":["dorsalturret"],"torpedo":["protontorpedoes"]}},{"id":"redsquadronbomber","name":"redsquadronbomber","points":38,"ship":"btlbywing","upgrades":{"turret":["ioncannonturret"],"device":["protonbombs"]}},{"id":"redsquadronbomber","name":"redsquadronbomber","points":38,"ship":"btlbywing","upgrades":{"turret":["ioncannonturret"],"device":["protonbombs"]}},{"id":"redsquadronbomber","name":"redsquadronbomber","points":29,"ship":"btlbywing"}],"points":191,"vendor":{"yasb":{"builder":"YASB 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Galactic%20Republic&d=v8ZsZ200Z361X137W136WWWWY361X137W136WWWWY361X138WWWW69WY361X138WWWW69WY361XWWWWW&sn=XTC21%20-%20Torbj%C3%B8rn%20%C3%98stb%C3%B8%20-%20Norway%20-%20Galactic%20Republic&obs=coreasteroid5,core2asteroid4,core2asteroid5"}},"version":"2.0.0","obstacles":["coreasteroid5","core2asteroid4","core2asteroid5"]}`

**Comment by raithos** [comment]
Yeah, this is an issue that I've tested for Dion extensively... I also can't reproduce it on my machine, but from what ive gathered, as soon as you edit the xws in any way, the autoupdate code triggers and then xws is updated to the correct value. But as I've said, since I've never been able to get the initial bug to trigger, I have no idea how to solve it right now.

**Comment by Patschke** [comment]
Moving the `@xws_textarea = ...` code to the same place of the `@tts_textarea = ...` seems to work? From what I can tell the TTS list is up-to-date from the beginning, so this should be fine?
