### ISSUE TITLE
YASB - Chinese Translation

### ISSUE THREAD

**Issue by eunoiagit** [raithos/xwing#808]
Hi YASB 2.0

Do you have any plan for translation into Traditional Chinese?
If not, would you be interested in working with us?

I am part of the oldest X-wing group in Taipei, Taiwan. Here's our FB pages: https://www.facebook.com/groups/xwingtaipei/
Some of our players has contributed to localizing the rules and cards for official X-wing products and Imperial Assault products with local distributor. Sadly, we don't really have official Chinese product aside from the Core Set. Since some translation for wave 1 & 2 and later product already existed, I'm think it might be helpful to put it somewhere people might find useful. 

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
Hi eunoiagit, 

I'd be happy to include Chinese as a language for YASB. I do not speak any Chinese, but we can get that going with your help (there are no plans for any translation/languages at all - if somebody want's to contribute a language I'll try to support that, but that's it). You may look at the [German localization file](https://github.com/raithos/xwing/blob/master/coffeescripts/translations/cards-de.coffee) to get an idea on how we include languages (the German happens to be the most complete, since I maintain the translation system and speak German myself). Basically translating YASB into a new language requires such a file for that language. For the start it is possible to just translate some parts/cards, which will result in the remainder being shown in English. 

Are you familiar with using git (and/or have any experience in coding)? "No" is a perfectly fine answer (and given that you just joined github actually what I'd guess), I just want to know what information I need to provide you to get you started ;-)

I'm always happy if someone wants to contribute towards adding new languages - it's awesome to see, that people all over the world are using YASB

**Comment by eunoiagit** [comment]
Hi Patrick,

Thanks for getting back to me so quickly. I have very little to no skill with git and coding, just some general idea from educational games. I read the file and I see that it’s possible to change everything from UI to the card text. I don’t know how well the UI can adapt to Chinese written character, but the Japanese in the card text area look fine to me. It the text file you show me all the text?

So if we are to proceed, I’ll start by working with one another players in my group to sort out how complete our translation is, and once we have a sizable chunk ready, we can start working on the text file. I’ll get back to you at the end of the week.

從 Windows 10 的郵件<https://go.microsoft.com/fwlink/?LinkId=550986>傳送

寄件者: Patrick ***@***.***>
傳送時間: 2021年6月7日 下午 05:42
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [raithos/xwing] YASB - Chinese Translation (#808)


Hi eunoiagit,

I'd be happy to include Chinese as a language for YASB. I do not speak any Chinese, but we can get that going with your help (there are no plans for any translation/languages at all - if somebody want's to contribute a language I'll try to support that, but that's it). You may look at the German localization file<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fraithos%2Fxwing%2Fblob%2Fmaster%2Fcoffeescripts%2Ftranslations%2Fcards-de.coffee&data=04%7C01%7C%7Ca44ac4e828314dd47cb908d9299888cc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637586557371060303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xr3JRCPzXcLusppxqBrLkakPDUpTkAgvex0q0alQL6U%3D&reserved=0> to get an idea on how we include languages (the German happens to be the most complete, since I maintain the translation system and speak German myself). Basically translating YASB into a new language requires such a file for that language. For the start it is possible to just translate some parts/cards, which will result in the remainder being shown in English.

Are you familiar with using git (and/or have any experience in coding)? "No" is a perfectly fine answer (and given that you just joined github actually what I'd guess), I just want to know what information I need to provide you to get you started ;-)

I'm always happy if someone wants to contribute towards adding new languages - it's awesome to see, that people all over the world are using YASB

**Comment by Patschke** [comment]
Yep, it should in principle be possible to provide an (almost) complete translation of YASB to any other language. The file I pointed you to is not 100% complete, (the last few expansions are missing), and maybe I overlooked some UI elements. As far as I know, a translation of the UI should also be possible, at least it is for the Japanese version? But maybe I don't quite get the issue that you are worried about (the Chinese characters should not make any problems - is there more to do e.g. regarding some sort of formatting?). 

When you start working on the Chinese language file, just a few notes on stuff you should be aware of: Make sure that you keep the formatting intact. Whitespace characters (e.g. the number of spaces at the start of a line) are not just there to make stuff look nice, but are important for the computer to actually correctly interpret the file. Stuff like e.g. replacing spaces with tabs (even if they can look the same) will break the functionality. Also make sure that quotation marks are used correctly. They tell the computer where a text starts and ends. One can use four different types (`"`, `'`, `"""`,`'''`), where it is important to start and end one text with the same type (they do have some slightly different meanings, but you can ignore that). Make sure to not use them inside the text (e.g. for card names like `"Quickdraw"`). 

If you are interested in using git to work together inside your player group, you may want to create a fork of this project. That is basically creating a copy of the YASB source code for you. You can then give anybody you want permissions to modify the files inside that fork, and we can (once you consider the translation good enough to be put online) grab it from there and merge it into the main repository. If you want to create and work on the Chinese language file in any other way, I'm of course also happy to retrieve contributions.

**Comment by eunoiagit** [comment]
Hi Patrick,

Sorry for the late reply. I think I’ve over-blown about the character issue, but thanks for the re-assurance.

We are compiling our translation currently. Thanks for the notes on the format. I’m thinking it might be easier for you if I use github. Let me know which translation file I should create a fork for.

從 Windows 10 的郵件<https://go.microsoft.com/fwlink/?LinkId=550986>傳送

寄件者: Patrick ***@***.***>
傳送時間: 2021年6月8日 下午 10:38
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [raithos/xwing] YASB - Chinese Translation (#808)


Yep, it should in principle be possible to provide an (almost) complete translation of YASB to any other language. The file I pointed you to is not 100% complete, (the last few expansions are missing), and maybe I overlooked some UI elements. As far as I know, a translation of the UI should also be possible, at least it is for the Japanese version? But maybe I don't quite get the issue that you are worried about (the Chinese characters should not make any problems - is there more to do e.g. regarding some sort of formatting?).

When you start working on the Chinese language file, just a few notes on stuff you should be aware of: Make sure that you keep the formatting intact. Whitespace characters (e.g. the number of spaces at the start of a line) are not just there to make stuff look nice, but are important for the computer to actually correctly interpret the file. Stuff like e.g. replacing spaces with tabs (even if they can look the same) will break the functionality. Also make sure that quotation marks are used correctly. They tell the computer where a text starts and ends. One can use four different types (", ', """,'''), where it is important to start and end one text with the same type (they do have some slightly different meanings, but you can ignore that). Make sure to not use them inside the text (e.g. for card names like "Quickdraw").

If you are interested in using git to work together inside your player group, you may want to create a fork of this project. That is basically creating a copy of the YASB source code for you. You can then give anybody you want permissions to modify the files inside that fork, and we can (once you consider the translation good enough to be put online) grab it from there and merge it into the main repository. If you want to create and work on the Chinese language file in any other way, I'm of course also happy to retrieve contributions.

**Comment by raithos** [comment]
any update on this?

**Comment by eunoiagit** [comment]
Hi! We are slowly working our way through the translation.
I would like to know which language file I can make a copy of so I can see how the format could work.

從 Windows 10 的郵件<https://go.microsoft.com/fwlink/?LinkId=550986>傳送

寄件者: ***@***.***>
傳送時間: 2021年6月29日 下午 02:30
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [raithos/xwing] YASB - Chinese Translation (#808)


any update on this?

**Comment by Patschke** [comment]
In terms of UI the german language file is the completest (https://github.com/raithos/xwing/blob/master/coffeescripts/translations/cards-de.coffee). 
In terms of cards the english file is the completest (https://github.com/raithos/xwing/blob/master/coffeescripts/content/cards-en.coffee). 

You can _fork_ the complete repository (there is a button at the top right) to create your own, independant working-copy of the complete project. In that _fork_ I'd recommend to copy the `cards-de.coffee` file to a new file (probably `cards-zh.coffee`?). You can then edit this new file, adding in the chinese translations. Editing is possible online via the browser interface (there is an edit button on top of each file), or offline. If you want to work offline, you need to _clone_ your own _fork_ (which is basically a fancy name for downloading it) using `git clone ...`. This will download your _fork_ to your computer, where you can edit the files using whichever tools you like. To upload it again, you need to _commit_ and _push_ the changes you made (using `git add .`, `git commit` and `git push`). When you are done doing that, leave us a note - we are able to include any edits from the _fork_ to the actual live version of YASB. You can not directly edit/create new files in this (the "live"/official) repository yourself. 

I hope this helps you to understand how to get started? If you have any more questions on the structure of the language files feel free to ask.

**Comment by eunoiagit** [comment]
Hi Patrick,

I’ve used your advise and fork a complete repository of the project, and create a new file cards-zh.coffee. Since we’re focusing on the cards first, I decided to copy the english text first. At the moment editing from the web should suffice. Once we have a sizable portion (maybe 80%), we’ll let you know. As I’m going to be more busy with real life job for the next few weeks, I don’t expect to be able to do much for now. I’ll check back at the end of the month to let you know how much progress we’ve made.

從 Windows 10 的郵件<https://go.microsoft.com/fwlink/?LinkId=550986>傳送

寄件者: Patrick ***@***.***>
傳送時間: 2021年7月2日 下午 09:29
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [raithos/xwing] YASB - Chinese Translation (#808)


In terms of UI the german language file is the completest (https://github.com/raithos/xwing/blob/master/coffeescripts/translations/cards-de.coffee<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fraithos%2Fxwing%2Fblob%2Fmaster%2Fcoffeescripts%2Ftranslations%2Fcards-de.coffee&data=04%7C01%7C%7Cc953af0d89c948b5af7b08d93d5d5de1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608293479576429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=briynegYCtSidSm8fWscKLrVpCyKyJ7NxX6BnvrXmuw%3D&reserved=0>).
In terms of cards the english file is the completest (https://github.com/raithos/xwing/blob/master/coffeescripts/content/cards-en.coffee<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fraithos%2Fxwing%2Fblob%2Fmaster%2Fcoffeescripts%2Fcontent%2Fcards-en.coffee&data=04%7C01%7C%7Cc953af0d89c948b5af7b08d93d5d5de1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608293479586379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tmc4JnXFkgIOpLCxoKT4pZD089zgLcr8tqfBDsbaBhE%3D&reserved=0>).

You can fork the complete repository (there is a button at the top right) to create your own, independant working-copy of the complete project. In that fork I'd recommend to copy the cards-de.coffee file to a new file (probably cards-zh.coffee?). You can then edit this new file, adding in the chinese translations. Editing is possible online via the browser interface (there is an edit button on top of each file), or offline. If you want to work offline, you need to clone your own fork (which is basically a fancy name for downloading it) using git clone .... This will download your fork to your computer, where you can edit the files using whichever tools you like. To upload it again, you need to commit and push the changes you made (using git add ., git commit and git push). When you are done doing that, leave us a note - we are able to include any edits from the fork to the actual live version of YASB. You can not directly edit/create new files in this (the "live"/official) repository yourself.

I hope this helps you to understand how to get started? If you have any more questions on the structure of the language files feel free to ask.

**Comment by raithos** [comment]
any update here?

**Comment by raithos** [comment]
I'm going to close this for now. If there is an update, I can reopen the task
