### ISSUE TITLE
Quad jumpers not valued correctly

### ISSUE THREAD

**Issue by mordrek70** [raithos/xwing#810]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

there would be a didfferent value for the various pilots for the quadjumper.

### Actual Behavior

all the quadjumer pilots are listing as bas 29 points for all four pilots in the scum list
![glitch](https://user-images.githubusercontent.com/64400703/121517019-3b7aa100-ca32-11eb-8351-80fdb8e47109.jpg)
.

### Language

The affected language(s).

**Comment by Patschke** [comment]
They all actually have the same point cost. Everything working as intended.
