### ISSUE TITLE
Moving ships below New Ship option is buggy

### ISSUE THREAD

**Issue by Patschke** [raithos/xwing#812]
I think it should not be allowed to move ships below the New Ship option. Otherwise e.g. the duplicate button on that ship will stop to work (`Cannot copy from self`). There are various other occasions where we assume, that the last entry of the ship list is the empty New Ship option. 

I've just noticed that you actually implemented that feature - I like it a lot :D

**Comment by raithos** [comment]
ok i have a fix, it shouldnt happen anymore, or at least happen a lot less
