### ISSUE TITLE
Corsair Crew incorrectly listed as Separatist not Scum

### ISSUE THREAD

**Issue by mephiston-x** [raithos/xwing#813]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

According to the points PDF and the spoiled image for Huge Ship & Epic Battles the restriction on "Corsair Crew" is Scum 

https://images-cdn.fantasyflightgames.com/filer_public/af/83/af83821b-c639-492f-9736-e55a63b33c07/huge_ships__epic_upgrades_trident.pdf

https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/192874662_1040039803192138_9184014839512616043_n.png?_nc_cat=111&ccb=1-3&_nc_sid=730e14&_nc_ohc=0y_yePrqr94AX8o4MFj&_nc_ht=scontent-sjc3-1.xx&oh=857cc24c99d7ddf5d4c0ff2acf43fa63&oe=60D77BC4

### Actual Behavior
Corsair Crew is unavailable for Scum Trident 
For Separatist Trident team Selection shows as
Corsair Crew (unreleased)
Restrictions: Extra , **Separatist Alliance**

### Language

All

**Comment by raithos** [comment]
will be fixed shortly
