### ISSUE TITLE
Jumpmaster 5000 does not appear in the MyCollections list.

### ISSUE THREAD

**Issue by djumeau** [raithos/xwing#815]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by djumeau** [comment]
Select "Your Collection" / "Expansions" Tab

Jumpmaster does not appear.

**Comment by raithos** [comment]
The jumpmaster is in the Punishing One Expansion Pack, so this is working as intended
