### ISSUE TITLE
Tie Defender Elite configuration card

### ISSUE THREAD

**Issue by FO3Winger** [raithos/xwing#824]
## YASB 2.0 Bug Report
The Skystrike Academy Squadron Pack addon "Tie Defender Elite" adds the configuration to ALL of my Tie Defenders in the squad. When I go to delete it from one ship, it deletes it from all of them. 

This should be able to be selected like the "Servomotors S-Foils" for the T-65 X-Wing, etc.

My current situation is that I'm building a squad of 5 Tie Defenders and only have 2 "Tie Defender Elite" cards but it either makes all my ships have it and gives me a "Cannot field this list" warning, or I just can't add it to my ships and can't reference the points correctly.

Thanks in advance if you're able to fix this!

**Comment by XPav** [comment]
TIE Defender Elite is a **Standarized** upgrade, meaning all TIE/Ds in your list must have it if any of them have it.

**Comment by FO3Winger** [comment]
Ah ok, thanks for the clarification! I guess I just need more cards then.

~Nick Champion
