### ISSUE TITLE
Language change issues

### ISSUE THREAD

**Issue by arkadiuszkuna** [raithos/xwing#825]
I once changed language to german and now even though I click english, yasb goes back to german or some weird mix of english and german.

[https://imgur.com/a/WEYKwmY](url)

F5 doesn't help, ctrl F5 doesn't help. When go into incognito, it's ok.

**Comment by raithos** [comment]
you might need to clear your cache in your browser, its probably saviing the language in there and just needs to be cleared. are you also logged in?

**Comment by arkadiuszkuna** [comment]
I tried to clear my cache, but the issue still persists  across my devices.
I am logged in into my Google Chrome. Logged out of YASB.

**Comment by pogster** [comment]
I have the same problem.

**Comment by pogster** [comment]
Duplicate with #803 maybe?
