### ISSUE TITLE
Still a typo on the compromising intel condition card

### ISSUE THREAD

**Issue by JediOswald** [raithos/xwing#830]
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times.

Note 1: If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
Note 2: Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

Expected Behavior
State what you expect to happen here.
Vi Moradi to be spelled Vi Moradi on the Compromising Intel Condition Card.

Actual Behavior
State what actually happens here.
Vi Moradi is spelled Vi Morandi (With an n in Moradi) on the Compromising Intel Condition Card still. Previously it was spelled incorrectly twice but now it is only spelled incorrectly once.
![Morandi](https://user-images.githubusercontent.com/87926233/127245714-fbc576a5-5df8-41f3-a913-b738b9aecc9e.png)

Language
English
The affected language(s).
English/All?

**Comment by raithos** [comment]
will be updated soon
