### ISSUE TITLE
minor error in straight maneuver graphic?

### ISSUE THREAD

**Issue by keatonr06** [raithos/xwing#833]
There's a few pixels of black going through the straight maneuver template graphic. I don't see it in the other graphics, so figured this may be an error. This is a supperrrr small thing and maybe it doesn't matter to you, but I figured it doesn't hurt much to point it out in case you feel like adjusting the svg. 

![image](https://user-images.githubusercontent.com/23128988/128568704-530fefad-4f46-44bb-b12a-e2e427b8b267.png) 

(Note the small black bar going through the base of the triangle)

**Comment by raithos** [comment]
i have a fix incoming, i hate that you pointed that out to me it must be addressed now that i see it
