### ISSUE TITLE
config slots don't appear to be showing up in the infopanel

### ISSUE THREAD

**Issue by keatonr06** [raithos/xwing#834]
config slots don't appear to be showing up in the infopanel

![image](https://user-images.githubusercontent.com/23128988/128580398-28fef4c1-9f61-4918-891c-0d96825057e9.png)

**Comment by keatonr06** [comment]
actually I think I found the bug. I think this class needs to be "config"

![image](https://user-images.githubusercontent.com/23128988/128580569-5677f35c-7ef6-4b4f-99f5-9bbee7c20f88.png)

**Comment by raithos** [comment]
thanks will be fixed soon
