### ISSUE TITLE
Empire: TIE Interceptor configuration slot bug

### ISSUE THREAD

**Issue by Buckelkratz** [raithos/xwing#836]
## YASB 2.0 Bug Report
TIE Interceptor configuration slot bug

### Expected Behavior

How to reproduce:
a) Choose "Galactic Empire" faction
b) Add a "TIE Interceptor" to your squad
c) Equip the ship with "Sensitive controls" in its configuration slot
d) Copy the ship (you have now 2 TIE Interceptors with "Sensitive controls" in your squad")
e) Remove the "Sensitive controls" in the slot of ship 2

f) What should happen now: Slot of ship 2 is cleared, Slot of ship 1 still has "Sensitive controls" equipped

### Actual Behavior

After e) is executed, also the slot of the other TIE Interceptor gets his slot cleared => BUG
If you have 3 or more ships like this, ALL configuration slots are handled the same

### Language

Tested in English on Firefox

**Comment by Patschke** [comment]
"Sensitive Controls" have the keyword "Standardized". As you can look up in the Rules section, this keyword indicates that `During squad building, if a player selects a ship with a standardized card equipped, each ship of that ship type (i.e., full ship name) in that player's squad must be equipped with a copy of that standardized card.. `

There is no bug here, this is simply working as intended. You cannot remove the "Sensitive Controls" from just one interceptor, as that would be against the rules.
