### ISSUE TITLE
R2D2 republic exporting as rebel r2d2 astromech

### ISSUE THREAD

**Issue by chrisalleng** [raithos/xwing#837]
## YASB 2.0 Bug Report
Republic AStromech R2D2 XWS export has the wrong value
### Expected Behavior
Should be 'r2d2-republic'

### Actual Behavior
exports as 'r2d2'

Sample export:
{"description":"","faction":"galacticrepublic","name":"Unnamed Squadron","pilots":[{"id":"jedigeneral","name":"jedigeneral","points":51,"ship":"eta2actis","upgrades":{"astromech":["r2d2"]}}],"points":51,"vendor":{"yasb":{"builder":"YASB 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Galactic%20Republic&d=v8ZsZ200Z436XWW340W&sn=Unnamed%20Squadron&obs="}},"version":"2.0.0"}
### Language

The affected language(s).

**Comment by raithos** [comment]
will be fixed soon
