### ISSUE TITLE
Can't chose Dalan Oberos

### ISSUE THREAD

**Issue by Kybelor** [raithos/xwing#840]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Able to chose Dalan Oberos in the Star Viper while having 1 Scum and Villany conversion Kit

### Actual Behavior

He is grey'd out and cannot be chosen

### Language

The affected language(s).

**Comment by XPav** [comment]
Strange -- the builder won't grey out based on what you say you've owned, it'll just warn you on the side.

I can chose him just fine.

**Comment by Patschke** [comment]
Does the squad already contain Dalan Obeers in the Kimogila?

**Comment by raithos** [comment]
Im going to close this since we cant reproduce and I haven't heard a response
