### ISSUE TITLE
Daredevil

### ISSUE THREAD

**Issue by neuromechanik** [raithos/xwing#843]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Daredevil requires small ship and white boost

### Actual Behavior

Able to equip Daredevil on HWK-290 without engine upgrade. 

### Language

The affected language(s).

**Comment by raithos** [comment]
This will take some time to fix, but will be super low priority because even if you can equip it you cant use it in that situation without engine upgrade anyways.
