### ISSUE TITLE
Website locks up for about 10 seconds...

### ISSUE THREAD

**Issue by ckdragons** [raithos/xwing#847]
Using FireFox 92.0 (64-bit) on Windows 10.

It seems every time that I select a new drop-down menu, the site freezes for about 10 seconds. This seems to happen on all my computers, including an iPad Mini 4 using Safari on iOS 14.

**Comment by raithos** [comment]
can you try some of the solves in #799? the most prominant solve is to disable autofil which seems to have a great effect.

**Comment by ckdragons** [comment]
Thank you, that seemed to work! While I didn't have Autofill Addresses enabled, I did have Autofill Credit Cards enabled. Disabling that seems to allow the site to respond much faster.
