### ISSUE TITLE
Homing missiles are missing

### ISSUE THREAD

**Issue by stavrjim** [raithos/xwing#853]
When you open the drop down for missiles, Homing Missiles do not appear after the last update

### Language

English
![image](https://user-images.githubusercontent.com/26796723/134644478-21e29fb4-7c72-4808-987b-81cd7e5fa98c.png)

**Comment by Patschke** [comment]
Just in case somebody else reads this issue and wondered what happened: Homing Missiles are currently not Hyperspace legal. Everything working as expected (Guess you figured that out :D)

**Comment by stavrjim** [comment]
Yes, and closed the issue because mornings are hard 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
