### ISSUE TITLE
Calculate Action For Resitance / Search not working

### ISSUE THREAD

**Issue by futil43** [raithos/xwing#862]
### Expected Behavior

Display pilot that have Calculate on ther action bar even if this isn't a default action from  the ship.

### Actual Behavior

Calculating ship/pilot are only Separatist : Can't find any other ship (Guri, 4l-om ...) 
I think (but haven't verify) the impact is on all pilot with modified action bar as they are listed in another part of the pilot description.

### Language

All Languages

**Comment by Patschke** [comment]
Thanks for the note. Should be only calculate actions affected, and will be fixed with the next update.
