### ISSUE TITLE
TIE/in Interceptor can't equip Angled Deflectors

### ISSUE THREAD

**Issue by ckdragons** [raithos/xwing#863]
As per the recent AMG forum posting, a TIE/in Interceptor equipped with Shield Upgrade should be able to also equip Angled Deflectors.

https://forums.atomicmassgames.com/topic/3409-tie-interceptor-with-shield-upgrade-and-angled-deflectors/

**Comment by Patschke** [comment]
Well, I am not sure if I want to implement that straight away. Are answers in that forum supposed to be official rulings?

The issue I have is: If modified stats are used for checks like that, I don't see why the modification done by the Angled Deflectors itself is not considered. So after equipping Angled Deflectors to any 1-shield ship (including TIE/in with shield upgrade), the shield value is reduced to 0 - so the ship does no longer fulfill the requirements, making the Angled Deflectors illegal. This is clearly not how it is supposed to work. 

The closest existing ruling in terms of cards referring to ship stats are variable point costs, here the unmodified value is used according to the rules ref: 
> Q: If a ship equips an upgrade that alters one of its values (such as agility), how does this affect variable cost upgrades?
> A: Other upgrades are ignored when calculating variable costs, and the base values of the ship are used. 

I do however see, that requirements in terms of actions can indeed be met by other upgrades providing those actions. 

Note that the official builder will also not allow you to equip that combination - however, as that builder is and always was buggy, I do not count that as an argument for or against that case. 

One last remark: Reinforce will reduce damage not below 1, and taking 1 dmg on an Interceptor is likely already bad enough. So I don't consider this issue urgent, as the idea of equipping those upgrades seems not too helpful after all. Of course, I still strive for correct implementations of the game mechanics and appreciate bug reports like this one!

**Comment by ckdragons** [comment]
I understand your concern, and everything you said makes sense, including this being a low priority issue. Playing Imperial myself, I wouldn't use this combination. I only mention this because, like you, I'm a completionist myself.

My understanding is the AMG XWing Forum is the "official" rules posting as the responders there are AMG employees.

Further, the official FFG squad builder is no longer supported as AMG announced there are abandoning it. Players are now reliant on great 3rd party squad building sites like yours!

I'm going to post a follow up forum question, asking them to clarify this response. I'll be including the information you mention above. I'll let you know how they respond.

**Comment by Patschke** [comment]
I've already asked them as well - they'll discuss it again (the link from your initial post is already no longer working).

**Comment by raithos** [comment]
There was a change request half a year ago about the same issue. I rejected it for the same reason, at the time the official builder did not allow you to equip it. Since the link doesn't exist anymore, There wont be any change until we get an official response that sticks. I am going to close this until we get a new response.

@Patschke the rules forums are supposed to be binding, so if they say its so, we should adjust.
