### ISSUE TITLE
Nashtah Pup

### ISSUE THREAD

**Issue by YautjaDreads** [raithos/xwing#870]
I am wondering why I can't add Nashtah Pup after adding a Hounds Tooth to the list

**Comment by Patschke** [comment]
Works fine for me. 

![image](https://user-images.githubusercontent.com/17853362/135969846-7993ac4e-9af2-4d04-9c39-590a9446b15b.png)

Note that the Nasthah Pup is not Hyperspace legal (https://images-cdn.fantasyflightgames.com/filer_public/c9/5f/c95fee08-1720-4a62-82c0-6fc66e3662fa/scum.pdf), so you can't add it to the list in Hyperspace mode if that's your question? Note that you also need to equip the Hounds Tooth title to a YV-666 (just adding the ship is not sufficient). 

If this really is a bug please provide additional steps on how to encounter it. Simply adding an YV-666, equipping the title and adding a Nashtah Pup works for me.

**Comment by YautjaDreads** [comment]
Thanks for the quick response! I actually felt really stupid after figuring it out right after I submitted this! Haha my bad

Von meinem iPhone gesendet
