### ISSUE TITLE
Squad Name when sharing List via "Text"

### ISSUE THREAD

**Issue by quall3** [raithos/xwing#871]
### Expected Behavior

When i have a list saved with a name, and share it via "Print/Export" -> "Text" the url contains the name of the list.

### Actual Behavior
The url always contains:
"Unsaved%20Squadron" as squad name.

**Comment by quall3** [comment]
wenn es eine gespeicherte liste ist steht da:
"Unnamed%20Squadron"

**Comment by Patschke** [comment]
I can confirm this bug. Actually it is not related to the print/export, but updates to the name are lacking. I believe there are 2 bugs we need to fix involved here: 
1. Squad name is not updated when saving a squad (Reproduce: Create new squad, save as. The name does not show up in the name fiel, nor in the url and then of course also not in the export)
2. Editing the squad name only updates the squad after doing some other change (Reproduce: Edit the squad name (icon beside squad name). The url does not (yet) update, as well as the exports. Only after another change it will)
I'll look into fixing these. 

Thanks for the report.
