### ISSUE TITLE
Wartime Loadout

### ISSUE THREAD

**Issue by Kleeg005** [raithos/xwing#874]
### Expected Behavior

The "Wartime Loadout" Configuration for the Resistance Y-Wing is "Standardized" and should automatically propagate throughout a list to ensure list legality.

### Actual Behavior

I can currently build a list in which I have both the "Wartime Loadout" Configuration as well as standard, non-Configured ships.

### Language
English.

**Comment by Patschke** [comment]
Duplicate of #873
