### ISSUE TITLE
Ships can be dragged above the dropdown menu

### ISSUE THREAD

**Issue by durand-wni** [raithos/xwing#878]
We can drag ships above the dropdown menu for selecting ship chassis (see [screenshot](https://imgur.com/a/hUFoR3d))

### Expected Behavior

When I drag up a ship, it should still display below the dropdown for adding ships.

### Actual Behavior

Ship is dragged above the dropdown menu

### Language

English

**Comment by raithos** [comment]
this is working as intended. the way the sorting works, there's no way to ensure the new ship addon is always locked to the bottom. this doesnt stop you from adding new ships, so functionally it has no impact on functionality.
