### ISSUE TITLE
Saboteur's Map isn't limited

### ISSUE THREAD

**Issue by Spyke114** [raithos/xwing#881]
While I'm submitting minor bugs...

### Expected Behavior

Can't equip more than one copy of Saboteur's Map because it's limited to 1 copy.

### Actual Behavior

Can equip more than one copy of Saboteur's Map because site is missing that it's limit 1.

### Language

English (didn't check others)

**Comment by Patschke** [comment]
will be fixed with next update, thanks for the note.
