### ISSUE TITLE
Blue Squadron Scout and K-2SO in the U-Wing have the wrong upgrade slots

### ISSUE THREAD

**Issue by JediOswald** [raithos/xwing#884]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Blue Squadron Scout is not supposed to have a talent slot, and K-2SO is supposed to have a talent slot (In the U-Wing)

### Actual Behavior

Blue Squadron Scout has the talent slot and K-2SO does not.

### Language

All.

**Comment by raithos** [comment]
ok will be fixed shortly
