### ISSUE TITLE
Bugs YASB

### ISSUE THREAD

**Issue by MightySouthside** [raithos/xwing#889]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

I have noticed some mistakes in the actual German YASB-build: 
When you equip weapons to epic ships, the OS-1 Configuration from the Alpha Class Star Wing appears instead of the Launch Tubes for epic Ships.

Boba Fett Scum Crew hast the wrong ability.

Hondo Ohnaka Crew hast the wrong ability

The “Energy” Symbol is missing at some epic abilities (not sure, if I got all examples, see my file)

Thank you for your great work!
Greetings Sephebos

### Actual Behavior
[YASB_Mistakes (1).docx](https://github.com/raithos/xwing/files/7452192/YASB_Mistakes.1.docx)

State what actually happens here.

### Language

The affected language(s). 
 German

**Comment by raithos** [comment]
@Patschke this seems like your realm

**Comment by Patschke** [comment]
I'll look into it. Sorry for the long responding time, I was on a conference.
