### ISSUE TITLE
Feature Request: Print Dials

### ISSUE THREAD

**Issue by Laurvin** [raithos/xwing#89]
When using the Fancy View (to print) would it be possible to include the ship dials as well? It would be great if that could be added. Thanks!

**Comment by schtein** [comment]
What would be great is the view you get on the right side of the screen when you select a ship, this includes the movement possibilities and would look quite good.

**Comment by Patschke** [comment]
Sounds good, I'll have a look at it.

**Comment by Patschke** [comment]
Implemented in #112 
I'd be happy to recieve some feedback.

**Comment by raithos** [comment]
I'll be pushing @Patschke updates shortly. You can select is as a printable option in the checkboxes in the print/view area.

**Comment by Patschke** [comment]
Guess we will wait for my next PR to actually have that feature - and not just a commented-out block of code that would enable it...
