### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#891]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s). 

In english, using firefox.
I just clicked in import:

{"faction":"firstorder","pilots":[{"id":"kyloren","ship":"tievnsilencer","points":87,"upgrades":{"force-power":["extrememaneuvers"],"tech":["sensorscramblers"],"torpedo":["iontorpedoes"]}},{"id":"lieutenanttavson","ship":"upsilonclasscommandshuttle","points":64,"upgrades":[]},{"id":"breach","ship":"tiesebomber","points":49,"upgrades":{"torpedo":["advprotontorpedoes"],"missile":["ionmissiles"],"device":["connernets","seismiccharges"]}}],"points":200,"vendor":[],"version":"2.0.0"}

Pasted and try to load it, but it gets stucked after click on button.

**Comment by raithos** [comment]
so the problem is tavison, the section "upgrades":[] (meaning no upgrades), breaks the xws importer. This seems like a new issue (and not sure if following the xws standard), where did you get the xws from?

**Comment by negroscuro** [comment]
I got that from export option in listfortress meta wing:List Archetype - MetaWing 2.0

| 
| 
|  | 
List Archetype - MetaWing 2.0

Matt Whited

Meta analysis for the X-Wing List Fortress
 |

 |

 |




    En jueves, 11 de noviembre de 2021 17:49:37 CET, raith ***@***.***> escribió:  
 
 


so the problem is tavison, the section "upgrades":[] (meaning no upgrades), breaks the xws importer. This seems like a new issue (and not sure if following the xws standard), where did you get the xws from?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by raithos** [comment]
i made a hotfix, but its still weird to provide emtpy fields as a part of the xws.
