### ISSUE TITLE
Points update not working on chrome

### ISSUE THREAD

**Issue by MickeyTheChin** [raithos/xwing#892]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Points to be correct 

### Actual Behavior

Points are incorrect. Most 200 pt lists i make are coming in at 207. Sinker is 54 instead of 53, Anakin is 56 instead of 51, Obi-wan is 49 instead of 48. Seems only i have this problem, i asked the FB community about it and everyone elses is up to date. Its also only on Chrome it seems, IE works fine, but doesnt print as good so i much prefer chrome! Though some of the upgrades wont load on that i.e Hate on Anakin pilot. Ive tried clearing cookies and history but thats not helped. Any suggestions? Thanks for all your work!
### Language

English

The affected language(s).

**Comment by raithos** [comment]
did you try to hard refresh? CTRL+F5. also, make sure the url doesnt have /old in it, because thats the old points link

**Comment by MickeyTheChin** [comment]
Sorted! The URL had /old in it. Thanks for your help mate, this has been annoying me for weeks!!! Thanks again for the site and everything you do!!
