### ISSUE TITLE
Plasma Torpedo missing

### ISSUE THREAD

**Issue by wernerjc1** [raithos/xwing#895]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Able to select Plasma Torpedo for any Rebel Alliance X-wing (or possibly any Torpedo upgrade slot)

### Actual Behavior

Do not see Plasma Torpedo as an option, but there is a Tracking Torpedo

**Comment by raithos** [comment]
https://puu.sh/Iq0Kk/ca5aea9f4d.png ???

Do you have  screenshot of this not working?

**Comment by wernerjc1** [comment]
Sorry to waste your time I guess, but I checked again and it is working
now. Sorry about that!
