### ISSUE TITLE
Feature Request - Ship Cost Range in Ship Summary

### ISSUE THREAD

**Issue by anohan** [raithos/xwing#896]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.
When browsing ships there is a ship chassis summary on the right, I would like the summary to have a ship point range of the lowest and highest ship cost range. As an example, when browsing and hovering over Rebel T65 X-Wing, I would like to see something like Ship Cost Range: 38 - 60.  I think it'll help when creating a list and you're looking for a ship to help fill it out.

### Actual Behavior

State what actually happens here.
Ship cost range is not currently listed. This is a feature request.

### Language

The affected language(s). 

N/A

**Comment by raithos** [comment]
to be honest, while i see the value in it, i'm not sure its something i want to do. I'll have to think about it

**Comment by anohan** [comment]
Thanks for considering it, Stephen! All good!

This is Steven G. of Fly Better, btw.

    On Friday, November 19, 2021, 09:44:10 PM PST, raith ***@***.***> wrote:  
 
 


to be honest, while i see the value in it, i'm not sure its something i want to do. I'll have to think about it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Patschke** [comment]
Seemed useful, I've implemented it.
