### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by redFarreg** [raithos/xwing#897]
Ignore if you wish, but being able to sort saved lists by most recent?

**Comment by raithos** [comment]
im not sure we save the last modified date on entries, it might not be possible without editing the back end server, which is more trouble than its worth right now.

**Comment by Patschke** [comment]
As far as I can tell we are currently not saving the date a squad has been created, so we are surely unable to sort existing lists by date. It should be possible to save that information in the future without changes to the back end server - we can just add an entry to the `additional_data` dictionary. Afaik the back end is agnostic regarding the content and number of key/value pairs of that dict, so in principle we can save pretty much anything we want in there. It's not much effort to add saving of the current date. 

Actually implementing the option to order the shown list by anything requires a bit more additional code though.

**Comment by raithos** [comment]
im going to close this for now. with the reset of lists with the new version, the dates isn't as important to do imo, and there's a lot of organization that can be used by the tag system already.
