### ISSUE TITLE
Drill Beak and Tractor Tentacles do not have an attack value

### ISSUE THREAD

**Issue by DeltaV1ms** [raithos/xwing#901]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

The cards Drill Beak and Tractor Tentacles have an attack value that appears as part of the card description.

### Actual Behavior

State what actually happens here.

The cards Drill Beak and Tractor Tentacles do not have an attack value that appears.

### Language

The affected language(s). 

All languages appear to be affected.

**Comment by Patschke** [comment]
Thanks for the note, will be fixed with as soon as PR #902 goes live.
