### ISSUE TITLE
Not a bug, but would love to pitch a feature!

### ISSUE THREAD

**Issue by piffopi** [raithos/xwing#903]
## YASB 2.0 feature request
@raithos I have an "elevator pitch" for an idea and functionality to add to YASB and I'd humbly request a webmeeting. 
I'll find a way to apologize for using GitHub to ping you  :D

### Expected Behavior
We really should talk asap!

### Actual Behavior
We are not talking.

### Language

Not relevant

**Comment by raithos** [comment]
email me at raithos@gmail.com
