### ISSUE TITLE
While lang is set to English - Ship Collection picks Spanish titles

### ISSUE THREAD

**Issue by minrray** [raithos/xwing#906]
![image](https://user-images.githubusercontent.com/38727351/145495402-03b67e0b-5e30-47dc-a210-6fe757f96449.png)

## YASB 2.0 Bug Report
While lang is set to English - Ship Collection picks Spanish ship names

### Expected Behavior

It should show English ship names

### Actual Behavior
![Capture2222](https://user-images.githubusercontent.com/38727351/145495453-b77f93d6-cf7b-4680-a9d0-6d6d337e36ea.JPG)

Spanish names...
### Language

English

**Comment by raithos** [comment]
is this still an issue after the latest update?

**Comment by minrray** [comment]
hello.tested, works perfectly fine, thank you!
