### ISSUE TITLE
Please check the Firespray available slots and ship upgrades. There should be a crew slot for Boba Fett flying with a slave 1 upgrade.

### ISSUE THREAD

**Issue by jzucchi79** [raithos/xwing#909]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment]
According to the point pdf (https://images-cdn.fantasyflightgames.com/filer_public/c9/5f/c95fee08-1720-4a62-82c0-6fc66e3662fa/scum.pdf), Boba does not have a crew slot (unlike the other pilots). Correct me if I'm wrong, but I believe everything is working as intended.

**Comment by jzucchi79** [comment]
The squad builder is correct. I checked it out with a friend and there's no
crew for Boba on a slave 1, although some tourney players have been doing
well claiming there is.

**Comment by raithos** [comment]
theyre likely referring to the recent amg stream where boba fett had a crew on it. until official points are updated there wont be any movement on yasb
