### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by Killdraven** [raithos/xwing#910]
### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by Killdraven** [comment]
Hello, maybe I could help in the ITALIAN translation. Contact me.

**Comment by Patschke** [comment]
I suggest that you check #779 and talk to @piffopi on how to contribute to the current work.

**Comment by piffopi** [comment]
> Hello, maybe I could help in the ITALIAN translation. Contact me.

Ciao! La traduzione è già in corso, ho avuto qualche bega a lavoro e ci ho messo una vita. Posso casomai contarti per la revisione? si parla di un orizzonte di qualche settimana.

ENG: translation ongoing, about 50% done (only upgrades missing) - as I have to deal with both translation and consistency checks. May I ping you in a few weeks if we need additional support for the review peocess?

**Comment by Killdraven** [comment]
Certo, se posso essere utile basta che mi dici come.
Buon anno nuovo
