### ISSUE TITLE
Strange Maths

### ISSUE THREAD

**Issue by BWilson24** [raithos/xwing#912]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

Randomizer should create a list by properly adding-up all of the points

### Actual Behavior

Somehow the algorithm is not adding points together properly. It made a list with over 300 points, but only tallied 50-ish points (see attached photo)

### Language

English
<img width="1280" alt="Screen Shot 2022-01-13 at 6 23 57 PM" src="https://user-images.githubusercontent.com/27526164/149441431-2da75e99-dc8f-40a6-a643-ef7d4e6392c7.png">

**Comment by raithos** [comment]
cant seem to replicate this. do you have any other information you can share?

**Comment by BWilson24** [comment]
The browser had been open for a while in the background. Maybe the idling
caused some miscommunication with the network? Also, it was running in
Chrome on Mac OS.
