### ISSUE TITLE
Feature request - see "Faction(s)" alongside other details in card browser

### ISSUE THREAD

**Issue by perthling** [raithos/xwing#913]
### Background
I'm brand new to X-Wing and have been directed to YASB by some experienced players citing this as an excellent resource!
As someone who knows very little about the game contents, I'm trying to establish which factions and expansions to get into.
The interface is incredibly responsive and in 'Card Browser' I have sorted by 'Source', which helps me quickly to eliminate Conversion Kits.
However I'm unable to ascertain the faction of the various pilots are, for example, which come in each expansion ('Source'). I'm confident this information would be readily available in your database.

### Feature Request
In 'Card Browser', include 'Faction(s)' in the far-right panel along with name, card type, ship, stats, etc.

**Comment by Patschke** [comment]
Seems reasonable, implemented in b57311e86a53400b9117ec53b6b2223943db671c 
It might be a bit until this PR goes online though. Thanks for the feedback, glad you like the card browser and consider it helpful!

**Comment by perthling** [comment]
You're a superstar Patrick! I've never used GitHub before, had no idea what
I was doing, and even then wasn't sure you'd receive it let alone action
thanks.
Thanks mate, Luke.
