### ISSUE TITLE
Mandalorian Royal guard should have a missile slot, not a torpedo slot

### ISSUE THREAD

**Issue by boredompwndu** [raithos/xwing#915]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior
![image](https://user-images.githubusercontent.com/8730661/155247871-32077842-ef6e-4ef5-b15a-70368f39d834.png)
### Actual Behavior
![image](https://user-images.githubusercontent.com/8730661/155247890-a4c09385-2006-430f-a6e5-777cb3e394b7.png)

### Language
English
The affected language(s).

**Comment by raithos** [comment]
update soon
