### ISSUE TITLE
Sheathipede and R4 Astromech interaction

### ISSUE THREAD

**Issue by xBraveOnex** [raithos/xwing#92]
### Expected Behavior

On the Sheathipede's dial the R4 astromech changes the difficulty of BASIC 1-2 maneuvers 

### Actual Behavior

The Sheathipede's 1 reverse is not a BASIC maneuver, it is an ADVANCED maneuver so should remain red when the R4 astromech is applied not turn white.

Thanks!!
P.S.  Love all your work, it has made my X-wing experience so much better!

**Comment by Patschke** [comment]
Fixed in #91
