### ISSUE TITLE
Jag in ARC-170 Mod slots are broken

### ISSUE THREAD

**Issue by ckdragons** [raithos/xwing#924]
Using new YASB 2. Only 1 Modification slot, "No modifications available".

**Comment by raithos** [comment]
https://puu.sh/IKVxV/1e8d8f7c07.png
https://puu.sh/IKVy6/a01049be7d.png
I see mod slots. They only have 1 according to the pdfs.

**Comment by ckdragons** [comment]
Need to select "Jag" in the ARC-170. It's the only ARC-170 pilot that has 2 Modification slots.
![image](https://user-images.githubusercontent.com/84493092/155263958-7fef70cd-6555-4dc9-a4da-8c606c40263c.png)

**Comment by ckdragons** [comment]
Tested again, I need to amend.... it has 2 Modification slots. 2nd slot isn't working.
![image](https://user-images.githubusercontent.com/84493092/155264025-d795d8d2-589c-4b60-bbf8-1228d3a80547.png)

**Comment by raithos** [comment]
got it will be fixed shortly
