### ISSUE TITLE
Saber squadron new slots

### ISSUE THREAD

**Issue by locowarrior** [raithos/xwing#929]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Saber squadron ace Should have 1 talent, 1 mod, and 1 missile slot.

### Actual Behavior

Saber squad instead has 1 talent, and 2 mod slots

### Language

Unsure

**Comment by Patschke** [comment]
What a crazy world we live in. Thanks for the note, will be fixed with #928
