### ISSUE TITLE
Maul Crew force/dark side slot

### ISSUE THREAD

**Issue by ilApogeo** [raithos/xwing#939]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

I put Maul crew on Scum Boba's Firespray, expected to get dark side drop down selection.

### Actual Behavior

I put Maul crew on Scum Boba's Firespray and did not get any additional drop down selections.

### Language

Checked English, Spanish and Italian, presumably the issue is in all languages.

![yasb-maul-bug-022322](https://user-images.githubusercontent.com/38863416/155398000-375f7293-c9e2-47d1-b0a2-a8c36dff4106.png)

**Comment by raithos** [comment]
thats working as intended. maul doesnt add force slots, just enables specific force upgrades to be used. if the ship doesnt have force slots already it cant take advantage of that
