### ISSUE TITLE
ST-70 Title 

### ISSUE THREAD

**Issue by Innkeeper16** [raithos/xwing#940]
YASP.App

### Expected Behavior

When you select the ST-70 Title, it states you get your Illicit for free.  Currently it is still charging the total load points.

State what you expect to happen here.

### Actual Behavior

State what actually happens here: The Illicit should cost 0 points.  Maybe if you select the title, maybe it should open another Illicit that does not cost points and hides one of the other Illicit from being used

### Language

State what language translation you use. English

Lastly,  thanks for all you do for the community.

**Comment by raithos** [comment]
no, this is working as intended. the facedown card is seperate from the builder. the ship itself has additional illicit slots and those are are not free as per the title.
