### ISSUE TITLE
Facebook login in development mode

### ISSUE THREAD

**Issue by splattr3D** [raithos/xwing#942]
### Expected Behavior

Log in to the new YASB.app (2.5 edition) using facebook, having my collection available.

### Actual Behavior

A new website says

App not set up
This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

![image](https://user-images.githubusercontent.com/56818885/155422907-f2ae6605-4139-45ff-b25e-06b031422a2d.png)

### Language

The affected language(s).

**Comment by raithos** [comment]
oops, turned on live mode
