### ISSUE TITLE
Tobias Beckett - Banned in Standard but in YASB Standard

### ISSUE THREAD

**Issue by Mega-Silver** [raithos/xwing#945]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Tobias Beckett not in Standard

### Actual Behavior

Tobias Beckett is shown in Standard Dropdown.

### Language

English.

**Comment by Patschke** [comment]
Thanks for the note.
