### ISSUE TITLE
yasb.app login failing

### ISSUE THREAD

**Issue by mjsaenz** [raithos/xwing#949]
I am using chrome on a windows 10 computer with a google account logged in. When I open yasb.app the "Checking auth status..." wheel spins for about 30 seconds before failing and turning into the "Log In" button. Clicking this button does nothing.

**Comment by raithos** [comment]
have you closed and reopened the site? sometimes if the auth page didnt open or is closed before authenticating this happens

**Comment by mjsaenz** [comment]
Closing the site did not fix it but restarting my pc did. Its probably a user issue.
