### ISSUE TITLE
SE Havoc Title card doesn't show the Sensor icon in the ability text

### ISSUE THREAD

**Issue by kyledsimpson** [raithos/xwing#95]
### Expected Behavior
Havoc should show a Sensor icon in the ability text

### Actual Behavior
It doesn't show a Sensor icon in the ability text.  But, it does correctly add a Sensor choice for the ship.

Thanks!

**Comment by Patschke** [comment]
Thanks for the feedback. Fixed in #91 

We still used the 1.0 name "system", as it is now named "sensor" it would not find the icon anymore
