### ISSUE TITLE
the IG2000 expansion is left off the new 2.5 rules set and the ship is not listed under the scum faction to even add to a squad

### ISSUE THREAD

**Issue by Adinelthims** [raithos/xwing#950]
### Expected Behavior

be able to ad the aggressor and IG pilots be able to be added to a squa 

### Actual Behavior

missing from list currently

### Language

State what language translation you use.

**Comment by Bmaenz** [comment]
Ig-2000 ships are not in Standard, if you want that ship you have to select extended as the format.

**Comment by Adinelthims** [comment]
> Ig-2000 ships are not in Standard, if you want that ship you have to select extended as the format.

thank you, I found it now
