### ISSUE TITLE
Kimogila Fighter is missing in 2.5

### ISSUE THREAD

**Issue by pdralston** [raithos/xwing#954]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Kimogila shows up in squadbuilder under Scum and Villiany

### Actual Behavior

Kimogila is no longer listed as of the 2.5 update 

![image](https://user-images.githubusercontent.com/25166909/155650177-7ffdc293-0428-4303-a1f1-263bb1cffd42.png)
![image](https://user-images.githubusercontent.com/25166909/155650251-bb7cb9db-2ff0-411e-93b0-caa74c3ce142.png)

**Comment by raithos** [comment]
its selectable in extended, by your own screenshots, its not legal in standard.
