### ISSUE TITLE
Lancer Class Pursuit Craft Missing

### ISSUE THREAD

**Issue by Asvaldrz** [raithos/xwing#955]
### Expected Behavior

Lancer Class Pursuit craft selectable from Scum Ship lists. Aka the Shadowcaster

### Actual Behavior

Lancer Class Pursuit craft missing from Scum Ship lists. Aka the Shadowcaster

### Language

Only checked english

**Comment by raithos** [comment]
lancer is selectable in extended. my guess is that you were in standard which its not legal
