### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#957]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Importing XWS with ships and upgrades of extended format

### Actual Behavior

When import ends it is showing standard mode and ships/upgrades not allowed are los and import is not done as expected

### Language

english

**Comment by skim-CG** [comment]
importing with xws is going to be fucked for a while, it wasnt designed to handle the new output and a lot of the new ships and pilots arent properly formatted for xws
