### ISSUE TITLE
No collection?

### ISSUE THREAD

**Issue by LordVorKon** [raithos/xwing#964]
(Yes, I used the same login)

Yasb.app does not have my collection.  Are we going to have to re-input all of that by hand?

**Comment by LordVorKon** [comment]
Disappointing.  My collection record should definitely be more than a month old, yeah.
I tried with different browsers on a different device.  One didn't let me log in at all (no window for it came up, even though it had no problems logging me in to the github.io domain).  The other logged in successfully but still no collection.

**Comment by raithos** [comment]
so i looked into whether or not we could import specific entries but i dont think thats the issue. i do know that google accounts have transfered over, but maybe its facebook or discord tahts a problem. can you tell me which way you logged in for reference? outside of that there's not much else we can do

**Comment by LordVorKon** [comment]
It was facebook.  I already went ahead and transfered it all manually.

**Comment by raithos** [comment]
ok thanks, i suspected it might be facebook. sorry for the inconvienence.
