### ISSUE TITLE
Sensitive Controls and Vectored Cannons are listed on incompatible ships

### ISSUE THREAD

**Issue by JanderRepro** [raithos/xwing#968]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

Sensitive Controls and Vectored Cannons (RZ-1) should be restricted to TIE Interceptor and RZ-1 A-Wing, respectively.

### Actual Behavior

They appear in Configuration dropdowns for other ships. They're greyed out and unselectable, but they still appear.

### Language

English.

**Comment by raithos** [comment]
thats as intended. they are not actually restricted by ship but by chassis ability, so they will be appear as greyed out on other ships. case in point, autothrusters is also on the tie silencer so they can equip autothrusters.
