### ISSUE TITLE
Chrome blocking backend cookie

### ISSUE THREAD

**Issue by nickell-andrew** [raithos/xwing#97]
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** If you find you are now missing ships, Conversion kits have been separated from your ship collection and no longer add ships. This was requested by several people in order to more accurately represent their collections. 
To fix the red issue, if you go into your collection and click on the ships tab, there is a list of all available ships and you can update the numbers accurately of all the 1.0 ships you had prior to the 2.0 launch. I am currently working on a setting to disable collection checking if but it wont be out until later.

### Expected Behavior

Oauth should work for google.

### Actual Behavior

Chrome was blocking a cookie being set for yasb-backend.herokuapp.com
I was able to bypass this issue by explicitly allowing this cookie, but chrome blocked it by default.

### Language

English

**Comment by raithos** [comment]
I was not able to replicate the issue here. is there any more information about the circumstances from which this occurred?

**Comment by ManuelWittke** [comment]
The Oauth issue occures when you block cookies by default (e.g. from other domains than the opend).
I had that with YASB 1.0 (Geordan hinted me on that after a very 
thorough bug search - thank you again for your time!)
YASB is opend from github.io. The Backend that sets the cookies opens from herokuapp.com.

**Comment by zacharyp** [comment]
I also noticed this was happening for me.  I had Privacy Badger installed, but when I disabled it for site, I was immediately logged into YASB2 as I expected 👍

**Comment by zacharyp** [comment]
Also, if I simply enabled cross site cookies from yasb-backend.herokuapp.com, it worked as well:

<img width="415" alt="screen shot 2018-09-24 at 6 31 48 pm" src="https://user-images.githubusercontent.com/58073/45982797-38dc8100-c028-11e8-9719-d099f22fe87c.png">

**Comment by nickell-andrew** [comment]
Sounds good. I just wanted to make sure people were aware that by default chrome was preventing login.
