### ISSUE TITLE
Feature request\inquiry

### ISSUE THREAD

**Issue by Nutano** [raithos/xwing#975]
Not a bug - so ignore I guess if not interested in feature request.

Is there a way to identify upgrades that are part of the ban list when selecting 'Extended' format?  Perhaps an asterix before the card name in the upgrade name? or actually have (ban list) part of the card name?

Thank you for all you do!
JM

**Comment by Nutano** [comment]
wrong site

**Comment by Patschke** [comment]
FYI: You've submitted the same issue to the very same repository twice. The front end has changed from raithos.github.io to yasb.app, but the source code is still at the same place. Not that it would cause any harm to submit stuff twice...
