### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Nutano** [raithos/xwing#976]
Resubmit cause I sent the other one on the old site by accident.

Not a bug - a feature request, ignore if only bugs are what is being looked at at this time.

Is there a way we can identify banned upgrades\pilots event when selecting 'Extended' format?  I am running an extended format to allow some players to bring some non-black box ships, yet the ban list is still in effect.  Perhaps something like an asterix before the upgrade name? Append (ban list) to the upgrade list?

Thank you for your time and what you do here!
Cheers
JM

**Comment by raithos** [comment]
The only card that is banned in both standard and extended is the delta 7b config. from what you're describing, it sounds like you're not aware that you can change the format in the dropdown in the top left. you can absolutely select banned ships in extended mode.
