### ISSUE TITLE
Update Delta-7b to same as Delta-7 quantity owned

### ISSUE THREAD

**Issue by ckdragons** [raithos/xwing#977]
Possible to set the quantity of Delta-7 ships to also show the same number of Delta-7B ships? Unless you are aware that AMG is releasing Delta-7B-specific ships in the near future. The list builder shows I own five (5) Delta-7 ships and zero (0) Delta-7b ships. Thanks.

**Comment by raithos** [comment]
yes, should be possible as long as you dont add loose ships. will add that soon

**Comment by raithos** [comment]
the downside will be that if you mix and match delta 7s it will show twice as many ships as you actually own. just keep that in mind

**Comment by ckdragons** [comment]
Hmmmm.... that is a good point. Thanks for all you do.
