### ISSUE TITLE
Feature request: Baned items included

### ISSUE THREAD

**Issue by Strikefire47** [raithos/xwing#981]
Hello, I was wondering if there was a way to include a dropdown option like epic and standard play that includes all of the banned items with their point values? This could be just an optional thing that could be enabled so we can still play with banned items in this new format?

**Comment by raithos** [comment]
you mean extended?

**Comment by Strikefire47** [comment]
My apologies for not checking, thank you so much for responding! Sorry to bother you and keep up the amazing work!
