### ISSUE TITLE
Named Delta 7B Pilots

### ISSUE THREAD

**Issue by GoldSquadronPodcast** [raithos/xwing#982]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

State what you expect to happen here.

Named Delta 7B Pilots Attack and Shield Value are Incorrect
They are currently Listed at 2 attack, 3 agi, and 1 Shield

### Actual Behavior

State what actually happens here.

All named Delta 7B Pilots should be 3 Attack, 2 Agi,  and 3 Shield due to the Errata page listed here:  https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/621ea5262bfe171a388df491/1646175531390/SWZ_Errata_1.4.1.pdf

### Language

The affected language(s).

**Comment by raithos** [comment]
yeah they are all correct, my guess is that you were accidentily looking at the delta 7, later on i will make a more clear distintction between them in the background image when i have some time
