### ISSUE TITLE
The Mandalorian should have Bounty Hunter keyword to equip Tracking Fob

### ISSUE THREAD

**Issue by Elred** [raithos/xwing#984]
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpetation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

AMG updated the points list (sneakily) and gave The Mandalorian the Bounty Hunter Pilot. The Mandalorian should thus be able to equip Tracking Fobs

### Actual Behavior

The Mandalorian cannot equip Tracking Fobs

### Language

Everything

**Comment by Patschke** [comment]
Thanks for the note, will be updated. 

The current way AMG provides lists is... well... stupid. Having a closer look at those documents: 
[New Ship Points](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/621ea58663e3bc0663b00bf9/1646175623062/SWZ_Ship_Points_1.4.1.pdf)
[Old Ship Points](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/62150240368e122d0a8a1219/1645544001070/Ship_Points_Jan22.pdf)
Shows, that a) you are indeed right, they added the key word (and changed the red in the X-Wing logo at the top), but nothing else and b) they both read the very same "Effective Date: ...". 
I'd expect them to show changes in color (like in the Rules Reference: Everything new in blue), but at the very least to use some sort of versioning system - I don't care if they call it version 1.4.1 or give it a date, or whatever - but they should never just use the very same version number for two different documents...

Guess neither you nor we can change anything on the way AMG provides those documents...

**Comment by raithos** [comment]
lets be real, ffg has done this in the past too. anyway, will be updated shortly
