### ISSUE TITLE
Expose Keywords to Builder UI and Card Browser

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#987]
The Pride of Mandalore pack introduces the "Mandalorian" keyword, and this is all well documented in the ship PDF and the YASB builder properly honors them.

Pilot keywords are not viewable in the builder nor searchable in the Card Browser.
Upgrade restrictions are viewable in the builder but are not searchable in the Card Browser.

Text Search does also not search Keywords or Restrictions.

This may lead to confusion as users try to figure out why, say, A-Wing Sabine can equip Clan Training but A-Wing Hera cannot.   

"Mandalorian" is an especially annoying keyword, as the historically-most-well-known "Mandalorian", Boba Fett, does not have the Mandalorian keyword.

**Comment by raithos** [comment]
i wish you wouldnt suggest these good ideas that take a bunch of work to do. its done
