### ISSUE TITLE
Incorrect XWS for some mandalorians

### ISSUE THREAD

**Issue by danrs** [raithos/xwing#989]
## YASB 2.0 Bug Report
Incorrect XWS ids for some of the new mandalorian cards

### Expected Behavior
Fenn crew: fennrau-crew
Bo-Katan rebel/scum crew: bokatankryze-rebel-scum
Bo-Katan republic/separatist crew: bokatankryze-crew
Gar Saxon crew: garsaxon-crew
Captain Hark crew: captainhark-crew
Rook Kast crew: rookkast-crew
Clan Wren Commando Team: clanwrencommandoteam
Nite Owl Commando Team: niteowlcommandoteam
Imperial Super Commando Team: imperialsupercommandoteam
Mandalorian Super Commando Team: mandaloriansupercommandoteam
Death Watch Commando Team:  deathwatchcommandoteam
Maul (Mandalore): maul-crew
Ahsoka crew: ahsokatano-crew
Gar saxon gunner: garsaxon-gunner
Obi-wan kenobi crew: obiwankenobi-crew
Pre Vizsla crew: previzsla-crew
Ursa Wren gunner: ursawren-gunner

### Actual Behavior
Fenn crew: fennrau
Bo-Katan rebel/scum crew: bokatankryze
Bo-Katan republic/separatist crew: bokatankryze
Gar Saxon crew: garsaxon
Captain Hark crew: captainhark
Rook Kast crew: rookkast
Clan Wren Commando Team: clanwrencommandos
Nite Owl Commando Team: niteowlcommandos
Imperial Super Commando Team: imperialsupercommandos
Mandalorian Super Commando Team: mandaloriansupercommandos
Death Watch Commando Team:  deathwatchcommandos
Maul (Mandalore): maul
Ahsoka crew: ahsokatano
Gar saxon gunner: garsaxon
Obi-wan kenobi crew: obiwankenobi
Pre Vizsla crew: previzsla
Ursa Wren gunner: ursawren

### Language
English

**Comment by danrs** [comment]
XWS has been updated to correct a number of wrong XWS IDs. The only remaining issues in YASB are:

Bo-Katan rebel/scum crew: currently `bokatankryze`, should be `bokatankryze-crew`
Maul (Mandalore): currently `maul`, should be `maul-crew`
Ahsoka crew: currently `ahsokatano`, should be `ahsokatano-crew`
Gar saxon gunner: currently `garsaxon`, should be `garsaxon-gunner`
Ursa Wren gunner: currently `ursawren`, should be `ursawren-gunner`

**Comment by danrs** [comment]
Also Maul pilot in the gauntlet fighter is currently `maul-gauntletfighter` in yasb but should be just `maul`. He doesn't conflict with the sith infiltrator because that one is `darthmaul`

**Comment by danrs** [comment]
Found another two, gauntlet pilots again:

`bokatan-separatistalliance` should be `bokatankryze-separatistalliance`
`bokatan` should be `bokatankryze`

**Comment by raithos** [comment]
i should have caught them all
