### ISSUE TITLE
second bomb cannot be added

### ISSUE THREAD

**Issue by negroscuro** [raithos/xwing#99]
Hello,
first of all thank yo for the great work with the builder.
The issue I noticed is I put a proton bomb and then a second one cannot be added in a different bomb slot...
Cheers,
Mario

## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by negroscuro** [comment]
The problem is to try to equip a second proton bomb on the same ship.

**Comment by LordVorKon** [comment]
All upgrades are 'one per ship'.  Rules reference, pg 17.  
![image](https://user-images.githubusercontent.com/42716764/45958074-be821180-bfd3-11e8-977e-98d788fa03bb.png)

**Comment by negroscuro** [comment]
I did not notice that, sorry.
