### ISSUE TITLE
Blazer Bomb

### ISSUE THREAD

**Issue by Mega-Silver** [raithos/xwing#998]
### Expected Behavior

Data for Blazer Bomb is on YASB, but not for the Blaze Dropped afterward.

### Actual Behavior

Blaze token effect is not listed.

### Language

English.

**Comment by raithos** [comment]
The blaze rules are listed as rules and not as a extra device rules clarification like the other bombs. I don't why its done this way, but I'm following the existing structure, so I wont be adding this to the condition info, it's in the rules if you need to reference it.
